// ================================================================
// Chemotherapy & Antimicrobial Pharmacology — Case Templates
// 8 templates covering: Malaria, HIV/AIDS, CAP, UTI, Sepsis,
// Meningitis, Typhoid, Cellulitis
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';
function tpl(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}

export const CHEMOTHERAPY_TEMPLATES: ClinicalCaseTemplate[] = [
  tpl('Chemotherapy & Antimicrobial Pharmacology', 'Infectious Diseases', 'Malaria', 'Severe Falciparum Malaria with Cerebral Involvement', 'Advanced',
    'High fever, confusion, and inability to wake for 12 hours',
    '{name}, a {age}-year-old {occupation} from {location}, was brought by family with a 3-day history of high fever (39-40°C), chills, severe headache, and muscle aches. Over the past 12 hours became confused, difficult to rouse, and has not eaten or drunk. Lives in a malaria-endemic area with recent rains. Has not used mosquito nets consistently.',
    'No significant PMH. No prior severe malaria. No known G6PD deficiency.',
    'No regular medications. Took paracetamol for fever.',
    'GCS 12 (E3 M5 V4). Febrile (39.5°C), tachycardic, tachypnoeic. Mild jaundice. No neck stiffness. No focal neurology. Palpable spleen (3cm below costal margin). Petechial rash on lower limbs. BP 100/60.',
    'Blood film: 12% parasitaemia (Plasmodium falciparum, mixed stages). Hb 8.5 g/dL. Platelets 35 x10^9/L. Glucose 52 mg/dL (hypoglycaemia). Creatinine 1.4 mg/dL. Bilirubin 3.5 mg/dL (unconjugated). LDH elevated. Lactate 4.5 mmol/L. Blood culture: drawn. HIV test: negative.',
    'CT head (if done): no acute pathology.',
    'Severe Falciparum Malaria with Cerebral Involvement, Severe Anaemia, Thrombocytopenia, and Hypoglycaemia (WHO Severe Malaria Criteria)',
    ['Cerebral Malaria', 'Meningitis/Encephalitis', 'Sepsis', 'Febrile Seizure', 'Cerebrovascular Accident'],
    'Rapidly reduce parasitaemia, manage complications (hypoglycaemia, anaemia, seizures), prevent death',
    '1. First-line for severe malaria: IV Artesunate 2.4 mg/kg at 0, 12, and 24 hours, then daily (dose: 120mg IV for 50kg patient). 2. After minimum 24 hours of IV artesunate and when able to tolerate oral: complete treatment with oral Artemether/Lumefantrine (6-dose course over 3 days). 3. Supportive care: IV 10% Dextrose for hypoglycaemia (50mL bolus). Blood transfusion if Hb <7 g/dL or symptomatic. Monitor for seizures — give IV Diazepam 5-10mg if occurs. 4. Broad-spectrum IV antibiotics if septic (IV Ceftriaxone 2g daily) until cultures negative.',
    'ICU monitoring. Strict I/O. Cooling measures (Paracetamol, tepid sponging). Prevent bedsores. Maintain airway if GCS drops.',
    'Admit to HDU/ICU. Start IV Artesunate immediately. Correct hypoglycaemia. Transfuse if Hb <7. Monitor: GCS q1h, parasitaemia q12h, glucose q4h, Hb, platelets, creatinine daily. Lumbar puncture if no improvement (to rule out meningitis).',
    '1. Life-threatening severe malaria with multi-organ involvement requiring urgent parenteral antimalarial therapy. 2. High mortality risk from cerebral malaria, severe anaemia, hypoglycaemia.',
    'GCS, vitals hourly. Parasitaemia q12-24h. Glucose q4-6h. Hb, platelets, creatinine, bilirubin daily. Watch for: blackwater fever (haemoglobinuria), acute kidney injury, ARDS, bleeding (DIC).',
    'Malaria is a medical emergency when it affects the brain. IV Artesunate is highly effective — most patients start improving in 24-48 hours. Full recovery is possible with prompt treatment. Long-term: always sleep under an insecticide-treated mosquito net. Severe malaria can be prevented by early treatment of uncomplicated malaria.',
    'Repeat blood film daily until parasitaemia clears (<0.1%). If neurological sequelae, refer for rehabilitation. Review Hb in 2 weeks.',
    'IV Artesunate is superior to IV Quinine for severe malaria (reduces mortality by 22.5% in the AQUAMAT trial). Intramuscular Artesunate is an option if IV access is not available. Hypoglycaemia in severe malaria is common (from both disease and quinine historically, less with artesunate). Cerebral malaria has 10-20% mortality even with optimal treatment. Splenomegaly and thrombocytopenia are common. Do not use artemisinin monotherapy for uncomplicated malaria (requires ACT to prevent resistance).',
    ['WHO Guidelines: Malaria Treatment', 'Kenya Malaria Treatment Guidelines', 'ACSM: Severe Malaria Management'],
  ),
  tpl('Chemotherapy & Antimicrobial Pharmacology', 'Infectious Diseases', 'HIV/AIDS', 'New Diagnosis of HIV in a Young Adult with Advanced Immunosuppression', 'Advanced',
    'Chronic diarrhoea, weight loss, persistent cough, and oral thrush for 2 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 2-month history of chronic watery diarrhoea, 8 kg weight loss, persistent dry cough, low-grade fevers, night sweats, and oral thrush. Reports being sexually active with multiple partners. Never tested for HIV. Has had two sexually transmitted infections in the past 2 years (syphilis, gonorrhoea).',
    'Recurrent STIs (syphilis 2 years ago, gonorrhoea 1 year ago). No known TB contact.',
    'No regular medications',
    'Thin, wasted appearance (BMI 17). Oral thrush (white plaques on tongue and buccal mucosa). Mild cervical lymphadenopathy. Chest: clear. Abdomen: mild epigastric tenderness. No skin lesions. No hepatosplenomegaly.',
    'HIV rapid test: Positive (Confirmatory ELISA positive). CD4 count: 68 cells/mm3 (severe immunosuppression). HIV viral load: 550,000 copies/mL. Hb 9.5 g/dL. WBC 3.2. Creatinine 0.8. CrAg (cryptococcal antigen): negative. Sputum Xpert MTB/RIF: Negative. CXR: normal. HBV serology: HBsAg negative. STI screening: syphilis RPR positive (1:8), treated.',
    'Chest X-ray: normal (no active TB).',
    'New Diagnosis of HIV-1 Infection with Severe Immunosuppression (WHO Stage 3: Oral Candidiasis, Unintentional Weight Loss, Chronic Diarrhoea)',
    ['HIV/AIDS', 'Pulmonary TB', 'Disseminated TB', 'Lymphoma', 'Chronic GI Infection'],
    'Start ART, prevent OIs, manage IRIS, screen for TB/Crypto, partner notification, prevent transmission',
    '1. Start ART: Tenofovir Disoproxil Fumarate 300mg daily + Lamivudine 300mg daily + Dolutegravir 50mg daily (TLD regimen — preferred first-line in Kenya). 2. OI Prophylaxis: Start CTX (Co-trimoxazole) 960mg daily (for CD4 <200, continues until CD4 >200 for 6 months). 3. TB Preventive Therapy (TPT): Isoniazid 300mg daily + Pyridoxine 25mg daily for 6 months (after ruling out active TB). 4. If CD4 <100: Cryptococcal antigen screening. 5. Screen for STIs and treat if positive. 6. Immunisations: PCV13, PPSV23, annual influenza. Assess for hepatitis B and treat if co-infected.',
    'Nutritional support: ready-to-use therapeutic foods if malnourished. Safe water and food hygiene for diarrhoea. Barrier contraception (condoms) for prevention of transmission. Partner notification and testing. Family planning counselling.',
    'Start TLD regimen (FDC = fixed dose combination, one tablet daily). Start CTX prophylaxis. Start INH/TPT. Schedule visit in 2 weeks for adherence check and side effects. Viral load monitoring in 6 months. Partner notification and testing. Refer to HIV support group.',
    '1. Advanced HIV with severe immunosuppression requiring urgent ART initiation. 2. High risk of OIs (PCP, TB, Cryptococcus) requiring prophylaxis. 3. Public health: transmission risk requiring prevention counselling.',
    'CD4 count at baseline (not needed to start ART). Viral load at 6 months, then annually. Creatinine at baseline, 3 months (tenofovir renal safety). Hb (AZT effect). Weight and nutritional status. Adherence at every visit. Screen for TB symptoms at every visit.',
    'HIV is a manageable chronic condition. With one tablet daily, you can achieve an undetectable viral load, which means you cannot transmit HIV to others (U=U). Take your medication at the same time every day. Join a support group to connect with others living with HIV. Use condoms to protect your partners. You can live a long, healthy life.',
    'HIV clinic in 2 weeks. Viral load in 6 months (target <50 copies/mL). CD4 monitoring 6-monthly until >200. Annual cervical cancer screening (women). Annual STI screening. Long-term: CV risk, bone density (tenofovir), renal function monitoring.',
    'Kenya uses the "Test and Treat" strategy — start ART on the same day as diagnosis regardless of CD4 count. Dolutegravir is the preferred third agent in Kenya (TLD regimen) — potent, well-tolerated, high barrier to resistance. Tenofovir can cause renal impairment — monitor creatinine. CTX prophylaxis is life-saving at CD4 <200 (prevents PCP, toxoplasmosis, bacterial infections). U=U (Undetectable = Untransmittable) is scientifically proven when viral load <200 copies/mL.',
    ['Kenya Guidelines: HIV Prevention and Treatment', 'WHO Guidelines: HIV/AIDS Management', 'CDC: HIV Clinical Guidelines'],
  ),
  tpl('Chemotherapy & Antimicrobial Pharmacology', 'Infectious Diseases', 'Urinary Tract Infection', 'Uncomplicated Lower Urinary Tract Infection in a Young Woman', 'Beginner',
    'Painful urination, frequency, urgency, and suprapubic discomfort for 3 days',
    '{name}, a {age}-year-old {occupation} from {location}, presents with 3-day history of dysuria (burning on urination), urinary frequency (urinating every 1-2 hours), urgency (sudden strong need to urinate), and suprapubic heaviness. No fever. No flank pain. No nausea/vomiting. No vaginal discharge or itching. Not pregnant. No prior UTIs in the past year.',
    'No chronic illnesses. Not pregnant. Sexually active, uses condoms inconsistently.',
    'No regular medications',
    'Afebrile. Suprapubic mild tenderness. No CVA tenderness. External genitalia: normal, no discharge. Urinalysis (dipstick): nitrites positive, leukocyte esterase positive, blood trace, WBC >50/hpf. Pregnancy test: negative.',
    'Urinalysis: Nitrite +, Leukocyte esterase +, WBC >50/hpf, RBC 5-10/hpf. Urine culture: pending (standard for uncomplicated UTI not required unless recurrent or treatment failure). Creatinine 0.7 mg/dL.',
    'No imaging indicated.',
    'Acute Uncomplicated Lower Urinary Tract Infection (Acute Cystitis)',
    ['Acute Cystitis', 'Acute Pyelonephritis', 'Urethritis (STI)', 'Vulvovaginitis', 'Interstitial Cystitis'],
    'Eradicate infection, relieve symptoms, prevent progression to pyelonephritis, minimise antibiotic use and resistance',
    '1. First-line empiric antibiotic: Nitrofurantoin 100mg BID for 5 days (preferred — low resistance, minimal GI effects, safe in early pregnancy). 2. Alternatives: Fosfomycin Trometamol 3g single dose sachet (good for MDR organisms). Pivmecillinam 400mg TID for 3 days. 3. If Nitrofurantoin unavailable or contraindicated: consider Oral Cefixime 400mg daily for 3-5 days. 4. AVOID: Amoxicillin, Co-trimoxazole, Ciprofloxacin (high resistance rates in Kenya for E. coli). 5. Symptomatic relief: Paracetamol for discomfort. Phenazopyridine 200mg TID for 2 days for dysuria (urine turns orange). 6. Encourage increased fluid intake.',
    'Increase water intake (2-3L/day). Empty bladder completely. Urinate after intercourse. Avoid holding urine. Wipe front to back.',
    'Prescribe Nitrofurantoin 100mg BID for 5 days. Urine culture not required unless: pregnant, recurrent UTI, failed treatment, or complicated. If symptoms persist after 48 hours, send urine culture and consider pyelonephritis.',
    '1. Uncomplicated bacterial cystitis requiring short-course narrow-spectrum antibiotic. 2. Recurrence prevention requires behavioural modification.',
    'Symptom diary: dysuria, frequency, urgency. If fever develops or flank pain, reassess for pyelonephritis. Post-treatment urine culture only if symptoms persist.',
    'Complete the full antibiotic course even if symptoms improve (usually 1-2 days). Drink plenty of water. Urinate when you feel the urge — do not hold it. Urinate soon after intercourse. Avoid douches or feminine hygiene sprays.',
    'Follow-up only if symptoms persist beyond 48 hours on antibiotics. If >2 UTIs in 6 months or >3 in 12 months, consider prophylactic antibiotics or vaginal oestrogen (postmenopausal).',
    'Uncomplicated UTI: affects otherwise healthy non-pregnant women with no anatomic/functional abnormalities. Nitrofurantoin is now first-line in most guidelines due to low resistance rates and minimal ecological impact. E. coli causes 75-90% of uncomplicated UTIs. In Kenya, E. coli resistance to Amoxicillin is >70%, Co-trimoxazole >60%, Ciprofloxacin >30% — these should not be used empirically. Pyuria without bacteriuria suggests urethritis (chlamydia/gonorrhoea) or interstitial cystitis.',
    ['IDSA Guidelines: Uncomplicated UTI', 'Kenya Clinical Guidelines: UTI Management', 'WHO: Antibiotic Stewardship in UTI'],
  ),
  tpl('Chemotherapy & Antimicrobial Pharmacology', 'Infectious Diseases', 'Sepsis', 'Neutropenic Sepsis in a Patient Receiving Chemotherapy', 'Advanced',
    'Fever, chills, and feeling extremely unwell 10 days after chemotherapy',
    '{name}, a {age}-year-old {occupation} from {location}, is 10 days post-cycle of chemotherapy for breast cancer (doxorubicin + cyclophosphamide). Developed a fever of 39.2°C this morning with chills, rigours, malaise, and mild oral mucositis. No localising symptoms. No cough, no dysuria, no diarrhoea. Neutropenic precautions observed at home.',
    'Breast cancer (Stage II, on adjuvant ACT chemotherapy cycle 3 of 6). Port-a-cath in situ. No known drug allergies.',
    'Chemotherapy: Doxorubicin 60mg/m2 + Cyclophosphamide 600mg/m2 (Day 10 post-cycle). Ondansetron 8mg TID PRN. Filgrastim (G-CSF) not prescribed this cycle.',
    'Febrile, tachycardic, mildly tachypnoeic. BP 100/60. Mucous membranes: mild oral mucositis. Port-a-cath site: clean, no erythema, no discharge. Lungs clear. Abdomen soft, non-tender. No skin lesions.',
    'ANC: 100 cells/mm3 (Severe Neutropenia). Hb 9.5. Platelets 55.000. CRP 150 mg/L. Procalcitonin 1.8 ng/mL. Creatinine 0.9. LFTs normal. Blood cultures: x2 sets drawn (peripheral + port). Urine culture: drawn. CXR: normal.',
    'Chest X-ray: clear. No focal consolidation.',
    'Febrile Neutropenia (Neutropenic Sepsis) — MASCC Score 18 (Low Risk)',
    ['Neutropenic Sepsis', 'Septic Shock', 'Pneumonia', 'Catheter-Related Bloodstream Infection', 'Mucositis-Associated Bacteraemia'],
    'Start empiric broad-spectrum antibiotics immediately, identify source, resolve neutropenia, prevent septic shock',
    '1. Emergency — start empiric antibiotics within 1 hour of presentation: IV Piperacillin/Tazobactam 4.5g Q6H (anti-pseudomonal beta-lactam). 2. If penicillin-allergic: IV Meropenem 1g Q8H or IV Cefepime 2g Q8H. 3. If vancomycin indicated (catheter-related infection, MRSA colonisation, or haemodynamic instability): add IV Vancomycin 15-20mg/kg Q12H (dose to renal function). 4. G-CSF (Filgrastim 300-480mcg SC daily) until ANC >500 (consider if pneumonia, sepsis, or expected prolonged neutropenia). 5. Fluconazole 400mg daily if persistent fever after 4-7 days of antibiotics (empiric antifungal).',
    'Strict neutropenic precautions: private room, hand hygiene, avoid fresh flowers/fruit, cooked diet only. Mouth care: Chlorhexidine mouthwash QID for mucositis.',
    'Admit to isolation room. Start IV Piperacillin/Tazobactam immediately. Blood cultures before antibiotics (do NOT delay antibiotics for cultures). Monitor vitals, temperature, ANC daily. Continue antibiotics until ANC >500 and afebrile for 48 hours. If ANC remains <100 after 7 days and persistent fever, add empiric antifungal.',
    '1. Life-threatening febrile neutropenia requiring immediate empiric broad-spectrum antibiotics. 2. Chemotherapy-induced severe neutropenia requiring G-CSF support.',
    'Vitals q4h. Temperature q4h. Daily: FBC (ANC), CRP, creatinine, blood cultures if new fever. Monitor for septic shock. Chest X-ray if cough/hypoxia. Monitor for antibiotic side effects. Daily mouth inspection.',
    'Fever after chemotherapy is a medical emergency — you did the right thing coming in immediately. You need IV antibiotics and close monitoring until your white blood cell count recovers (usually 3-5 days). You are in isolation to protect you from infection. Hand washing is the most important thing we all can do.',
    'Continue antibiotics until ANC >500. Discharge when afebrile for 48 hours and ANC >500. Next chemotherapy cycle: consider G-CSF primary prophylaxis.',
    'Febrile neutropenia: ANC <500 and a single temperature >38.3°C or temperature >38°C for >1 hour. This is an oncologic emergency — antibiotics must be given within 1 hour of presentation. MASCC score helps risk-stratify: Low risk (>21) can be managed with oral antibiotics as outpatient. High risk (<15) requires inpatient IV antibiotics. The most common source of infection is the patient\'s own GI flora (translocation through damaged mucosa). G-CSF reduces duration of neutropenia but does not reduce mortality.',
    ['IDSA Guidelines: Febrile Neutropenia', 'NCCN Guidelines: Myeloid Growth Factors', 'Kenya Cancer Treatment Guidelines'],
  ),
  tpl('Chemotherapy & Antimicrobial Pharmacology', 'Infectious Diseases', 'Typhoid Fever', 'Typhoid Fever in a Young Adult with Prolonged Fever', 'Intermediate',
    'High fever for 10 days with headache, abdominal pain, and constipation',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 10-day history of daily high fever (39-40°C, worse in evenings), severe frontal headache, malaise, loss of appetite, and abdominal discomfort. Initially constipated, now has loose stools. Reports a dry cough. No vomiting. No blood in stool. No rash. Drinks water from a borehole; street food consumption.',
    'No significant PMH. No chronic medications.',
    'Took paracetamol for fever with minimal effect. No antibiotics.',
    'Fever 39.5°C. Toxic appearing. Relative bradycardia (HR 90 for temp 39.5°C). Rose spots noted on chest (faint, blanching maculopapules). Mild hepatomegaly (2cm below costal margin). Spleen tip palpable. Abdomen: mild diffuse tenderness, no guarding. Coated tongue. Chest: clear.',
    'WBC 6.5 x10^9/L (leukopenia). Hb 12.0. Platelets 180. CRP 85. Blood culture: drawn (yield best in first week of illness). Widal test: O agglutinin titre 1:160 (positive). Stool culture: pending. LFTs: AST 65, ALT 55. Urinalysis: normal.',
    'No acute imaging. CXR: normal.',
    'Enteric Fever (Typhoid) — Presumptive, Awaiting Culture Confirmation',
    ['Typhoid Fever', 'Malaria', 'Dengue Fever', 'Brucellosis', 'Viral Hepatitis'],
    'Eradicate Salmonella Typhi, resolve fever, prevent complications (intestinal perforation, haemorrhage, chronic carriage)',
    '1. First-line empiric therapy: Oral Azithromycin 1g daily for 7 days (preferred due to increasing fluoroquinolone resistance). 2. Alternative: IV Ceftriaxone 2g daily for 10-14 days (if severe, vomiting, or complications). 3. If fluoroquinolone-susceptible confirmed: Ciprofloxacin 500mg BID for 10 days (check sensitivity first). 4. Do NOT use Amoxicillin or Co-trimoxazole (high resistance). 5. Antipyretics: Paracetamol 1g QID PRN. 6. Avoid anti-motility agents for diarrhoea.',
    'Adequate hydration (ORS or IV fluids if unable to tolerate oral). Small frequent meals. Rest. Strict hand hygiene. Proper food and water sanitation. Notify public health authorities.',
    'Start oral Azithromycin 1g daily for 7 days. If vomiting or severe, admit for IV Ceftriaxone. Monitor temperature and symptoms. Report any sudden worsening of abdominal pain, tenderness, or distension (possible perforation). Stool cultures at end of treatment to confirm clearance. Contact tracing of household contacts.',
    '1. Systemic Salmonella infection requiring effective antibiotic therapy. 2. Public health: reportable disease requiring source investigation and prevention.',
    'Temperature chart (should improve in 3-5 days). Monitor for: abdominal distension, tenderness (perforation — occurs in 3-5% in week 2-3), GI bleeding, altered mental status. Stool culture post-treatment to confirm clearance.',
    'Typhoid is spread through contaminated food and water. Treatment takes about a week, and fever should gradually improve. Drink only boiled or treated water. Wash hands thoroughly with soap, especially after using the toilet and before eating. Do not prepare food for others until your stool tests show you are no longer carrying the bacteria.',
    'Review in 1 week to assess treatment response. Repeat stool culture 1 week after completing antibiotics to confirm clearance. If relapse (5-10%): re-treat with different antibiotic class.',
    'Typhoid fever is a notifiable disease in Kenya. The classic "stepladder" fever pattern (gradually rising over days) is less common; most present with sustained high fever. Relative bradycardia (pulse-temperature dissociation) is a classic sign. Widal test is unreliable in endemic areas (high baseline titres) — culture confirmation is gold standard. Intestinal perforation typically occurs in the 2nd-3rd week of illness and presents with acute abdomen. Multi-drug resistant (MDR) S. Typhi and XDR (extensively drug-resistant) strains are emerging — Azithromycin and Ceftriaxone are current first-line options.',
    ['WHO Guidelines: Typhoid Fever Management', 'Kenya Clinical Guidelines: Enteric Fever', 'CDC: Typhoid Fever'],
  ),
];
