// ================================================================
// Clinical Pharmacy — Case Templates (5 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const CLINICAL_PHARMACY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Clinical Pharmacy', 'Clinical Pharmacy / Polypharmacy', 'Polypharmacy Review', 'Complex Polypharmacy Review in an Elderly Patient with Multiple Comorbidities', 'Advanced',
    'Patient on 12 regular medications — dizziness, falls, confusion, and poor adherence',
    '{name}, a {age}-year-old retired {occupation} from {location}, presents for a comprehensive medication review. Currently on 12 regular medications. Over the past 3 months: 2 falls at home, increasing confusion (attributed to "old age"), dizziness on standing, poor appetite, and significant weight loss (6kg). Daughter reports patient frequently misses doses and gets confused about which medications to take. Recently admitted for a fall that caused a hip contusion.',
    'Type 2 Diabetes (20 years), Hypertension (20 years), CKD Stage 3b (eGFR 38), Ischaemic Heart Disease (post-MI 5 years ago, on dual antiplatelet), Heart Failure with reduced EF (EF 40%), Atrial Fibrillation (CHA2DS2VASc 7), Osteoarthritis (knees, hips), Benign Prostatic Hyperplasia, Depression (mild), Insomnia',
    `Medication List (12 regular meds):
1. Metformin 1g BID
2. Glibenclamide 5mg BID
3. Amlodipine 10mg daily
4. Losartan 100mg daily
5. Bisoprolol 5mg daily
6. Aspirin 75mg daily
7. Clopidogrel 75mg daily
8. Warfarin 5mg daily (INR target 2-3)
9. Furosemide 40mg daily
10. Spironolactone 25mg daily
11. Omeprazole 20mg daily (started in hospital 3 months ago)
12. Paracetamol 1g QID (PRN)
+ Zopiclone 7.5mg at bedtime (PRN for sleep)
+ Ibuprofen 400mg PRN (for joint pain — self-prescribed)`,
    'BP supine 142/88, BP standing 108/64 (orthostatic hypotension — drops 34/24). HR 62 (irregularly irregular). BMI 21 (underweight). Mild pedal oedema. Heart sounds: S1 variable, no murmurs. Lungs: mild basal crackles. Abdomen: soft. Cognitive assessment: Montreal Cognitive Assessment (MoCA) 20/30 (mild cognitive impairment). Gait: slow, unsteady, uses walking stick.',
    'K+ 4.2, Na+ 135, Cr 1.9 (eGFR 38), Hb 10.2 (normocytic — anaemia of CKD), INR 3.1 (supratherapeutic — target 2-3). HbA1c 6.8% (on target, but risk of hypoglycaemia due to glibenclamide + reduced renal function). TSH normal. Vitamin D 18 ng/mL (deficient). B12 185 pg/mL (low borderline).',
    'No acute imaging indicated.',
    'Polypharmacy (12 regular medications) with Drug-Related Problems: Adverse Drug Reactions, Drug-Drug Interactions, Inappropriate Prescribing in Older Adults, Suboptimal Adherence, and High Risk of Major Bleeding and Falls',
    ['Polypharmacy with drug-related problems', 'Dementia (medication-induced cognitive impairment)', 'Frailty syndrome', 'Age-related cognitive decline', 'Anaemia of chronic disease'],
    'Reduce pill burden, withdraw potentially inappropriate medications, correct drug-drug interactions, simplify regimen, improve adherence and quality of life',
    '1. STOP Aspirin (no benefit in stable CAD on Clopidogrel + Warfarin — triple therapy increases bleeding risk). 2. STOP Ibuprofen (contraindicated in CKD, HF, and on anticoagulation — nephrotoxic, increases bleeding risk, worsens HF). 3. STOP Glibenclamide (risk of hypoglycaemia in elderly with CKD — SULFONYLUREA of longest duration and highest hypoglycaemia risk). SWITCH to: lower-risk sulfonylurea (Glipizide 5-10mg daily) or DPP-4i (Sitagliptin 50mg daily) or SGLT2i (Dapagliflozin 10mg — but eGFR 38 so use with caution). 4. REDUCE Bisoprolol dose (2.5mg daily — still provides beta-blockade but less orthostatic hypotension). 5. Consider STOP Spironolactone (hyperkalaemia risk with eGFR 38 + warfarin interaction). 6. STOP Omeprazole unless clear ongoing indication (PPI use >8 weeks without indication — risk of B12 deficiency, fractures, C. diff, CKD). 7. STOP Zopiclone (falls risk + cognitive impairment in elderly). 8. Optimise Warfarin: check INR more frequently, reduce dose if needed (currently supratherapeutic). 9. Replace Paracetamol with simple PRN analgesia — avoid NSAIDs. 10. Simplify regimen: Once-daily where possible (e.g., Losartan/amlodipine single pill combination, Metformin XR once daily). 11. Bone health trial: Vitamin D 800 IU daily, Calcium 500mg daily. 12. Consider: START antidepressant with better safety profile if depression warrants treatment (SSRI — Sertraline 25-50mg daily, but monitor for bleeding risk with warfarin).',
    'Simplify packaging: Pill organiser (dosette box). Use large-print labels. Involve daughter/carer in medication management. Fall prevention: home safety assessment, remove rugs, improve lighting, non-slip shoes. Physiotherapy for gait and balance. Nutritional support (appetite stimulants, high-calorie supplements).',
    'Comprehensive medication review completed. Deprescribe: Aspirin, Ibuprofen, Glibenclamide, Zopiclone, Omeprazole. Reduce Bisoprolol. Consider switching to DPP-4i. Continue warfarin with close INR monitoring. Start Vitamin D + Calcium. Arrange pill organiser and carer support. Refer to dietitian. Review in 2 weeks for INR and to reassess adherence.',
    '1. Complex polypharmacy with 12 medications in an elderly patient with multiple comorbidities, CKD, and falls risk. 2. Multiple potentially inappropriate medications per Beers Criteria and STOPP/START criteria. 3. High bleeding risk (triple therapy + NSAID + supratherapeutic INR).',
    '2 weeks: INR, Cr/eGFR, K+, Hb. Monthly: BP, orthostatic vitals, adherence check. 3 monthly: HbA1c, LFTs, cognitive screening. Annual: falls risk assessment, medication review, renal function.',
    'Your loved one is on too many medications — some may be causing more harm than good. We will slowly stop the medications that are not needed or that increase the risk of falls and bleeding. We will simplify the remaining ones so they are easier to take. Do NOT stop any medications without consulting us first — especially the blood thinner (warfarin).',
    'GP/Clinical Pharmacist monthly for medication review and INR. Falls clinic. Dietitian. Physiotherapy. Geriatrician if cognitive decline progresses. Review need for anticholinergic burden (avoid if possible).',
    'Polypharmacy is the single greatest risk factor for adverse drug events in older adults. The Beers Criteria (AGS) and STOPP/START criteria are essential tools for deprescribing in the elderly. The most dangerous medications in older adults: benzodiazepines, anticholinergics, long-acting sulfonylureas, NSAIDs, and triple antithrombotic therapy. A good rule of thumb: for every medication, ask "Is the indication still present? Is the dose appropriate? Is there a safer alternative? Can we stop it?" The "prescribing cascade" is common — treating an ADR with another drug (e.g., giving omeprazole for dyspepsia from aspirin, or antihypertensives for bisoprolol withdrawal). Always check for drug interactions in the elderly.',
    ['ACS Beers Criteria for Potentially Inappropriate Medication Use in Older Adults', 'STOPP/START Criteria', 'WHO: Medication Safety in Older Adults', 'Kenya Clinical Guidelines: Geriatric Care'],
  ),
  t('Clinical Pharmacy', 'Clinical Pharmacy / Antimicrobial Stewardship', 'Antimicrobial Stewardship', 'Antimicrobial Stewardship Review: De-Escalation of Broad-Spectrum Antibiotics', 'Advanced',
    'IV Meropenem started empirically 72 hours ago — patient improving — is de-escalation appropriate?',
    '{name}, a {age}-year-old {occupation} from {location}, was admitted 3 days ago with severe community-acquired pneumonia (CAP) and septic shock. Started on IV Meropenem 1g q8h + Vancomycin 1g q12h empirically. Patient is now clinically improving: fever resolved, BP normalising off vasopressors, O2 saturations improving on 2L nasal prongs (from 15L non-rebreather). Microbiology results now returning. Pharmacy/ID team is reviewing for antimicrobial de-escalation.',
    'No significant PMH. No known drug allergies. No recent hospitalisations. Immunocompetent.',
    'Status epilepticus — no regular meds. Hospital: IV Meropenem 1g q8h (72h), IV Vancomycin 1g q12h (72h).',
    'Current: HR 88, BP 118/72 (off vasopressors), Temp 37.1, RR 20, SpO2 94% on 2L NC. Chest: decreased air entry right lower zone, resolving. Improved from admission: 3 days ago — Temp 39.8, HR 112, BP 82/48, RR 32, SpO2 84% on RA.',
    `Blood cultures (day 0): Streptococcus pneumoniae (penicillin MIC 0.06 mcg/mL — susceptible). Sputum culture: S. pneumoniae (same). No MRSA. No gram-negatives.
Labs: WBC 9.2 (was 18.0 on admission), Neutrophils 70%, CRP 35 mg/L (was 180), Procalcitonin 0.5 ng/mL (was 25). Cr 0.9, eGFR >60.
CRP/PCT trend confirms resolving infection.`,
    'Chest X-ray (today): Right lower lobe consolidation (resolving, decreased density compared to admission).',
    'Severe Community-Acquired Pneumonia due to Penicillin-Susceptible Streptococcus pneumoniae — Clinically Responding to Treatment',
    ['Severe CAP (S. pneumoniae)', 'Hospital-Acquired Pneumonia', 'Aspiration Pneumonia', 'Atypical Pneumonia'],
    'De-escalate antibiotics based on microbiology, avoid unnecessary broad-spectrum use, prevent antimicrobial resistance, reduce side effects and cost',
    '1. STOP Vancomycin (no MRSA identified, no indications for ongoing MRSA coverage). 2. De-escalate Meropenem: Transition to a narrower-spectrum, penicillin-based regimen. OPTIONS: IV Benzylpenicillin 4 million units q4h (narrowest, most targeted, and penicillin-susceptible S. pneumoniae). OR IV Amoxicillin/Clavulanate 1.2g q8h (broader, but better oral step-down option). 3. If clinically stable and tolerating oral: Step down to oral Amoxicillin 1g TID or Amoxicillin/Clavulanate 625mg TID to complete 7-day course (4 days remaining). 4. Duration: 7 days total (from day 1 of effective therapy) — current evidence supports shorter courses for CAP if clinical improvement. 5. No role for continued broad-spectrum therapy when directed therapy is available.',
    'Monitor clinical status: vitals, O2 requirements, chest signs. Encourage early mobilisation. Nutritional support. Deep breathing exercises. Ensure adequate hydration.',
    'De-escalate: STOP Vancomycin. Switch Meropenem → IV Benzylpenicillin 4MU q4h (or Amoxicillin/Clavulanate IV). If tolerating oral in 24h: switch to Amoxicillin 1g TID or Amoxicillin/Clavulanate 625mg TID. Complete 7 days total. Discharge when stable (afebrile 24h, SpO2 >92% on RA, tolerating oral).',
    '1. Clear microbiology results allow targeted therapy — de-escalation is a core antimicrobial stewardship principle. 2. Unnecessary broad-spectrum antibiotics increase risk of C. difficile, resistance, and adverse effects.',
    'Daily: vitals, O2 sat, chest signs, temperature, oral tolerance. Labs: repeat CRP/PCT trend (optional if resolving). No routine cultures needed unless deterioration. Monitor for C. difficile (diarrhoea) — risk increased by broad-spectrum antibiotics.',
    'You are recovering well. The lab has identified the bacteria causing your pneumonia and it is sensitive to a simpler, safer antibiotic. We are therefore changing your antibiotics from the very broad ones to a more targeted treatment. This reduces side effects and helps prevent antibiotic resistance.',
    'Complete antibiotic course (7 days total). Follow-up: chest X-ray in 6 weeks for radiological resolution (if >50 years or smoker). Pneumococcal vaccination before discharge. Influenza vaccination (annually).',
    'Antimicrobial stewardship is not about restricting antibiotics — it\'s about choosing the RIGHT antibiotic, at the RIGHT dose, for the RIGHT duration. De-escalation is safe and recommended once microbiology results are available and the patient is clinically improving. Procalcitonin is a useful biomarker to guide duration and de-escalation decisions. The mantra: "Start smart, then focus." In severe CAP, S. pneumoniae is still the most common pathogen — and it is often penicillin-susceptible. Vancomycin should be stopped if MRSA is ruled out — continuing it unnecessarily increases nephrotoxicity risk.',
    ['IDSA Guidelines: Antimicrobial Stewardship', 'WHO: Antimicrobial Stewardship Programs', 'Kenya Clinical Guidelines: Antibiotic Use', 'CDC: Core Elements of Antibiotic Stewardship'],
  ),
  t('Clinical Pharmacy', 'Clinical Pharmacy / Transitions of Care', 'Medication Reconciliation', 'Medication Reconciliation and Transitions of Care in Heart Failure Discharge', 'Intermediate',
    'Discharge medication list differs significantly from pre-admission medications — pharmacist review needed',
    '{name}, a {age}-year-old retired {occupation} from {location}, is being discharged after a 10-day admission for decompensated heart failure (acute pulmonary oedema requiring IV furosemide). During admission, several medication changes were made: furosemide was switched from IV to oral, lisinopril was stopped due to acute kidney injury (creatinine rose from 1.2 to 2.1 mg/dL), bisoprolol was held due to bradycardia (HR 48 bpm), and two new medications were started — dapagliflozin 10mg and spironolactone 25mg. Patient also has type 2 diabetes and COPD. Daughter reports confusion about which medications to continue and which to stop. Patient feels anxious about going home on "different medications."',
    'Heart Failure with reduced EF (EF 30%, known 2 years), Type 2 Diabetes (10 years, on insulin), COPD Stage II, CKD Stage 3a (baseline eGFR 45, now 35), Hypertension, Osteoarthritis',
    'Pre-admission Medications: 1. Furosemide 80mg OD, 2. Lisinopril 10mg OD, 3. Bisoprolol 5mg OD, 4. Metformin 500mg BID, 5. Gliclazide 80mg BID, 6. Insulin Glargine 20 units at bedtime, 7. Salbutamol MDI 2 puffs PRN, 8. Tiotropium 18mcg OD inhaler, 9. Paracetamol 1g QID PRN. Discharge Medications: 1. Furosemide 80mg OD, 2. Bisoprolol 2.5mg OD (halved dose), 3. Metformin 500mg BID (continued), 4. Gliclazide 80mg OD (reduced from BID), 5. Insulin Glargine 16 units at bedtime (reduced), 6. Salbutamol MDI 2 puffs PRN, 7. Tiotropium 18mcg OD, 8. Dapagliflozin 10mg OD (NEW), 9. Spironolactone 25mg OD (NEW). STOPPED: Lisinopril. Paracetamol not prescribed on discharge.',
    'BP 118/72, HR 64 (irregularly irregular, previously 48 on admission). SpO2 94% on RA. Weight 78 kg (down 4 kg from admission — decongested). JVP not elevated. No peripheral oedema. Lungs: clear bilaterally. Mild bilateral crackles at bases.',
    'Cr 1.8 (improving from 2.1 on admission, baseline 1.2), eGFR 38. K+ 5.1 (mildly elevated — watch with spironolactone + no ACEi). Na+ 136. Hb 11.2. HbA1c 7.8% (suboptimal). BNP 850 pg/mL (down from 2200 on admission). INR 1.1. LFTs normal.',
    'Chest X-ray: resolving pulmonary oedema, mild cardiomegaly, bilateral pleural effusions (improved). ECG: AF, rate 64, no acute changes.',
    'Decompensated Heart Failure with Multiple Medication Changes Requiring Comprehensive Discharge Medication Reconciliation',
    ['Medication error at transitions of care', 'Heart failure decompensation', 'Drug-induced AKI', 'Hyperkalaemia risk (spironolactone + CKD)', 'Inappropriate prescribing in CKD'],
    'Ensure accurate medication reconciliation between admission and discharge, identify and resolve all discrepancies, counsel patient and caregiver on new and changed medications, prevent 30-day readmission, ensure safe transition from hospital to home',
    '1. Discrepancy 1 — Lisinopril STOPPED: correctly held during AKI (creatinine 2.1, K+ 5.1). Plan: monitor renal function and K+ outpatient. When Cr returns to baseline (<1.5) and K+ <5.0, consider restarting at low dose (Lisinopril 2.5mg) or switching to Candesartan. 2. Discrepancy 2 — Bisoprolol REDUCED from 5mg to 2.5mg: appropriate given bradycardia on admission. Plan: uptitrate back to 5mg once HR consistently >60 at rest. 3. Discrepancy 3 — Gliclazide REDUCED from BID to OD: appropriate to avoid hypoglycaemia with reduced insulin and renal function. 4. Discrepancy 4 — Insulin Glargine REDUCED from 20 to 16 units: appropriate given reduced oral hypoglycaemics stopped (no ACEi), and lower calorie intake during admission. 5. NEW — Dapagliflozin 10mg: SGLT2 inhibitor with mortality benefit in HFrEF (DAPA-HF trial). counsel: take in morning, may cause genital yeast infection, ensure adequate hydration, will reduce blood sugar slightly. NOT indicated for glycaemic control alone — this is for heart failure. 6. NEW — Spironolactone 25mg: mineralocorticoid receptor antagonist with mortality benefit in HFrEF (RALES trial). Counsel: take in morning, avoid potassium-rich salt substitutes, risk of hyperkalaemia with CKD — monitor K+ at 1 week and 4 weeks. 7. MISSING — Paracetamol was on pre-admission list but not prescribed at discharge: add back PRN for osteoarthritis pain (safe in CKD). 8. Renal protective measures: avoid NSAIDs, avoid nephrotoxic drugs, maintain hydration, sick-day rules for metformin (hold if dehydrated/vomiting).',
    'Medication reconciliation completed. All discrepancies identified and explained. Patient and daughter educated on: new medications (dapagliflozin, spironolactone), stopped medications (lisinopril), dose changes (bisoprolol, gliclazide, insulin). Provided written discharge medication list. Sick-day rules provided. Pill organiser arranged. GP letter with medication changes sent.',
    'Comprehensive care plan: Continue Furosemide 80mg OD, Bisoprolol 2.5mg OD (uptitrate as tolerated), Metformin 500mg BID, Gliclazide 80mg OD, Insulin Glargine 16 units at bedtime, Dapagliflozin 10mg OD, Spironolactone 25mg OD, Tiotropium 18mcg OD, Salbutamol PRN. Add Paracetamol PRN for osteoarthritis. Monitor K+ and Cr in 1 week before considering restarting ACEi. Avoid NSAIDs. Follow sick-day rules for metformin.',
    '1. Four medication discrepancies identified between pre-admission and discharge lists — medication reconciliation prevented potential harm. 2. Hyperkalaemia risk: Spironolactone + CKD + no ACEi — close K+ monitoring required. 3. Hypoglycaemia risk: insulin + gliclazide + SGLT2i + reduced renal function — educate on symptoms.',
    'K+ and Cr at 1 week post-discharge, then at 4 weeks. Blood glucose daily for first 2 weeks (hypoglycaemia risk with multiple changes). BP twice weekly (home monitoring). Weight daily (decompensated HF red flags: >2kg gain in 48h). HbA1c at 3 months.',
    'Your heart medications have changed. Two new medications have been added — one helps your heart pump better and one protects your kidneys. One medication (lisinopril) was stopped because it affected your kidneys during this admission. The blood thinner dose was reduced because your heart rate was slow. Please take your medications at the same time each morning. Weigh yourself daily — if you gain more than 2 kg in 2 days, call us. Avoid salt substitutes (they contain potassium). Do not take ibuprofen or any NSAIDs. If you feel dizzy, weak, or confused, come to the hospital immediately.',
    'GP review in 1 week for BP, weight, and symptom assessment. Heart failure clinic in 4 weeks. Renal function (K+, Cr) at 1 week and 4 weeks. Echocardiogram in 3 months to reassess EF. Annual influenza and pneumococcal vaccination.',
    'Medication reconciliation is a critical pharmacy intervention that reduces adverse drug events by 50% during care transitions. The most common discrepancies at discharge are: omissions (intentional drugs not re-prescribed), dose changes not documented, and new medications not explained. In heart failure, SGLT2 inhibitors (dapagliflozin, empagliflozin) now have Class I indication for HFrEF regardless of diabetes status (DAPA-HF, EMPEROR-Reduced trials). Spironolactone reduces mortality by 30% in HFrEF but carries hyperkalaemia risk — monitor K+ closely in CKD. Sick-day rules are essential for patients on metformin, ACE inhibitors, and diuretics.',
    ['ISMP: Medication Reconciliation Best Practices', 'WHO: Medication Safety in Transitions of Care', 'Kenya Clinical Guidelines: Heart Failure Management', 'DAPA-HF Trial (NEJM 2019)'],
  ),
  t('Clinical Pharmacy', 'Clinical Pharmacy / Pharmacokinetics', 'Therapeutic Drug Monitoring', 'Vancomycin Trough-Guided Dosing in a Patient with MRSA Bacteraemia and Changing Renal Function', 'Advanced',
    'IV Vancomycin being given for MRSA bacteraemia — request for TDM and dose adjustment based on renal function and trough levels',
    '{name}, a {age}-year-old {occupation} from {location} (weight 78 kg), is on Day 4 of IV Vancomycin 1g q12h for methicillin-resistant Staphylococcus aureus (MRSA) bacteraemia from an infected central line. Blood cultures growing MRSA (vancomycin MIC 1.0 mcg/mL). Current vancomycin trough level drawn this morning: 8.5 mcg/mL. Serum creatinine rising from a baseline of 1.0 to 1.6 mg/dL (eGFR 42). Patient is in the medical ICU. The clinical pharmacist has been consulted to optimise vancomycin dosing using pharmacokinetic principles.',
    'Type 2 Diabetes (8 years), Hypertension, CKD Stage 3b (baseline eGFR 48), Recent central line-associated bloodstream infection, No known drug allergies',
    'IV Vancomycin 1g q12h (Day 4), IV Piperacillin-Tazobactam 4.5g q6h, IV Normal Saline maintenance, Insulin sliding scale, Amlodipine 5mg daily, Pantoprazole 40mg daily',
    'Temp 38.1°C (improving from 39.5°C on Day 1). HR 88, BP 118/72, RR 20, SpO2 96% on RA. Central line site: mild erythema but no purulent discharge. Lungs clear. Central line tip culture: pending. Blood cultures (Day 4): pending clearance.',
    'Vancomycin trough (Day 4, pre-4th dose): 8.5 mcg/mL (target 15-20 mcg/mL for MRSA bacteraemia). Cr 1.6 mg/dL (baseline 1.0, rising), eGFR 42. BUN 32 mg/dL. K+ 4.0. WBC 11.5 (was 18.0 on admission). CRP 35 (was 120). MRSA MIC to vancomycin: 1.0 mcg/mL (intermediate susceptibility per CLSI — borderline). Blood cultures (Day 1): MRSA positive. Repeat cultures pending.',
    'ECHO: no vegetations (rule out endocarditis — negative). CXR: no infiltrates. Central line Doppler: DVT ruled out.',
    'MRSA Central Line-Associated Bloodstream Infection (CLABSI) with Subtherapeutic Vancomycin Trough Levels and Acute Kidney Injury — Requiring Pharmacokinetic Dose Optimisation',
    ['MRSA CLABSI', 'Acute Kidney Injury (vancomycin ± piperacillin-tazobactam induced)', 'Catheter-related bloodstream infection', 'Infective endocarditis (rule out)'],
    'Achieve therapeutic vancomycin trough 15-20 mcg/mL, prevent further nephrotoxicity, clear MRSA bacteraemia, remove infected central line, optimise antimicrobial duration',
    '1. VANCOMYCIN DOSING (Pharmacokinetic Approach): Current dose: 1g q12h (~12.8 mg/kg/dose). Trough: 8.5 mcg/mL (subtherapeutic). Estimated CrCl (Cockcroft-Gault): ~45 mL/min. Suggested dose adjustment: Increase to 15 mg/kg/dose (≈1.2g) q12h. Verify with: NEW trough in 3-4 doses (Day 6-7). Target: trough 15-20 mcg/mL. If Cr continues to rise: extend interval to q24h rather than increasing dose (to reduce AUC-related nephrotoxicity). 2. Alternative: If vancomycin MIC >1.5 or rising Cr/not achieving target: consider switch to Daptomycin 8-10 mg/kg IV q24h (Cubicin) or Linezolid 600mg IV/PO q12h (if no cytopenias). 3. NEPHROTOXICITY MANAGEMENT: Piperacillin-Tazobactam increases vancomycin nephrotoxicity risk (synergistic AKI). Consider switching to Cefepime if gram-negative coverage still needed. Maintain IV fluids (1 mL/kg/hr). Avoid concurrent NSAIDs, IV contrast, and other nephrotoxins. 4. LINE MANAGEMENT: Remove infected central line immediately — source control is essential. Insert new line at a different site. 5. DURATION: Minimum 14 days from first negative blood culture. Repeat blood cultures daily until negative. 6. MONITORING: Vancomycin trough pre-4th dose after dose change. Cr, BUN daily. Urine output. Consider AUC-based monitoring if available (target AUC24/MIC >400).',
    'Remove infected central line. Insert PICC or new central line. Daily blood cultures until negative. Adequate hydration (IV fluids 1 mL/kg/hr). Nutritional support. Strict hand hygiene and line maintenance protocols.',
    'Adjust Vancomycin to 1.2g q12h (15 mg/kg). Increase frequency of trough monitoring to q72h. Remove existing central line today and insert new line. Start IV fluids 80 mL/hr. Monitor Cr, K+, and trough levels daily. If trough remains subtherapeutic after dose adjustment, consider Daptomycin switch. Discuss with infectious diseases team. Continue for 14 days after first negative culture.',
    '1. Subtherapeutic vancomycin trough in MRSA bacteraemia: trough 8.5 vs target 15-20 mcg/mL — AUC/MIC likely <400 — risk of treatment failure. 2. Vancomycin-induced acute kidney injury: rising Cr from 1.0 to 1.6 while on vancomycin + piperacillin-tazobactam (synergistic nephrotoxicity). 3. Infected central line: source control required for cure.',
    'Vancomycin trough after dose change (Day 7-8). Cr, BUN, K+ daily. Repeat blood cultures daily until negative (minimum 2 sets). Temperature chart. Urine output. Signs of vancomycin infusion reaction (Red Man Syndrome) with increased dose — pre-medicate with antihistamine, slow infusion rate to 1-2 hours. Audiological monitoring if prolonged therapy.',
    'Vancomycin is a powerful antibiotic, but it must be carefully dosed to make sure enough drug reaches the bacteria. We are increasing your dose based on blood levels. We need frequent blood tests to monitor kidney function and drug levels. The infected central line must be removed to fully treat the infection — this is a critical step. Drink plenty of fluids. Report any hearing changes, ringing in ears, or dizziness (vancomycin can rarely affect hearing).',
    'Infectious Diseases follow-up for duration of therapy. Repeat echocardiogram to rule out endocarditis if persistent bacteraemia. Continue trough monitoring q72h. If renal function stabilises, can transition to outpatient parenteral antimicrobial therapy (OPAT). Audiological assessment if therapy extends beyond 4 weeks.',
    'Vancomycin pharmacokinetics: Volume of distribution = 0.7 L/kg (approx). Half-life: 6-12 hours with normal renal function, extends significantly in AKI. Trough monitoring is standard but AUC-guided dosing (AUC24/MIC >400) is superior for efficacy and safety. The ratio of vancomycin to piperacillin-tazobactam in causing AKI is synergistic — avoid this combination when possible. MRSA with vancomycin MIC >1.5 mcg/mL should be treated with alternative agents (daptomycin, linezolid, ceftaroline). Red Man Syndrome is not an allergic reaction — it is a histamine release phenomenon that can be managed by slowing the infusion and pre-treating with antihistamines. Remove the central line — antibiotics without source control will NOT cure the infection.',
    ['IDSA Guidelines: MRSA Infections', 'Sanford Guide to Antimicrobial Therapy', 'ASHP Guidelines: Vancomycin Monitoring', 'Kenya Clinical Guidelines: Antimicrobial Stewardship'],
  ),
];
