// ================================================================
// CNS Pharmacology — Case Templates
// 8 templates covering: Epilepsy, Parkinsons, Alzheimers, Migraine,
// Depression, Anxiety, Bipolar, Schizophrenia
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';
function tpl(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}

export const CNS_TEMPLATES: ClinicalCaseTemplate[] = [
  tpl(
    'Central Nervous System Pharmacology', 'Neurology', 'Epilepsy', 'New-Onset Generalised Tonic-Clonic Seizure in a Young Adult', 'Intermediate',
    'Sudden loss of consciousness with convulsions for 5 minutes — first episode ever',
    '{name}, a {age}-year-old {occupation} from {location}, had a witnessed generalised tonic-clonic seizure lasting ~5 minutes at work. Was confused and sleepy for 30 minutes post-ictally. No prior seizures. No head trauma. No alcohol or drug use. No fever. No family history of epilepsy.',
    'No significant PMH. No prior head injuries. No meningitis/encephalitis history.',
    'No regular medications',
    'Post-ictal state, drowsy but orienting. USA. No focal neurological deficits. Fundoscopy normal. No meningism. GCS 15 at time of exam.',
    'Glucose 95 mg/dL. Na+ 140, K+ 4.1, Ca 9.0, Mg 2.0. CBC normal. LFTs normal. Toxicology screen: negative. EEG (after 24h): interictal epileptiform discharges (spike-wave) over right temporal region. MRI brain: normal.',
    '',
    'New-Onset Epilepsy — Right Temporal Lobe Epilepsy with Generalised Tonic-Clonic Seizures',
    ['Generalised Epilepsy', 'Focal Epilepsy', 'Syncope', 'Psychogenic Non-Epileptic Seizure', 'Hypoglycaemia'],
    'Confirm diagnosis, exclude secondary causes, initiate monotherapy antiseizure drug, advise on driving and safety',
    '1. First-line monotherapy for focal seizures: Levetiracetam 250-500mg BID (titrate to 1000-1500mg BID), OR Carbamazepine MR 200mg BID (titrate to 400-600mg BID). 2. Alternative first-line: Lamotrigine 25mg daily (titrate slowly over 6-8 weeks to 100-200mg BID). 3. Seizure rescue: Buccal Midazolam 10mg PRN for prolonged seizures (>5 min). 4. Start at low dose and titrate to seizure control/side effects. 5. Check FBC, LFTs, Na before and during Carbamazepine therapy.',
    'Driving restriction: must not drive for at least 6 months after last seizure (report to NTSA in Kenya). Avoid sleep deprivation. Avoid alcohol excess. Safe bathing (shower not bath).',
    'Start AED monotherapy. Counsel on driving restrictions, medication adherence, and seizure triggers. Arrange follow-up EEG in 3-6 months. Advise family on first aid during seizures. Register with epilepsy clinic.',
    '1. New-onset epilepsy requiring initiation of maintenance AED therapy. 2. Safety risk: driving, work, and daily activities during titration period.',
    'Seizure diary (frequency, type, triggers). AED side effects (drowsiness, dizziness, rash). Drug levels (if on Carbamazepine or Phenytoin). FBC, LFTs, Na at 1 month (if on CBZ).',
    'Take your medication exactly as prescribed — missing doses can trigger seizures. Do not drive until your doctor confirms it is safe. Avoid alcohol and sleep deprivation. Your family should know basic seizure first aid (recovery position, time the seizure, call 911 if >5 min).',
    'Neurology clinic in 4-6 weeks for dose titration. Driving fitness assessment. If seizure-free for 2 years on monotherapy, consider medication withdrawal (under specialist guidance).',
    'In new-onset epilepsy: EEG and MRI brain are standard. EEG can be normal interictally — sleep-deprived EEG increases yield. Levetiracetam is preferred for focal seizures (good efficacy, no drug interactions, rapid titration). Carbamazepine is effective but induces CYP450 and causes hyponatraemia. Lamotrigine has excellent tolerability but requires very slow titration. In Kenya: Phenobarbital is cheapest but has sedation and tolerance issues — use as last resort.',
    ['ILAE Guidelines: Epilepsy Management', 'Kenya Clinical Guidelines: Epilepsy', 'WHO: Epilepsy Management'],
  ),
  tpl(
    'Central Nervous System Pharmacology', 'Neurology', 'Parkinson Disease', 'Idiopathic Parkinson Disease with Worsening Motor Symptoms', 'Intermediate',
    'Progressive tremor, stiffness, slowness of movement, and frequent falls for 1 year',
    '{name}, a {age}-year-old {occupation} from {location}, presents with gradually worsening rest tremor of the right hand (described as "pill-rolling"), stiffness in the right arm and leg, slow movements (difficulty buttoning shirts, getting out of car), shuffling gait, and 2 falls in the past month. Family reports he has a blank facial expression and speaks softly. Symptoms started 2 years ago but attributed to aging. No cognitive decline.',
    'Hypertension (well-controlled). No other chronic illness.',
    'Amlodipine 5mg daily',
    'Masked facies (hypomimia). Rest tremor (right hand, 4-5 Hz, "pill-rolling," decreases with purposeful movement). Cogwheel rigidity in right arm and leg. Bradykinesia (slow finger taps, foot taps). Shuffling gait with reduced arm swing on right. Postural instability (positive pull test — retropulsion). Unified Parkinsons Disease Rating Scale (UPDRS) Part III: 32/108. MMSE: 28/30 (normal).',
    'CBC, CMP: normal. MRI brain: unremarkable (age-appropriate atrophy). DaTSCAN (SPECT): reduced dopamine transporter binding in bilateral putamen (confirmatory).',
    '',
    'Idiopathic Parkinson Disease (Hoehn & Yahr Stage 2.5 — Bilateral disease with mild postural instability)',
    ['Parkinson Disease', 'Essential Tremor', 'Drug-Induced Parkinsonism', 'Multiple System Atrophy', 'Progressive Supranuclear Palsy'],
    'Improve motor function and quality of life, manage symptoms with minimal side effects, prevent falls, plan for disease progression',
    '1. First-line therapy for significant motor impairment: Levodopa/Carbidopa (Co-careldopa) 100/25mg TID, increase gradually to 2 tablets TID as needed. 2. If dyskinesias or motor fluctuations develop: add entacapone 200mg with each Levodopa dose, or consider dopamine agonist (Pramipexole 0.125mg TID titrate slowly, or Ropinirole). 3. Alternative first-line in younger patients (<60): MAO-B inhibitor (Rasagiline 1mg daily, Selegiline 5mg BID) or dopamine agonist. 4. For tremor: Anticholinergic (Trihexyphenidyl/Benzhexol 2mg TID — use cautiously in elderly). 5. Osteoporosis prevention: Calcium + Vit D (fall risk).',
    'Physiotherapy: gait and balance training. Occupational therapy: home modifications, assistive devices. Speech therapy: LSVT (Lee Silverman Voice Treatment). Regular exercise (tai chi, cycling). Fall prevention: home safety assessment, remove rugs, grab bars.',
    'Start Levodopa/Carbidopa 100/25mg TID with meals (or 30 min before meals). Titrate to symptom control over 4-8 weeks. Refer to physiotherapy, occupational therapy, and speech therapy. Optimise blood pressure control (avoid medications causing orthostasis). Review in 4 weeks.',
    '1. Progressive neurodegenerative disease requiring dopaminergic replacement. 2. Fall risk due to postural instability requiring multidisciplinary rehabilitation.',
    'UPDRS motor score at each visit. Frequency and severity of off periods and dyskinesias. Fall diary. Orthostatic BP checks. MMSE/MoCA annually for cognitive decline. Assess for non-motor symptoms: depression, sleep, constipation, pain.',
    'Levodopa is the most effective medication for Parkinsons — it replaces the dopamine your brain is missing. It will significantly improve your movement and quality of life. Some people develop involuntary movements (dyskinesias) after years of use — this can be managed. Continue exercising — it helps slow disease progression. Do not stop medications abruptly (neuroleptic malignant syndrome).',
    'Neurology clinic in 4 weeks for dose titration. Physiotherapy ongoing. Annual cognitive screening. Monitor for disease progression and medication complications. Driving assessment if safety concern.',
    'Levodopa remains the gold standard for Parkinsons — no evidence that early use accelerates disease progression or complications. The "levodopa sparing" approach (starting with dopamine agonists or MAO-B inhibitors) is only for younger patients to delay motor complications. Protein-rich meals can reduce Levodopa absorption — take doses 30-60 min before meals if on/off fluctuations develop. Do not stop Levodopa abruptly (withdrawal can cause neuroleptic malignant syndrome).',
    ['NICE Guideline: Parkinsons Disease', 'MDS Evidence-Based Review: Parkinsons Treatment', 'Kenya Clinical Guidelines: Parkinsons'],
  ),
  tpl(
    'Central Nervous System Pharmacology', 'Psychiatry', 'Depression', 'Moderate-to-Severe Major Depressive Disorder with Atypical Features', 'Intermediate',
    'Persistent low mood, loss of interest, hypersomnia, increased appetite, and hopelessness for 3 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with persistent depressed mood, anhedonia (no longer enjoys hobbies or time with children), excessive sleep (12+ hours/day), increased appetite with weight gain (5 kg), fatigue, and difficulty concentrating. Reports feeling "numb" and "empty." Has passive death wishes but no active plan. No manic or hypomanic episodes. Stressors: financial difficulties and marital conflict. Previous episode 5 years ago after childbirth (postpartum depression, treated with sertraline with good response).',
    'History of postpartum depression (5 years ago, treated with Sertraline 100mg for 12 months, fully recovered). No suicide attempts.',
    'No current medications',
    'Depressed affect, tearful, poor eye contact, psychomotor retardation. Speech slow, quiet. Thought content: helpless, worthless, passive suicidal ideation (no intent/plan). No psychotic features. PHQ-9: 22/27 (severe). GAD-7: 12/21 (moderate anxiety).',
    'TSH: 2.0 mIU/L (normal). B12: 450 pg/mL. Hb: 12.5. FBC normal.',
    '',
    'Major Depressive Disorder, Recurrent, Moderate-Severe (DSM-5)',
    ['Major Depressive Disorder', 'Bipolar Disorder (depressive phase)', 'Adjustment Disorder', 'Hypothyroidism', 'Chronic Fatigue Syndrome'],
    'Achieve remission of depressive symptoms, restore functioning, prevent relapse, ensure safety',
    '1. SSRI: Sertraline 50mg daily for 1 week, then increase to 100mg daily (good previous response). 2. Adjunct for sleep/appetite (atypical features): Mirtazapine 15-30mg at bedtime (sedating, increases appetite, good for weight loss — however patient has increased appetite already, so use cautiously). 3. If minimal response at 6 weeks at 100mg: increase to 150-200mg daily or switch to alternative class (Venlafaxine or Bupropion). 4. If no response at 8 weeks to two adequate trials: refer for psychiatric consultation (consider ECT if severe with suicidality).',
    'Psychotherapy: Cognitive Behavioural Therapy (CBT) or Interpersonal Therapy — weekly for 12-16 sessions. Behavioural activation: re-engage in pleasurable activities gradually. Exercise: 30 mins of brisk walking 5 days/week. Sleep hygiene if hypersomnia. Marital counselling referral.',
    'Start Sertraline 50mg daily. Assess suicide risk at each visit. Schedule weekly follow-up for first month (medication check + brief CBT). Refer for CBT. Encourage adherence — antidepressants take 4-6 weeks for full effect. Plan for 12 months of treatment after remission to prevent relapse.',
    '1. Recurrent depressive episode requiring pharmacotherapy and psychotherapy. 2. Suicidal ideation requiring close monitoring and safety planning.',
    'PHQ-9 weekly until symptoms improve. Suicide risk assessment at every visit (ideation, plan, intent, means). Monitor for SSRI side effects (GI upset, sexual dysfunction, initial anxiety increase). Monitor for mood switch (mania/hypomania — rule out bipolar disorder).',
    'Antidepressants are not "happy pills" — they work by correcting a chemical imbalance in the brain. They take 4-6 weeks to work fully. Side effects like nausea or headache usually improve in 1-2 weeks. Do not stop abruptly (discontinuation syndrome). Therapy combined with medication is more effective than either alone. Reach out if you feel worse or have suicidal thoughts.',
    'Psychiatry/GP follow-up in 2 weeks (phone or visit). Continue monthly until remission, then every 3 months. Once fully remitted for 12 months, consider slow taper (over 4-6 months).',
    'SSRIs are first-line for moderate-severe depression — all SSRIs are equally effective but differ in side effects. Sertraline: good balance of efficacy and tolerability, low drug interactions, safe in overdose. Fluoxetine: longest half-life, best for adherence, worst initial anxiety. Atypical features (hypersomnia, hyperphagia, leaden paralysis) may respond better to MAOIs or SSRIs/SNRIs. Always assess for bipolar disorder before starting antidepressants (risk of mood switch). ECT is safe and highly effective for severe, treatment-resistant, or psychotic depression.',
    ['APA Guidelines: Major Depressive Disorder', 'Lancet: Depression Treatment', 'Kenya Mental Health Policy Guidelines'],
  ),
  tpl(
    'Central Nervous System Pharmacology', 'Psychiatry', 'Schizophrenia', 'First-Episode Schizophrenia with Positive and Negative Symptoms', 'Advanced',
    'Hearing voices, believing people are following him, social withdrawal, and poor self-care for 6 months',
    '{name}, a {age}-year-old {occupation} from {location}, was brought by his mother with a 6-month history of gradually worsening symptoms: hearing multiple voices commenting on his actions and conversing with each other (auditory hallucinations), believing neighbours are spying on him and police are plotting to arrest him (persecutory delusions), becoming socially withdrawn, neglecting personal hygiene, sleeping poorly, and losing interest in activities. No previous psychiatric history. No substance use. No manic or depressive symptoms.',
    'No prior psychiatric history. No significant medical history. No head injury. No substance use. Family history: paternal uncle had "mental illness."',
    'No medications',
    'Masked facies (hypomimia). Rest tremor (right hand, 4-5 Hz, "pill-rolling," decreases with purposeful movement). Cogwheel rigidity in right arm and leg. Bradykinesia (slow finger taps, foot taps). Shuffling gait with reduced arm swing on right. Postural instability (positive pull test — retropulsion). Unified Parkinsons Disease Rating Scale (UPDRS) Part III: 32/108. MMSE: 28/30 (normal).',
    'CBC, CMP: normal. MRI brain: unremarkable (age-appropriate atrophy). DaTSCAN (SPECT): reduced dopamine transporter binding in bilateral putamen (confirmatory).',
    '',
    'Idiopathic Parkinson Disease (Hoehn & Yahr Stage 2.5 — Bilateral disease with mild postural instability)',
    ['Parkinson Disease', 'Essential Tremor', 'Drug-Induced Parkinsonism', 'Multiple System Atrophy', 'Progressive Supranuclear Palsy'],
    'Improve motor function and quality of life, manage symptoms with minimal side effects, prevent falls, plan for disease progression',
    '1. First-line therapy for significant motor impairment: Levodopa/Carbidopa (Co-careldopa) 100/25mg TID, increase gradually to 2 tablets TID as needed. 2. If dyskinesias or motor fluctuations develop: add entacapone 200mg with each Levodopa dose, or consider dopamine agonist (Pramipexole 0.125mg TID titrate slowly, or Ropinirole). 3. Alternative first-line in younger patients (<60): MAO-B inhibitor (Rasagiline 1mg daily, Selegiline 5mg BID) or dopamine agonist. 4. For tremor: Anticholinergic (Trihexyphenidyl/Benzhexol 2mg TID — use cautiously in elderly). 5. Osteoporosis prevention: Calcium + Vit D (fall risk).',
    'Physiotherapy: gait and balance training. Occupational therapy: home modifications, assistive devices. Speech therapy: LSVT (Lee Silverman Voice Treatment). Regular exercise (tai chi, cycling). Fall prevention: home safety assessment, remove rugs, grab bars.',
    'Start Levodopa/Carbidopa 100/25mg TID with meals (or 30 min before meals). Titrate to symptom control over 4-8 weeks. Refer to physiotherapy, occupational therapy, and speech therapy. Optimise blood pressure control (avoid medications causing orthostasis). Review in 4 weeks.',
    '1. Progressive neurodegenerative disease requiring dopaminergic replacement. 2. Fall risk due to postural instability requiring multidisciplinary rehabilitation.',
    'UPDRS motor score at each visit. Frequency and severity of off periods and dyskinesias. Fall diary. Orthostatic BP checks. MMSE/MoCA annually for cognitive decline. Assess for non-motor symptoms: depression, sleep, constipation, pain.',
    'Levodopa is the most effective medication for Parkinsons — it replaces the dopamine your brain is missing. It will significantly improve your movement and quality of life. Some people develop involuntary movements (dyskinesias) after years of use — this can be managed. Continue exercising — it helps slow disease progression. Do not stop medications abruptly (neuroleptic malignant syndrome).',
    'Neurology clinic in 4 weeks for dose titration. Physiotherapy ongoing. Annual cognitive screening. Monitor for disease progression and medication complications. Driving assessment if safety concern.',
    'Levodopa remains the gold standard for Parkinsons — no evidence that early use accelerates disease progression or complications. The "levodopa sparing" approach (starting with dopamine agonists or MAO-B inhibitors) is only for younger patients to delay motor complications. Protein-rich meals can reduce Levodopa absorption — take doses 30-60 min before meals if on/off fluctuations develop. Do not stop Levodopa abruptly (withdrawal can cause neuroleptic malignant syndrome).',
    ['NICE Guideline: Parkinsons Disease', 'MDS Evidence-Based Review: Parkinsons Treatment', 'Kenya Clinical Guidelines: Parkinsons'],
  ),
];
