// ================================================================
// Dermatology — Case Templates (5 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const DERMATOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Dermatology', 'Dermatology', 'Acne', 'Moderate-to-Severe Acne Vulgaris in an Adolescent', 'Beginner',
    'Persistent pimples, blackheads, and cysts on the face and back for 2 years',
    '{name}, a {age}-year-old {occupation} from {location}, presents with acne affecting the face (cheeks, forehead, chin) and upper back for 2 years. Lesions include blackheads (open comedones), whiteheads (closed comedones), inflammatory papules, pustules, and several painful cystic nodules (1-2 cm). Has tried over-the-counter benzoyl peroxide and salicylic acid washes with minimal improvement. No scarring yet. Reports low self-esteem and avoiding social situations.',
    'No significant PMH. No hirsutism or irregular menses (excludes PCOS). No prior isotretinoin use.',
    'No regular medications. OTC benzoyl peroxide 5% gel PRN.',
    'Face: Multiple open and closed comedones, inflammatory papules and pustules, and 4 tender cystic nodules on cheeks and jawline. Back: scattered comedones and papules. No active scarring. No signs of hyperandrogenism.',
    'No routine labs needed. If considering isotretinoin: FBC, LFTs, Cr, fasting lipids, pregnancy test (female).',
    'No imaging indicated.',
    'Moderate-to-Severe Acne Vulgaris (Grade III-IV, face and trunk)',
    ['Acne Vulgaris', 'Rosacea', 'Folliculitis', 'PCOS (if signs of hyperandrogenism)', 'Perioral Dermatitis'],
    'Clear active lesions, prevent scarring, improve self-esteem, prevent recurrence',
    '1. Topical therapy (for comedonal + inflammatory): Adapalene 0.1% gel + Benzoyl Peroxide 2.5-5% gel (apply thin layer at night). 2. Add topical antibiotic: Clindamycin 1% gel + Benzoyl Peroxide (combined formulation preferred to reduce antibiotic resistance). 3. If moderate-severe or not responding: add ORAL antibiotic: Doxycycline 100mg daily (or Lymecycline 408mg daily) for 8-12 weeks. 4. For large cysts: Intralesional Triamcinolone injection (2.5-5 mg/mL). 5. If severe, scarring, or treatment-resistant: Refer for isotretinoin (started by dermatologist only). 6. Maintenance: Adapalene/BPO long-term, stop oral antibiotics after 8-12 weeks.',
    'Gentle face wash BID with mild cleanser. Non-comedogenic moisturiser. Sunscreen (tretinoin and BPO increase photosensitivity). Avoid picking/squeezing lesions. Stress management.',
    'Start Adapalene 0.1% + BPO 2.5% combination gel at night. Start Doxycycline 100mg daily. Review in 8 weeks. If good response, continue topical but stop oral abx. If cystic lesions persist, consider isotretinoin referral.',
    '1. Moderate-severe inflammatory acne requiring combination topical + oral therapy. 2. Risk of scarring and psychosocial impact warranting effective treatment.',
    'Lesion count at each visit. Assess for side effects: Adapalene (dryness, peeling, photosensitivity), Doxycycline (GI upset, photosensitivity, oesophagitis). If female on isotretinoin: monthly pregnancy tests.',
    'Consistency is key — the topical treatment must be applied daily even if not seeing immediate results. It often gets worse before it gets better (purging in first 4 weeks). Do not pick pimples (causes scars). Use sunscreen daily. Complete the full course of oral antibiotics.',
    'Dermatology clinic in 8 weeks. If isotretinoin needed: close monitoring for side effects (dry lips, dry skin, myalgia, mood changes). No pregnancy during isotretinoin — 2 forms of contraception required.',
    'Acne pathogenesis involves 4 factors: follicular hyperkeratinisation (microcomedones), increased sebum production (androgen-driven), Cutibacterium acnes colonisation, and inflammation. Adapalene is a retinoid that normalises follicular keratinisation. Doxycycline reduces C. acnes and has anti-inflammatory properties. Antibiotic resistance is a growing concern — avoid prolonged courses (>12 weeks) and combine with BPO. Isotretinoin is highly effective but teratogenic (requires iPledge-like program in many countries).',
    ['KDIGO Guidelines: CKD-MBD and Electrolytes', 'Kenya Clinical Guidelines: Electrolyte Disorders'],
  ),
  t('Dermatology', 'Dermatology', 'Eczema', 'Acute Exacerbation of Atopic Dermatitis in a Young Child', 'Intermediate',
    'Severe itching and red, weeping rash on the face, arms, and legs for 1 week',
    '{name}, a {age}-year-old child from {location}, is brought by mother with a 1-week flare of intensely itchy, red, weeping rash on the face, flexural areas (antecubital and popliteal fossae), and extensor surfaces. Child is irritable, scratching constantly, and sleeping poorly. Has a history of eczema since infancy. Triggered by a recent upper respiratory infection and change in weather (cold, dry season).',
    'Atopic dermatitis (since 6 months old), Mild asthma, Allergic rhinitis. No known food allergies.',
    'Emollients (Aqueous cream) — used irregularly. Hydrocortisone 1% cream — used during flares PRN. Cetirizine syrup 5mg PRN for itching.',
    'Face, neck, flexures, and extensor surfaces: erythematous, weeping, crusted plaques with excoriations. Lichenification in antecubital and popliteal fossae (chronic). Impetiginised areas: honey-coloured crusts on face. Eczema Area and Severity Index (EASI): 18/72 (moderate-severe).',
    'No routine labs. If impetigo suspected: swab for culture (Staph aureus common). IgE: elevated (not diagnostic).',
    'No imaging indicated.',
    'Acute Moderate-Severe Atopic Dermatitis Flare with Secondary Impetiginisation (Staph aureus superinfection)',
    ['Atopic Dermatitis', 'Contact Dermatitis', 'Seborrhoeic Dermatitis', 'Scabies', 'Psoriasis'],
    'Reduce inflammation and pruritus, treat secondary infection, restore skin barrier, prevent flares',
    '1. Topical corticosteroids (step-up potency for flare): face: Hydrocortisone 1% BID for 5-7 days. Body: Betamethasone Valerate 0.1% cream BID for 7-10 days, then step down to Hydrocortisone. 2. Topical calcineurin inhibitor (for sensitive areas): Tacrolimus 0.03% ointment BID (face, flexures) as steroid-sparing. 3. Emollients: Apply thick emollient (50/50 white soft paraffin/liquid paraffin or Cetomacrogol) LIBERALLY and FREQUENTLY (every 2-4 hours when awake). 4. Antihistamine: Cetirizine syrup 5mg BID or Hydroxyzine 10-25mg at bedtime (for itch and sleep). 5. Antibiotics for impetigo: Flucloxacillin 250mg QID (child dose 12.5 mg/kg QID) for 7 days. 6. Wet wrap therapy if severe (short-term). 7. Avoid triggers: soap, bubble bath, wool, overheating.',
    'Bleach baths (dilute, 1/4 cup household bleach in full bathtub) twice weekly to reduce Staph colonisation. Cotton clothing. Maintain cool environment. Short, lukewarm baths (5-10 min) with emollient wash, pat dry, then apply topical within 3 minutes.',
    'Start potent topical steroid to body for 7 days, mild to face. Start oral Flucloxacillin for impetigo. Start antihistamine. Increase emollient use. Review in 1 week. If improved, step down to lower potency steroid. Educate mother on "treating the flare and preventing the next."',
    '1. Acute moderate-severe atopic dermatitis flare with bacterial superinfection. 2. Chronic disease requiring long-term maintenance therapy and trigger avoidance.',
    'EASI score weekly. Assess for signs of infection (weeping, honey-coloured crusts, fever). Monitor growth (children with severe atopic dermatitis may have growth delay if topical steroids overused or disease severe). Sleep quality.',
    'Eczema is a chronic condition — treatment involves both treating flares and maintaining healthy skin between flares. Moisturisers are the most important daily treatment — apply at least 3-4 times daily. Steroids are for flares only, use as directed. Stop scratching by keeping nails short and using antihistamines at night.',
    'Dermatology clinic in 1 week. If recurrent infections: consider bleach baths 2x/week. If severe and persistent: consider referral for systemic therapy (Dupilumab, Cyclosporine, or Methotrexate).',
    'The eczema treatment ladder: emollients (daily) → topical steroids + calcineurin inhibitors (for flares) → phototherapy → systemic immunomodulators. Emollients are the cornerstone of management — they reduce steroid requirements and prevent flares. There is NO role for antihistamines in eczema management except for sleep disturbance from itch (they do not reduce histamine-mediated itch in eczema). Secondary staphylococcal infection is common — treat promptly with anti-staphylococcal antibiotics. Topical steroids should be used: apply to active eczema, use the weakest effective potency, stop when clear, restart when flares.',
    ['NICE Guidelines: Atopic Eczema', 'AAAAI Guidelines: Atopic Dermatitis', 'Kenya Clinical Guidelines: Dermatology'],
  ),
];
