// ================================================================
// Endocrine Pharmacology — Case Templates
// 8 templates covering: T1DM, T2DM, DKA, HHS, Hypothyroidism,
// Hyperthyroidism, Osteoporosis, Adrenal Insufficiency
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';

function tpl(
  pharmacologySubject: string, specialty: string, disease: string,
  title: string, difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string, hpi: string, pmh: string, medHx: string,
  pe: string, labs: string, imaging: string,
  diagnosis: string, ddx: string[],
  goals: string, pharm: string, nonPharm: string, carePlan: string,
  dtps: string, monitoring: string, counselling: string, followUp: string,
  pearls: string, references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject, specialty, disease, title, difficulty,
    chiefComplaintTemplate: chiefComplaint, hpiTemplate: hpi,
    pmhTemplate: pmh, medHxTemplate: medHx, peTemplate: pe,
    labsTemplate: labs, imagingTemplate: imaging, diagnosis, ddx,
    goalsTemplate: goals, pharmTemplate: pharm,
    nonPharmTemplate: nonPharm, carePlanTemplate: carePlan,
    dtpsTemplate: dtps, monitoringTemplate: monitoring,
    counsellingTemplate: counselling, followUpTemplate: followUp,
    pearlsTemplate: pearls, references,
  };
}

export const ENDOCRINE_TEMPLATES: ClinicalCaseTemplate[] = [
  tpl(
    'Endocrine Pharmacology', 'Endocrinology', 'Type 1 Diabetes',
    'New-Onset Type 1 Diabetes in an Adolescent Presenting with DKA',
    'Intermediate',
    'Vomiting, abdominal pain, rapid breathing, and confusion for 2 days',
    '{name}, a {age}-year-old {occupation} from {location}, was brought to {setting} by parents with a 2-day history of excessive thirst (drinking 5+L water daily), frequent urination (bedwetting at night), weight loss (4 kg over 2 weeks), and fatigue. Over the past 24 hours developed vomiting, deep rapid breathing, severe abdominal pain, and progressive drowsiness. Parents report she had a "flu-like" illness 5 days ago.',
    'Previously healthy. No chronic illnesses. Not on any medications. Family history: maternal uncle has Type 1 Diabetes.',
    'No regular medications',
    'Drowsy, GCS 14. Deep sighing respirations (Kussmaul pattern). Fruity odour on breath. Dry mucous membranes, sunken eyes, reduced skin turgor. Abdomen: mild diffuse tenderness, no guarding. Severe dehydration (10%).',
    'VBG: pH 7.05, HCO3 6, pCO2 18, Base excess -18. Blood glucose 580 mg/dL (32.2 mmol/L). Serum Ketones: 7.2 mmol/L (strongly positive). Na+ 128 mEq/L (corrected Na 138), K+ 5.8 mEq/L, Cl- 95, Creatinine 1.2 mg/dL. HbA1c 11.8%. Urinalysis: 4+ glucose, 4+ ketones.',
    'No acute imaging. CXR: normal.',
    'New-Onset Type 1 Diabetes Mellitus presenting with Diabetic Ketoacidosis (Severe DKA)',
    ['Diabetic Ketoacidosis', 'Hyperosmolar Hyperglycaemic State', 'Acute Pancreatitis', 'Sepsis', 'Salicylate Poisoning'],
    'Correct dehydration, normalise blood glucose, resolve ketoacidosis, initiate basal-bolus insulin regimen, educate family on diabetes management',
    '1. Fluids: 10 mL/kg 0.9% Normal Saline over 1 hour, then calculate deficit (10% dehydration = 100 mL/kg) and replace over 24-48 hours. Change to 5% Dextrose + 0.45% NaCl when glucose <250 mg/dL. 2. Insulin: IV Regular Insulin infusion at 0.1 units/kg/hour. Do not start insulin if K+ <3.3 mEq/L (correct K+ first). 3. Potassium: when K+ <5.5, add 20-30 mEq KCl per litre of IV fluid to maintain K+ 4-5. 4. Transition to subcutaneous: Insulin Glargine (once daily) + Insulin Aspart (with meals) when DKA resolved (pH >7.3, HCO3 >15, able to eat). Give Glargine 2 hours before stopping IV insulin.',
    'ICU/HDU admission for close monitoring. NPO until ketoacidosis resolves. Bladder catheter for accurate urine output. Cardiac monitoring for arrhythmias.',
    'Admit to HDU/ICU. Start DKA protocol per ISPAD guidelines. Hourly glucose monitoring, ABG/VBG q2-4h. Correct fluids, insulin, potassium as above. Once DKA resolved: transition to basal-bolus SC insulin. Diabetes nurse educator consult. Involve dietitian. Assess home support and psychosocial needs.',
    '1. Life-threatening DKA at initial presentation of Type 1 Diabetes requiring urgent metabolic correction. 2. Need for lifelong insulin therapy and comprehensive diabetes education.',
    'Hourly: fingerstick glucose (target: decrease 50-75 mg/dL/hour). q2-4h: VBG (pH, HCO3), electrolytes (K+, Na+), anion gap. Continuous cardiac monitoring. Strict I/O (target urine output >0.5 mL/kg/hr). Neuro status (risk of cerebral oedema in children).',
    'Type 1 Diabetes is a lifelong condition requiring daily insulin injections. You will learn to check blood sugar, calculate insulin doses, and manage sick days. This is not your fault — it is an autoimmune condition. With proper management, you can live a full, healthy life. Your family and diabetes team will support you.',
    'Diabetes clinic in 1-2 weeks post-discharge. Continue insulin titration under specialist guidance. Annual screening: HbA1c, renal function, eye exam, foot exam. Psychosocial support.',
    'In DKA, insulin should NEVER be stopped if K+ is low (<3.3) — correct K+ first, then start insulin. Hypokalaemia with insulin therapy can cause fatal arrhythmias. Cerebral oedema is the most feared complication of DKA in children — monitor for headache, bradycardia, hypertension, GCS decline. Insulin drip should continue until anion gap closes, not just normoglycaemia.',
    ['ISPAD Guidelines: DKA in Children', 'ADA Standards of Care in Diabetes 2024', 'Kenya Clinical Guidelines: Diabetes Management'],
  ),

  tpl(
    'Endocrine Pharmacology', 'Endocrinology', 'Type 2 Diabetes',
    'Newly Diagnosed Type 2 Diabetes with Poor Glycaemic Control',
    'Beginner',
    'Excessive thirst, frequent urination, and unintentional weight loss for 2 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with polyuria (urinating 8-10 times/day and 3-4 times/night), polydipsia (drinking 3-4L water/day), blurred vision, and fatigue. Has lost 5 kg over 2 months without trying. Reports poor diet (frequent chapatis, mandazi, soda) and sedentary lifestyle. BMI 33 kg/m². No prior blood glucose testing.',
    'Hypertension (diagnosed 1 year ago), Dyslipidaemia (known, not on treatment). Family history: father and two siblings have Type 2 Diabetes.',
    'Amlodipine 5mg daily',
    'Obese (BMI 33). Mild acanthosis nigricans on neck. Central obesity (waist circumference 109 cm). Fundoscopy: normal retina (no diabetic retinopathy). Foot exam: normal. BP 138/85.',
    'Fasting glucose: 210 mg/dL (11.7 mmol/L). Random glucose: 310 mg/dL (17.2 mmol/L). HbA1c: 9.8%. Fasting lipid panel: LDL 160 mg/dL, HDL 35 mg/dL, Triglycerides 280 mg/dL. Creatinine 0.9 mg/dL, eGFR 78. Urinalysis: 2+ glucose, no ketones, no protein. ALT 55 (mild elevation — possible NAFLD).',
    'No acute imaging needed.',
    'Newly Diagnosed Type 2 Diabetes Mellitus with Poor Glycaemic Control (HbA1c 9.8%) and Co-morbid Metabolic Syndrome',
    ['Type 2 Diabetes', 'Type 1 Diabetes', 'Secondary Diabetes (Cushings, acromegaly)', 'Stress Hyperglycaemia', 'Pancreatic Insufficiency'],
    'Achieve glycaemic target (HbA1c <7%), preserve beta-cell function, reduce cardiovascular risk, manage weight',
    '1. First-line therapy: Metformin 500mg daily with evening meal for 1 week, then increase to 500mg BID. Target dose 1g BID or 2g extended-release daily as tolerated. 2. If metformin intolerant or HbA1c remains >7% after 3 months: add SGLT2i (Dapagliflozin 10mg daily or Empagliflozin 10-25mg daily) or DPP4i (Sitagliptin 100mg daily). 3. Statin: Atorvastatin 20mg daily for CV risk reduction. 4. ACEi/ARB: consider Ramipril 2.5mg daily or Losartan 25mg daily for nephroprotection if UACR >30.',
    'Medical nutrition therapy: reduce carbohydrate and sugar intake, portion control, replace refined grains with whole grains. Structured exercise: 150 mins/week moderate activity (brisk walking). Weight loss goal: 5-10% of body weight over 6 months. Diabetes self-management education.',
    'Start Metformin and titrate. Start Atorvastatin. Refer to diabetes educator, dietitian, and for diabetes self-management education. Check HbA1c in 3 months. Initiate annual screening: retinal exam, urine albumin, foot exam. Discuss glucose self-monitoring.',
    '1. New diagnosis of T2DM with HbA1c >9% requiring pharmacotherapy and lifestyle intervention. 2. Cardiovascular risk factors (hypertension, obesity, dyslipidaemia, family history) requiring comprehensive management.',
    'HbA1c every 3 months until target, then twice yearly. Fasting glucose and weight at each visit. Annual: lipid panel, serum creatinine + eGFR, urinary albumin/creatinine ratio, dilated eye exam, foot exam. BP at each visit.',
    'Type 2 Diabetes is a serious but manageable condition. Metformin is the first-line medication — take with meals to minimise stomach upset. Weight loss and dietary changes can dramatically improve blood sugar — some patients even achieve remission. Check your feet daily for cuts or blisters. Join a diabetes support group.',
    'Diabetes clinic review in 3 months. Repeat HbA1c. Titrate medications. If HbA1c >7% on metformin monotherapy, consider adding Dapagliflozin or a GLP-1 receptor agonist for additional glucose control and weight loss.',
    'Metformin is first-line for T2DM due to efficacy, safety, low cost, and cardiovascular benefit. It does NOT cause hypoglycaemia when used alone. HbA1c target of <7% is appropriate for most adults (individualise: <8% for elderly or with complications). In Kenya, access to Metformin, Glibenclamide, and Insulin is generally good via KEMSA; access to newer agents (SGLT2i, GLP-1 RA, DPP4i) is limited by cost.',
    ['ADA Standards of Care in Diabetes 2024', 'IDF Clinical Practice Recommendations for T2DM', 'Kenya Clinical Guidelines: Diabetes Mellitus'],
  ),

  tpl(
    'Endocrine Pharmacology', 'Endocrinology', 'Diabetic Ketoacidosis',
    'Recurrent DKA in a Young Adult with Type 1 Diabetes and Insulin Non-Adherence',
    'Advanced',
    'Nausea, vomiting, abdominal pain, and difficulty breathing for 1 day',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 24-hour history of nausea, vomiting, diffuse abdominal pain, and deep rapid breathing. She stopped taking her insulin 4 days ago because she "felt fine" and was tired of injections. Also has symptoms of a urinary tract infection (dysuria, frequency) for the past week. This is her 4th DKA admission in the past year.',
    'Type 1 Diabetes Mellitus (diagnosed 8 years ago), Recurrent UTIs, Depression (untreated)',
    'Insulin Glargine 22 units SC at bedtime, Insulin Aspart 6-8 units with meals (stopped 4 days ago)',
    'Tachycardic, tachypnoeic. Deep sighing respirations. Fruity breath. Dry mucous membranes. Mild suprapubic tenderness. Drowsy but arousable (GCS 14).',
    'Glucose 450 mg/dL (25 mmol/L). VBG: pH 7.08, HCO3 7, pCO2 20, BE -16. Serum ketones: 6.8 mmol/L. Na 132, K 5.5, Cl 98, Cr 1.3. HbA1c 13.1%. Urinalysis: 4+ glucose, 4+ ketones, positive leukocyte esterase and nitrites. Urine culture: pending.',
    'No acute imaging.',
    'Severe Diabetic Ketoacidosis Precipitated by Insulin Omission and Urinary Tract Infection',
    ['DKA', 'Hyperosmolar Hyperglycaemic State', 'Acute Pancreatitis', 'Sepsis', 'Intra-abdominal Infection'],
    'Correct DKA, treat underlying UTI, identify and address barriers to insulin adherence, initiate mental health support',
    '1. DKA protocol: IV Normal Saline 1L over 1 hour, then 250-500 mL/hour. IV Regular Insulin 0.1 units/kg bolus then 0.1 units/kg/hour infusion. Add K+ when <5.5. Add 5% dextrose when glucose <250 mg/dL. 2. Antibiotics: IV Ceftriaxone 1g daily for UTI (empiric, adjust per culture). 3. Once DKA resolved: restart basal-bolus insulin. Assess for home support. 4. Mental health: Depression screening (PHQ-9). Refer to counselling/psychiatry.',
    'ICU/HDU monitoring. Social work consult for adherence barriers. Diabetes educator consult.',
    'Treat DKA per protocol. Treat UTI. After resolution: explore reasons for insulin omission — needle phobia? cost? depression? lack of family support? Simplify insulin regimen if possible (e.g., Insulin Degludec once daily + Aspart). Consider insulin pump if available and suitable. Refer to psychologist/psychiatrist for depression management.',
    '1. Recurrent DKA from insulin non-adherence requiring urgent medical and psychosocial intervention. 2. Underlying mental health condition (depression) contributing to self-care deficits. 3. Concomitant UTI precipitating metabolic crisis.',
    'Hourly glucose. q2-4h VBG, electrolytes. I/O. Temperature, WBC, CRP for infection. Assess mood and suicide risk. Assess home environment and family support.',
    'Insulin is not optional — it is life-saving. I understand injections are difficult, but missing them leads to DKA, which is dangerous and requires hospitalisation. We need to find a way to make diabetes management work for you. Are you willing to talk to a counsellor about how you are feeling?',
    'Diabetes clinic in 1 week. Mental health follow-up. Social worker for adherence support. Consider community health worker home visits.',
    'Recurrent DKA is always a medical and psychosocial emergency. Ask about: insulin access, injection technique, dietary issues, mental health, family support, alcohol/substance use. Every DKA admission is an opportunity to intervene on the root cause. Depression is 2-3x more common in people with diabetes and significantly impacts self-care.',
    ['ADA Standards of Care 2024: Psychosocial Care', 'ISPAD Guidelines: DKA', 'Kenya Clinical Guidelines: Diabetes and Mental Health'],
  ),

  tpl(
    'Endocrine Pharmacology', 'Endocrinology', 'Hyperosmolar Hyperglycaemic State',
    'Hyperosmolar Hyperglycaemic State in an Elderly Patient with Type 2 Diabetes',
    'Advanced',
    'Profound weakness, confusion, and very high blood sugar for 3 days',
    '{name}, a {age}-year-old {occupation} from {location}, was found confused and unable to walk by a neighbour. Reports extreme thirst over the past week, frequent urination, and progressive weakness. Has not been eating well due to a recent diarrhoeal illness (5 days). Stopped taking diabetes medications 2 days ago because of reduced oral intake. No vomiting. Caretaker reports decreased urine output over the past 24 hours.',
    'Type 2 Diabetes (10 years), Hypertension, Osteoarthritis, CKD Stage 3a',
    'Glibenclamide 10mg BID, Metformin 1g BID, Amlodipine 5mg daily, Aspirin 75mg daily',
    'Severely dehydrated: dry mucous membranes, sunken eyes, poor skin turgor. Confused (GCS 13). No Kussmaul respirations. BP 100/55 (supine), HR 105. Afebrile. No focal neurological signs.',
    'Glucose: 985 mg/dL (54.7 mmol/L). Na+: 152 mEq/L (severe hypernatraemia). K+: 3.8, Cl-: 120, BUN: 65 mg/dL, Cr: 2.5 mg/dL (AKI, baseline Cr 1.3). Calculated serum osmolality: 365 mOsm/kg (normal 285-295). VBG: pH 7.38, HCO3 22, pCO2 40. Ketones: negative. HbA1c: 12.5%.',
    'Head CT: no acute intracranial pathology.',
    'Hyperosmolar Hyperglycaemic State (HHS) with Severe Hypovolaemia and Acute Kidney Injury',
    ['HHS', 'DKA', 'Hypernatraemic Dehydration', 'Stroke', 'Sepsis'],
    'Correct volume deficit (12-15L deficit), normalise serum osmolality and glucose gradually, identify and treat precipitating illness, prevent complications (thrombosis, cerebral oedema)',
    '1. IV fluids: 0.9% Normal Saline 1L over 1 hour, then 500-1000 mL/hour. Reassess haemodynamics. When BP stable and euvolemic, switch to 0.45% NaCl if corrected Na >150 mmol/L. Total fluid deficit is typically 8-12L. 2. Insulin: low-dose IV Regular Insulin 0.05 units/kg/hour (HHS is less insulin-sensitive than DKA). Start only after adequate fluid resuscitation. Target glucose decrease 50-75 mg/dL/hour. 3. Add 5% Dextrose when glucose <300 mg/dL. 4. Anticoagulation: prophylactic LMWH (Enoxaparin 40mg SC daily) due to high thrombotic risk. 5. Treat precipitating cause: antibiotics for infection.',
    'Monitor urine output hourly (Foley catheter). Cardiac monitoring. Central line if haemodynamically unstable. Nutritional support.',
    'Admit to HDU/ICU. Aggressive IV fluids (patients with HHS typically have 8-12L deficit). Slow correction of hyperosmolality (target decrease of 3-5 mOsm/kg/hour). Insulin at lower dose than DKA. Monitor for thromboembolic events. Identify precipitant (infection in this case). Transition to SC insulin when glucose <300 mg/dL and patient eating.',
    '1. HHS with severe volume depletion and AKI requiring aggressive but cautious fluid resuscitation. 2. High thrombotic risk requiring prophylactic anticoagulation. 3. Precipitating infection causing reduced oral intake and medication omission.',
    'Hourly: glucose, vitals, I/O. q4h: Na, K, Cl, BUN, Cr, calculated osmolality. q6h: VBG. Daily: ECG, cardiac enzymes. Monitor for fluid overload. Monitor for thrombosis. Neuro checks for cerebral oedema.',
    'This condition developed because of severe dehydration caused by very high blood sugar levels. The most important treatment is IV fluids — you need several litres. Insulin is given in lower doses than for DKA. We found an infection that likely triggered this episode. Recovery takes several days.',
    'Endocrine clinic in 2 weeks after discharge. Review diabetes medications (discontinue sulfonylurea, consider adding SGLT2i or GLP-1 RA if renal function recovers). Ensure sick-day management plan.',
    'HHS has a higher mortality (5-20%) than DKA (<1%) — largely due to older age and comorbidities. Key difference from DKA: minimal ketosis (enough insulin to suppress lipolysis but not enough to promote glucose utilisation). The fluid deficit in HHS is massive (8-12L vs 3-5L in DKA). Serum osmolality >330 is the hallmark. Cerebral oedema is a risk if glucose is corrected too quickly (decrease no more than 50-75 mg/dL/hour).',
    ['ADA Consensus Report: DKA and HHS', 'Joint British Diabetes Societies: HHS Guidelines', 'Kenya Clinical Guidelines: Hyperglycaemic Emergencies'],
  ),

  tpl(
    'Endocrine Pharmacology', 'Endocrinology', 'Hypothyroidism',
    'Newly Diagnosed Hypothyroidism in a Middle-Aged Woman',
    'Beginner',
    'Progressive fatigue, weight gain, cold intolerance, and constipation for 6 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with gradually worsening fatigue, lethargy, weight gain (8 kg over 6 months despite no change in diet), feeling cold when others are comfortable, constipation, dry skin, hair loss, and heavy menstrual periods. Reports slow thinking and difficulty concentrating at work. Has been told she "looks puffy." No prior thyroid issues.',
    'No significant PMH. Two normal pregnancies (children aged 12 and 15). Family history: mother has hypothyroidism.',
    'No regular medications',
    'Appears tired, slow speech. BMI 31. Skin: cool, dry, rough texture. Hair: thinning, brittle. Face: periorbital puffiness, dull expression. Neck: small diffuse goitre (30-40g), firm, non-tender, no nodules. Reflexes: delayed relaxation phase (hung-up reflexes). Pulse 58 bpm. BP 145/90.',
    'TSH: 28.5 mIU/L (0.5-4.5). Free T4: 0.4 ng/dL (0.8-1.8). Anti-TPO antibodies: positive (452 IU/mL, high titre — confirms autoimmune aetiology). Hb 10.8 g/dL (normocytic, normochromic). Lipid panel: Total cholesterol 280, LDL 190, HDL 45, TG 200 (secondary hyperlipidaemia). ECG: sinus bradycardia.',
    'No imaging required. Thyroid ultrasound: mild diffuse heterogeneity, no suspicious nodules.',
    'Primary Hypothyroidism (Autoimmune/Hashimoto Thyroiditis) with Moderate-Severe Symptoms',
    ['Primary Hypothyroidism', 'Subclinical Hypothyroidism', 'Sick Euthyroid Syndrome', 'Anaemia', 'Depression'],
    'Normalise thyroid hormone levels, relieve symptoms, avoid overtreatment, manage associated dyslipidaemia',
    '1. Levothyroxine (T4) replacement: Start at 50 mcg daily, taken on an empty stomach with water, 30-60 minutes before breakfast. 2. Target dose: 1.6 mcg/kg ideal body weight (typically 75-125 mcg daily). 3. Increase dose by 25 mcg increments every 4-6 weeks based on TSH. 4. Initial target TSH: 0.5-2.5 mIU/L. 5. For concurrent dyslipidaemia: thyroid replacement alone may normalise lipids — reassess after 6 months before adding a statin.',
    'No specific dietary restrictions — just consistency in timing of levothyroxine (same time each day). Avoid taking with calcium, iron, or high-fibre foods. Regular exercise to help with weight management.',
    'Start Levothyroxine 50 mcg daily. Recheck TSH and free T4 in 6 weeks. Titrate by 25 mcg increments until TSH in normal range. Once stable, monitor TSH annually. Advise that symptom improvement takes 2-4 weeks for energy, weight loss may take 2-3 months.',
    '1. Thyroid hormone deficiency requiring lifelong replacement therapy. 2. Secondary dyslipidaemia that may resolve with thyroid replacement. 3. Risk of overtreatment (iatrogenic hyperthyroidism) if dose too high.',
    'TSH and free T4 every 6 weeks until stable, then annually. Monitor for symptoms of over-replacement (palpitations, anxiety, insomnia, weight loss, heat intolerance). Assess for symptom resolution at each visit. Lipid panel in 6 months.',
    'Levothyroxine is NOT a "pick-me-up" or weight loss drug — it replaces the hormone your thyroid cannot produce. Take it on an empty stomach with water, 30-60 min before breakfast. Do not take with coffee, tea, calcium, or iron. It takes 6-8 weeks to see the full effect of a dose change. You will likely need this medication for life.',
    'Endocrine clinic in 6 weeks for TSH check and dose titration. Once stable, annual TSH monitoring. Annual thyroid exam to assess goitre size (may regress with treatment).',
    'Levothyroxine has a narrow therapeutic index — consistency in brand, timing, and absorption is critical. Switching brands can alter TSH levels. In young healthy patients, start at full replacement dose (1.6 mcg/kg). In elderly or those with cardiac disease, start low (12.5-25 mcg) and increase slowly. Pregnancy increases levothyroxine requirements by 30-50%. Subclinical hypothyroidism (TSH 4.5-10 with normal T4) is controversial — treat if TPO-positive, symptomatic, or pregnant.',
    ['ATA Guidelines: Hypothyroidism', 'ETA Guidelines: Subclinical Hypothyroidism', 'Kenya Clinical Guidelines: Thyroid Disorders'],
  ),

  tpl(
    'Endocrine Pharmacology', 'Endocrinology', 'Hyperthyroidism',
    'Symptomatic Graves Disease with Ophthalmopathy in a Young Woman',
    'Intermediate',
    'Rapid heart rate, weight loss despite increased appetite, bulging eyes, and tremors for 3 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 3-month history of palpitations, feeling hot and sweating excessively, weight loss (6 kg) despite increased appetite, fine tremors of the hands, anxiety, irritability, and insomnia. Has noticed her eyes are "staring" and "bulging" and feels like there is sand in her eyes. Reports increased frequency of bowel movements. Menstrual periods have become lighter and irregular.',
    'No significant PMH. Non-smoker (important — smoking worsens Graves ophthalmopathy). Family history: mother had "thyroid problems."',
    'No regular medications',
    'Anxious, restless, rapid speech. Pulse 112 bpm, BP 145/70, warm moist skin. Eyes: bilateral proptosis (exophthalmos), lid lag (von Graefe sign), lid retraction, conjunctival injection, mild periorbital oedema. Thyroid: diffuse smooth enlargement (~60 g), bruit audible on auscultation. Fine tremor of outstretched hands. Reflexes: brisk. Mild proximal muscle weakness.',
    'TSH: <0.01 mIU/L (undetectable). Free T4: 4.2 ng/dL (0.8-1.8). Free T3: 15.6 pmol/L (3.5-6.5). TSH Receptor Antibody (TRAb): positive. Anti-TPO: positive. Hb: normal. ECG: sinus tachycardia.',
    'Thyroid ultrasound: Diffusely enlarged gland with increased vascularity (thyroid inferno pattern on Doppler). No nodules.',
    'Graves Disease with Overt Hyperthyroidism and Mild to Moderate Ophthalmopathy',
    ['Graves Disease', 'Toxic Nodular Goitre', 'Subacute Thyroiditis', 'Exogenous Thyroid Hormone Ingestion', 'Anxiety Disorder'],
    'Normalise thyroid function, relieve symptoms, protect the eyes, prevent complications (thyroid storm, AF, osteoporosis)',
    '1. Symptom control: Propranolol 40mg TID (non-selective beta-blocker reduces palpitations, tremor, anxiety, and also blocks peripheral T4-to-T3 conversion). 2. Definitive therapy (choose one) per patient factors: a) Thionamide: Carbimazole 20-40mg daily (or Methimazole 15-30mg daily) — blocks thyroid hormone synthesis. Alternatively Propylthiouracil (PTU) 100-150mg TID if first-trimester pregnancy or adverse reaction to Carbimazole. b) Radioactive Iodine (RAI) therapy 131-I (contraindicated if active ophthalmopathy or pregnancy). c) Thyroidectomy (total) if large goitre, compressive symptoms, or patient preference. 3. For ophthalmopathy: Artificial tears (Hypromellose) 4-6x daily, sunglasses, head elevation at night. Refer to ophthalmology if optic nerve compression suspected.',
    'Smoking cessation counselling (critical — smoking dramatically worsens Graves ophthalmopathy). Complete rest during initial treatment. High-calorie diet to reverse weight loss. Cool environment.',
    'Start Carbimazole 30mg daily (in divided doses) + Propranolol 40mg TID. Recheck TFTs in 4-6 weeks. When euthyroid (usually 4-8 weeks), titrate Carbimazole to lowest effective maintenance dose (5-15mg daily). Discuss long-term treatment options (RAI vs surgery vs continued medical therapy). Ophthalmology referral for eye assessment.',
    '1. Overt hyperthyroidism requiring rapid symptom control and definitive management. 2. Active Graves ophthalmopathy potentially requiring specific treatment and smoking cessation. 3. Childbearing-age female — implications for pregnancy planning.',
    'TFTs (TSH, FT4, FT3) every 4-6 weeks during dose titration, then every 3-6 months once stable. FBC and LFTs monthly for first 3 months of Carbimazole (risk of agranulocytosis — advise patient to report sore throat or fever immediately). ECG if AF develops. Bone density if risk factors.',
    'Carbimazole can very rarely cause a serious drop in white blood cells (agranulocytosis) — if you get a sudden sore throat or fever, STOP the medication and go to hospital immediately for a blood test. Propranolol will quickly improve your palpitations and anxiety. Smoking will make your eye disease much worse. Discuss the three treatment options with your endocrinologist.',
    'Endocrine clinic in 4-6 weeks. Ophthalmology review for formal assessment and management of eye disease. Pregnancy counselling — must be euthyroid before conceiving (Carbimazole/PTU require adjustments).',
    'Graves disease is the most common cause of hyperthyroidism in iodine-sufficient areas. Propranolol provides rapid symptom relief but does not reduce hormone levels — it blocks adrenergic symptoms. Carbimazole/Methimazole are first-line thionamides (PTU is second-line due to hepatotoxicity risk). Agranulocytosis (risk 0.3-0.5%) presents with sudden fever/sore throat — warn every patient. RAI is contraindicated if active ophthalmopathy (can worsen it) or pregnancy.',
    ['ATA Guidelines: Hyperthyroidism', 'ETA Guidelines: Graves Orbitopathy', 'Kenya Clinical Guidelines: Thyroid Disease'],
  ),

  tpl(
    'Endocrine Pharmacology', 'Endocrinology', 'Osteoporosis',
    'Postmenopausal Osteoporosis with a Vertebral Compression Fracture',
    'Intermediate',
    'Sudden onset of severe mid-back pain after lifting a heavy object',
    '{name}, a {age}-year-old {occupation} from {location}, presents with acute onset of severe mid-thoracic back pain that started when she lifted a 10 kg bag of maize. Pain is sharp, localised to the mid-back, worse with standing and movement, relieved by lying flat. No radiation to legs. No numbness or weakness. No bowel/bladder dysfunction. Reports height loss of 5 cm over the past 5 years and a history of wrist fracture 3 years ago after a fall from standing height. Menopause at age 48 (now 10 years postmenopausal).',
    'Hypertension (well-controlled). No prior DXA scan. No prior falls assessment. Family history: mother had hip fracture at age 78.',
    'Amlodipine 5mg daily. Calcium 500mg + Vitamin D 400 IU daily (intermittent adherence).',
    'Mid-thoracic spine tenderness to palpation (T9-T10 level). No step deformity. Neurological exam: normal (no cord compression). No point tenderness over sacrum. Height 152 cm (previously 157 cm). Kyphotic posture.',
    'Calcium 9.2 mg/dL (8.5-10.5). Phosphate 3.5 mg/dL (2.5-4.5). 25(OH) Vitamin D: 18 ng/mL (deficient, normal >30). ALP 140 U/L (mildly elevated — bone formation marker). PTH: slightly elevated 75 pg/mL (secondary to Vit D deficiency). TSH: 2.1 mIU/L (normal). Serum creatinine: 0.9. Hb normal. SPEP: no monoclonal band.',
    'Spine X-ray: Wedge compression fracture of T10 with ~25% height loss. Vertebral bodies: generalised osteopenia. DXA scan (done after): Lumbar spine T-score -3.2, Femoral neck T-score -2.8.',
    'Osteoporotic Vertebral Compression Fracture (T10) in the Setting of Postmenopausal Osteoporosis and Vitamin D Deficiency',
    ['Osteoporotic Fracture', 'Traumatic Vertebral Fracture', 'Malignant Spinal Cord Compression', 'Osteomalacia', 'Paget Disease of Bone'],
    'Relieve acute back pain, treat underlying osteoporosis to prevent future fractures, correct vitamin D deficiency, reduce fall risk',
    '1. Acute pain management: Paracetamol 1g QID. Consider short-term weak opioid (Tramadol 50mg PRN) if pain severe. Avoid NSAIDs (renal risk in elderly). 2. Calcium and Vitamin D: Calcium carbonate 1000mg daily + Vitamin D3 2000 IU daily (loading for 8-12 weeks, then maintenance 800-1000 IU/day). 3. Antiresorptive therapy: Start a bisphosphonate — Alendronate 70mg ONCE WEEKLY (take with full glass of water on empty stomach, stay upright for 30 min). Or Zoledronic Acid 5mg IV once yearly (if unable to tolerate oral bisphosphonate). 4. If severe or contraindication to bisphosphonate: consider Denosumab 60mg SC every 6 months or Teriparatide (PTH analogue) 20mcg SC daily. 5. Fall prevention: home safety assessment, balance exercises, gait aid if needed.',
    'Short period of bed rest (<1 week, to avoid deconditioning). Physiotherapy for core strengthening and balance training. Spinal brace for comfort if needed (short-term). Weight-bearing exercise when pain resolves (walking). Dietary: calcium-rich foods (milk, yoghurt, sardines, kale).',
    'Treat acute fracture pain. Start Calcium + Vitamin D loading dose. Start weekly Alendronate. Refer to physiotherapy and falls clinic. Assess for secondary causes of osteoporosis (thyroid, Cushings, medications). Re-check 25(OH) Vitamin D in 3 months. Repeat DXA scan in 2 years to assess treatment response.',
    '1. Established osteoporosis with fragility fracture requiring pharmacotherapy. 2. Vitamin D deficiency contributing to bone loss. 3. High risk of future fractures (hip, spine, wrist) requiring comprehensive bone protection.',
    'Adherence to weekly bisphosphonate (alendronate) or yearly IV infusion. Monitor for side effects: GI upset (alendronate), osteonecrosis of the jaw (rare, with dental screening before starting), atypical femur fracture (rare). 25(OH) Vitamin D level in 3 months. DXA in 2 years.',
    'Osteoporosis is a silent disease — the fracture is the first sign. Falls can be prevented with home modifications (remove rugs, improve lighting, grab bars in bathroom). Take your weekly alendronate correctly to avoid oesophageal irritation. Weight-bearing exercise (walking, dancing) strengthens bones. Smoking cessation and limiting alcohol are essential.',
    'Falls clinic review. Physiotherapy for balance and gait training. Repeat DXA in 2 years. Dental check before starting bisphosphonate (if needed). Annual review of bone health.',
    'A fragility fracture (fracture from a fall from standing height or less) is diagnostic of osteoporosis regardless of DXA T-score. All patients with fragility fractures should be treated. Bisphosphonates reduce hip fracture risk by 50% and vertebral fracture risk by 50-70%. After 5 years of alendronate, reassess fracture risk — some patients may benefit from a drug holiday. Denosumab should not be stopped without switching to a bisphosphonate (rapid bone loss and rebound fracture risk).',
    ['NOF Guidelines: Osteoporosis Management', 'AACE/ACE Guidelines: Postmenopausal Osteoporosis', 'Kenya Clinical Guidelines: Metabolic Bone Disease'],
  ),

  tpl(
    'Endocrine Pharmacology', 'Endocrinology', 'Adrenal Insufficiency',
    'Primary Adrenal Insufficiency Presenting with an Adrenal Crisis',
    'Advanced',
    'Profound weakness, vomiting, abdominal pain, and hypotension for 2 days',
    '{name}, a {age}-year-old {occupation} from {location}, presents with severe fatigue, nausea, vomiting, diffuse abdominal pain, and near-collapse. Family reports progressive weakness over the past month with unintentional weight loss (6 kg), darkening of the skin (especially knuckles, gums, and scars), and craving for salt. Symptoms worsened acutely after a 2-day diarrhoeal illness. Now unable to stand, confused, and BP is very low.',
    'Previously healthy. No known PMH. No prior steroid use.',
    'No regular medications',
    'GCS 14 (confused). Cachectic, hyperpigmentation of skin (knuckles, palmar creases, buccal mucosa, recent scars). BP 75/45 mmHg supine, HR 115. Dehydrated (reduced skin turgor, dry mucous membranes). Mild diffuse abdominal tenderness. No peritoneal signs.',
    'Na+: 122 mEq/L (hyponatraemia). K+: 6.1 mEq/L (hyperkalaemia). BUN: 45 mg/dL, Cr: 1.8 mg/dL. Glucose: 52 mg/dL (hypoglycaemia). VBG: pH 7.28, HCO3 16 (mild metabolic acidosis). Cortisol (random, in crisis): 3.2 mcg/dL (markedly low, normal >18 in stress). ACTH: >500 pg/mL (normal 10-60). Aldosterone: <4 ng/dL. Renin: >10 ng/mL/hr.',
    'CT abdomen: Small adrenal glands with calcifications (suggesting prior TB or autoimmune destruction). Chest X-ray: normal (no evidence of active TB).',
    'Acute Adrenal Crisis (Addisonian Crisis) — Likely Primary Adrenal Insufficiency Secondary to Autoimmune Adrenalitis',
    ['Adrenal Crisis', 'Septic Shock', 'Hypovolaemic Shock', 'Acute Abdomen', 'Salt-Wasting Nephropathy'],
    'Resuscitate immediately with steroids and fluids, correct electrolyte abnormalities and hypoglycaemia, diagnose underlying cause, establish long-term replacement therapy',
    '1. IMMEDIATE: IV Hydrocortisone 100mg bolus, then 100mg IV every 6 hours (or 200mg/day continuous infusion). 2. IV Normal Saline 1L over 30-60 mins, then 200-500 mL/hour based on BP response (total deficit 3-5L). 3. Dextrose: IV 50% Dextrose 25-50g (1-2 ampules) for hypoglycaemia. 4. Correct hyperkalaemia with insulin/glucose or calcium gluconate if ECG changes. 5. Identify and treat precipitating cause (infection — check cultures, CXR, urinalysis). 6. Once stable, transition to oral replacement: Hydrocortisone 20mg AM + 10mg 6PM (mimics circadian rhythm) AND Fludrocortisone 0.05-0.1mg daily (mineralocorticoid replacement).',
    'ICU admission. Strict I/O. Cardiac monitoring. Avoid potassium-containing IV fluids.',
    'Admit to ICU. Stress-dose hydrocortisone immediately. Aggressive IV fluid resuscitation. Correct electrolyte and metabolic derangements. Search for precipitating infection (MC+S, CXR, urinalysis). Once haemodynamically stable, wean IV hydrocortisone over 2-3 days to oral replacement. Perform ACTH stimulation test for confirmation AFTER resolution of crisis (or use pre-treatment cortisol/ACTH levels).',
    '1. Life-threatening adrenal crisis requiring immediate steroid replacement and haemodynamic support. 2. Chronic adrenal insufficiency not previously diagnosed, now acutely decompensated due to intercurrent illness. 3. Severe electrolyte disturbances (hyponatraemia, hyperkalaemia, hypoglycaemia) requiring careful correction.',
    'Continuous: BP, HR, ECG. Hourly glucose. q4-6h: Na, K, glucose, creatinine. Daily: cortisol levels (to guide weaning), monitoring for fluid overload. Watch for signs of over-replacement (hypertension, hypokalaemia, oedema).',
    'Adrenal insufficiency means your adrenal glands do not produce enough stress hormones. You need lifelong replacement with hydrocortisone and fludrocortisone. You must never miss a dose. During illness (fever, vomiting, diarrhoea), you need to DOUBLE or TRIPLE your dose (sick-day rules). Always wear a MedicAlert bracelet. If you cannot keep tablets down due to vomiting, go to hospital for IV hydrocortisone.',
    'Endocrine clinic in 4-6 weeks after discharge for adrenal antibody testing and bone density baseline. Provide MedicAlert bracelet and sick-day rules card. Educate patient and family on emergency injection of hydrocortisone (provide IM hydrocortisone kit). Annual: electrolytes, renin, DXA.',
    'Primary adrenal insufficiency (Addison disease) in Kenya is frequently post-TB (TB destroys adrenal glands) or autoimmune. Hyponatraemia + hyperkalaemia + hypoglycaemia + hypotension is a classic combination pointing to mineralocorticoid deficiency. NEVER give steroids without checking for TB unless you have ruled it out (steroids can reactivate latent TB). Sick-day rules: double or triple hydrocortisone dose during febrile illness, injury, or surgery. If vomiting, give IM/IV hydrocortisone and go to hospital.',
    ['ESE Guidelines: Adrenal Insufficiency', 'Kenya Clinical Guidelines: Adrenal Disorders', 'WHO: Management of Adrenal Crisis'],
  ),
];
