// ================================================================
// Gap-fill clinical case templates for integrated units that lacked
// template coverage: ENT, Geriatric, Obstetrics & Gynaecology, Paediatric.
// Each template follows the ClinicalCaseTemplate interface from generateCases.ts.
// All patients are fictional Kenyan identities for educational use.
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';

// ---------- ENT ----------
export const ENT_TEMPLATES: ClinicalCaseTemplate[] = [
  {
    pharmacologySubject: 'ENT Pharmacotherapy',
    specialty: 'ENT',
    disease: 'Acute Otitis Media',
    title: 'Acute Otitis Media in a Young Child',
    difficulty: 'Beginner',
    chiefComplaintTemplate: '3-day history of ear pain and fever in a child',
    hpiTemplate: '{name}, a {age}-year-old child from {location}, presents with right ear pain and fever for 3 days. Mother reports irritability, tugging at the right ear, poor feeding, and a temperature of 38.9°C. No cough, no diarrhoea. The child attends a local daycare.',
    pmhTemplate: 'Former preterm (34 weeks), no recurrent infections',
    medHxTemplate: 'Paracetamol syrup PRN for fever, no regular medications',
    peTemplate: 'Toxic-looking child, T 38.9°C. Right tympanic membrane bulging, erythematous, with reduced mobility on pneumatic otoscopy. Left ear normal. No mastoid tenderness. Neck supple.',
    labsTemplate: 'WBC 14.2 x10^9/L (6-17.5), neutrophils 62%. CRP 28 mg/L (<5). No need for culture unless treatment fails.',
    imagingTemplate: '',
    diagnosis: 'Acute Otitis Media (right)',
    ddx: ['Acute Otitis Media', 'Otitis Externa', 'Acute Mastoiditis', 'Foreign body ear', 'Referred dental pain'],
    goalsTemplate: 'Relieve pain, eradicate infection, prevent complications (mastoiditis, perforation), counsel on judicious antibiotic use',
    pharmTemplate: '1. Analgesia: Paracetamol 15 mg/kg PO QDS (max 60 mg/kg/day) or Ibuprofen 10 mg/kg TDS. 2. Antibiotic: Amoxicillin 45 mg/kg/day PO divided TDS for 5-7 days (first-line). If penicillin allergic: Azithromycin 10 mg/kg day 1 then 5 mg/kg days 2-5. 3. Topical warmth for pain relief.',
    nonPharmTemplate: 'Encourage fluids, observe for 48-72h; many mild cases self-resolve. Avoid inserting objects into the ear. Adequate analgesia.',
    carePlanTemplate: 'Start analgesia and amoxicillin. Review in 48-72h; if no improvement or worsening, reassess for complications and consider antibiotic switch (co-amoxiclav). Counselling on completion of course and warning signs.',
    dtpsTemplate: '1. Pharmacotherapy: amoxicillin first-line; resistance and allergy alter choice. 2. Overuse of antibiotics in AOM drives resistance — watchful waiting is appropriate in older, mild cases.',
    monitoringTemplate: 'Temperature, pain score, feeding, and hearing. Watch for mastoid tenderness, facial palsy, or persistent fever suggesting mastoiditis.',
    counsellingTemplate: 'Complete the full antibiotic course. Seek care if fever persists >48h, ear discharge, or child becomes very lethargic. Avoid putting anything in the ear.',
    followUpTemplate: 'Routine review in 2-4 weeks; hearing screen if recurrent. Recurrent AOM (>3/6 months) refer to ENT.',
    pearlsTemplate: 'Amoxicillin is first-line for AOM; treat children <6 months or severe cases promptly. Watchful waiting is acceptable in selected older children with mild disease. Complications include mastoiditis and tympanic perforation.',
    references: ['Kenya Paediatric Protocols', 'WHO Acute Ear Infections Guidelines'],
  },
  {
    pharmacologySubject: 'ENT Pharmacotherapy',
    specialty: 'ENT',
    disease: 'Bacterial Sinusitis',
    title: 'Acute Bacterial Sinusitis Following Viral URTI',
    difficulty: 'Intermediate',
    chiefComplaintTemplate: 'Facial pain and purulent nasal discharge for 10 days after a cold',
    hpiTemplate: '{name}, a {age}-year-old {occupation} from {location}, developed a runny nose and sore throat 10 days ago (viral URTI). Symptoms initially improved but then worsened on day 7 with frontal facial pain, purulent green nasal discharge, fever, and maxillary tooth pain. Reports double sickening.',
    pmhTemplate: 'Allergic rhinitis, well controlled',
    medHxTemplate: 'Cetirizine 10mg daily, saline nasal spray',
    peTemplate: 'T 38.2°C. Tenderness over maxillary sinuses, transillumination reduced on right. Nasal mucosa erythematous with purulent discharge. Mild periorbital swelling absent. Throat clear.',
    labsTemplate: 'WBC 11.8 x10^9/L, CRP 22 mg/L. Nasal swab not routinely required.',
    imagingTemplate: 'Not indicated acutely; CT sinuses only if complication suspected (orbital/intracranial).',
    diagnosis: 'Acute Bacterial Sinusitis (maxillary)',
    ddx: ['Viral Rhinosinusitis', 'Acute Bacterial Sinusitis', 'Allergic Rhinitis flare', 'Dental abscess', 'Migraine'],
    goalsTemplate: 'Eradicate infection, relieve symptoms, prevent orbital/intracranial complications',
    pharmTemplate: '1. Analgesia: Paracetamol 1g TDS. 2. Intranasal corticosteroid: Fluticasone 50 mcg 2 sprays/nostril daily (reduces inflammation). 3. First-line antibiotic if severe/prolonged: Amoxicillin-Clavulanate 625mg TDS for 5-7 days. Penicillin allergic: Doxycycline 100mg BD. 4. Saline nasal irrigation.',
    nonPharmTemplate: 'Steam inhalation, adequate hydration, avoid allergens. Nasal saline irrigation.',
    carePlanTemplate: 'Start fluticasone and analgesia; add amoxicillin-clavulanate given >10 days and severity. Review in 5-7 days. Advise warning signs (periorbital swelling, visual change, severe headache).',
    dtpsTemplate: '1. Most sinusitis is viral; antibiotics reserved for severe/prolonged/bilateral cases. 2. Intranasal steroids reduce mucosal oedema and improve drainage.',
    monitoringTemplate: 'Symptom resolution, temperature, periorbital/visual changes. Watch for orbital cellulitis.',
    counsellingTemplate: 'Use nasal spray correctly (aim laterally). Complete antibiotics. Seek urgent care for eye swelling or vision change.',
    followUpTemplate: 'Review in 1 week; ENT if recurrent/chronic (>12 weeks).',
    pearlsTemplate: 'Clinical diagnosis; antibiotics for >10 days, high fever, or bilateral/severe disease. Intranasal corticosteroids are key adjuncts. Orbital cellulitis is a dangerous complication.',
    references: ['EPOS Guidelines: Rhinosinusitis', 'Kenya ENT Clinical Protocols'],
  },
  {
    pharmacologySubject: 'ENT Pharmacotherapy',
    specialty: 'ENT',
    disease: 'Benign Paroxysmal Positional Vertigo',
    title: 'BPPV Presenting with Positional Vertigo',
    difficulty: 'Intermediate',
    chiefComplaintTemplate: 'Sudden spinning dizziness on turning in bed for 1 week',
    hpiTemplate: '{name}, a {age}-year-old {occupation} from {location}, reports brief episodes of severe spinning dizziness triggered by rolling over in bed or looking up, each lasting under a minute. No hearing loss, tinnitus, or neurological symptoms. Recent head trauma 1 month ago.',
    pmhTemplate: 'Hypertension, osteoporosis',
    medHxTemplate: 'Amlodipine 5mg daily, Calcium/Vitamin D',
    peTemplate: 'Positive Dix-Hallpike manoeuvre on right with rotational nystagmus after latency. No spontaneous nystagmus. Neuro exam normal. Tuning fork hearing normal.',
    labsTemplate: 'Not required unless red flags. HbA1c, lipid profile for cardiovascular risk.',
    imagingTemplate: 'MRI brain only if central signs/red flags.',
    diagnosis: 'Benign Paroxysmal Positional Vertigo (posterior canal, right)',
    ddx: ['BPPV', 'Vestibular neuritis', 'Meniere disease', 'Vertebrobasilar ischaemia', 'Drug-induced vertigo'],
    goalsTemplate: 'Relieve vertigo, reposition otoconia, counsel on manoeuvres, review medication causes',
    pharmTemplate: '1. Particle repositioning: Epley manoeuvre (curative in most). 2. Symptomatic: Betahistine 16mg TDS (limited evidence, may help). 3. Anti-emetic if severe: Prochlorperazine 5mg TDS short course. 4. Review medications causing dizziness (amlodipine, polypharmacy).',
    nonPharmTemplate: 'Epley manoeuvre performed, teach home manoeuvre. Avoid sudden head movements initially. Fall precautions.',
    carePlanTemplate: 'Perform Epley manoeuvre, arrange vestibular rehab if persistent. Review drug list for vestibular suppressants. Counsel on safety.',
    dtpsTemplate: '1. BPPV is mechanical — repositioning cures, not chronic medication. 2. Vestibular suppressants (prochlorperazine) only short-term; they delay central compensation.',
    monitoringTemplate: 'Episode frequency, residual dizziness, falls risk. Hearing if atypical.',
    counsellingTemplate: 'Episodes are brief and benign. Perform Epley at home if trained. Avoid sedating drugs. Stand up slowly.',
    followUpTemplate: 'Review in 1-2 weeks; ENT if refractory for vestibular testing.',
    pearlsTemplate: 'Diagnosis by positional nystagmus with latency. Epley manoeuvre is first-line. Avoid prolonged vestibular suppressants. Red flags (neurological, hearing loss) warrant imaging.',
    references: ['BPPV Clinical Practice Guideline (AAO-HNS)', 'Kenya Neurology Protocols'],
  },
];

// ---------- Geriatric ----------
export const GERIATRIC_TEMPLATES: ClinicalCaseTemplate[] = [
  {
    pharmacologySubject: 'Geriatric Pharmacotherapy',
    specialty: 'Geriatrics',
    disease: 'Polypharmacy & Falls',
    title: 'Recurrent Falls in an Older Adult on Multiple Medications',
    difficulty: 'Advanced',
    chiefComplaintTemplate: 'Two falls at home in the past month',
    hpiTemplate: '{name}, a {age}-year-old {occupation} from {location}, has had two falls at home in the past month, one resulting in a wrist fracture. Lives alone. Daughter reports increasing confusion, drowsiness, and urinary incontinence at night. Takes 9 regular medications prescribed by different clinicians.',
    pmhTemplate: 'Hypertension, Type 2 Diabetes, Osteoporosis, Insomnia, Benign Prostatic Hyperplasia, Depression',
    medHxTemplate: 'Amlodipine 10mg, Metformin 1g BID, Alendronate 70mg weekly, Zolpidem 10mg nocte, Tamsulosin 0.4mg, Amitriptyline 25mg nocte, Atenolol 50mg, Furosemide 40mg, Diclofenac 50mg PRN',
    peTemplate: 'Gait unsteady, wide-based. Orthostatic BP: 150/85 supine, 110/65 standing (drop 40/20). MMSE 22/30. Bruising, right wrist cast. Dry mucous membranes. Bladder distended.',
    labsTemplate: 'Na 133 (136-145), K 3.3 (3.5-5.0), Cr 1.4 (eGFR 42), Glucose 9.1. TSH normal. Vit D low.',
    imagingTemplate: 'DEXA: T-score -3.1 lumbar spine. X-ray: healed wrist fracture.',
    diagnosis: 'Geriatric Polypharmacy with Fall Risk and Anticholinergic Burden',
    ddx: ['Polypharmacy adverse effects', 'Delirium', 'Parkinson disease', 'Normal pressure hydrocephalus', 'Hypothyroidism'],
    goalsTemplate: 'Deprescribe high-risk medications, reduce fall risk, correct deficits, improve function',
    pharmTemplate: '1. STOP Zolpidem and Amitriptyline (sedating, anticholinergic, fall risk) — switch insomnia to sleep hygiene, depression to sertraline 50mg. 2. STOP Diclofenac (NSAID + furosemide = AKI/bleed risk); use paracetamol 1g QDS. 3. Review Atenolol + Amlodipine for orthostatic hypotension; reduce dose. 4. Continue Alendronate, Tamsulosin. 5. Correct K+, Vit D. 6. Consider benzodiazepine taper if used.',
    nonPharmTemplate: 'Fall-proof home: remove rugs, install grab bars, improve lighting. Physiotherapy balance training. Occupational therapy assessment. Medication review with pharmacist.',
    carePlanTemplate: 'Comprehensive geriatric assessment. Deprescribe CNS-active and nephrotoxic drugs. Start balance physiotherapy. Monitor BP sitting/standing. Review in 2 weeks after changes.',
    dtpsTemplate: '1. Polypharmacy and anticholinergic/sedative load drive falls and delirium in frail elders. 2. Furosemide + NSAID + ACEi/ARB = "triple whammy" AKI risk.',
    monitoringTemplate: 'Orthostatic BP, MMSE, fall diary, renal function, gait. Review medicine changes.',
    counsellingTemplate: 'Explain why stopping certain pills reduces falls. Use one pharmacy. Bring all medicines to reviews. Report drowsiness or confusion.',
    followUpTemplate: 'Geriatric clinic in 2 weeks; pharmacist medication review. DEXA monitoring.',
    pearlsTemplate: 'Apply STOPP/START criteria. Aim for <5 medicines where possible. The "triple whammy" (diuretic + NSAID + RAAS inhibitor) risks AKI. Sedatives and anticholinergics are top fall contributors.',
    references: ['STOPP/START Criteria v2', 'Kenya Geriatrics Society: Falls in Older Adults'],
  },
  {
    pharmacologySubject: 'Geriatric Pharmacotherapy',
    specialty: 'Geriatrics',
    disease: 'Delirium',
    title: 'Acute Confusional State in an Elderly Patient',
    difficulty: 'Advanced',
    chiefComplaintTemplate: 'Sudden confusion and agitation over 2 days',
    hpiTemplate: '{name}, a {age}-year-old {occupation} from {location}, was previously independent but over 2 days became confused, disorientated, and agitated, pulling out IV lines. Family states she was well until a urinary tract infection began. No prior dementia history.',
    pmhTemplate: 'Osteoarthritis, Hypertension, Mild cognitive impairment',
    medHxTemplate: 'Paracetamol, Amlodipine, Donepezil 5mg',
    peTemplate: 'Acutely confused, fluctuating consciousness, disorientated. Flapping tremor. Suprapubic tenderness, foul urine. Dehydrated. Chest clear.',
    labsTemplate: 'WBC 15 x10^9/L, Cr 1.6 (baseline 1.0), Urinalysis: leucocytes++, nitrites+. Na 130, K 4.0.',
    imagingTemplate: 'CT head: no acute haemorrhage. (if red flags, LP to exclude meningitis)',
    diagnosis: 'Hyperactive Delirium secondary to Urinary Tract Infection',
    ddx: ['Delirium', 'Dementia with behavioural disturbance', 'CNS infection', 'Drug intoxication', 'Hypoglycaemia'],
    goalsTemplate: 'Treat precipitant, ensure safety, symptomatic control, avoid harm from over-sedation',
    pharmTemplate: '1. Treat UTI: empirical IV/PO Ceftriaxone 1g daily or oral Nitrofurantoin 100mg QDS (adjust for renal function). 2. Avoid physical restraint; if severe agitation risking harm, short-course Haloperidol 0.5mg PO/IM (low geriatric dose) or Quetiapine 12.5-25mg. 3. Rehydrate, correct Na+. 4. Review and STOP unnecessary anticholinergics.',
    nonPharmTemplate: 'Calm environment, reorientation, glasses/hearing aids, early mobility, family presence, regular meals, sleep hygiene. Treat pain.',
    carePlanTemplate: 'Admit, treat infection, monitor cognition 2-4 hourly, safety measures. Deprescribe contributors. Review daily; discharge when alert and infection resolving.',
    dtpsTemplate: '1. Delirium is acute, fluctuating, due to underlying cause — treat that, not just symptoms. 2. Antipsychotics increase stroke/mortality risk in elderly; use lowest dose, shortest duration.',
    monitoringTemplate: 'Confusion Assessment Method (CAM) score, vitals, renal function, hydration, infection markers.',
    counsellingTemplate: 'Reassure family delirium is usually reversible. Prevent recurrence: treat infections early, avoid polypharmacy, ensure hydration.',
    followUpTemplate: 'Geriatric review post-discharge; cognitive baseline reassessment at 1 month.',
    pearlsTemplate: 'Delirium = acute brain failure from precipitant (infection, meds, dehydration). Treat cause first. Antipsychotics are last-resort, low-dose, short-course in elderly. Non-pharmacological care is primary.',
    references: ['NICE Guideline CG103: Delirium', 'Kenya Geriatrics Society: Delirium'],
  },
  {
    pharmacologySubject: 'Geriatric Pharmacotherapy',
    specialty: 'Geriatrics',
    disease: 'Atrial Fibrillation in Elderly',
    title: 'Atrial Fibrillation with Fall Risk in an Octogenarian',
    difficulty: 'Intermediate',
    chiefComplaintTemplate: 'Palpitations and dizziness for 1 week',
    hpiTemplate: '{name}, a {age}-year-old {occupation} from {location}, reports irregular palpitations, lightheadedness, and reduced exercise tolerance for a week. No syncope. Has hypertension and mild CKD. Recent fall with minor bruise. Daughter concerned about blood thinners given falls.',
    pmhTemplate: 'Hypertension, CKD stage 3, previous fall',
    medHxTemplate: 'Amlodipine 5mg, Ramipril 2.5mg, Furosemide 20mg',
    peTemplate: 'Irregularly irregular pulse 110, BP 145/85. No murmur. No signs of HF. Neuro: no focal deficit. Ecchymosis on arm.',
    labsTemplate: 'Hb 12.5, Cr 1.5 (eGFR 38), K 4.4, INR 1.0, TSH normal. Troponin negative.',
    imagingTemplate: 'ECG: AF with RVR. Echo: LVEF 55%, no valve disease, LA 4.2cm.',
    diagnosis: 'Atrial Fibrillation with Rapid Ventricular Response (CHA2DS2-VASc 4, HAS-BLED 3)',
    ddx: ['Atrial Fibrillation', 'Sick sinus syndrome', 'Hyperthyroidism', 'Anaemic states', 'SVT'],
    goalsTemplate: 'Rate control, stroke prevention权衡 fall risk, optimise Renal function',
    pharmTemplate: '1. Rate control: Bisoprolol 1.25-2.5mg daily (start low in elderly/CKD). 2. Anticoagulation: given CHA2DS2-VASc 4, offer DOAC (Apixaban 2.5mg BID if CrCl 15-29 or weight <60kg/age>80; else 5mg BID). Discuss fall risk vs stroke prevention — net benefit favours anticoagulation. 3. Avoid Amiodarone (toxicity). 4. Review furosemide dosing for renal function.',
    nonPharmTemplate: 'Fall risk assessment, home safety, BP monitoring. Cardiac rhythm review. Bleeding precaution education.',
    carePlanTemplate: 'Start low-dose bisoprolol; initiate apixaban after weighing risks with family. Monitor Renal function, HR, BP. Falls clinic referral.',
    dtpsTemplate: '1. Stroke risk (CHA2DS2-VASc 4) outweighs fall risk — anticoagulate. 2. DOAC dosing must be renally adjusted; avoid interacting drugs (e.g., NSAIDs).',
    monitoringTemplate: 'HR, BP, renal function, haemoglobin (bleed), signs of stroke. Annual reassessment.',
    counsellingTemplate: 'Anticoagulants prevent strokes; report any unusual bleeding. Use razor carefully, avoid contact sports. Do not stop suddenly.',
    followUpTemplate: 'Cardiology/geriatric review in 4 weeks; renal function and rate control.',
    pearlsTemplate: 'In AF, stroke prevention usually outweighs fall risk. DOACs require renal dosing. Start beta-blockers low in frail elders with CKD. HAS-BLED guides bleeding risk but is not a reason to withhold anticoagulation.',
    references: ['ESC AF Guidelines', 'Kenya Cardiology Society: AF in Elderly'],
  },
];

// ---------- Obstetrics & Gynaecology ----------
export const OBSTETRICS_GYNAECOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  {
    pharmacologySubject: 'Obstetrics & Gynaecology Pharmacotherapy',
    specialty: 'Obstetrics and Gynecology',
    disease: 'Pre-eclampsia',
    title: 'New-Onset Hypertension in Late Pregnancy',
    difficulty: 'Advanced',
    chiefComplaintTemplate: 'Headache and swelling with high blood pressure at 34 weeks gestation',
    hpiTemplate: '{name}, a {age}-year-old {occupation} from {location}, at 34 weeks gestation, presents with frontal headache, visual blurring, and sudden facial/hand swelling for 2 days. Antenatal visits irregular. No vaginal bleeding or abdominal pain. Fetal movements normal.',
    pmhTemplate: 'Nulliparous, no chronic illness prior to pregnancy',
    medHxTemplate: 'Iron + folic acid supplementation, no regular medicines',
    peTemplate: 'BP 165/110 mmHg. Pallor, facial and pedal oedema. Hyperreflexia. Clonus present. Fundoscopy: arteriolar spasm. Abdominal: uterine size dates, fundal height 34cm, no tenderness. Fetal HR 140 regular.',
    labsTemplate: 'Protein/Creatinine ratio 350 mg/mmol (>30 indicates proteinuria). Platelets 110 x10^9/L (150-400). ALT 68 U/L, AST 72 U/L. Cr 0.9, Urate 0.52 mmol/L. Hb 10.8.',
    imagingTemplate: 'Obstetric ultrasound: estimated fetal weight 2.1kg (25th centile), amniotic fluid normal, Doppler umbilical artery normal.',
    diagnosis: 'Pre-eclampsia with Severe Features at 34 Weeks',
    ddx: ['Pre-eclampsia', 'Chronic Hypertension with superimposed pre-eclampsia', 'HELLP syndrome', 'Gestational hypertension', 'Acute fatty liver of pregnancy'],
    goalsTemplate: 'Control BP, prevent eclampsia, assess maternal/fetal status, plan timely delivery',
    pharmTemplate: '1. Seizure prophylaxis: IV/IM Magnesium Sulphate 4g loading over 20 min then 1g/hr infusion (monitor reflexes, RR, urine output; have Calcium Gluconate 1g for toxicity). 2. Antihypertensive: IV Labetalol 20mg escalating, or Oral Nifedipine 10-20mg, target <160/110. 3. Corticosteroids: Dexamethasone 12mg IM BD x2 for fetal lung maturity (if <34+6). 4. Avoid ACEi/ARB, NSAIDs, and diuretics (relative).',
    nonPharmTemplate: 'Admit to obstetric high-care. Continuous fetal monitoring. Strict I/O. Seizure precautions. Prepare for delivery.',
    carePlanTemplate: 'Stabilise with magnesium and antihypertensive, give steroids, then plan delivery (vaginal if favourable, else caesarean) at 34-37 weeks depending on stability. Postpartum monitoring for 48-72h (risk persists).',
    dtpsTemplate: '1. Magnesium sulphate prevents eclampsia; monitor for toxicity (loss of patellar reflex, RR<12, urine<30ml/h). 2. Avoid teratogenic/nephrotoxic drugs; labelalol/nifedipine preferred in pregnancy.',
    monitoringTemplate: 'Hourly BP, reflexes, RR, urine output, platelets, LFTs, fetal CTG. Watch for eclampsia/HELLP.',
    counsellingTemplate: 'Explain pre-eclampsia and need for early delivery. Report headache, visual changes, or decreased fetal movement. Postpartum follow-up for chronic hypertension screening.',
    followUpTemplate: 'Postnatal review at 6 weeks; BP checks. Future pregnancy counselling for recurrence risk.',
    pearlsTemplate: 'Magnesium sulphate is definitive for eclampsia prophylaxis. Target delivery at 37 weeks (or sooner if severe). ACEi/ARBs, statins, and warfarin are teratogenic — avoid in pregnancy. Postpartum BP monitoring is essential.',
    references: ['FIGO Guidelines: Pre-eclampsia', 'Kenya Ministry of Health: Maternal Care'],
  },
  {
    pharmacologySubject: 'Obstetrics & Gynaecology Pharmacotherapy',
    specialty: 'Obstetrics and Gynecology',
    disease: 'Bacterial Vaginosis / Preterm Labour',
    title: 'Preterm Labour with Bacterial Vaginosis',
    difficulty: 'Intermediate',
    chiefComplaintTemplate: 'Regular abdominal tightening and vaginal discharge at 30 weeks',
    hpiTemplate: '{name}, a {age}-year-old {occupation} from {location}, at 30 weeks gestation, presents with regular lower abdominal tightening every 8-10 minutes for 3 hours and watery vaginal discharge with a fishy odour. No bleeding. Previous preterm loss at 28 weeks.',
    pmhTemplate: 'One prior preterm birth',
    medHxTemplate: 'Prenatal vitamins, ferrous sulphate',
    peTemplate: 'BP 118/75. Abdomen: uterine contractions palpable, soft, non-tender. Speculum: pooled amniotic fluid, clue cells on wet mount, positive whiff test. Cervix 2cm dilated, 50% effaced.',
    labsTemplate: 'Wet mount: clue cells, pH>4.5. FFn positive. CRP 18. Hb 11.2. Group B Streptococcus status unknown.',
    imagingTemplate: 'Transabdominal ultrasound: cervical length 2.0cm, singleton cephalic, AFI normal.',
    diagnosis: 'Symptomatic Preterm Labour with Bacterial Vaginosis at 30 Weeks',
    ddx: ['Preterm labour', 'UTI', 'Round ligament pain', 'Placental abruption', 'Braxton Hicks'],
    goalsTemplate: 'Delay delivery, mature fetal lungs, treat infection, improve neonatal outcome',
    pharmTemplate: '1. Tocolysis: Nifedipine 20mg PO then 10-20mg Q6-8h (short-term). 2. Fetal lung maturity: Betamethasone 12mg IM BD x2. 3. Antibiotics for BV: Metronidazole 400mg TDS 7 days (or 2g stat). 4. Magnesium sulphate 4g loading if <32 weeks for neuroprotection. 5. Group B Strep prophylaxis at delivery with Penicillin G.',
    nonPharmTemplate: 'Admit, hydration, fetal monitoring, pelvic rest, monitor for chorioamnionitis. Steroid course completion.',
    carePlanTemplate: 'Give steroids and metronidazole, tocolysis for 48h, monitor uterine activity and fetal status. Aim to reach >34 weeks. Transfer to facility with NICU if <32 weeks.',
    dtpsTemplate: '1. Antenatal steroids halve neonatal respiratory distress and mortality. 2. Treating BV reduces preterm birth recurrence. 3. Tocolytics only bridge to steroid effect, not long-term stop labour.',
    monitoringTemplate: 'Contraction frequency, fetal heart rate, maternal temp, WBC/CRP, cervical change. Watch for infection.',
    counsellingTemplate: 'Explain steroid benefits for baby, signs of labour progression, when to return. Pelvic rest.',
    followUpTemplate: 'Antenatal clinic after stabilisation; cervical length surveillance. Neonatal follow-up post-delivery.',
    pearlsTemplate: 'Antenatal corticosteroids before 34+6 weeks are the single most effective intervention for prematurity outcomes. Metronidazole treats BV in pregnancy (safe). Avoid indomethacin tocolysis near term (closure of ductus).',
    references: ['WHO: Preterm Birth Guidelines', 'Kenya Maternal Health Protocols'],
  },
  {
    pharmacologySubject: 'Obstetrics & Gynaecology Pharmacotherapy',
    specialty: 'Obstetrics and Gynecology',
    disease: 'Postpartum Haemorrhage',
    title: 'Primary Postpartum Haemorrhage after Vaginal Delivery',
    difficulty: 'Advanced',
    chiefComplaintTemplate: 'Excessive bleeding after delivery of the placenta',
    hpiTemplate: '{name}, a {age}-year-old {occupation} from {location}, delivered vaginally 1 hour ago. Estimated blood loss now 900 mL with continuous lochial bleeding and a soft, boggy uterus. She feels dizzy and thirsty. No trauma to birth canal confirmed. Fundus not contracting well.',
    pmhTemplate: 'Grande multipara, anaemia in pregnancy (Hb 9.5 at booking)',
    medHxTemplate: 'Iron supplementation, no other medicines',
    peTemplate: 'Pale, tachycardic HR 120, BP 90/55. Uterus boggy, fundus at umbilicus. Perineal pad saturating. Cold peripheries.',
    labsTemplate: 'Hb 7.2 g/dL (booking 9.5), Clotting: PT 16s, APTT 40s, Fibrinogen 1.2 g/L (low). Group O RhD negative crossmatched. Lactate 4.',
    imagingTemplate: 'Bedside ultrasound: retained products vs clot; if uncertain, examine under anaesthesia.',
    diagnosis: 'Primary Postpartum Haemorrhage (uterine atony) with coagulopathy',
    ddx: ['Uterine atony', 'Retained products', 'Genital tract trauma', 'Placenta accreta', 'Coagulation disorder'],
    goalsTemplate: 'Stop bleeding, restore volume and clotting, prevent shock and death',
    pharmTemplate: '1. Uterotonics: Oxytocin 10 IU IM/IV infusion (40 IU in 500mL over 4h); Ergometrine 0.2mg IM if no hypertension; Misoprostol 600mcg PR/SL; Tranexamic acid 1g IV. 2. Resuscitate: blood transfusion (O RhD negative uncrossmatched if urgent), IV fluids, FFP + Cryoprecipitate for fibrinogen. 3. Treat cause; prepare for surgical/balloon tamponade if medical fails.',
    nonPharmTemplate: 'Bimanual uterine massage, catheter, continuous monitoring, emergency theatre standby, cell salvage if available.',
    carePlanTemplate: 'Aggressive uterotonics + tranexamic acid, volume resuscitation with blood products, monitor clotting. If unresolved, intrauterine balloon, B-Lynch, or hysterectomy. RhIG if RhD negative.',
    dtpsTemplate: '1. PPH is a leading cause of maternal death; uterotonics (especially oxytocin) are first-line. 2. Tranexamic acid within 3h reduces mortality. 3. Correct fibrinogen early.',
    monitoringTemplate: 'Hourly pulse/BP, urine output, Hb, coagulation, temperature, bleeding volume. Early warning scores.',
    counsellingTemplate: 'Explain what happened and treatment. Future pregnancy counselling for recurrence. Contraception planning.',
    followUpTemplate: 'Postnatal ward monitoring 24-48h; anaemia treatment; family planning visit 6 weeks.',
    pearlsTemplate: 'Active management of third stage (oxytocin) prevents most PPH. Tranexamic acid <3h saves lives. Treat fibrinogen <2 g/L with cryoprecipitate. RhD-negative mothers need anti-D.',
    references: ['WHO: Postpartum Haemorrhage', 'Kenya EmOC Protocols'],
  },
];

// ---------- Paediatric ----------
export const PAEDIATRIC_TEMPLATES: ClinicalCaseTemplate[] = [
  {
    pharmacologySubject: 'Paediatric Pharmacotherapy',
    specialty: 'Pediatrics',
    disease: 'Severe Pneumonia',
    title: 'Severe Pneumonia in a Malnourished Child',
    difficulty: 'Intermediate',
    chiefComplaintTemplate: 'Fast breathing and cough with fever for 3 days',
    hpiTemplate: '{name}, a {age}-year-old child from {location}, presents with cough, fever, and fast breathing for 3 days, worsening today with inability to feed and lethargy. No convulsions. Immunisation incomplete (no PCV). Moderate acute malnutrition noted.',
    pmhTemplate: 'Moderate acute malnutrition, no prior admissions',
    medHxTemplate: 'Paracetamol at home, no antibiotics',
    peTemplate: 'Tachypnoea (RR 64), subcostal retractions, nasal flaring, grunting. SpO2 88% on room air. Crackles right lower zone. Hepatomegaly 2cm. No neck stiffness.',
    labsTemplate: 'WBC 19 x10^9/L, CRP 90 mg/L. Hb 8.5 (anaemia of malnutrition). Blood glucose 4.0. HIV status unknown.',
    imagingTemplate: 'Chest X-ray: right lower lobe consolidation with effusion.',
    diagnosis: 'Severe Pneumonia (bacterial, likely Strept pneumoniae) with hypoxaemia',
    ddx: ['Severe pneumonia', 'Bronchiolitis', 'Asthma exacerbation', 'TB pneumonia', 'Heart failure'],
    goalsTemplate: 'Eradicate infection, correct hypoxia, manage malnutrition, prevent death',
    pharmTemplate: '1. Oxygen via nasal prongs to maintain SpO2 >90%. 2. Empiric IV antibiotics: Benzylpenicillin 50 mg/kg QDS + Gentamicin 7.5 mg/kg OD (or Ampicillin + Gentamicin). 5-day course, step down to Amoxicillin PO if improving. 3. Paracetamol 15 mg/kg for fever. 4. Fluids: cautious maintenance (avoid overload); treat hypoglycaemia with 10% dextrose if low. 5. Start therapeutic feeding for malnutrition.',
    nonPharmTemplate: 'Position for comfort, monitor SpO2, encourage feeding, kangaroo care, infection control.',
    carePlanTemplate: 'Admit to paediatric ward/HDU, oxygen + IV antibiotics, monitor respiratory distress and SpO2. Review at 48h; step-down to oral amoxicillin. Nutritional rehabilitation alongside.',
    dtpsTemplate: '1. Paediatric dosing is weight-based — never adult doses. 2. Hypoxaemia must be corrected; oxygen is life-saving. 3. Malnutrition worsens outcomes; feeding started early.',
    monitoringTemplate: 'RR, SpO2, temperature, feeding, urine output, glucose. Watch for deterioration/effusion.',
    counsellingTemplate: 'Complete antibiotics. Feed frequently, observe breathing. Seek care if worse. Complete immunisations including PCV.',
    followUpTemplate: 'Review at 48h and at discharge; malnutrition clinic; immunisation catch-up.',
    pearlsTemplate: 'WHO classifies pneumonia by respiratory rate and danger signs. Oxygen + appropriate antibiotics save lives. Always weight-based dosing in children. Malnutrition is a key co-morbidity.',
    references: ['WHO Pocket Book of Hospital Care for Children', 'Kenya Paediatric Protocols'],
  },
  {
    pharmacologySubject: 'Paediatric Pharmacotherapy',
    specialty: 'Pediatrics',
    disease: 'Acute Gastroenteritis with Dehydration',
    title: 'Acute Watery Diarrhoea and Dehydration in a Toddler',
    difficulty: 'Beginner',
    chiefComplaintTemplate: 'Frequent watery stools and vomiting for 2 days',
    hpiTemplate: '{name}, a {age}-year-old child from {location}, has had 10-12 watery stools and 4 episodes of vomiting over 2 days during a cholera outbreak season. Now lethargic, drinking poorly, with sunken eyes and no urine for 8 hours.',
    pmhTemplate: 'Previously healthy, fully immunised',
    medHxTemplate: 'ORS at home, no facility care yet',
    peTemplate: 'Lethargic, sunken eyes, dry mucous membranes, skin pinch slow (>2s). HR 150, BP low, capillary refill 4s. Weight 9 kg (lost ~10%). No visible peristalsis.',
    labsTemplate: 'Electrolytes: Na 132, K 2.9, HCO3 12 (metabolic acidosis). Cr slightly up. Stool Rapid test for rotavirus positive; cholera culture pending in outbreak.',
    imagingTemplate: 'Not indicated.',
    diagnosis: 'Acute Gastroenteritis with Severe Dehydration (probable rotavirus/cholera)',
    ddx: ['Acute gastroenteritis', 'Cholera', 'Intussusception', 'Sepsis', 'Malabsorption'],
    goalsTemplate: 'Rehydrate, maintain, prevent recurrence, nutrition continuation',
    pharmTemplate: '1. Severe dehydration: IV Ringers Lactate 30 mL/kg in first hour, then 70 mL/kg over next 5h (or Ng tube if unable to drink), reassess. 2. Add Potassium 3-4 mmol/kg/day once urine flows. 3. Zinc 20 mg/day x10-14 days. 4. Switch to ORS once alert. 5. Continue age-appropriate feeding (not starve). 6. If cholera: single-dose Azithromycin 20 mg/kg.',
    nonPharmTemplate: 'Frequent small ORS sips, continue breastfeeding, strict hand hygiene, isolation precautions in outbreak. Monitor hydration signs.',
    carePlanTemplate: 'IV rehydration by plan, reassess hydration hourly, add K+, start zinc and feeding. Discharge on ORS with caretaker education. Report-to-health-facility signs.',
    dtpsTemplate: '1. Rehydration is the cornerstone; zinc and feeding reduce duration/mortality. 2. Avoid anti-motility drugs (loperamide) and routine antibiotics in non-cholera GE.',
    monitoringTemplate: 'Hydration signs, urine output, K+, weight, stool frequency, alertness. Watch for overload.',
    counsellingTemplate: 'Give ORS at home for mild dehydration, continue feeding, wash hands. Return if no urine, very sleepy, or blood in stool.',
    followUpTemplate: 'Rehydration clinic next day if discharged; immunisation (rotavirus) catch-up.',
    pearlsTemplate: 'Treat dehydration by Plan (WHO): ORS for some, IV for severe. Zinc + continued feeding halve mortality. Never withhold food. Loperamide is unsafe in young children.',
    references: ['WHO: Diarrhoeal Disease Management', 'Kenya Paediatric Protocols'],
  },
  {
    pharmacologySubject: 'Paediatric Pharmacotherapy',
    specialty: 'Pediatrics',
    disease: 'Neonatal Sepsis',
    title: 'Suspected Neonatal Sepsis in a 5-Day-Old',
    difficulty: 'Advanced',
    chiefComplaintTemplate: 'Poor feeding, lethargy, and fever in a newborn',
    hpiTemplate: '{name}, a 5-day-old neonate from {location}, delivered at home, presents with poor sucking, lethargy, temperature 38.3°C, and grunting. Born to a mother with prolonged rupture of membranes. No antenatal care. Appears ill.',
    pmhTemplate: 'Home delivery, no prophylaxis, low birth weight 2.0 kg',
    medHxTemplate: 'None',
    peTemplate: 'Lethargic, hypotonic, tachypnoeic (grunting), poor perfusion, capillary refill 4s, temp 38.3°C. Umbilicus erythematous. Fontanelle normal.',
    labsTemplate: 'WBC 4.2 (neutropaenia), CRP 60, blood culture pending. Glucose 2.4 (hypoglycaemia). Lactate 4.5.',
    imagingTemplate: 'Chest X-ray: possible patchy infiltrate. LP if meningitis suspected (send CSF culture).',
    diagnosis: 'Suspected Early Neonatal Sepsis (possible E. coli / Group B Strep)',
    ddx: ['Neonatal sepsis', 'Meningitis', 'Pneumonia', 'Hypoglycaemia', 'TORCH infection'],
    goalsTemplate: 'Empiric antimicrobial cover, support, prevent mortality and sequelae',
    pharmTemplate: '1. Empiric IV antibiotics: Ampicillin 50 mg/kg QDS + Gentamicin 5 mg/kg OD (adjust for renal function/age). 2. Correct hypoglycaemia: 10% dextrose IV bolus then infusion. 3. Support: oxygen, fluids (maintenance, cautious), keep warm. 4. Acyclovir if HSV risk. 5. Review cultures at 48h; tailor therapy.',
    nonPharmTemplate: 'Neonatal ICU care, temperature regulation, feeding support (NG/expressed milk), monitor glucose, aseptic care.',
    carePlanTemplate: 'Admit to neonatal unit, start empiric antibiotics promptly (do not delay for cultures), support ABCs, monitor glucose and vital signs. LP if meningitis suspected. 10-14 day course per organism.',
    dtpsTemplate: '1. Neonatal sepsis is an emergency — start antibiotics immediately; mortality high if delayed. 2. Dosing is weight and age (postnatal) dependent; gentamicin intervals differ in newborns. 3. Hypoglycaemia common and dangerous.',
    monitoringTemplate: 'Temp, RR, HR, glucose q4-6h, perfusion, I/O, cultures, CRP trend. Watch for shock.',
    counsellingTemplate: 'Explain seriousness and treatment. Kangaroo mother care when stable. Follow-up for neurodevelopment. Antenatal care importance.',
    followUpTemplate: 'Neonatal follow-up at discharge; developmental surveillance; ensure immunisations.',
    pearlsTemplate: 'In suspected neonatal sepsis give antibiotics without delay — do not wait for cultures. Ampicillin + gentamicin covers common organisms. Always check glucose in ill neonates. Kangaroo care reduces mortality.',
    references: ['WHO: Neonatal Care', 'Kenya Newborn Health Protocols'],
  },
];
