// ================================================================
// Gastrointestinal Pharmacology — Case Templates
// 8 templates covering: PUD, GERD, H. pylori, Cirrhosis, Hepatitis,
// Pancreatitis, IBS, IBD
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';

function tpl(
  pharmacologySubject: string, specialty: string, disease: string,
  title: string, difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string, hpi: string, pmh: string, medHx: string,
  pe: string, labs: string, imaging: string,
  diagnosis: string, ddx: string[],
  goals: string, pharm: string, nonPharm: string, carePlan: string,
  dtps: string, monitoring: string, counselling: string, followUp: string,
  pearls: string, references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject, specialty, disease, title, difficulty,
    chiefComplaintTemplate: chiefComplaint, hpiTemplate: hpi,
    pmhTemplate: pmh, medHxTemplate: medHx, peTemplate: pe,
    labsTemplate: labs, imagingTemplate: imaging, diagnosis, ddx,
    goalsTemplate: goals, pharmTemplate: pharm,
    nonPharmTemplate: nonPharm, carePlanTemplate: carePlan,
    dtpsTemplate: dtps, monitoringTemplate: monitoring,
    counsellingTemplate: counselling, followUpTemplate: followUp,
    pearlsTemplate: pearls, references,
  };
}

export const GASTROINTESTINAL_TEMPLATES: ClinicalCaseTemplate[] = [
  tpl(
    'Gastrointestinal Pharmacology', 'Gastroenterology', 'Peptic Ulcer Disease',
    'Duodenal Ulcer Presenting with Epigastric Pain and Nocturnal Symptoms',
    'Beginner',
    'Burning epigastric pain relieved by food, worse at night, for 3 weeks',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 3-week history of burning epigastric pain that comes on 2-3 hours after meals and is relieved by eating or taking antacids. Pain wakes him at night (~2 AM). Reports bloating and occasional nausea but no vomiting. Has been using an over-the-counter antacid mixture (Maalox) with temporary relief. Appetite is good and no weight loss. No NSAID use.',
    'No significant PMH. Non-smoker. Drinks alcohol occasionally (weekends only).',
    'No regular medications. Uses OTC antacids PRN.',
    'Well-nourished. Mild epigastric tenderness on deep palpation. No guarding or rebound. Bowel sounds normal. No masses. Rectal exam: brown stool, occult blood negative.',
    'Hb 14.0 g/dL. H. pylori stool antigen: Positive. LFTs normal. Serum gastrin: normal. Fasting glucose: normal.',
    'No imaging indicated. Upper GI endoscopy (if performed): clean-based duodenal ulcer in the duodenal bulb, no stigmata of recent haemorrhage.',
    'Duodenal Ulcer — H. pylori Positive',
    ['Duodenal Ulcer', 'Gastric Ulcer', 'GERD', 'Non-Ulcer Dyspepsia', 'Pancreatitis'],
    'Heal ulcer, eradicate H. pylori, relieve symptoms, prevent recurrence and complications',
    '1. First-line H. pylori eradication therapy per Kenya guidelines: Triple therapy for 14 days: Omeprazole 20mg BID + Amoxicillin 1g BID + Clarithromycin 500mg BID. 2. Continue Omeprazole 20mg daily for 4-8 weeks total for ulcer healing. 3. If penicillin-allergic: Omeprazole 20mg BID + Metronidazole 400mg BID + Clarithromycin 500mg BID (or Tetracycline 500mg QID + Metronidazole 400mg TID + Bismuth + PPI).',
    'Avoid NSAIDs, alcohol, and smoking during treatment. Small frequent meals. Avoid spicy or acidic foods if they worsen symptoms.',
    'Start triple therapy for 14 days. Continue PPI for total 8 weeks. Confirm H. pylori eradication with stool antigen test at 4 weeks after completing antibiotics. Advise on alarm symptoms (melena, haematemesis, severe pain).',
    '1. Active H. pylori infection causing duodenal ulcer requiring eradication therapy. 2. Risk of ulcer complications (bleeding, perforation) if untreated.',
    'Symptom diary. Monitor for side effects of triple therapy (metallic taste with clarithromycin, diarrhoea, nausea). Stool antigen test at 4 weeks post-treatment to confirm eradication.',
    'Take all medications as prescribed. Complete the full 14-day course even if symptoms improve — stopping early leads to treatment failure and antibiotic resistance. Report severe diarrhoea (C. difficile risk with antibiotics). Avoid NSAIDs permanently.',
    'Gastroenterology review in 8 weeks to confirm healing. Repeat endoscopy only if symptoms persist or alarm features develop.',
    'H. pylori eradication success rates with standard triple therapy are declining (<80% in many regions) due to clarithromycin resistance. If first-line fails, switch to bismuth-based quadruple therapy or levofloxacin-based regimen. Always confirm eradication 4 weeks after treatment.',
    ['Kenya Clinical Guidelines: Peptic Ulcer Disease', 'ACG Guidelines: H. pylori Management', 'Maastricht VI/Florence Consensus: H. pylori'],
  ),

  tpl(
    'Gastrointestinal Pharmacology', 'Gastroenterology', 'GERD',
    'Gastro-Oesophageal Reflux Disease with Oesophagitis',
    'Beginner',
    'Frequent heartburn, regurgitation, and sour taste in mouth for 2 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with retrosternal burning sensation (heartburn) occurring 30-60 minutes after meals, worse on lying down or bending forward. Reports acid regurgitation leaving a sour taste, occasional difficulty swallowing (dysphagia) with solid food, and chronic cough (worse at night). Symptoms started 2 months ago and have been increasing in frequency (now daily). Uses over-the-counter antacids with minimal relief. BMI 31 kg/m².',
    'Mild intermittent asthma. No prior GI surgery.',
    'No regular medications',
    'Overweight (BMI 31). Oral cavity: dental enamel erosion noted. Mild halitosis. Abdomen: soft, non-tender. No epigastric masses. No hepatosplenomegaly.',
    'Hb 13.5 g/dL. H. pylori stool antigen: Negative. OGD (if performed): Los Angeles Grade B oesophagitis (linear erosions <5mm not extending between mucosal folds at distal oesophagus). Biopsy: negative for Barretts or dysplasia.',
    'No routine imaging. Barium swallow (if dysphagia): normal oesophageal motility, hiatal hernia noted.',
    'Gastro-Oesophageal Reflux Disease with Grade B Reflux Oesophagitis',
    ['GERD', 'Non-Erosive Reflux Disease', 'Functional Dyspepsia', 'Oesophageal Spasm', 'Peptic Ulcer Disease'],
    'Control symptoms, heal oesophagitis, prevent complications (stricture, Barretts oesophagus, aspiration), improve quality of life',
    '1. PPI therapy: Omeprazole 20mg daily before breakfast for 8 weeks (or Esomeprazole 40mg daily, Pantoprazole 40mg daily). 2. If partial response: increase to BID dosing. 3. Antacids/alginates PRN for breakthrough symptoms (e.g., Gaviscon Advance 10mL after meals and at bedtime). 4. If nocturnal symptoms despite PPI: add H2RA (Ranitidine 150mg or Famotidine 20mg at bedtime, though Ranitidine is off-market in some regions). 5. Prokinetic agents (Metoclopramide 10mg TID) may be considered but use cautiously due to side effects.',
    'Weight loss (target BMI <25). Elevate head of bed (6-8 inch blocks under headposts). Avoid meals within 3 hours of bedtime. Avoid triggers: fatty foods, chocolate, caffeine, alcohol, carbonated drinks, spicy foods. Stop smoking.',
    'Start PPI at standard dose. Lifestyle modifications as above. Review in 4-8 weeks. If symptoms controlled, step down to lowest effective PPI dose (e.g., maintenance Omeprazole 10-20mg daily). If poor response: OGD to assess for complications, pH monitoring, manometry.',
    '1. Acid reflux causing erosive oesophagitis requiring gastric acid suppression. 2. Modifiable risk factors: obesity and dietary habits.',
    'Symptom diary (frequency and severity of heartburn, regurgitation). Watch for alarm symptoms: dysphagia, weight loss, GI bleeding, anaemia. Annual FBC to check for iron deficiency.',
    'Take PPI 30-60 minutes before breakfast for best effect. PPI is not a "when needed" drug — daily adherence is key for healing. Weight loss is the single most effective lifestyle change. Elevate head of bed — use blocks, not extra pillows (pillows increase abdominal pressure).',
    'Follow-up in 8 weeks. If symptoms recur on step-down PPI, continue lowest effective maintenance dose long-term. Repeat OGD in 3-5 years if Barretts surveillance needed.',
    'PPIs are the most effective medical therapy for GERD. They should be taken 30-60 min before meals (not at bedtime) for maximal effect on proton pumps activated by food intake. Long-term PPI use (>1 year) warrants monitoring for: B12 deficiency, osteoporosis, hypomagnesaemia, C. difficile, and community-acquired pneumonia.',
    ['ACG Guidelines: GERD Management', 'Lyon Consensus: GERD Definition', 'Kenya Essential Medicines List: GI Medicines'],
  ),

  tpl(
    'Gastrointestinal Pharmacology', 'Gastroenterology', 'Helicobacter pylori Infection',
    'H. pylori-Positive Gastritis in a Young Adult with Dyspepsia',
    'Beginner',
    'Chronic epigastric discomfort, bloating, and belching for 2 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with long-standing epigastric discomfort described as gnawing, associated with bloating, excessive belching, and early satiety. No specific food triggers. No nocturnal pain. No weight loss. Was treated for "gastritis" twice in the past year with antacids and ranitidine but symptoms always returned. No NSAID use.',
    'No significant PMH.',
    'No regular medications. Previous courses of Ranitidine and antacids.',
    'Healthy appearance. Epigastric mild tenderness. No masses. No hepatosplenomegaly.',
    'H. pylori stool antigen: Positive. Urea breath test: Positive. Hb 13.8 g/dL (normal). LFTs normal. OGD: diffuse antral gastritis, no ulcers, biopsies taken.',
    'No imaging indicated.',
    'Chronic H. pylori-Associated Antral Gastritis',
    ['H. pylori Gastritis', 'Non-Ulcer Dyspepsia', 'Functional Dyspepsia', 'Peptic Ulcer Disease', 'Gastric Cancer'],
    'Eradicate H. pylori, resolve gastritis, reduce risk of peptic ulcer and gastric cancer, relieve dyspeptic symptoms',
    '1. First-line therapy (if no prior macrolide exposure): Clarithromycin-based triple therapy for 14 days: Omeprazole 20mg BID + Amoxicillin 1g BID + Clarithromycin 500mg BID. 2. If penicillin-allergic: Bismuth quadruple therapy: Omeprazole 20mg BID + Bismuth subsalicylate 524mg QID + Metronidazole 500mg TID + Tetracycline 500mg QID for 14 days. 3. Alternative in high clarithromycin resistance: Bismuth quadruple therapy as above.',
    'Avoid NSAIDs and alcohol during treatment. No specific dietary restrictions.',
    'Prescribe 14-day eradication therapy. Explain importance of completing full course. Confirm eradication with stool antigen or urea breath test at least 4 weeks after completion. If positive: salvage therapy with bismuth quadruple or levofloxacin-based regimen.',
    '1. Active H. pylori infection causing chronic gastritis requiring eradication. 2. Risk of progression to PUD, MALT lymphoma, or gastric adenocarcinoma if untreated.',
    'Monitor for side effects of antibiotics (diarrhoea, metallic taste, nausea). Urea breath test or stool antigen at 4 weeks post-treatment to confirm eradication.',
    'Complete ALL 14 days of treatment — even one missed dose can lead to resistance. Avoid alcohol during treatment and for 1 week after (metronidazole interaction). The dark stools from bismuth (if on quadruple therapy) are normal. Report severe diarrhoea or rash.',
    'Follow-up in 6-8 weeks to review eradication test results. If eradication fails, refer to gastroenterology for resistance-guided therapy.',
    'Clarithromycin resistance rates in Kenya are rising (estimated 20-30%). Bismuth quadruple therapy is recommended as first-line in areas with >15% clarithromycin resistance. H. pylori is a WHO Class I carcinogen for gastric cancer. Eradication reduces gastric cancer risk in patients with precancerous lesions.',
    ['Maastricht VI Consensus: H. pylori', 'Kenya Clinical Guidelines: Dyspepsia Management', 'ACG Guidelines: H. pylori Treatment'],
  ),

  tpl(
    'Gastrointestinal Pharmacology', 'Hepatology', 'Liver Cirrhosis',
    'Compensated Liver Cirrhosis with New-Onset Ascites and Hepatic Encephalopathy',
    'Advanced',
    'Increasing abdominal swelling, confusion, and yellow eyes for 1 week',
    '{name}, a {age}-year-old {occupation} from {location}, was brought by family due to progressive abdominal distension, confusion (not recognising family members), and jaundice noticed over the past week. Family reports decreased appetite, weight gain (abdominal), and that he has been sleeping during the day and agitated at night. Has a long history of heavy alcohol use (changaa and busaa daily for 15+ years). Stopped lactulose 5 days ago because of diarrhoea.',
    'Alcohol-related liver disease (diagnosed 3 years ago after an episode of variceal bleed, banded). Hypertension.',
    'Spironolactone 100mg daily, Furosemide 40mg daily, Nadolol 40mg daily, Lactulose 30mL TID (intermittent adherence)',
    'Jaundiced, confused (GCS 14/15), asterixis present. Abdomen: distended, tense, shifting dullness positive, fluid thrill positive. Caput medusae. Palmar erythema. Spider naevi (2 on chest). Lower extremity 2+ pitting oedema.',
    'Hb 10.5 g/dL. WBC 4.2. Platelets 85 (thrombocytopenia). Na+ 126 mEq/L (hyponatraemia). K+ 3.1 mEq/L. Creatinine 1.4 mg/dL (AKI). Total bilirubin 4.8 mg/dL (direct 2.5). AST 85, ALT 55 (AST>ALT). Albumin 2.4 g/dL. INR 1.7. Ascitic fluid: SAAG >1.1, PMN <250 cells/mm3 (no SBP). Ammonia: 95 µmol/L.',
    'Abdominal ultrasound: Coarse nodular liver, caudate lobe hypertrophy, splenomegaly (14.5cm), large volume ascites, portal vein diameter 14mm (portal hypertension).',
    'Decompensated Alcohol-Related Cirrhosis (Child-Pugh Class C) with Ascites, Hepatic Encephalopathy (Grade 2), and Acute Kidney Injury (Hepatorenal Syndrome Type 1 vs Pre-Renal)',
    ['Decompensated Cirrhosis', 'Spontaneous Bacterial Peritonitis', 'Acute Hepatitis', 'Heart Failure', 'Budd-Chiari Syndrome'],
    'Reverse hepatic encephalopathy, mobilise ascites, prevent SBP, assess for liver transplant, correct hyponatraemia and AKI',
    '1. Hepatic Encephalopathy: Restart Lactulose 30mL every 2-4 hours until 2-3 soft stools/day. Add Rifaximin 550mg BID (if available). 2. Ascites: Therapeutic paracentesis (large volume if tense). Hold diuretics if creatinine rising or hyponatraemia worsening. IV Albumin 25% 20-40g daily if large volume paracentesis >5L or Hepatorenal Syndrome suspected. 3. AKI: Hold diuretics, volume expand with IV Albumin, stop nephrotoxins. 4. Correct K+ to >3.5. 5. Avoid sedatives for confusion (may worsen encephalopathy).',
    'Low sodium diet (<2g/day). Fluid restriction 1.5L/day if Na <125. Bed rest. Daily weights. Abstain from alcohol completely. Nutritional support (high calorie, moderate protein, with branch-chain amino acids if protein intolerant).',
    'Admit to medical ward. Aggressive lactulose therapy. Stop diuretics. Large volume paracentesis with albumin cover. Monitor neuro status, urine output, daily weights, abdominal girth. Discuss transplant evaluation with hepatology. Assess for alcohol cessation programmes.',
    '1. Decompensated cirrhosis with multiple complications: encephalopathy, ascites, hyponatraemia, AKI. 2. Non-adherence to lactulose precipitating hepatic encephalopathy. 3. Diuretic-induced complications (hyponatraemia, hypokalaemia, AKI).',
    'Daily: weight, abdominal girth, strict I/O, neuro status (GCS, asterixis), BMP (Na, K, Cr), LFTs, INR. Monitor stool frequency on lactulose (target: 2-3 soft BMs/day). Monitor for SBP (fever, worsening ascites, abdominal pain).',
    'Abstinence from alcohol is essential for any improvement in liver function. Lactulose titration: adjust dose to achieve 2-3 soft bowel movements daily. Watch for confusion, sleep reversal, personality changes — early signs of encephalopathy. Low salt diet means no added salt, avoid processed foods.',
    'Hepatology follow-up in 1-2 weeks post-discharge. Transplant evaluation if eligible (abstinence for 6 months required in most programmes). OGD for variceal screening if not up to date.',
    'Hepatic encephalopathy is a clinical diagnosis — ammonia levels correlate poorly with severity. Lactulose works by acidifying the colon, converting NH3 to NH4+ (non-absorbable). Rifaximin is an evidence-based add-on for secondary prevention. Diuretics in cirrhosis can precipitate hepatorenal syndrome — use cautiously. Persistent hyponatraemia (Na <120) despite fluid restriction may require 3% saline (risk of osmotic demyelination, correct slowly).',
    ['EASL Guidelines: Decompensated Cirrhosis', 'AASLD Guidelines: Hepatic Encephalopathy', 'Kenya Clinical Guidelines: Liver Disease'],
  ),

  tpl(
    'Gastrointestinal Pharmacology', 'Hepatology', 'Hepatitis',
    'Acute Hepatitis B Virus Infection with Jaundice',
    'Intermediate',
    'Yellow eyes and skin, dark urine, extreme fatigue, and right upper quadrant pain for 1 week',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive jaundice, dark urine (cola-coloured), pale stools, severe fatigue, anorexia, nausea, and right upper quadrant discomfort. Symptoms began with fever, myalgia, and joint pain 2 weeks ago, which resolved. Now feels profoundly weak. No known prior liver disease.',
    'No significant PMH. No known hepatitis. No IV drug use. Reports one new sexual partner in the past 3 months (condom use inconsistent).',
    'No regular medications.',
    'Deeply jaundiced. Mild RUQ tenderness. Liver: palpable 3cm below costal margin, firm, mildly tender. No splenomegaly. No ascites. No asterixis.',
    'Total bilirubin 12.5 mg/dL (direct 8.2). AST 1250 U/L, ALT 1580 U/L (ALT>AST). ALP 180 U/L. Hb 13.0, WBC 6.5, Platelets 220. INR 1.3. HBsAg: Positive. HBeAg: Positive. Anti-HBc IgM: Positive. Anti-HBs: Negative. Anti-HAV IgM: Negative. Anti-HCV: Negative. HBV DNA: 6.8 log10 IU/mL.',
    'Abdominal ultrasound: Hepatomegaly (18cm), diffusely increased echogenicity (echogenic liver), no focal lesions, normal spleen, no ascites.',
    'Acute Hepatitis B Virus Infection (HBeAg-positive, high viral load)',
    ['Acute HBV', 'Acute Hepatitis A', 'Acute Alcoholic Hepatitis', 'Drug-Induced Liver Injury', 'Autoimmune Hepatitis'],
    'Supportive care during acute illness, monitor for fulminant hepatitis, prevent chronic HBV (in adults, 95% clear spontaneously), reduce transmission risk',
    '1. No specific antiviral therapy indicated for acute HBV in immunocompetent adults (spontaneous clearance rate 95%). 2. Supportive care: IV fluids if dehydrated, Antiemetics (Ondansetron 4mg IV PRN if no prolonged QT), avoid hepatotoxic drugs (paracetamol max 2g/day, no NSAIDs). 3. Consider Tenofovir Disoproxil Fumarate 300mg daily if: severe/fulminant hepatitis (INR >1.5, encephalopathy) or prolonged course (>4 weeks with persistent high ALT). 4. Vitamin K 10mg IV if INR elevated.',
    'Rest, adequate nutrition (small frequent meals, high-carbohydrate), avoid alcohol completely for 6 months minimum. Contact tracing and vaccination of household contacts and sexual partners.',
    'Admit for monitoring of acute hepatitis. LFTs, INR daily. Watch for signs of fulminant hepatitis: rising INR, encephalopathy, hypoglycaemia. Notify public health authorities (reportable disease). Counsel on transmission prevention: no unprotected sex, no sharing toothbrushes/razors, clean blood spills with bleach.',
    '1. Acute HBV infection requiring supportive care and monitoring for fulminant disease. 2. Public health concern: transmissible disease requiring contact tracing and prevention.',
    'Daily: LFTs, INR, bilirubin, mental status. Platelet count. Monitor for signs of progression to fulminant hepatitis (encephalopathy, rising INR, rapid drop in liver size). HBV DNA at diagnosis. Repeat HBsAg at 6 months to check clearance.',
    'Hepatitis B is transmitted through blood, sexual contact, and from mother to child. Use condoms consistently until you test negative for HBsAg. Your household contacts and sexual partners need testing and vaccination. Do not drink alcohol for at least 6 months. Rest is important — your liver needs energy to heal.',
    'Gastroenterology/hepatology clinic in 4 weeks. Repeat LFTs, HBsAg, HBeAg, and HBV DNA in 3 and 6 months. If HBsAg remains positive at 6 months, diagnosis changes to chronic HBV and treatment may be indicated.',
    'In healthy adults, >95% of acute HBV infections clear spontaneously. Risk of chronic infection is inversely related to age: <5% in adults, 30-50% in children <6 years, 90% in neonates. Tenofovir is not routinely indicated for acute HBV but should be considered in severe/fulminant cases. All pregnant women should be screened for HBsAg — infants of HBsAg+ mothers need HBIG + vaccine within 12 hours.',
    ['Kenya Clinical Guidelines: Hepatitis B Management', 'EASL Guidelines: Hepatitis B', 'WHO Guidelines: Prevention of Mother-to-Child Transmission of HBV'],
  ),

  tpl(
    'Gastrointestinal Pharmacology', 'Gastroenterology', 'Pancreatitis',
    'Acute Pancreatitis Secondary to Gallstones',
    'Advanced',
    'Severe epigastric pain radiating to the back, nausea, and vomiting for 12 hours',
    '{name}, a {age}-year-old {occupation} from {location}, presents with acute onset of severe epigastric pain described as "boring" and radiating straight through to the back. Pain started 12 hours after a heavy meal and is constant, rated 9/10. Associated with nausea, repeated vomiting (non-bilious), and inability to keep fluids down. Sitting forward provides some relief. Has had similar but milder episodes in the past after fatty meals.',
    'Overweight (BMI 29). Known gallstones (incidental finding on USS 2 years ago). No gallstone-related complications previously. No alcohol use.',
    'No regular medications',
    'In severe distress, leaning forward. Low-grade fever. Tachycardic. Abdomen: epigastric tenderness with guarding, decreased bowel sounds. Murphy sign negative. No jaundice.',
    'Serum Lipase: 1850 U/L (normal <60). Amylase: 1200 U/L. WBC 14.5. CRP 240 mg/L. LFTs: AST 120, ALT 95, ALP 180, GGT 210, Total bilirubin 1.8 mg/dL (suggests possible gallstone in common bile duct). Ca: 8.8 mg/dL. Triglycerides: normal. ABG: pH 7.35. Lactic acid: 2.1.',
    'Abdominal ultrasound: Multiple gallstones in a thick-walled gallbladder. Common bile duct 10mm (dilated). Pancreas: diffusely enlarged and hypoechoic (acute pancreatitis). No pseudocyst.',
    'Acute Biliary Pancreatitis (Moderately Severe per Revised Atlanta Classification)',
    ['Acute Pancreatitis (biliary)', 'Acute Pancreatitis (alcoholic)', 'Perforated Peptic Ulcer', 'Cholecystitis', 'Mesenteric Ischaemia'],
    'Pain control, aggressive IV fluid resuscitation, monitor for complications (necrosis, organ failure), definitive management of gallstones',
    '1. Aggressive IV fluid resuscitation: Ringer\'s Lactate at 250-300 mL/hour for first 24-48 hours (monitor for fluid overload). 2. Analgesia: IV Morphine 5-10mg q4h PRN (no evidence that morphine worsens outcomes). 3. Antiemetics: Ondansetron 4mg IV q8h. 4. Notify for ERCP (endoscopic retrograde cholangiopancreatography) within 24-48 hours if evidence of cholangitis or persistent biliary obstruction (bilirubin rising, dilated CBD). 5. No routine antibiotics unless evidence of infected necrosis or cholangitis (imipenem or meropenem if infected).',
    'NPO initially (nasogastric tube if vomiting). Stepwise reintroduction of oral feeds when pain subsides, hunger returns, and lipase trending down (start clear liquids, low-fat diet). Monitor for complications: pancreatic necrosis, pseudocyst, organ failure.',
    'Admit to ward or HDU. Aggressive IV fluids. Pain control. Monitor for organ failure (renal, respiratory, cardiovascular). Assess severity: APACHE II, Ranson criteria, or BISAP score. Arrange ECRP if biliary obstruction persists. Once pancreatitis resolves, plan for laparoscopic cholecystectomy during same admission (reduces recurrence).',
    '1. Acute biliary pancreatitis requiring fluid resuscitation and supportive care. 2. Obstructing gallstone requiring ECRP. 3. Risk of necrotising pancreatitis and multi-organ failure.',
    'First 24 hours: vital signs q1h, I/O q1h, oxygen saturation, urine output (>0.5 mL/kg/hr). Daily: LFTs, lipase, CRP, Ca, Lactic acid. Assess for organ failure: respiratory (PaO2/FiO2), renal (creatinine), cardiovascular (need for vasopressors). CT scan with contrast at 72 hours if no improvement (to assess for necrosis).',
    'Acute pancreatitis is a serious condition requiring intensive monitoring. The initial treatment is aggressive IV fluids and strict bowel rest. Gallstones are the most common cause in Kenya — you will need gallbladder removal surgery once the inflammation resolves to prevent recurrence. Recovery may take 1-2 weeks.',
    'Surgical review for laparoscopic cholecystectomy after resolution. Outpatient follow-up in 4 weeks post-discharge. Pancreatic enzyme replacement (Creon) if exocrine insufficiency develops.',
    'Revised Atlanta Classification: Mild (no organ failure, no complications), Moderately Severe (organ failure <48 hours or local complications), Severe (organ failure >48 hours). Aggressive IV fluids in first 24 hours are the most important intervention — hypovolaemia is the main driver of pancreatic necrosis. Morphine is safe for pain in pancreatitis. ECRP is indicated only if cholangitis or persistent obstruction.',
    ['IAP/APA Guidelines: Acute Pancreatitis', 'ACG Guidelines: Acute Pancreatitis', 'Kenya Clinical Guidelines: Gallstone Disease'],
  ),

  tpl(
    'Gastrointestinal Pharmacology', 'Gastroenterology', 'Irritable Bowel Syndrome',
    'Diarrhoea-Predominant IBS Affecting Work and Quality of Life',
    'Intermediate',
    'Chronic intermittent abdominal pain and frequent loose stools for 6 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 6-month history of recurrent crampy abdominal pain (usually left lower quadrant or diffuse), associated with urgent loose stools (3-5 episodes/day, watery/mushy). Pain is relieved by defecation. Symptoms are worse in the morning and after meals. Reports bloating, mucus in stool, and feeling of incomplete evacuation. No nocturnal symptoms. No weight loss. No blood in stool. Symptoms are causing significant anxiety about going out. Precipitated by a stressful work period and a bout of food poisoning.',
    'No significant PMH. Family history: mother had "colitis." Non-smoker. Not on any regular medications.',
    'No regular medications. Has tried loperamide PRN with partial relief.',
    'General: Anxious but well-nourished, BMI 26. Abdomen: mild diffuse tenderness on deep palpation, no guarding. Normal bowel sounds. No organomegaly. Rectal exam: normal tone, no masses, brown stool, occult blood negative.',
    'Hb 13.2 g/dL (normal). CRP 2 mg/L (normal). TTG IgA: negative (rules out coeliac disease). Stool culture: negative. Stool calprotectin: 30 mcg/g (normal <50 — rules out inflammatory bowel disease). Faecal occult blood: negative. Thyroid function: normal.',
    'Imaging not routinely indicated. Colonoscopy (if over 45 or alarm features): normal mucosa throughout, random biopsies normal.',
    'Irritable Bowel Syndrome — Diarrhoea-Predominant (IBS-D) per Rome IV Criteria',
    ['IBS-D', 'IBD (Crohns/UC)', 'Coeliac Disease', 'Microscopic Colitis', 'Lactose Intolerance', 'Hyperthyroidism'],
    'Relieve abdominal pain and diarrhoea, improve stool consistency, reduce impact on quality of life, rule out organic disease',
    '1. First-line: Antispasmodic — Mebeverine 135mg TID or Hyoscine Butylbromide 10mg TID PRN for pain. 2. For diarrhoea: Loperamide 2mg PRN up to 16mg/day (take before meals/situations where urgency is anticipated). 3. Second-line: Low-dose tricyclic antidepressant — Amitriptyline 10-25mg at bedtime (slows transit, reduces visceral pain). 4. If constipation-predominant: Linaclotide 290mcg daily or Lubiprostone. 5. Probiotics: consider Bifidobacterium infantis 1 sachet daily. 6. Consider Rifaximin 550mg TID for 14 days if non-C IBS-D with bloating.',
    'Dietary: Low FODMAP diet trial for 4-6 weeks under dietitian guidance. Keep symptom diary: identify personal triggers (common: wheat, dairy, onions, beans, caffeine, alcohol). Stress management: CBT, gut-directed hypnotherapy, mindfulness. Regular exercise. Adequate sleep.',
    'Confirm Rome IV criteria and negative alarm features. Start with lifestyle modifications and symptom diary. Trial of low-FODMAP diet. PRN medications for pain and diarrhoea. If limited response after 3 months, start low-dose amitriptyline. Avoid unnecessary colonoscopy if <45 and no alarm features.',
    '1. Chronic functional GI disorder requiring symptom management and dietary modification. 2. Psychological factors (anxiety, stress sensitivity) contributing to symptom severity.',
    'Symptom diary (Bristol Stool Chart, pain frequency/severity, triggers). Quality of life assessment (IBS-QOL). Monitor for alarm features. Annual FBC and CRP.',
    'IBS is a real condition — it is not "all in your head." The gut and brain communicate bidirectionally (gut-brain axis). Stress management is as important as medication. The low-FODMAP diet is effective but should be done with expert guidance. Keep a symptom diary to identify your personal triggers.',
    'Follow-up in 4-8 weeks to assess response. If poor response: consider dietitian referral, psychological therapies, or medication adjustment (increase amitriptyline gradually). Repeat assessment if alarm features develop.',
    'Rome IV criteria: Recurrent abdominal pain (>1 day/week in last 3 months) associated with ≥2 of: related to defecation, change in stool frequency, change in stool form. IBS is a diagnosis of exclusion only in the presence of alarm features. Low-dose tricyclics (amitriptyline) are underutilised but highly effective for IBS — they work by modulating visceral pain and gut transit. Low-FODMAP diet reduces symptoms in 50-80% of patients.',
    ['Rome IV Diagnostic Criteria: IBS', 'ACG Guidelines: IBS Management', 'NICE Guideline: IBS in Adults'],
  ),

  tpl(
    'Gastrointestinal Pharmacology', 'Gastroenterology', 'Inflammatory Bowel Disease',
    'Moderate Ulcerative Colitis with Frequent Relapses',
    'Advanced',
    'Bloody diarrhoea, abdominal cramps, and urgency for 4 weeks',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 4-week flare of bloody diarrhoea (6-8 episodes/day), lower abdominal cramping, tenesmus, and urgency. Reports fatigue and mild weight loss (3 kg over 2 months). Has a history of ulcerative colitis (diagnosed 3 years ago, pancolitis on colonoscopy). Previously well-controlled on Mesalazine but defaulted treatment 2 months ago due to cost. Has had 3 flares in the past year requiring oral steroids.',
    'Ulcerative Colitis (pancolitis, diagnosed age 25), Anaemia of chronic disease',
    'Mesalazine 4.8g daily (oral, suspended 2 months ago), occasional loperamide for diarrhoea',
    'Mildly pale. Abdomen: left lower quadrant tenderness, no guarding, no masses. Perianal inspection: normal. PR: blood on glove. Temperature: 37.5°C.',
    'Hb 10.2 g/dL (normocytic, normochromic). WBC 11.5. Platelets 450 (thrombocytosis of inflammation). CRP 65 mg/L. ESR 45 mm/hr. Calprotectin (faecal): 1200 mcg/g (markedly elevated). Albumin 3.0 g/dL. Stool cultures: negative for pathogens. pANCA: positive.',
    'Flexible sigmoidoscopy: Erythema, granularity, friable mucosa, loss of vascular pattern, superficial ulcerations extending to 40 cm (moderate disease, Mayo Endoscopic Score 2). Biopsies: active chronic colitis with crypt abscesses, no dysplasia.',
    'Moderate Ulcerative Colitis Flare (Pancolitis, Mayo Score 8/12)',
    ['Ulcerative Colitis', 'Crohns Colitis', 'Infectious Colitis', 'Irritable Bowel Syndrome', 'Diverticulitis'],
    'Induce remission, prevent hospitalisation, avoid corticosteroids (steroid-sparing strategy), maintain long-term remission',
    '1. Re-start and optimise Mesalazine: Mesalazine 4.8g daily PO (maximum dose) + Mesalazine enema 4g/60mL at bedtime for 4 weeks. 2. If inadequate response at 2 weeks: add oral Prednisolone 40mg daily for 1 week, then taper by 5mg weekly. 3. If steroid-dependent or refractory: start Thiopurine (Azathioprine 2-2.5 mg/kg daily or 6-Mercaptopurine 1-1.5 mg/kg daily). 4. If not responding: escalate to biologic therapy (Infliximab 5mg/kg IV at weeks 0, 2, 6 then q8w). 5. Iron supplementation: IV Iron sucrose or oral Ferrous sulphate.',
    'Bowel rest only if severe. Encourage oral nutrition with soft, low-residue diet during acute flare. Avoid NSAIDs (can worsen IBD). Smoking cessation (protective in UC but harmful in Crohns).',
    'Admit if severe (Mayo >10, Hb <9, albumin <3, >10 bloody stools/day) or if outpatient management fails. For this moderate flare: outpatient optimised oral + rectal mesalazine. Review in 2 weeks. If no improvement: start prednisolone taper. Consider thiopurine for steroid-sparing maintenance.',
    '1. Active moderate UC flare requiring escalation of mesalazine therapy. 2. Relapse due to medication non-adherence (cost barrier). 3. Risk of steroid dependence given multiple prior steroid courses.',
    'Stool chart: frequency, consistency, blood. CRP trend. FBC for Hb, platelets. Monitor for steroid side effects if prescribed. If on thiopurine: TPMT genotype before starting, then monthly FBC and LFTs. If on Infliximab: TB screening (Quantiferon, CXR) and HBV serology.',
    'Ulcerative colitis is a chronic condition requiring long-term maintenance therapy — even when you feel well. Stopping medication is the most common cause of flares. Mesalazine maintenance therapy reduces colorectal cancer risk. Report any increase in bloody stools, severe abdominal pain, or fever immediately.',
    'Gastroenterology clinic in 2 weeks to assess response. If in remission, step down to mesalazine 2.4g daily maintenance. Surveillance colonoscopy after 8-10 years of disease for dysplasia/cancer surveillance.',
    'Mayo Score: 0-2 remission, 3-5 mild, 6-10 moderate, 11-12 severe. Pancolitis warrants full maintenance therapy — left-sided disease can use mesalazine enemas alone. Infliximab has transformed UC management — early use in steroid-refractory disease reduces colectomy rates. Mesalazine works locally on the colonic mucosa — never crush/chew tablets (need the pH-dependent coating to reach the colon intact).',
    ['ECCO Guidelines: Ulcerative Colitis', 'ACG Guidelines: Ulcerative Colitis Management', 'WHO: Essential IBD Medicines'],
  ),
];
