// ================================================================
// Hematology — Case Templates (5 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const HEMATOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Hematology', 'Haematology', 'Sickle Cell Disease', 'Vaso-Occlusive Crisis in a Patient with Sickle Cell Disease', 'Intermediate',
    'Severe bone pain in the legs and back for 3 days',
    '{name}, a {age}-year-old {occupation} from {location}, presents with severe, sharp pain in both shins and the lower back of 3 days duration. Pain is 8/10, constant, worse with movement. Reports dark urine. Has had similar crises 3 times in the past year requiring hospitalisation. Precipitated by cold weather. Takes folic acid irregularly. No fever, no cough, no chest pain.',
    'Sickle Cell Disease (HbSS, known since childhood), Recurrent vaso-occlusive crises, Gallstones (known), No history of stroke, No priapism.',
    'Folic Acid 5mg daily (intermittent adherence), Hydroxyurea (not taking — not prescribed), Paracetamol PRN',
    'Mild jaundice. Tender over bilateral tibiae and lumbar spine. No joint swelling. Lungs clear. No hepatosplenomegaly (autosplenectomy typical in adults with HbSS). CV: systolic flow murmur. Temp 37.2°C.',
    'Hb 7.5 g/dL (baseline ~7-8). WBC 14.5 (leukocytosis — crisis). Platelets 450. Reticulocytes 8% (elevated). Bilirubin 2.5 mg/dL (unconjugated). LDH 650 U/L (elevated, haemolysis). Creatinine 0.8. Blood film: sickle cells, target cells, nucleated RBCs. Oxygen saturation 97%.',
    'Chest X-ray: no consolidation, no acute chest findings.',
    'Acute Vaso-Occlusive Crisis (Bone Painful Crisis) in Sickle Cell Disease (HbSS)',
    ['Vaso-Occlusive Crisis', 'Acute Chest Syndrome', 'Osteomyelitis', 'Septic Arthritis', 'Aplastic Crisis'],
    'Relieve pain aggressively, prevent complications (ACS, stroke, infection), maintain hydration and oxygenation, prevent future crises',
    '1. Analgesia: IV Morphine 0.1 mg/kg (5mg) q2-4h PRN (patient-controlled analgesia preferred if available). Oral slow-release Morphine 10-30mg q12h once oral tolerated. Adjunct: Ibuprofen 400mg TID (if no renal impairment). 2. Hydration: IV Normal Saline or Ringer\'s Lactate at maintenance + 50% (1.5x maintenance). 3. Oxygen: only if SpO2 <95% or respiratory symptoms. 4. Folic Acid 5mg daily. 5. Consider Hydroxyurea (HU) for prevention: start at 500mg daily (if >3 crises/year, after counselling and baseline FBC). 6. If severe or prolonged: consider exchange transfusion (target HbS <30%). 7. Antibiotics: only if fever or infection suspected.',
    'Keep warm. Incentive spirometry (10 breaths q2h) to prevent atelectasis/ACS. Adequate nutrition. Psychological support for chronic pain. Avoid trigger factors (cold, dehydration, infection, stress, alcohol).',
    'Admit to medical ward. Aggressive pain control (morphine as above). IV fluids. Warmth. Incentive spirometry. Monitor for acute chest syndrome (fever, cough, chest pain, hypoxia — CXR and start empiric antibiotics if develops). Consider starting Hydroxyurea for secondary prevention.',
    '1. Acute vaso-occlusive crisis requiring hospitalisation for pain control and prevention of complications. 2. High risk of acute chest syndrome (leading cause of death in SCD adults).',
    'Pain score q4h. Oxygen saturation continuously. Temperature q4h. Respiratory rate and chest auscultation daily. Monitor for ACS: new fever, cough, chest pain, hypoxia, infiltrate on CXR. Hb and reticulocytes daily. I/O chart.',
    'Sickle cell pain is real and serious — we will treat it aggressively. Drink plenty of water, keep warm, and avoid infections. Incentive spirometry helps prevent lung complications. Long-term, Hydroxyurea can reduce crisis frequency by 50%. Considered a disease-modifying therapy. Folic acid is essential — take it daily.',
    'Haematology clinic in 2 weeks to discuss starting Hydroxyurea. Annual: TCD (if child), renal function, pulmonary function, retinal exam. Vaccinations: PCV13, PPSV23, meningococcal, annual influenza, hepatitis B.',
    'Vaso-occlusive crisis results from sickled RBCs obstructing microvasculature, causing ischaemia-reperfusion injury and severe pain. Acute chest syndrome is the leading cause of death — defined as new pulmonary infiltrate + fever, chest pain, or respiratory symptoms. Treatment of ACS: antibiotics (ceftriaxone + azithromycin), bronchodilators, incentive spirometry, and exchange transfusion if severe. Hydroxyurea increases HbF and reduces crisis frequency by 50%. In Kenya, newborn screening for SCD is expanding, and hydroxyurea is available through KEMSA.',
    ['NHLBI Guidelines: Sickle Cell Disease', 'Kenya Clinical Guidelines: Sickle Cell Disease'],
  ),
  t('Hematology', 'Haematology', 'Venous Thromboembolism', 'Deep Vein Thrombosis with Pulmonary Embolism in a Post-Surgical Patient', 'Advanced',
    'Sudden onset of shortness of breath and pleuritic chest pain 5 days after hip replacement, with left leg swelling',
    '{name}, a {age}-year-old {occupation} from {location}, is on Day 5 post elective left total hip replacement. Developed acute onset of pleuritic right-sided chest pain, dyspnoea, and palpitations this morning. Also notes her left leg is swollen, warm, and tender compared to the right. No haemoptysis. Received pharmacological VTE prophylaxis (enoxaparin 40mg SC daily) but missed her dose yesterday.',
    'Osteoarthritis left hip (s/p elective THR), Hypertension, Obesity (BMI 33). No prior VTE. Not on OCP/HRT.',
    'Enoxaparin 40mg SC daily (VTE prophylaxis, one dose missed). Amlodipine 5mg daily. Paracetamol for pain.',
    'Tachycardic (HR 115). Tachypnoeic (RR 26). BP 125/80. SpO2 90% on room air. Right lung: decreased breath sounds at base, no wheeze. Left leg: swollen (3cm larger circumference than right), warm, tender calf, positive Homans sign (pain on dorsiflexion), no erythema. Surgical wound clean, dry, intact.',
    'Wells Score for DVT: 3 (likely DVT). Wells Score for PE: 6 (high probability PE). D-dimer: elevated 3.2 mcg/mL (should not be used for diagnosis in surgical patients — too non-specific). ABG: pH 7.45, pCO2 32, pO2 68 on RA, HCO3 24. Troponin: 0.04 ng/mL (high-sensitivity, normal). ECG: sinus tachycardia, no S1Q3T3. CXR: normal.',
    'CT Pulmonary Angiogram: Intraluminal filling defect in right lower lobe segmental pulmonary artery. Left lower limb venous Doppler: Acute DVT in left femoral and popliteal veins (non-occlusive thrombus).',
    'Acute Left Lower Extremity Deep Vein Thrombosis with Ipsilateral Segmental Pulmonary Embolism (Provoked by Surgery)',
    ['PE with DVT', 'Community-Acquired Pneumonia', 'Acute Coronary Syndrome', 'Musculoskeletal Chest Pain', 'Wound Infection'],
    'Treat VTE, prevent thrombus extension and recurrence, reduce VTE-related mortality and morbidity, prevent post-thrombotic syndrome',
    '1. Anticoagulation: Start LMWH (Enoxaparin 1.5mg/kg SC daily or 1mg/kg SC BID) — dose: 100mg daily for a 67kg patient. Bridge to oral anticoagulant. 2. Long-term anticoagulation: Warfarin (target INR 2-3, starting day 1 of LMWH, continue LMWH for >5 days and until INR >2 for 24 hours). OR DOAC: Rivaroxaban 15mg BID for 21 days, then 20mg daily, OR Apixaban 10mg BID for 7 days then 5mg BID. 3. DOAC is preferred over warfarin due to no monitoring requirement and fewer drug interactions. 4. Thrombolysis (systemic or catheter-directed): indicated for massive PE with haemodynamic instability (not indicated here — normotensive). 5. Compression stockings: to prevent post-thrombotic syndrome. 6. Ambulation as tolerated (no evidence that bedrest reduces embolisation).',
    'Ambulation with compression stockings. Leg elevation when sitting. Incentive spirometry. DVT prophylaxis counselling for future surgeries.',
    'Admit to medical ward. Start therapeutic LMWH immediately (before CT results if high suspicion). Start Rivaroxaban 15mg BID. Discharge when stable (afebrile, haemodynamically stable, oxygenating well on room air). Duration: minimum 3-6 months. Assess for provoked vs unprovoked aetiology.',
    '1. Acute proximal DVT with segmental PE requiring full therapeutic anticoagulation. 2. Provoked by surgery and temporary risk factor — determine optimal treatment duration.',
    'Daily: vitals, SpO2, leg circumference. Check for bleeding (any anticoagulant). If on warfarin: INR daily until therapeutic. DOAC: no routine monitoring. After discharge: review in 2 weeks for symptom assessment.',
    'Blood clots after surgery are a recognised complication. Treatment involves blood thinning medications for at least 3-6 months. Rivaroxaban is once-daily after the first 3 weeks. Watch for signs of bleeding: unusual bruising, blood in urine/stool, bleeding gums. Seek immediate help if you develop severe headache (rule out intracranial bleed). Wear compression stockings to reduce leg swelling long-term.',
    'Haematology/GP in 2 weeks. Anticoagulation clinic (if on warfarin). Duration: at least 3 months. If unprovoked or recurrent, consider extended anticoagulation (>12 months). Review bleeding risk (HAS-BLED score) at each visit.',
    'VTE management has 3 phases: acute (first 5-10 days), long-term (3-6 months), and extended (beyond 6 months if high risk of recurrence). DOACs (Rivaroxaban, Apixaban, Edoxaban, Dabigatran) have largely replaced warfarin in Kenya for eligible patients (available through KEMSA and private pharmacies). Warfarin remains the standard for mechanical heart valves and antiphospholipid syndrome. LMWH is preferred for acute phase in cancer-associated thrombosis. Compression stockings reduce post-thrombotic syndrome by 50%.',
    ['CHEST Guidelines: VTE Management', 'ESC Guidelines: PE Management', 'Kenya Clinical Guidelines: Thromboembolism'],
  ),
];
