// ================================================================
// Hematology — Case Templates (5 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const HEMATOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Hematology', 'Haematology', 'Sickle Cell Disease', 'Vaso-Occlusive Crisis in a Patient with Sickle Cell Disease', 'Intermediate',
    'Severe bone pain in the legs and back for 3 days',
    '{name}, a {age}-year-old {occupation} from {location}, presents with severe, sharp pain in both shins and the lower back of 3 days duration. Pain is 8/10, constant, worse with movement. Reports dark urine. Has had similar crises 3 times in the past year requiring hospitalisation. Precipitated by cold weather. Takes folic acid irregularly. No fever, no cough, no chest pain.',
    'Sickle Cell Disease (HbSS, known since childhood), Recurrent vaso-occlusive crises, Gallstones (known), No history of stroke, No priapism.',
    'Folic Acid 5mg daily (intermittent adherence), Hydroxyurea (not taking — not prescribed), Paracetamol PRN',
    'Mild jaundice. Tender over bilateral tibiae and lumbar spine. No joint swelling. Lungs clear. No hepatosplenomegaly (autosplenectomy typical in adults with HbSS). CV: systolic flow murmur. Temp 37.2°C.',
    'Hb 7.5 g/dL (baseline ~7-8). WBC 14.5 (leukocytosis — crisis). Platelets 450. Reticulocytes 8% (elevated). Bilirubin 2.5 mg/dL (unconjugated). LDH 650 U/L (elevated, haemolysis). Creatinine 0.8. Blood film: sickle cells, target cells, nucleated RBCs. Oxygen saturation 97%.',
    'Chest X-ray: no consolidation, no acute chest findings.',
    'Acute Vaso-Occlusive Crisis (Bone Painful Crisis) in Sickle Cell Disease (HbSS)',
    ['Vaso-Occlusive Crisis', 'Acute Chest Syndrome', 'Osteomyelitis', 'Septic Arthritis', 'Aplastic Crisis'],
    'Relieve pain aggressively, prevent complications (ACS, stroke, infection), maintain hydration and oxygenation, prevent future crises',
    '1. Analgesia: IV Morphine 0.1 mg/kg (5mg) q2-4h PRN (patient-controlled analgesia preferred if available). Oral slow-release Morphine 10-30mg q12h once oral tolerated. Adjunct: Ibuprofen 400mg TID (if no renal impairment). 2. Hydration: IV Normal Saline or Ringer\'s Lactate at maintenance + 50% (1.5x maintenance). 3. Oxygen: only if SpO2 <95% or respiratory symptoms. 4. Folic Acid 5mg daily. 5. Consider Hydroxyurea (HU) for prevention: start at 500mg daily (if >3 crises/year, after counselling and baseline FBC). 6. If severe or prolonged: consider exchange transfusion (target HbS <30%). 7. Antibiotics: only if fever or infection suspected.',
    'Keep warm. Incentive spirometry (10 breaths q2h) to prevent atelectasis/ACS. Adequate nutrition. Psychological support for chronic pain. Avoid trigger factors (cold, dehydration, infection, stress, alcohol).',
    'Admit to medical ward. Aggressive pain control (morphine as above). IV fluids. Warmth. Incentive spirometry. Monitor for acute chest syndrome (fever, cough, chest pain, hypoxia — CXR and start empiric antibiotics if develops). Consider starting Hydroxyurea for secondary prevention.',
    '1. Acute vaso-occlusive crisis requiring hospitalisation for pain control and prevention of complications. 2. High risk of acute chest syndrome (leading cause of death in SCD adults).',
    'Pain score q4h. Oxygen saturation continuously. Temperature q4h. Respiratory rate and chest auscultation daily. Monitor for ACS: new fever, cough, chest pain, hypoxia, infiltrate on CXR. Hb and reticulocytes daily. I/O chart.',
    'Sickle cell pain is real and serious — we will treat it aggressively. Drink plenty of water, keep warm, and avoid infections. Incentive spirometry helps prevent lung complications. Long-term, Hydroxyurea can reduce crisis frequency by 50%. Considered a disease-modifying therapy. Folic acid is essential — take it daily.',
    'Haematology clinic in 2 weeks to discuss starting Hydroxyurea. Annual: TCD (if child), renal function, pulmonary function, retinal exam. Vaccinations: PCV13, PPSV23, meningococcal, annual influenza, hepatitis B.',
    'Vaso-occlusive crisis results from sickled RBCs obstructing microvasculature, causing ischaemia-reperfusion injury and severe pain. Acute chest syndrome is the leading cause of death — defined as new pulmonary infiltrate + fever, chest pain, or respiratory symptoms. Treatment of ACS: antibiotics (ceftriaxone + azithromycin), bronchodilators, incentive spirometry, and exchange transfusion if severe. Hydroxyurea increases HbF and reduces crisis frequency by 50%. In Kenya, newborn screening for SCD is expanding, and hydroxyurea is available through KEMSA.',
    ['NHLBI Guidelines: Sickle Cell Disease', 'Kenya Clinical Guidelines: Sickle Cell Disease'],
  ),
  t('Hematology', 'Haematology', 'Venous Thromboembolism', 'Deep Vein Thrombosis with Pulmonary Embolism in a Post-Surgical Patient', 'Advanced',
    'Sudden onset of shortness of breath and pleuritic chest pain 5 days after hip replacement, with left leg swelling',
    '{name}, a {age}-year-old {occupation} from {location}, is on Day 5 post elective left total hip replacement. Developed acute onset of pleuritic right-sided chest pain, dyspnoea, and palpitations this morning. Also notes her left leg is swollen, warm, and tender compared to the right. No haemoptysis. Received pharmacological VTE prophylaxis (enoxaparin 40mg SC daily) but missed her dose yesterday.',
    'Osteoarthritis left hip (s/p elective THR), Hypertension, Obesity (BMI 33). No prior VTE. Not on OCP/HRT.',
    'Enoxaparin 40mg SC daily (VTE prophylaxis, one dose missed). Amlodipine 5mg daily. Paracetamol for pain.',
    'Tachycardic (HR 115). Tachypnoeic (RR 26). BP 125/80. SpO2 90% on room air. Right lung: decreased breath sounds at base, no wheeze. Left leg: swollen (3cm larger circumference than right), warm, tender calf, positive Homans sign (pain on dorsiflexion), no erythema. Surgical wound clean, dry, intact.',
    'Wells Score for DVT: 3 (likely DVT). Wells Score for PE: 6 (high probability PE). D-dimer: elevated 3.2 mcg/mL (should not be used for diagnosis in surgical patients — too non-specific). ABG: pH 7.45, pCO2 32, pO2 68 on RA, HCO3 24. Troponin: 0.04 ng/mL (high-sensitivity, normal). ECG: sinus tachycardia, no S1Q3T3. CXR: normal.',
    'CT Pulmonary Angiogram: Intraluminal filling defect in right lower lobe segmental pulmonary artery. Left lower limb venous Doppler: Acute DVT in left femoral and popliteal veins (non-occlusive thrombus).',
    'Acute Left Lower Extremity Deep Vein Thrombosis with Ipsilateral Segmental Pulmonary Embolism (Provoked by Surgery)',
    ['PE with DVT', 'Community-Acquired Pneumonia', 'Acute Coronary Syndrome', 'Musculoskeletal Chest Pain', 'Wound Infection'],
    'Treat VTE, prevent thrombus extension and recurrence, reduce VTE-related mortality and morbidity, prevent post-thrombotic syndrome',
    '1. Anticoagulation: Start LMWH (Enoxaparin 1.5mg/kg SC daily or 1mg/kg SC BID) — dose: 100mg daily for a 67kg patient. Bridge to oral anticoagulant. 2. Long-term anticoagulation: Warfarin (target INR 2-3, starting day 1 of LMWH, continue LMWH for >5 days and until INR >2 for 24 hours). OR DOAC: Rivaroxaban 15mg BID for 21 days, then 20mg daily, OR Apixaban 10mg BID for 7 days then 5mg BID. 3. DOAC is preferred over warfarin due to no monitoring requirement and fewer drug interactions. 4. Thrombolysis (systemic or catheter-directed): indicated for massive PE with haemodynamic instability (not indicated here — normotensive). 5. Compression stockings: to prevent post-thrombotic syndrome. 6. Ambulation as tolerated (no evidence that bedrest reduces embolisation).',
    'Ambulation with compression stockings. Leg elevation when sitting. Incentive spirometry. DVT prophylaxis counselling for future surgeries.',
    'Admit to medical ward. Start therapeutic LMWH immediately (before CT results if high suspicion). Start Rivaroxaban 15mg BID. Discharge when stable (afebrile, haemodynamically stable, oxygenating well on room air). Duration: minimum 3-6 months. Assess for provoked vs unprovoked aetiology.',
    '1. Acute proximal DVT with segmental PE requiring full therapeutic anticoagulation. 2. Provoked by surgery and temporary risk factor — determine optimal treatment duration.',
    'Daily: vitals, SpO2, leg circumference. Check for bleeding (any anticoagulant). If on warfarin: INR daily until therapeutic. DOAC: no routine monitoring. After discharge: review in 2 weeks for symptom assessment.',
    'Blood clots after surgery are a recognised complication. Treatment involves blood thinning medications for at least 3-6 months. Rivaroxaban is once-daily after the first 3 weeks. Watch for signs of bleeding: unusual bruising, blood in urine/stool, bleeding gums. Seek immediate help if you develop severe headache (rule out intracranial bleed). Wear compression stockings to reduce leg swelling long-term.',
    'Haematology/GP in 2 weeks. Anticoagulation clinic (if on warfarin). Duration: at least 3 months. If unprovoked or recurrent, consider extended anticoagulation (>12 months). Review bleeding risk (HAS-BLED score) at each visit.',
    'VTE management has 3 phases: acute (first 5-10 days), long-term (3-6 months), and extended (beyond 6 months if high risk of recurrence). DOACs (Rivaroxaban, Apixaban, Edoxaban, Dabigatran) have largely replaced warfarin in Kenya for eligible patients (available through KEMSA and private pharmacies). Warfarin remains the standard for mechanical heart valves and antiphospholipid syndrome. LMWH is preferred for acute phase in cancer-associated thrombosis. Compression stockings reduce post-thrombotic syndrome by 50%.',
    ['CHEST Guidelines: VTE Management', 'ESC Guidelines: PE Management', 'Kenya Clinical Guidelines: Thromboembolism'],
  ),
  t('Hematology', 'Haematology', 'Iron Deficiency Anaemia', 'Iron Deficiency Anaemia Due to Menorrhagia in a Young Woman', 'Beginner',
    'Fatigue, pallor, and heavy menstrual bleeding for several months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with 6 months of progressive fatigue, breathlessness on exertion, dizziness, and pallor. Reports heavy menstrual bleeding — soaking through a pad every 1-2 hours for 5-7 days, with clots. Also reports unusual cravings for ice and soil (pica). No melaena, no haematuria, no cough. Diet is low in red meat — mostly ugali and vegetables. Not pregnant (last menstrual period 2 weeks ago). Has been taking over-the-counter iron tablets irregularly.',
    'No significant PMH. No history of bleeding disorders. No GI symptoms (no dyspepsia, no change in bowel habits). No family history of anaemia.',
    'Ferrous sulfate 200mg (irregular adherence, takes maybe 2-3 times per week). No other regular medications.',
    'Pale conjunctivae, pale nail beds. Tongue: smooth, atrophic papillae. Heart: tachycardic (HR 102), systolic flow murmur (grade 2/6 at left sternal edge). Lungs: clear. Abdomen: soft, no masses. Pelvic: bulky uterus on bimanual exam (suggests fibroids). BMI 20.',
    'Hb 7.2 g/dL (severe anaemia). MCV 68 fL (microcytic). MCH 22 pg (hypochromic). RDW 18% (elevated — anisocytosis). Ferritin 8 ng/mL (severely depleted iron stores — diagnostic). Serum iron 8 µmol/L (low). TIBC 85 µmol/L (elevated — iron-deficient erythropoiesis). Transferrin saturation 9% (low). Reticulocytes 1% (inappropriately low for anaemia — hypoproliferative). Peripheral blood film: microcytic hypochromic red cells, pencil cells, target cells, thrombocytosis (platelets 480 — reactive). Coagulation: PT, APTT normal.',
    'No imaging indicated acutely. If GI blood loss suspected: consider faecal occult blood test and coeliac screen (anti-tTG IgA). Pelvic ultrasound if menorrhagia workup needed (fibroids, endometrial pathology).',
    'Severe Iron Deficiency Anaemia (Hb 7.2, Ferritin 8) Due to Chronic Blood Loss (Menorrhagia)',
    ['Anaemia of chronic disease', 'Thalassaemia trait', 'Sideroblastic anaemia', 'Coeliac disease-associated iron deficiency'],
    'Correct iron deficiency, investigate and manage the underlying cause (menorrhagia), achieve normal haemoglobin and ferritin, prevent recurrence',
    '1. Oral iron replacement: Ferrous sulfate 200mg (elemental iron 65mg) TID on an empty stomach (1 hour before meals or 2 hours after). 2. If oral iron not tolerated (constipation, nausea — common in Kenya): switch to Ferrous gluconate 300mg TID (better tolerated) or Ferrous fumarate 210mg BID. 3. Take with Vitamin C (e.g., orange juice) to enhance absorption. 4. Avoid tea, coffee, dairy, and antacids within 2 hours of iron (inhibit absorption). 5. If Hb not rising by 1-2 g/dL in 3-4 weeks: check adherence, consider IV iron (Iron sucrose or Ferric carboxymaltose) if oral not tolerated or ineffective. 6. Blood transfusion: consider if symptomatic with Hb <7 or haemodynamically unstable (this patient: Hb 7.2, tachycardic — transfusion may be considered if symptomatic, but oral iron trial is reasonable if stable). 7. Investigate menorrhagia: pelvic ultrasound (fibroids?), gynaecology referral. 8. Coeliac screening: anti-tTG IgA (coeliac disease is a common cause of iron deficiency in young women — often missed). 9. Treat underlying cause alongside iron replacement.',
    'Dietary counselling: increase iron-rich foods — red meat (nyama choma, beef stew), liver, beans (njahi, green grams), dark leafy greens (sukuma wiki, spinach), fortified cereals. Pair with vitamin C sources (oranges, tomatoes, mangoes). Avoid tea with meals. Manage menorrhagia: hormonal options (combined OCP, progestogens), tranexamic acid, or surgical options depending on cause.',
    'Start Ferrous sulfate 200mg TID with orange juice. Repeat Hb and reticulocytes at 2 weeks (expect reticulocyte rise — "reticulocyte crisis" at 7-10 days), then Hb at 4 weeks. Continue iron for 3-6 months after Hb normalises to replenish stores. Pelvic ultrasound for menorrhagia workup. Coeliac screen. If ferritin <15 or no response: IV iron. Gynaecology referral if fibroids identified.',
    '1. Severe iron deficiency anaemia (Hb 7.2, Ferritin 8) requiring aggressive oral iron replacement and investigation of cause. 2. Menorrhagia is the most common cause of iron deficiency in premenopausal women — always investigate. 3. Coeliac disease must be considered in any young woman with unexplained iron deficiency.',
    'Hb rise of 1-2 g/dL expected in 3-4 weeks with adherence. Reticulocyte count should rise at 7-10 days (confirms response). Iron must continue for 3-6 months after Hb normalises to replenish ferritin stores (ferritin >50 ng/mL is target). Monitor for iron overload if on long-term therapy (rare with oral iron in premenopausal women with ongoing losses). If ferritin >100 and Hb normal, stop iron and recheck in 3 months.',
    'Take your iron tablets every day — this is very important. Take them on an empty stomach with orange juice for best absorption. If they cause stomach upset, take them with a small amount of food (reduces absorption slightly but better than not taking them). Avoid tea and coffee within 1-2 hours of taking iron. Your stool may turn dark or black — this is normal and harmless. It takes 3-6 months to fully replenish your iron stores even after your blood tests improve — do not stop early.',
    'Haematology or GP in 4 weeks for repeat bloods. If Hb rising well, continue and review at 3 months. Gynaecology referral for menorrhagia (fibroid evaluation). Coeliac screen result review. If no response to oral iron at 4-6 weeks: investigate further (repeat ferritin, consider malabsorption, GI blood loss).',
    'Iron deficiency is the most common nutritional deficiency worldwide and the most common cause of anaemia in premenopausal women. The WHO estimates 30% of women of reproductive age in Kenya are iron deficient. Ferritin <15 ng/mL is diagnostic of iron depletion (specificity 99%). Oral iron absorption is maximised by taking on an empty stomach with vitamin C. The "reticulocyte crisis" at 7-10 days confirms the bone marrow is responding. Tea polyphenols and tannins inhibit non-haem iron absorption by up to 60%. IV iron (ferric carboxymaltose) is now recommended for patients who fail or cannot tolerate oral iron — it can replete stores in a single infusion.',
    ['WHO: Anaemia Prevention and Control', 'Kenya Clinical Guidelines: Haematology', 'BSH Guidelines: Iron Deficiency', 'ACOG: Iron Deficiency Anaemia in Women'],
  ),
  t('Hematology', 'Haematology', 'Anticoagulation Management', 'Warfarin Management with Supratherapeutic INR in a Patient with Mechanical Heart Valve', 'Intermediate',
    'Routine INR check reveals dangerously high level — patient on warfarin for mechanical mitral valve',
    '{name}, a {age}-year-old {occupation} from {location}, attends the anticoagulation clinic for routine INR monitoring. Has a mechanical mitral valve replacement (St. Jude Medical, size 29mm) done 3 years ago at the Nairobi Heart Institute. Target INR: 2.5-3.5. Today\'s INR: 5.8 (critically elevated). Patient reports no bleeding symptoms — no haematuria, melaena, haemoptysis, bruising, or gum bleeding. Reports feeling well. On questioning, reveals she started a course of Amoxicillin 500mg TID 5 days ago for a dental abscess (prescribed by local dentist). Also admits to drinking 2-3 cups of green tea daily (previously drank none). Has been taking paracetamol 1g QID for dental pain.',
    'Mechanical Mitral Valve (St. Jude, 2023), Hypertension, Hyperlipidaemia. No prior bleeding events.',
    'Warfarin 5mg daily (self-managed — takes based on previous INR results). Amlodipine 5mg daily. Atorvastatin 20mg daily. Paracetamol 1g QID (PRN — dental pain, started 5 days ago). Amoxicillin 500mg TID (started 5 days ago by dentist).',
    'Well-appearing, not in distress. No signs of active bleeding. No petechiae, no ecchymoses. Gums: no bleeding around dental abscess site. Heart: mechanical valve sounds (click), regular rhythm, no murmurs. Lungs clear. Abdomen: soft, non-tender, no hepatosplenomegaly. Neurological: no focal deficits. BP 132/78, HR 72, afebrile.',
    'INR 5.8 (critically supratherapeutic — target 2.5-3.5). PT 58 seconds (markedly prolonged). APTT: prolonged. FBC: Hb 12.8 (stable — no active bleeding). Platelets 250. Cr 0.8. LFTs normal. Anti-Xa level not routinely available.',
    'Echocardiogram (baseline, 6 months ago): mechanical mitral valve functioning normally, no thrombus, no paravalvular leak. ECG: atrial fibrillation, rate 72, no ST changes. Chest X-ray: normal.',
    'Supratherapeutic INR (5.8) in a Patient on Warfarin for Mechanical Mitral Valve — Drug Interaction (Amoxicillin) Identified',
    ['Warfarin overdose', 'Drug-drug interaction (antibiotic + warfarin)', 'Mechanical valve thrombosis risk', 'Active haemorrhage', 'Intracranial haemorrhage'],
    'Reduce INR to therapeutic range safely, prevent bleeding complications, maintain adequate anticoagulation for mechanical valve, prevent valve thrombosis, educate on drug interactions and dietary factors',
    '1. HOLD Warfarin immediately — do not take tonight\'s dose. 2. Vitamin K decision: INR 5.8 WITHOUT bleeding — observation alone is acceptable if INR expected to correct within 24-48 hours. However, given mechanical mitral valve (highest thrombotic risk valve position), consider LOW-DOSE oral Vitamin K (1-2.5mg PO) to accelerate correction while maintaining some anticoagulation. Avoid high-dose Vitamin K (over-correction risks thrombosis). 3. Re-check INR in 12-24 hours. 4. If INR drops to <5.0 by next day: resume Warfarin at REDUCED dose (e.g., 3.5-4mg daily instead of 5mg). 5. Address drug interaction: Amoxicillin inhibits gut flora that produce vitamin K, increases warfarin effect. Options: switch to non-interacting antibiotic (Azithromycin 500mg OD for dental abscess) OR reduce warfarin dose during antibiotic course. 6. Address green tea: Vitamin K in green tea — patient now DRINKING it (was not before), which would normally DECREASE INR. But she started it recently and it has not yet reached steady state. The antibiotic effect is currently dominant. 7. Paracetamol: high-dose paracetamol (>2g/day for >3 days) can increase INR — reduce to 500mg QID or 1g TID (max 3g/day). 8. Once INR stabilised: resume Warfarin at adjusted dose, re-check INR weekly until stable, then return to routine monitoring.',
    'Counselling completed on drug interactions: antibiotics (especially amoxicillin, metronidazole, ciprofloxacin, co-trimoxazole), herbal products (green tea, cranberry juice, St. John\'s Wort), dietary vitamin K consistency, and paracetamol dose. Provided written drug interaction card. Discussed when to seek emergency care (signs of bleeding). INR monitoring schedule reinforced.',
    '1. INR 5.8 (critically elevated) — 2.3x upper limit of target range. 2. Drug-drug interaction identified as precipitant (amoxicillin + warfarin). 3. Mechanical mitral valve carries highest thrombotic risk — must maintain adequate anticoagulation.',
    'Re-check INR in 12-24 hours (today at 4pm, tomorrow morning). If INR <5: resume warfarin at reduced dose and re-check in 3 days. If INR still >5: repeat low-dose Vitamin K and re-check. Weekly INR until stable (2 consecutive INRs in range). Then return to monthly monitoring. Document interaction in patient records. Flag amoxicillin as interacting antibiotic.',
    'Your blood thinner level is too high — this increases your bleeding risk. We are holding your warfarin for tonight and will recheck your blood tomorrow. The cause is the antibiotic (amoxicillin) your dentist prescribed — it interacts with warfarin and makes it stronger. Always tell any doctor, dentist, or pharmacist that you take warfarin before they prescribe ANY medication. Some antibiotics, painkillers, and herbal products can dangerously affect your warfarin level. Keep your vitamin K intake consistent — do not suddenly start or stop eating green leafy vegetables or drinking green tea. Seek emergency care immediately if you notice: blood in urine or stool, severe headache, vomiting blood, or unusual bruising.',
    'INR tomorrow morning. Anticoagulation clinic weekly until stable (2 consecutive INRs in range). Gastroenterology referral if bleeding develops. Cardiology review to confirm target INR range. Dental follow-up for abscess management. Consider INR self-management education (patient already self-managing).',
    'Warfarin has a narrow therapeutic index and is subject to numerous drug interactions. Amoxicillin increases INR by inhibiting vitamin K-producing gut bacteria — this interaction is well-documented and can raise INR by 0.5-2.0 units. Mechanical mitral valves require the highest INR target (2.5-3.5) and carry the greatest thrombotic risk if under-anticoagulated. Low-dose Vitamin K (1-2.5mg) is preferred for supratherapeutic INR without bleeding — it reduces INR without fully reversing anticoagulation. High-dose Vitamin K (>5mg) risks over-correction and thrombosis in mechanical valve patients. In Kenya, anticoagulation clinic services are limited — patient self-management with point-of-care INR devices is an emerging model.',
    'Warfarin is considered one of the most dangerous medications when not properly monitored due to its narrow therapeutic index. Always maintain consistent vitamin K intake. Drug interactions with warfarin are numerous — always check before adding any new medication. Amoxicillin is a commonly overlooked interacting drug.',
    ['ACCP Guidelines: Warfarin Management', 'ESC Guidelines: Mechanical Heart Valve Anticoagulation', 'Kenya Clinical Guidelines: Anticoagulation', 'WHO: Patient Safety — Medication Interactions'],
  ),
];
