/**
 * Master Drug List — Clinova target: 1,000–1,200 unique generic medicines.
 * Sources: Kenya Drug Index (KDI), Kenya Essential Medicines List (KEML),
 * WHO Essential Medicines List, BNF, major international formularies.
 * This is the user-supplied master list + alphabetical extension.
 * The merge script (scripts/merge-master-list.ts) unions this with
 * scripts/drug-registry-canonical.json (deduped, case-insensitive).
 */
export const MASTER_DRUG_LIST: string[] = [
  // ── A ───────────────────────────────────────────────────────────
  'Abacavir',
  'Abacavir/Lamivudine',
  'Abacavir/Lamivudine/Zidovudine',
  'Abaloparatide',
  'Abatacept',
  'Abemaciclib',
  'Acalabrutinib',
  'Acarbose',
  'Acebutolol',
  'Aceclofenac',
  'Acemetacin',
  'Acenocoumarol',
  'Acetazolamide',
  'Acetylcysteine',
  'Aciclovir',
  'Acitretin',
  'Adalimumab',
  'Adenosine',
  'Adrenaline',
  'Afatinib',
  'Albendazole',
  'Albumin Human',
  'Albuterol',
  'Alclometasone',
  'Alendronic Acid',
  'Alfuzosin',
  'Aliskiren',
  'Allopurinol',
  'Almotriptan',
  'Alogliptin',
  'Alprazolam',
  'Alteplase',
  'Aluminium Hydroxide',
  'Amantadine',
  'Amikacin',
  'Amiloride',
  'Aminophylline',
  'Amiodarone',
  'Amitriptyline',
  'Amlodipine',
  'Amoxicillin',
  'Amoxicillin/Clavulanic Acid',
  'Amphotericin B',
  'Ampicillin',
  'Ampicillin/Sulbactam',
  'Amprenavir',
  'Anastrozole',
  'Anidulafungin',
  'Apalutamide',
  'Apixaban',
  'Apomorphine',
  'Aripiprazole',
  'Artemether',
  'Artemether/Lumefantrine',
  'Artesunate',
  'Ascorbic Acid',
  'Aspirin',
  'Atenolol',
  'Atorvastatin',
  'Atovaquone',
  'Atropine',
  'Azathioprine',
  'Azelaic Acid',
  'Azilsartan',
  'Azithromycin',
  'Aztreonam',

  // ── B ───────────────────────────────────────────────────────────
  'Baclofen',
  'Bedaquiline',
  'Beclometasone',
  'Bendamustine',
  'Benralizumab',
  'Benzathine Benzylpenicillin',
  'Benzhexol',
  'Benzocaine',
  'Benzoyl Peroxide',
  'Benzylpenicillin',
  'Betahistine',
  'Betamethasone',
  'Bexarotene',
  'Bicalutamide',
  'Bictegravir',
  'Bimatoprost',
  'Bisacodyl',
  'Bisoprolol',
  'Bivalirudin',
  'Bleomycin',
  'Bortezomib',
  'Bosentan',
  'Brimonidine',
  'Brinzolamide',
  'Bromhexine',
  'Bromocriptine',
  'Budesonide',
  'Bumetanide',
  'Buprenorphine',
  'Bupivacaine',
  'Bupropion',
  'Buspirone',
  'Busulfan',

  // ── C ───────────────────────────────────────────────────────────
  'Cabazitaxel',
  'Cabergoline',
  'Caffeine',
  'Calamine',
  'Calcitriol',
  'Calcium Carbonate',
  'Calcium Gluconate',
  'Canagliflozin',
  'Candesartan',
  'Capecitabine',
  'Capreomycin',
  'Captopril',
  'Carbamazepine',
  'Carbimazole',
  'Carboplatin',
  'Carvedilol',
  'Caspofungin',
  'Cefaclor',
  'Cefadroxil',
  'Cefalexin',
  'Cefazolin',
  'Cefepime',
  'Cefixime',
  'Cefoperazone',
  'Cefotaxime',
  'Cefoxitin',
  'Ceftazidime',
  'Ceftibuten',
  'Ceftizoxime',
  'Ceftriaxone',
  'Cefuroxime',
  'Celecoxib',
  'Cephalexin',
  'Ceritinib',
  'Cetirizine',
  'Chlorambucil',
  'Chloramphenicol',
  'Chlordiazepoxide',
  'Chlorhexidine',
  'Chloroquine',
  'Chlorpheniramine',
  'Chlorpromazine',
  'Cholecalciferol',
  'Cholestyramine',
  'Cilostazol',
  'Cinacalcet',
  'Ciprofloxacin',
  'Cisplatin',
  'Citalopram',
  'Clarithromycin',
  'Clindamycin',
  'Clobazam',
  'Clobetasol',
  'Clomifene',
  'Clomipramine',
  'Clonazepam',
  'Clonidine',
  'Clopidogrel',
  'Clotrimazole',
  'Clozapine',
  'Cloxacillin',
  'Colchicine',
  'Colistin',
  'Cyanocobalamin',
  'Cyclobenzaprine',
  'Cyclophosphamide',
  'Cycloserine',
  'Cyclosporine',

  // ── D ───────────────────────────────────────────────────────────
  'Dabigatran',
  'Dacarbazine',
  'Dapagliflozin',
  'Daptomycin',
  'Daratumumab',
  'Darunavir',
  'Dasatinib',
  'Daunorubicin',
  'Deferasirox',
  'Deferoxamine',
  'Deflazacort',
  'Delamanid',
  'Denosumab',
  'Desloratadine',
  'Desmopressin',
  'Dexamethasone',
  'Dexketoprofen',
  'Dexlansoprazole',
  'Diazepam',
  'Diclofenac',
  'Dicloxacillin',
  'Didanosine',
  'Digoxin',
  'Diltiazem',
  'Dimenhydrinate',
  'Diphenhydramine',
  'Dipyridamole',
  'Disulfiram',
  'Dobutamine',
  'Docetaxel',
  'Dolutegravir',
  'Domperidone',
  'Donepezil',
  'Dopamine',
  'Doxazosin',
  'Doxepin',
  'Doxorubicin',
  'Doxycycline',
  'Droperidol',
  'Dulaglutide',
  'Duloxetine',

  // ── E ───────────────────────────────────────────────────────────
  'Edoxaban',
  'Efavirenz',
  'Empagliflozin',
  'Enalapril',
  'Enoxaparin',
  'Entecavir',
  'Ephedrine',
  'Epinephrine',
  'Eplerenone',
  'Epoetin Alfa',
  'Erlotinib',
  'Ertapenem',
  'Erythromycin',
  'Escitalopram',
  'Esmolol',
  'Esomeprazole',
  'Estradiol',
  'Ethambutol',
  'Ethinylestradiol',
  'Ethionamide',
  'Etodolac',
  'Etoposide',
  'Etoricoxib',
  'Everolimus',
  'Exemestane',
  'Exenatide',

  // ── F ───────────────────────────────────────────────────────────
  'Famciclovir',
  'Famotidine',
  'Febuxostat',
  'Felodipine',
  'Fenofibrate',
  'Fentanyl',
  'Ferrous Fumarate',
  'Ferrous Sulfate',
  'Fexofenadine',
  'Filgrastim',
  'Finasteride',
  'Flecainide',
  'Flucloxacillin',
  'Fluconazole',
  'Flucytosine',
  'Fludrocortisone',
  'Flumazenil',
  'Fluorouracil',
  'Fluoxetine',
  'Fluphenazine',
  'Flutamide',
  'Fluticasone',
  'Folic Acid',
  'Fondaparinux',
  'Fosfomycin',
  'Fosinopril',
  'Furosemide',

  // ── G ───────────────────────────────────────────────────────────
  'Gabapentin',
  'Ganciclovir',
  'Gatifloxacin',
  'Gefitinib',
  'Gemcitabine',
  'Gemifloxacin',
  'Gentamicin',
  'Glibenclamide',
  'Gliclazide',
  'Glimepiride',
  'Glipizide',
  'Gliquidone',
  'Glucagon',
  'Glyceryl Trinitrate',
  'Glycopyrrolate',
  'Goserelin',
  'Granisetron',
  'Griseofulvin',
  'Guanfacine',

  // ── H ───────────────────────────────────────────────────────────
  'Haloperidol',
  'Heparin',
  'Hydralazine',
  'Hydrochlorothiazide',
  'Hydrocortisone',
  'Hydroxychloroquine',
  'Hydroxyurea',
  'Hydroxyzine',
  'Hyoscine Butylbromide',

  // ── I ───────────────────────────────────────────────────────────
  'Ibuprofen',
  'Idarubicin',
  'Imatinib',
  'Imipenem/Cilastatin',
  'Imiquimod',
  'Indapamide',
  'Indomethacin',
  'Insulin Aspart',
  'Insulin Degludec',
  'Insulin Detemir',
  'Insulin Glargine',
  'Insulin Lispro',
  'Insulin NPH',
  'Insulin Premix',
  'Insulin Regular',
  'Ipratropium',
  'Irbesartan',
  'Irinotecan',
  'Iron Dextran',
  'Iron Sucrose',
  'Isavuconazole',
  'Isoniazid',
  'Isosorbide Dinitrate',
  'Isosorbide Mononitrate',
  'Isotretinoin',
  'Isradipine',
  'Itraconazole',
  'Ivabradine',
  'Ivermectin',

  // ── K ───────────────────────────────────────────────────────────
  'Kanamycin',
  'Ketamine',
  'Ketoconazole',
  'Ketoprofen',
  'Ketorolac',
  'Ketotifen',

  // ── L ───────────────────────────────────────────────────────────
  'Labetalol',
  'Lactulose',
  'Lamivudine',
  'Lamotrigine',
  'Lansoprazole',
  'Latanoprost',
  'Leflunomide',
  'Lenvatinib',
  'Letrozole',
  'Leuprolide',
  'Levetiracetam',
  'Levocetirizine',
  'Levodopa',
  'Levofloxacin',
  'Levonorgestrel',
  'Levothyroxine',
  'Lidocaine',
  'Linezolid',
  'Liraglutide',
  'Lisinopril',
  'Lithium Carbonate',
  'Lomefloxacin',
  'Loperamide',
  'Lopinavir',
  'Loratadine',
  'Lorazepam',
  'Losartan',
  'Lurasidone',
  'Lymecycline',

  // ── M ───────────────────────────────────────────────────────────
  'Magnesium Sulfate',
  'Mannitol',
  'Maraviroc',
  'Mebendazole',
  'Meclizine',
  'Medroxyprogesterone',
  'Mefenamic Acid',
  'Megestrol',
  'Melatonin',
  'Meloxicam',
  'Memantine',
  'Mercaptopurine',
  'Meropenem',
  'Mesalazine',
  'Mesna',
  'Metformin',
  'Methadone',
  'Methotrexate',
  'Methyldopa',
  'Methylphenidate',
  'Methylprednisolone',
  'Metoclopramide',
  'Metolazone',
  'Metoprolol',
  'Metronidazole',
  'Micafungin',
  'Miconazole',
  'Midazolam',
  'Milrinone',
  'Minocycline',
  'Minoxidil',
  'Mirtazapine',
  'Misoprostol',
  'Mitomycin',
  'Mitotane',
  'Mometasone',
  'Montelukast',
  'Morphine',
  'Moxifloxacin',
  'Mupirocin',
  'Mycophenolate Mofetil',

  // ── N ───────────────────────────────────────────────────────────
  'Nabumetone',
  'Nadolol',
  'Nafcillin',
  'Nalbuphine',
  'Naloxone',
  'Naltrexone',
  'Naphazoline',
  'Naproxen',
  'Nateglinide',
  'Nebivolol',
  'Neomycin',
  'Neostigmine',
  'Nevirapine',
  'Nicardipine',
  'Nicotine',
  'Nifedipine',
  'Nilotinib',
  'Nimesulide',
  'Nitrazepam',
  'Nitrofurantoin',
  'Nitroglycerin',
  'Noradrenaline',
  'Norethisterone',
  'Norfloxacin',
  'Nystatin',

  // ── O ───────────────────────────────────────────────────────────
  'Octreotide',
  'Ofloxacin',
  'Olanzapine',
  'Olmesartan',
  'Olopatadine',
  'Olsalazine',
  'Omeprazole',
  'Ondansetron',
  'Orlistat',
  'Orphenadrine',
  'Oseltamivir',
  'Oxacillin',
  'Oxaliplatin',
  'Oxazepam',
  'Oxcarbazepine',
  'Oxymetazoline',
  'Oxytetracycline',
  'Oxybutynin',
  'Oxycodone',
  'Oxytocin',

  // ── P ───────────────────────────────────────────────────────────
  'Paclitaxel',
  'Pamidronate',
  'Pantoprazole',
  'Paracetamol',
  'Paroxetine',
  'Pazopanib',
  'Pemetrexed',
  'Penciclovir',
  'Penicillamine',
  'Penicillin V',
  'Pentamidine',
  'Pentoxifylline',
  'Perampanel',
  'Perindopril',
  'Permethrin',
  'Perphenazine',
  'Phenelzine',
  'Phenobarbital',
  'Phenoxybenzamine',
  'Phenylephrine',
  'Phenytoin',
  'Phytomenadione',
  'Pilocarpine',
  'Pimecrolimus',
  'Pimozide',
  'Pindolol',
  'Pioglitazone',
  'Piperacillin',
  'Piperacillin/Tazobactam',
  'Pirfenidone',
  'Piroxicam',
  'Podophyllotoxin',
  'Polymyxin B',
  'Posaconazole',
  'Potassium Chloride',
  'Potassium Permanganate',
  'Povidone-Iodine',
  'Pralidoxime',
  'Prasugrel',
  'Pravastatin',
  'Praziquantel',
  'Prazosin',
  'Prednisolone',
  'Prednisone',
  'Pregabalin',
  'Primaquine',
  'Primidone',
  'Probenecid',
  'Procainamide',
  'Procaine',
  'Prochlorperazine',
  'Procyclidine',
  'Progesterone',
  'Proguanil',
  'Promethazine',
  'Propafenone',
  'Propantheline',
  'Propofol',
  'Propranolol',
  'Propylthiouracil',
  'Protamine Sulfate',
  'Pseudoephedrine',
  'Pyrazinamide',
  'Pyridoxine',
  'Pyrimethamine',

  // ── Q ───────────────────────────────────────────────────────────
  'Quetiapine',
  'Quinapril',
  'Quinidine',
  'Quinine',

  // ── R ───────────────────────────────────────────────────────────
  'Rabeprazole',
  'Raltegravir',
  'Ramipril',
  'Ranitidine',
  'Ranolazine',
  'Rasagiline',
  'Rasburicase',
  'Reboxetine',
  'Regorafenib',
  'Remdesivir',
  'Repaglinide',
  'Ribavirin',
  'Rifabutin',
  'Rifampicin',
  'Rifaximin',
  'Rilpivirine',
  'Riluzole',
  'Rimantadine',
  "Ringer's Lactate",
  'Risedronate',
  'Risperidone',
  'Ritonavir',
  'Rivaroxaban',
  'Rivastigmine',
  'Rizatriptan',
  'Rocuronium',
  'Ropinirole',
  'Ropivacaine',
  'Rosuvastatin',
  'Roxithromycin',
  'Rufinamide',

  // ── S ───────────────────────────────────────────────────────────
  'Sacubitril/Valsartan',
  'Salbutamol',
  'Salicylic Acid',
  'Salmeterol',
  'Saxagliptin',
  'Scopolamine',
  'Secnidazole',
  'Selegiline',
  'Semaglutide',
  'Senna',
  'Sertaconazole',
  'Sertraline',
  'Sevelamer',
  'Sevoflurane',
  'Sildenafil',
  'Silver Sulfadiazine',
  'Simvastatin',
  'Sirolimus',
  'Sitagliptin',
  'Sodium Bicarbonate',
  'Sodium Chloride',
  'Sodium Cromoglicate',
  'Sodium Valproate',
  'Sofosbuvir',
  'Sorafenib',
  'Sotalol',
  'Spectinomycin',
  'Spironolactone',
  'Streptomycin',
  'Succinylcholine',
  'Sucralfate',
  'Sufentanil',
  'Sulbactam',
  'Sulfadiazine',
  'Sulfadoxine',
  'Sulfamethoxazole',
  'Sulfamethoxazole/Trimethoprim',
  'Sulfasalazine',
  'Sulindac',
  'Sumatriptan',
  'Sunitinib',
  'Suxamethonium',

  // ── T ───────────────────────────────────────────────────────────
  'Tacrolimus',
  'Tamoxifen',
  'Tamsulosin',
  'Tazarotene',
  'Teicoplanin',
  'Telmisartan',
  'Temazepam',
  'Temozolomide',
  'Tenecteplase',
  'Tenofovir Alafenamide',
  'Tenofovir Disoproxil',
  'Terazosin',
  'Terbinafine',
  'Terbutaline',
  'Teriparatide',
  'Testosterone',
  'Tetracycline',
  'Thalidomide',
  'Theophylline',
  'Thiamine',
  'Thiopental',
  'Thioguanine',
  'Thiotepa',
  'Ticagrelor',
  'Tigecycline',
  'Timolol',
  'Tinidazole',
  'Tiotropium',
  'Tirofiban',
  'Tizanidine',
  'Tobramycin',
  'Tocilizumab',
  'Tolbutamide',
  'Tolcapone',
  'Tolmetin',
  'Tolterodine',
  'Topiramate',
  'Topotecan',
  'Torasemide',
  'Tramadol',
  'Trandolapril',
  'Tranexamic Acid',
  'Trastuzumab',
  'Trazodone',
  'Tretinoin',
  'Triamcinolone',
  'Triamterene',
  'Triazolam',
  'Trifluoperazine',
  'Trimethoprim',
  'Trimipramine',
  'Tropicamide',
  'Trospium',

  // ── U ───────────────────────────────────────────────────────────
  'Umeclidinium',
  'Ursodeoxycholic Acid',
  'Ustekinumab',

  // ── V ───────────────────────────────────────────────────────────
  'Valaciclovir',
  'Valganciclovir',
  'Valproic Acid',
  'Valsartan',
  'Vancomycin',
  'Vardenafil',
  'Varenicline',
  'Vasopressin',
  'Vecuronium',
  'Venetoclax',
  'Venlafaxine',
  'Verapamil',
  'Vigabatrin',
  'Vilazodone',
  'Vinblastine',
  'Vincristine',
  'Vinorelbine',
  'Vitamin K',
  'Voriconazole',

  // ── W ───────────────────────────────────────────────────────────
  'Warfarin',

  // ── X ───────────────────────────────────────────────────────────
  'Xylometazoline',

  // ── Z ───────────────────────────────────────────────────────────
  'Zafirlukast',
  'Zaleplon',
  'Zanamivir',
  'Zidovudine',
  'Zinc Sulfate',
  'Ziprasidone',
  'Zoledronic Acid',
  'Zolmitriptan',
  'Zolpidem',
  'Zonisamide',
  'Zopiclone',
  'Zuclopenthixol',
]
