// ================================================================
// Oncology — Case Templates (6 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const ONCOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Oncology', 'Oncology', 'Breast Cancer', 'Early-Stage HR+ Breast Cancer in a Postmenopausal Woman — Adjuvant Therapy Decision', 'Intermediate',
    'Newly diagnosed breast cancer — discussing treatment plan after lumpectomy',
    '{name}, a {age}-year-old {occupation} from {location}, recently underwent a lumpectomy for a 1.8 cm invasive ductal carcinoma discovered on screening mammography. Sentinel lymph node biopsy negative. Now attending oncology clinic to discuss adjuvant therapy. No symptoms. Good performance status (ECOG 0).',
    'Postmenopausal. Hypertension. Osteopenia. No prior cancers.',
    'Amlodipine 5mg daily, Calcium 600mg + Vitamin D 400 IU daily',
    'Well-appearing. Right breast: well-healed lumpectomy scar, no palpable masses. No axillary lymphadenopathy. Normal cardiac and respiratory exam. BMI 28.',
    'Pathology: IDC Grade 2, ER 95%+, PR 80%+, HER2-negative (IHC 1+), Ki-67 12%. Sentinel LN: 0/2 negative. Oncotype DX recurrence score: 16 (low risk). Hb 12.5, Cr 0.8, ALT normal. ECG: normal.',
    'Mammogram: post-op changes, no residual calcifications. Breast ultrasound: normal.',
    'Early-Stage Hormone Receptor-Positive, HER2-Negative Breast Cancer (pT1c N0 M0, Stage IA)',
    ['Invasive Ductal Carcinoma', 'Ductal Carcinoma In Situ (DCIS)', 'Lobular Carcinoma'],
    'Reduce risk of recurrence, manage endocrine therapy side effects, maintain bone health, achieve long-term survival',
    '1. Adjuvant endocrine therapy: Aromatase Inhibitor (Anastrozole 1mg daily or Letrozole 2.5mg daily) for 5-10 years. In postmenopausal women, AIs are superior to Tamoxifen. 2. Bone protection (AI increases bone loss): Ensure adequate Calcium 1200mg/day + Vitamin D 800-1000 IU/day. Consider bisphosphonate (Alendronate 70mg weekly or Zoledronic acid 5mg IV yearly) given baseline osteopenia (T-score -1.8). 3. Adjuvant radiation: Whole breast radiotherapy (standard after lumpectomy) for 3-6 weeks. 4. No chemotherapy indicated (Oncotype DX recurrence score 16, low risk).',
    'Weight-bearing exercise. Smoking cessation. Limit alcohol. Healthy diet. Breast self-awareness. Annual mammography.',
    'Start Anastrozole 1mg daily. Refer to radiation oncology. Baseline DXA (done: T-score -1.8). Baseline fasting lipid panel (AIs can increase cholesterol). Schedule oncology follow-up in 3-6 months.',
    '1. Need for adjuvant endocrine therapy to reduce recurrence risk (~50% risk reduction with 5 years of AI). 2. AI-induced bone loss requires monitoring and bone protection.',
    'Annual mammography. DXA every 2 years (or sooner if risk factors). Lipid panel annually. Monitor for AI side effects: arthralgias (50%), hot flashes, vaginal dryness, mood changes. Assess adherence at each visit.',
    'Anastrozole blocks estrogen production — it reduces the risk of breast cancer returning by about half. The most common side effects are joint pain and hot flashes. Joint pain can be managed with exercise, NSAIDs, or switching to a different AI. Take calcium and Vitamin D daily to protect your bones.',
    'Oncology clinic in 3-6 months for tolerance assessment. Annual mammography. DXA in 2 years. Consider extending AI to 10 years if high-risk features.',
    'Aromatase inhibitors (Anastrozole, Letrozole, Exemestane) are the standard of care for postmenopausal women with HR+ breast cancer. They DO NOT work in premenopausal women (ovaries upregulate estrogen production). The SOFT/TEXT trials demonstrated AI superiority over Tamoxifen in postmenopausal women. Oncotype DX recurrence score <18 predicts minimal benefit from chemotherapy. AI-induced arthralgias are common and the most frequent reason for discontinuation — switching to a different AI often helps.',
    ['NCCN Guidelines: Breast Cancer', 'St. Gallen Consensus: Early Breast Cancer', 'Kenya Cancer Treatment Guidelines'],
  ),
  t('Oncology', 'Oncology', 'Prostate Cancer', 'Metastatic Hormone-Sensitive Prostate Cancer in an Elderly Man', 'Advanced',
    'Difficulty urinating, bone pain, and weight loss for 3 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive urinary hesitancy, weak stream, nocturia (4-5x/night), and low back pain for 3 months. Has lost 5 kg unintentionally over 2 months. No haematuria. No prior PSA testing. No history of prostate cancer in family.',
    'Hypertension, Type 2 Diabetes (diet-controlled). No prior prostate issues.',
    'Amlodipine 5mg daily',
    'Prostate: enlarged, firm, with a hard nodule on the right lobe (T3a). Reduced anal sphincter tone. Digital rectal exam: prostate ~45g, irregular, fixed. Tenderness over lumbar spine. No neurological deficits.',
    'PSA: 245 ng/mL. Hb 10.5 (anaemia of chronic disease). Creatinine 1.3 mg/dL (mild obstructive uropathy). ALP 250 U/L (elevated, bone metastases). Bone scan: multiple hot spots in lumbar spine, pelvis, ribs, and femur. Prostate biopsy (transrectal ultrasound-guided): Adenocarcinoma, Gleason score 4+5=9 (Grade Group 5).',
    'Bone scan (Tc-99m MDP): Multifocal osteoblastic metastases in axial skeleton. CT abdomen/pelvis: enlarged prostate with seminal vesicle involvement. No visceral metastases.',
    'Metastatic Hormone-Sensitive Prostate Cancer (mHSPC, Stage IVB, Gleason 9, High Volume per CHAARTED criteria)',
    ['Prostate Cancer', 'Benign Prostatic Hyperplasia', 'Metastatic Spine Tumour', 'Chronic Prostatitis', 'UTI'],
    'Suppress testosterone, reduce tumour burden, relieve bone pain, prevent spinal cord compression, prolong survival',
    '1. Androgen Deprivation Therapy (ADT): GnRH agonist — Leuprolide 22.5mg IM every 3 months OR Goserelin 10.8mg SC every 3 months (plus short-term antiandrogen Bicalutamide 50mg daily for 2 weeks to prevent tumour flare). 2. ADT + Anti-androgen: continue Bicalutamide 50mg daily. 3. Add chemotherapy: Docetaxel 75mg/m2 IV every 3 weeks for 6 cycles (if fit for chemo, ECOG 0-1). 4. Alternatively (if not fit for chemo): ADT + Abiraterone Acetate 1000mg daily + Prednisolone 5mg BID. 5. Bone protection: Zoledronic acid 4mg IV every 3-6 months OR Denosumab 60mg SC every 6 months. 6. Analgesia: Paracetamol + NSAIDs + opioids according to WHO ladder for bone pain. Palliative radiotherapy for painful bone metastases.',
    'Spinal precautions (avoid heavy lifting, bending). If cord compression suspected (back pain + leg weakness/numbness/bladder dysfunction): urgent MRI and radiotherapy/neurosurgery. Urethral stent or TURP if urinary obstruction severe.',
    'Start ADT with Leuprolide 22.5mg IM + Bicalutamide 50mg daily for flare protection. Refer to radiation oncology for palliative RT to painful bone sites. Start Zoledronic acid. Assess fitness for Docetaxel chemotherapy. CT/MRI spine if back pain with neurological symptoms. Social work and palliative care referral.',
    '1. Metastatic prostate cancer requiring ADT as backbone therapy. 2. High-volume metastatic disease appropriate for ADT + Docetaxel (survival benefit). 3. Bone metastases at risk of skeletal-related events requiring bone-protective agents.',
    'PSA monthly during induction, then every 3 months. Testosterone (should be <50 ng/dL). Hb, Cr, LFTs, ALP, Ca monthly. Bone density (DXA) at baseline and annually. Monitor for ADT side effects: hot flashes, fatigue, loss of libido, gynaecomastia, osteoporosis, CV risk. Docetaxel: FBC before each cycle (risk of neutropenia).',
    'The treatment involves lowering your testosterone (male hormone), which prostate cancer depends on to grow. This can be done with injections every 3 months. Side effects include hot flashes, fatigue, decreased sexual desire, and weight gain — most are manageable. We add chemotherapy to improve survival. Bone metastases can be treated with radiation if painful. You will be monitored closely with PSA blood tests.',
    'Medical oncology in 4 weeks for chemotherapy initiation (if planned). PSA at 1 month (should drop significantly). Ongoing: ADT injections every 3 months. Monitor for castration-resistant progression (rising PSA despite castrate testosterone levels).',
    'ADT is the backbone of mHSPC treatment — prostate cancer cells are driven by androgens. The addition of Docetaxel chemotherapy to ADT improves overall survival by 13-15 months in high-volume disease (CHAARTED trial). Abiraterone + Prednisolone is an alternative for those unfit for chemo. GnRH agonists cause an initial testosterone surge ("tumour flare") — antiandrogen (Bicalutamide) for 2 weeks prevents this. GnRH antagonists (Degarelix) avoid the flare but are injectable monthly. Denosumab is superior to Zoledronic acid for preventing skeletal-related events.',
    ['NCCN Guidelines: Prostate Cancer', 'EAU Guidelines: Prostate Cancer', 'Kenya Cancer Treatment Guidelines'],
  ),
  t('Oncology', 'Oncology', 'Colorectal Cancer', 'Stage III Colon Cancer — Adjuvant Chemotherapy Decision', 'Intermediate',
    'Follow-up after surgical resection of colon cancer — discussing chemotherapy',
    '{name}, a {age}-year-old {occupation} from {location}, recently underwent a right hemicolectomy for a colonic mass found during colonoscopy for iron deficiency anaemia and altered bowel habits. Pathology confirmed stage III disease. Now attending oncology clinic to discuss adjuvant chemotherapy. Recovering well from surgery. ECOG 1.',
    'Hypertension. No prior abdominal surgeries. No family history of colorectal cancer.',
    'Amlodipine 5mg daily. Iron supplementation.',
    'Well-healed midline scar. Abdomen soft, non-tender. No palpable masses. No lymphadenopathy. Good nutritional status.',
    'Pathology: Moderately differentiated adenocarcinoma of the ascending colon. Tumour invading through muscularis propria into serosa (pT3). 3 of 18 lymph nodes positive (pN1b). Margins negative (R0 resection). MSI status: MSS (microsatellite stable). KRAS/NRAS/BRAF: wild-type. CEA (baseline): 5.2 ng/mL (mildly elevated). FBC, LFTs, Cr: normal.',
    'CT chest/abdomen/pelvis (post-op): no residual disease, no metastases. Colonoscopy: clear.',
    'Stage III (pT3 N1b M0) Adenocarcinoma of the Ascending Colon — R0 Resection, Microsatellite Stable',
    ['Colon Cancer Stage III', 'Rectal Cancer', 'Colonic Adenoma', 'IBD-Associated Dysplasia'],
    'Reduce risk of recurrence with adjuvant chemotherapy, manage treatment side effects, monitor for disease recurrence',
    '1. Adjuvant chemotherapy: FOLFOX regimen (Oxaliplatin 85mg/m2 IV Day 1 + Leucovorin 400mg/m2 IV Day 1 + 5-FU 400mg/m2 IV bolus then 2400mg/m2 IV infusion over 46 hours) every 2 weeks for 12 cycles (6 months). 2. Alternative: CAPOX regimen (Capecitabine 1000mg/m2 PO BID Days 1-14 + Oxaliplatin 130mg/m2 IV Day 1) every 3 weeks for 8 cycles. 3. If age >70: discuss risks/benefits of adding Oxaliplatin. 4. If MSI-H: consider single-agent immune checkpoint inhibitor (Pembrolizumab) instead of chemotherapy — not applicable here (MSS). 5. CEA monitoring every 3 months for 3 years. 6. Colonoscopy in 1 year.',
    'Dietary: small frequent meals, avoid cold foods (Oxaliplatin can cause pharyngolaryngeal dysaesthesia with cold). Exercise during treatment to reduce fatigue. Good oral hygiene. Hand-foot syndrome care (moisturisers, avoid hot water) if on Capecitabine.',
    'Start adjuvant FOLFOX chemotherapy 4-8 weeks post-surgery. Place central line (PICC or Port-a-cath) for 5-FU infusion. Pre-medication: antiemetics (Aprepitant, Dexamethasone, 5-HT3 antagonist). Monitor for Oxaliplatin neurotoxicity at each cycle. Dose reduction or discontinuation if significant neuropathy.',
    '1. Stage III colon cancer with high risk of recurrence requiring adjuvant systemic therapy. 2. Chemotherapy toxicity management (neuropathy, neutropenia, fatigue, GI).',
    'FBC before each cycle (ANC >1500). LFTs, Cr before each cycle. Neurotoxicity assessment (sensory, motor, functional). Monitor for: neutropenic fever, diarrhoea, stomatitis, hand-foot syndrome. CEA every 3 months. CT chest/abdomen/pelvis every 6-12 months for 3-5 years.',
    'Adjuvant chemotherapy reduces the risk of cancer returning by 30-50%. Treatment is given every 2 weeks for 6 months. The most notable side effect is nerve tingling/numbness from Oxaliplatin — avoid cold drinks and cold air during and after infusion. Most side effects are temporary. Stay active and eat well to maintain strength during treatment.',
    'Medical oncology every 2 cycles during treatment. CEA every 3 months. Colonoscopy in 1 year. CT scans every 6-12 months. Long-term: surveillance for 5 years, then less frequent.',
    'Adjuvant chemotherapy for Stage III colon cancer is standard of care — reduces 5-year recurrence risk from ~50% to ~25%. The MOSAIC trial established FOLFOX as the standard regimen. The addition of Oxaliplatin to 5-FU/Leucovorin improves disease-free survival by 7-8%. Cumulative Oxaliplatin-induced peripheral neuropathy is dose-limiting — assess before each cycle. Patients with MSI-H (15% of Stage III) may not benefit from 5-FU but benefit from immunotherapy.',
    ['NCCN Guidelines: Colon Cancer', 'ESMO Guidelines: Colorectal Cancer', 'Kenya Cancer Treatment Guidelines'],
  ),
];
