// ================================================================
// Oncology — Case Templates (6 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const ONCOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Oncology', 'Oncology', 'Breast Cancer', 'Early-Stage HR+ Breast Cancer in a Postmenopausal Woman — Adjuvant Therapy Decision', 'Intermediate',
    'Newly diagnosed breast cancer — discussing treatment plan after lumpectomy',
    '{name}, a {age}-year-old {occupation} from {location}, recently underwent a lumpectomy for a 1.8 cm invasive ductal carcinoma discovered on screening mammography. Sentinel lymph node biopsy negative. Now attending oncology clinic to discuss adjuvant therapy. No symptoms. Good performance status (ECOG 0).',
    'Postmenopausal. Hypertension. Osteopenia. No prior cancers.',
    'Amlodipine 5mg daily, Calcium 600mg + Vitamin D 400 IU daily',
    'Well-appearing. Right breast: well-healed lumpectomy scar, no palpable masses. No axillary lymphadenopathy. Normal cardiac and respiratory exam. BMI 28.',
    'Pathology: IDC Grade 2, ER 95%+, PR 80%+, HER2-negative (IHC 1+), Ki-67 12%. Sentinel LN: 0/2 negative. Oncotype DX recurrence score: 16 (low risk). Hb 12.5, Cr 0.8, ALT normal. ECG: normal.',
    'Mammogram: post-op changes, no residual calcifications. Breast ultrasound: normal.',
    'Early-Stage Hormone Receptor-Positive, HER2-Negative Breast Cancer (pT1c N0 M0, Stage IA)',
    ['Invasive Ductal Carcinoma', 'Ductal Carcinoma In Situ (DCIS)', 'Lobular Carcinoma'],
    'Reduce risk of recurrence, manage endocrine therapy side effects, maintain bone health, achieve long-term survival',
    '1. Adjuvant endocrine therapy: Aromatase Inhibitor (Anastrozole 1mg daily or Letrozole 2.5mg daily) for 5-10 years. In postmenopausal women, AIs are superior to Tamoxifen. 2. Bone protection (AI increases bone loss): Ensure adequate Calcium 1200mg/day + Vitamin D 800-1000 IU/day. Consider bisphosphonate (Alendronate 70mg weekly or Zoledronic acid 5mg IV yearly) given baseline osteopenia (T-score -1.8). 3. Adjuvant radiation: Whole breast radiotherapy (standard after lumpectomy) for 3-6 weeks. 4. No chemotherapy indicated (Oncotype DX recurrence score 16, low risk).',
    'Weight-bearing exercise. Smoking cessation. Limit alcohol. Healthy diet. Breast self-awareness. Annual mammography.',
    'Start Anastrozole 1mg daily. Refer to radiation oncology. Baseline DXA (done: T-score -1.8). Baseline fasting lipid panel (AIs can increase cholesterol). Schedule oncology follow-up in 3-6 months.',
    '1. Need for adjuvant endocrine therapy to reduce recurrence risk (~50% risk reduction with 5 years of AI). 2. AI-induced bone loss requires monitoring and bone protection.',
    'Annual mammography. DXA every 2 years (or sooner if risk factors). Lipid panel annually. Monitor for AI side effects: arthralgias (50%), hot flashes, vaginal dryness, mood changes. Assess adherence at each visit.',
    'Anastrozole blocks estrogen production — it reduces the risk of breast cancer returning by about half. The most common side effects are joint pain and hot flashes. Joint pain can be managed with exercise, NSAIDs, or switching to a different AI. Take calcium and Vitamin D daily to protect your bones.',
    'Oncology clinic in 3-6 months for tolerance assessment. Annual mammography. DXA in 2 years. Consider extending AI to 10 years if high-risk features.',
    'Aromatase inhibitors (Anastrozole, Letrozole, Exemestane) are the standard of care for postmenopausal women with HR+ breast cancer. They DO NOT work in premenopausal women (ovaries upregulate estrogen production). The SOFT/TEXT trials demonstrated AI superiority over Tamoxifen in postmenopausal women. Oncotype DX recurrence score <18 predicts minimal benefit from chemotherapy. AI-induced arthralgias are common and the most frequent reason for discontinuation — switching to a different AI often helps.',
    ['NCCN Guidelines: Breast Cancer', 'St. Gallen Consensus: Early Breast Cancer', 'Kenya Cancer Treatment Guidelines'],
  ),
  t('Oncology', 'Oncology', 'Prostate Cancer', 'Metastatic Hormone-Sensitive Prostate Cancer in an Elderly Man', 'Advanced',
    'Difficulty urinating, bone pain, and weight loss for 3 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive urinary hesitancy, weak stream, nocturia (4-5x/night), and low back pain for 3 months. Has lost 5 kg unintentionally over 2 months. No haematuria. No prior PSA testing. No history of prostate cancer in family.',
    'Hypertension, Type 2 Diabetes (diet-controlled). No prior prostate issues.',
    'Amlodipine 5mg daily',
    'Prostate: enlarged, firm, with a hard nodule on the right lobe (T3a). Reduced anal sphincter tone. Digital rectal exam: prostate ~45g, irregular, fixed. Tenderness over lumbar spine. No neurological deficits.',
    'PSA: 245 ng/mL. Hb 10.5 (anaemia of chronic disease). Creatinine 1.3 mg/dL (mild obstructive uropathy). ALP 250 U/L (elevated, bone metastases). Bone scan: multiple hot spots in lumbar spine, pelvis, ribs, and femur. Prostate biopsy (transrectal ultrasound-guided): Adenocarcinoma, Gleason score 4+5=9 (Grade Group 5).',
    'Bone scan (Tc-99m MDP): Multifocal osteoblastic metastases in axial skeleton. CT abdomen/pelvis: enlarged prostate with seminal vesicle involvement. No visceral metastases.',
    'Metastatic Hormone-Sensitive Prostate Cancer (mHSPC, Stage IVB, Gleason 9, High Volume per CHAARTED criteria)',
    ['Prostate Cancer', 'Benign Prostatic Hyperplasia', 'Metastatic Spine Tumour', 'Chronic Prostatitis', 'UTI'],
    'Suppress testosterone, reduce tumour burden, relieve bone pain, prevent spinal cord compression, prolong survival',
    '1. Androgen Deprivation Therapy (ADT): GnRH agonist — Leuprolide 22.5mg IM every 3 months OR Goserelin 10.8mg SC every 3 months (plus short-term antiandrogen Bicalutamide 50mg daily for 2 weeks to prevent tumour flare). 2. ADT + Anti-androgen: continue Bicalutamide 50mg daily. 3. Add chemotherapy: Docetaxel 75mg/m2 IV every 3 weeks for 6 cycles (if fit for chemo, ECOG 0-1). 4. Alternatively (if not fit for chemo): ADT + Abiraterone Acetate 1000mg daily + Prednisolone 5mg BID. 5. Bone protection: Zoledronic acid 4mg IV every 3-6 months OR Denosumab 60mg SC every 6 months. 6. Analgesia: Paracetamol + NSAIDs + opioids according to WHO ladder for bone pain. Palliative radiotherapy for painful bone metastases.',
    'Spinal precautions (avoid heavy lifting, bending). If cord compression suspected (back pain + leg weakness/numbness/bladder dysfunction): urgent MRI and radiotherapy/neurosurgery. Urethral stent or TURP if urinary obstruction severe.',
    'Start ADT with Leuprolide 22.5mg IM + Bicalutamide 50mg daily for flare protection. Refer to radiation oncology for palliative RT to painful bone sites. Start Zoledronic acid. Assess fitness for Docetaxel chemotherapy. CT/MRI spine if back pain with neurological symptoms. Social work and palliative care referral.',
    '1. Metastatic prostate cancer requiring ADT as backbone therapy. 2. High-volume metastatic disease appropriate for ADT + Docetaxel (survival benefit). 3. Bone metastases at risk of skeletal-related events requiring bone-protective agents.',
    'PSA monthly during induction, then every 3 months. Testosterone (should be <50 ng/dL). Hb, Cr, LFTs, ALP, Ca monthly. Bone density (DXA) at baseline and annually. Monitor for ADT side effects: hot flashes, fatigue, loss of libido, gynaecomastia, osteoporosis, CV risk. Docetaxel: FBC before each cycle (risk of neutropenia).',
    'The treatment involves lowering your testosterone (male hormone), which prostate cancer depends on to grow. This can be done with injections every 3 months. Side effects include hot flashes, fatigue, decreased sexual desire, and weight gain — most are manageable. We add chemotherapy to improve survival. Bone metastases can be treated with radiation if painful. You will be monitored closely with PSA blood tests.',
    'Medical oncology in 4 weeks for chemotherapy initiation (if planned). PSA at 1 month (should drop significantly). Ongoing: ADT injections every 3 months. Monitor for castration-resistant progression (rising PSA despite castrate testosterone levels).',
    'ADT is the backbone of mHSPC treatment — prostate cancer cells are driven by androgens. The addition of Docetaxel chemotherapy to ADT improves overall survival by 13-15 months in high-volume disease (CHAARTED trial). Abiraterone + Prednisolone is an alternative for those unfit for chemo. GnRH agonists cause an initial testosterone surge ("tumour flare") — antiandrogen (Bicalutamide) for 2 weeks prevents this. GnRH antagonists (Degarelix) avoid the flare but are injectable monthly. Denosumab is superior to Zoledronic acid for preventing skeletal-related events.',
    ['NCCN Guidelines: Prostate Cancer', 'EAU Guidelines: Prostate Cancer', 'Kenya Cancer Treatment Guidelines'],
  ),
  t('Oncology', 'Oncology', 'Colorectal Cancer', 'Stage III Colon Cancer — Adjuvant Chemotherapy Decision', 'Intermediate',
    'Follow-up after surgical resection of colon cancer — discussing chemotherapy',
    '{name}, a {age}-year-old {occupation} from {location}, recently underwent a right hemicolectomy for a colonic mass found during colonoscopy for iron deficiency anaemia and altered bowel habits. Pathology confirmed stage III disease. Now attending oncology clinic to discuss adjuvant chemotherapy. Recovering well from surgery. ECOG 1.',
    'Hypertension. No prior abdominal surgeries. No family history of colorectal cancer.',
    'Amlodipine 5mg daily. Iron supplementation.',
    'Well-healed midline scar. Abdomen soft, non-tender. No palpable masses. No lymphadenopathy. Good nutritional status.',
    'Pathology: Moderately differentiated adenocarcinoma of the ascending colon. Tumour invading through muscularis propria into serosa (pT3). 3 of 18 lymph nodes positive (pN1b). Margins negative (R0 resection). MSI status: MSS (microsatellite stable). KRAS/NRAS/BRAF: wild-type. CEA (baseline): 5.2 ng/mL (mildly elevated). FBC, LFTs, Cr: normal.',
    'CT chest/abdomen/pelvis (post-op): no residual disease, no metastases. Colonoscopy: clear.',
    'Stage III (pT3 N1b M0) Adenocarcinoma of the Ascending Colon — R0 Resection, Microsatellite Stable',
    ['Colon Cancer Stage III', 'Rectal Cancer', 'Colonic Adenoma', 'IBD-Associated Dysplasia'],
    'Reduce risk of recurrence with adjuvant chemotherapy, manage treatment side effects, monitor for disease recurrence',
    '1. Adjuvant chemotherapy: FOLFOX regimen (Oxaliplatin 85mg/m2 IV Day 1 + Leucovorin 400mg/m2 IV Day 1 + 5-FU 400mg/m2 IV bolus then 2400mg/m2 IV infusion over 46 hours) every 2 weeks for 12 cycles (6 months). 2. Alternative: CAPOX regimen (Capecitabine 1000mg/m2 PO BID Days 1-14 + Oxaliplatin 130mg/m2 IV Day 1) every 3 weeks for 8 cycles. 3. If age >70: discuss risks/benefits of adding Oxaliplatin. 4. If MSI-H: consider single-agent immune checkpoint inhibitor (Pembrolizumab) instead of chemotherapy — not applicable here (MSS). 5. CEA monitoring every 3 months for 3 years. 6. Colonoscopy in 1 year.',
    'Dietary: small frequent meals, avoid cold foods (Oxaliplatin can cause pharyngolaryngeal dysaesthesia with cold). Exercise during treatment to reduce fatigue. Good oral hygiene. Hand-foot syndrome care (moisturisers, avoid hot water) if on Capecitabine.',
    'Start adjuvant FOLFOX chemotherapy 4-8 weeks post-surgery. Place central line (PICC or Port-a-cath) for 5-FU infusion. Pre-medication: antiemetics (Aprepitant, Dexamethasone, 5-HT3 antagonist). Monitor for Oxaliplatin neurotoxicity at each cycle. Dose reduction or discontinuation if significant neuropathy.',
    '1. Stage III colon cancer with high risk of recurrence requiring adjuvant systemic therapy. 2. Chemotherapy toxicity management (neuropathy, neutropenia, fatigue, GI).',
    'FBC before each cycle (ANC >1500). LFTs, Cr before each cycle. Neurotoxicity assessment (sensory, motor, functional). Monitor for: neutropenic fever, diarrhoea, stomatitis, hand-foot syndrome. CEA every 3 months. CT chest/abdomen/pelvis every 6-12 months for 3-5 years.',
    'Adjuvant chemotherapy reduces the risk of cancer returning by 30-50%. Treatment is given every 2 weeks for 6 months. The most notable side effect is nerve tingling/numbness from Oxaliplatin — avoid cold drinks and cold air during and after infusion. Most side effects are temporary. Stay active and eat well to maintain strength during treatment.',
    'Medical oncology every 2 cycles during treatment. CEA every 3 months. Colonoscopy in 1 year. CT scans every 6-12 months. Long-term: surveillance for 5 years, then less frequent.',
    'Adjuvant chemotherapy for Stage III colon cancer is standard of care — reduces 5-year recurrence risk from ~50% to ~25%. The MOSAIC trial established FOLFOX as the standard regimen. The addition of Oxaliplatin to 5-FU/Leucovorin improves disease-free survival by 7-8%. Cumulative Oxaliplatin-induced peripheral neuropathy is dose-limiting — assess before each cycle. Patients with MSI-H (15% of Stage III) may not benefit from 5-FU but benefit from immunotherapy.',
    ['NCCN Guidelines: Colon Cancer', 'ESMO Guidelines: Colorectal Cancer', 'Kenya Cancer Treatment Guidelines'],
  ),
  t('Oncology', 'Oncology', 'Breast Cancer', 'HER2-Positive Breast Cancer — Neoadjuvant Chemotherapy with AC-THP Regimen', 'Advanced',
    'Newly diagnosed HER2+ breast cancer — planning neoadjuvant chemotherapy before surgery',
    '{name}, a {age}-year-old {occupation} from {location}, was diagnosed with invasive ductal carcinoma of the left breast 2 weeks ago after discovering a painless lump. Core biopsy confirmed HER2-positive disease (IHC 3+). Oncology team recommends neoadjuvant chemotherapy to downstage the tumour before surgery. ECOG performance status 0. Expresses concern about chemotherapy side effects, hair loss, and ability to continue working as a {occupation}. Husband is supportive. Two school-age children at home.',
    'No significant PMH. No prior cancers. No family history of breast cancer. No known drug allergies.',
    'No regular medications. No hormonal contraceptives.',
    'Left breast: 3.5 cm palpable mass in the upper outer quadrant. Left axilla: 2 palpable, mobile lymph nodes (clinically node-positive). No skin changes, no nipple retraction. Right breast: normal. ECOG 0. BMI 25.',
    'Core biopsy: Invasive ductal carcinoma, Grade 3. ER 10% (low positive), PR negative. HER2: IHC 3+ (strongly positive). Ki-67: 40% (high proliferation). Axillary USS: 2 suspicious lymph nodes (cortical thickening). MRI breast: 3.5 cm mass, no multifocal disease. Staging CT chest/abdomen/pelvis: no metastatic disease. FBC, LFTs, Cr: normal. Cardiac echo: EF 62% (normal baseline).',
    'MRI left breast: 3.5 cm enhancing mass, clinically node-positive (cN1). No distant metastases on staging CT. Echocardiogram: EF 62%, no wall motion abnormalities.',
    'Left Invasive Ductal Carcinoma, HER2-Positive, Clinical Stage IIB (T2 N1 M0)',
    ['HER2+ Breast Cancer', 'Triple-Negative Breast Cancer', 'Inflammatory Breast Cancer', 'Fibroadenoma', 'Phyllodes Tumour'],
    'Achieve pathological complete response (pCR) with neoadjuvant therapy, downstage tumour for breast-conserving surgery, reduce risk of recurrence, monitor and manage chemotherapy-induced cardiotoxicity',
    '1. Neoadjuvant chemotherapy — AC-THP regimen (standard of care for HER2+ Stage II-III): Phase 1: Doxorubicin 60mg/m2 IV + Cyclophosphamide 600mg/m2 IV Day 1, every 2 weeks for 4 cycles (AC q2). Growth factor support: Pegfilgrastim 6mg SC Day 2 after each AC cycle (primary G-CSF prophylaxis — febrile neutropenia risk >20% with dose-dense AC). 2. Phase 2: Paclitaxel 80mg/m2 IV weekly for 12 weeks + Trastuzumab 8mg/kg loading then 6mg/kg IV q3w + Pertuzumab 840mg loading then 420mg IV q3w (THP). 3. Antiemetic prophylaxis for AC: Aprepitant (NK1 RA) 125mg PO Day 1, 80mg Days 2-3 + Ondansetron 16mg IV pre-chemo + Dexamethasone 12mg IV pre-chemo then 8mg PO Days 2-4. 4. Antiemetic for Paclitaxel: Ondansetron 8mg IV + Dexamethasone 8mg IV. 5. Cardiotoxicity monitoring: Echo at baseline (done: EF 62%), repeat after 4 cycles of AC, then every 3 months during Trastuzumab. Hold Trastuzumab if EF drops >10% from baseline or below 50%. 6. In Kenya: Trastuzumab biosimilars (e.g., Ogivri, Trazimera) are more accessible and affordable than Herceptin — ensure biosimilar access through KEMSA or NHIF. 7. Post-neoadjuvant: surgical reassessment — if pCR, proceed to lumpectomy or mastectomy. If residual disease, consider T-DM1 (ado-trastuzumab emtansine) as adjuvant.',
    'Nutritional support: high-protein diet to maintain weight during chemotherapy. Exercise: moderate activity as tolerated (reduces chemotherapy-related fatigue). Hair loss counselling: provide head covering options, discuss cold cap therapy if available. Fertility preservation: discuss before chemotherapy (egg/embryo freezing — must be offered to all premenopausal women before gonadotoxic therapy). Psychosocial support: breast cancer support group referral.',
    'Admit Day 1 for AC cycle 1: pre-medicate with antiemetics, administer Doxorubicin + Cyclophosphamide IV, administer Pegfilgrastim Day 2. Discharge same day. Cycle 2 in 14 days. After 4 AC cycles: re-stage (echo, imaging), then transition to Paclitaxel + Trastuzumab + Pertuzumab (THP) for 12 weeks. Surgical planning after completion of neoadjuvant therapy. Total neoadjuvant duration: ~18-20 weeks.',
    '1. HER2+ breast cancer with excellent prognosis when treated with anti-HER2 therapy — pCR rates 40-60% with AC-THP. 2. Febrile neutropenia risk with dose-dense AC mandates G-CSF prophylaxis. 3. Cardiotoxicity from Trastuzumab requires serial echocardiographic monitoring — usually reversible if caught early.',
    'Echo: baseline (done), after AC (week 8), then every 3 months during Trastuzumab. FBC before each AC cycle (ANC >1.5 for treatment). LFTs, Cr before each cycle. Monitor for: febrile neutropenia (temp >38.3°C or >38.0 for 1 hour — emergency department, IV antibiotics), mucositis, peripheral neuropathy (Paclitaxel), cardiotoxicity (Trastuzumab). Tumour assessment after neoadjuvant (MRI or clinical exam).',
    'You will receive 8 cycles of chemotherapy over about 5 months. The first 4 are stronger (AC) and require an injection to protect your white blood cells. The next 12 weeks combine a weekly chemotherapy with two targeted therapies that specifically fight HER2-positive cancer. Hair loss is expected — it will grow back after treatment. The targeted therapy can affect heart function, so we will check your heart with an echo scan regularly. Report any shortness of breath, new cough, or swelling in legs immediately. Eat well, stay active, and attend all your appointments.',
    'Medical oncology: every 2 weeks during AC, weekly during Paclitaxel. Echo monitoring as above. Surgery clinic referral after neoadjuvant completion (week 18-20). Fertility preservation counselling BEFORE first cycle (urgent if not yet discussed). Radiation oncology referral post-surgery. Support groups and psychosocial support.',
    'The AC-THP regimen has transformed outcomes for HER2+ breast cancer — pCR (pathological complete response) rates are 40-60%, and 5-year survival exceeds 85% with appropriate therapy. Trastuzumab targets the HER2 receptor and has reduced HER2+ breast cancer mortality by 33%. Pertuzumab adds further benefit by preventing HER2-HER3 heterodimerisation (CLEOPATRA trial). In Kenya, biosimilar trastuzumab (e.g., Ogivri) is available at significantly lower cost through KEMSA and some NHIF-covered facilities. Cardiotoxicity from Trastuzumab is typically reversible if detected early — EF monitoring is mandatory. Dose-dense AC requires G-CSF support due to >20% febrile neutropenia risk.',
    ['NCCN Guidelines: Breast Cancer', 'ESMO Guidelines: HER2+ Breast Cancer', 'Kenya Cancer Treatment Guidelines', 'CLEOPATRA Trial (NEJM 2012)'],
  ),
  t('Oncology', 'Oncology', 'Cervical Cancer', 'Chemotherapy-Induced Nausea and Vomiting (CINV) in a Patient Receiving Cisplatin for Cervical Cancer', 'Intermediate',
    'Severe nausea and vomiting during and after cisplatin-based chemotherapy',
    '{name}, a {age}-year-old {occupation} from {location}, is receiving her 2nd cycle of concurrent chemoradiation for locally advanced cervical cancer (FIGO Stage IIB). She is on Cisplatin 40mg/m2 weekly (5 cycles) as radiosensitiser plus external beam radiotherapy. After cycle 1, she experienced severe nausea and vomiting — both acute (within 24 hours) and delayed (days 2-5). She was admitted for IV fluids and antiemetics after cycle 1. Now preparing for cycle 2 and wants to avoid a repeat of the vomiting. Reports she was unable to eat for 4 days after cycle 1, lost 3 kg, and felt too weak to attend radiation sessions on 2 of 5 days.',
    'Cervical Cancer Stage IIB (diagnosed 4 weeks ago). No other significant PMH. HPV 16 positive. No prior chemotherapy.',
    'Ondansetron 8mg IV pre-chemotherapy (given at last cycle — inadequate). Metoclopramide 10mg TID PRN. Paracetamol.',
    'Mildly dehydrated appearance (last cycle). BMI 22 (down from 25 at diagnosis — 3 kg weight loss). Oral mucosa: mild mucositis (Grade 1). Abdomen: soft. Pelvic exam: cervical mass responding to chemoradiation (partial response). ECOG 1.',
    'Hb 11.5. WBC 5.2. Platelets 220. Cr 0.7. Na+ 135, K+ 3.6. Mg2+ 1.7 (low — cisplatin-induced hypomagnesaemia). LFTs normal.',
    'CT chest/abdomen/pelvis (baseline): locally advanced cervical mass, no distant metastases. ECG: normal QTc.',
    'Chemotherapy-Induced Nausea and Vomiting (CINV) — High Emetic Risk (Cisplatin-Based Regimen) in Locally Advanced Cervical Cancer',
    ['CINV (high emetic risk)', 'Opioid-induced nausea', 'Infection-related nausea', 'Brain metastases', 'Intestinal obstruction'],
    'Achieve complete emetic control (no nausea, no vomiting) during and after chemotherapy, maintain hydration and nutritional status, ensure patient completes full chemoradiation course without treatment delays, improve quality of life',
    '1. HIGH EMETIC RISK protocol (cisplatin ≥50mg/m2 = high risk; this patient receives 40mg/m2 weekly but cumulative dose and individual sensitivity classify as high risk given her prior severe CINV): Triple antiemetic prophylaxis: a) NK1 Receptor Antagonist: Aprepitant 125mg PO 1 hour before chemo Day 1, then 80mg PO Days 2-3. b) 5-HT3 Receptor Antagonist: Ondansetron 16mg IV (or 24mg PO) 30 minutes before cisplatin — higher dose than standard 8mg due to prior treatment failure. c) Dexamethasone 12mg IV before chemo, then 8mg PO Days 2-4. 2. For cycle 2: ADD Palonosetron 0.25mg IV (long-acting 5-HT3 RA, superior for delayed CINV) instead of or in addition to ondansetron. 3. BREAKTHROUGH nausea (if occurs despite prophylaxis): add Prochlorperazine 10mg PO/IM q6h PRN or Metoclopramide 10mg PO/IV q6h (avoid metocloprazole — extrapyramidal risk with prochlorperazine). 4. Delayed CINV (days 2-5): continue Dexamethasone 8mg PO Days 2-4 + Aprepitant 80mg Days 2-3. 5. If still refractory: consider Olanzapine 10mg daily for 3 days (emerging evidence for refractory CINV). 6. Ensure adequate hydration: IV normal saline 1-2L pre/post cisplatin. Electrolyte replacement: Mg2+ and K+ supplementation.',
    'Small, frequent meals (6-8 per day). Avoid strong-smelling, greasy, spicy foods. Ginger tea (traditional remedy with evidence). Cold or room-temperature foods (less odour). Avoid lying flat for 1 hour after eating. Oral hygiene (rinsing mouth before meals). Acupressure wrist bands (P6 point). Adequate rest before chemotherapy sessions.',
    'Pre-medicate: Aprepitant 125mg PO at 10am (1 hour before), Palonosetron 0.25mg IV at 11am, Dexamethasone 12mg IV at 11:30am, Cisplatin 40mg/m2 IV over 1-2 hours. Post-chemo: Ondansetron 8mg IV q8h for 24h, Dexamethasone 8mg PO Days 2-4, Aprepitant 80mg PO Days 2-3. Home antiemetics: Prochlorperazine 10mg PO q6h PRN. IV fluids at home if available (normal saline 1L). Review Day 3 for hydration status and breakthrough nausea. Weight and oral intake assessment.',
    '1. High emetic risk regimen with prior CINV failure on standard prophylaxis — needs escalated triple antiemetic regimen. 2. Delayed CINV is the most common reason for treatment delays in cervical cancer chemoradiation. 3. Inadequate emetic control leads to dehydration, malnutrition, treatment delays, and reduced survival.',
    'Nausea and vomiting assessment (CTCAE grade) before each radiation session. Weight: daily during chemoradiation (any loss >2% in a week requires intervention). Electrolytes (Mg2+, K+, Na+) before each cisplatin cycle (hypomagnesaemia is cumulative). Renal function (cisplatin nephrotoxicity). Hydration status (mucous membranes, skin turgor, urine output). Oral intake diary.',
    'The most important thing is to take your anti-sickness medicines PREVENTIVELY — before the nausea starts. Once vomiting begins, it is much harder to control. Take the tablets exactly as prescribed, even on days you feel well. If you vomit within 1 hour of taking oral antiemetics, contact us immediately — you may need an injection. Small, frequent meals are better than large meals. Avoid foods with strong smells. Ginger tea may help. Keep a food and nausea diary to help us adjust your medications. Do not skip your radiation because of nausea — we can manage this.',
    'Oncology Day Unit: before each weekly cisplatin cycle. Radiation oncology: daily during chemoradiation (5 days/week, 5-6 weeks). Dietitian review if weight loss >5%. GP for hydration support between cycles if needed. Psycho-oncology referral for anxiety related to CINV.',
    'Cisplatin is the most emetogenic chemotherapy agent (emetic risk >90% without prophylaxis). The 3-drug antiemetic regimen (NK1 RA + 5-HT3 RA + Dexamethasone) is the standard of care for high emetogenic chemotherapy. Aprepitant (NK1 RA) blocks substance P in the brainstem vomiting centre and is superior to 5-HT3 RA alone for delayed CINV. Palonosetron has a longer half-life than ondansetron and is more effective for delayed CINV. In Kenya, Aprepitant availability may be limited — when unavailable, high-dose dexamethasone + ondansetron is the fallback. Olanzapine 10mg for 3 days is a low-cost, effective adjunct for refractory CINV. Cervical cancer chemoradiation requires 5 weekly cisplatin cycles — adequate emetic control is essential to prevent treatment delays that compromise outcomes.',
    ['NCCN Guidelines: Antiemesis', 'ASCO Antiemetic Guidelines', 'Kenya Clinical Guidelines: Oncology Supportive Care', 'MASCC/ESMO Antiemetic Guidelines 2023'],
  ),
];
