// ================================================================
// Ophthalmology — Case Templates (5 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const OPHTHALMOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Ophthalmology', 'Ophthalmology', 'Open Angle Glaucoma', 'Newly Diagnosed Open-Angle Glaucoma in a Hypertensive Patient', 'Intermediate',
    'Gradual loss of peripheral vision over the past year, now bumping into door frames',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive, painless loss of peripheral vision over 12 months, first noticed when bumping into objects on the side. Also reports difficulty seeing at night. No eye pain, redness, or halos around lights. No sudden vision loss. Eye exam: IOP elevated. Previously treated for hypertension.',
    'Hypertension (well-controlled). No known DM. No prior eye surgery. Family history: father had glaucoma.',
    'Amlodipine 5mg daily, Hydrochlorothiazide 25mg daily. No current eye drops.',
    'VA: R 6/9, L 6/9 (best corrected). IOP: R 28 mmHg, L 26 mmHg (normal 10-21). Gonioscopy: open angles bilaterally. Optic disc cupping: vertical cup-to-disc ratio 0.8 R, 0.7 L (increased). Visual field: bilateral arcuate scotomas (inferior and superior). Cornea: clear. Anterior chamber: deep and quiet.',
    'No specific labs required for diagnosis. If starting Acetazolamide: check K+, bicarbonate, baseline renal function.',
    'OCT (Optical Coherence Tomography): reduced retinal nerve fibre layer (RNFL) thickness in both eyes — inferior and superior quadrants.',
    'Primary Open-Angle Glaucoma (POAG), Moderate-Stage Bilateral',
    ['Primary Open-Angle Glaucoma', 'Ocular Hypertension (elevated IOP but no disc/field damage)', 'Angle-Closure Glaucoma (excluded by gonioscopy)', 'Normal Tension Glaucoma', 'Secondary Glaucoma'],
    'Lower IOP to target (target <18 mmHg), preserve remaining vision, prevent progression to blindness, lifelong adherence',
    '1. First-line (prostaglandin analogue): Latanoprost 0.005% eye drops once daily at night (most effective, once daily, well-tolerated). 2. If IOP not at target after 4-6 weeks, add: Timolol 0.5% (beta-blocker) BID. Or Dorzolamide 2% TID (carbonic anhydrase inhibitor). Or Brimonidine 0.2% BID (alpha-2 agonist). 3. If IOP still elevated: fixed combination drops (e.g., Latanoprost/Timolol) to improve adherence. 4. If maximal medical therapy fails AND IOP remains elevated with progression: Laser Trabeculoplasty (SLT) or Trabeculectomy (surgery). 5. Avoid systemic carbonic anhydrase inhibitors (Acetazolamide) for chronic use (side effects). Reserve for acute IOP elevation.',
    'Avoid activities that raise IOP: heavy lifting, head-down positions, Valsalva manoeuvre. Eye protection. Driving: report to licensing authority (visual field loss may affect driving ability).',
    'Start Latanoprost 0.005% at night. Teach proper eye drop instillation technique (punctal occlusion to reduce systemic absorption). Review in 4-6 weeks to check IOP. If IOP target not reached, add Timolol 0.5% BID. Continue monitoring visual fields and optic disc annually.',
    '1. New diagnosis of POAG with moderate field loss — needs consistent treatment to prevent progression. 2. Requires long-term monitoring and medication adherence.',
    'IOP measurement at each visit. Visual field testing every 6-12 months. Optic disc photography/OCT annually. Check adherence and technique at each visit. Monitor for side effects: Latanoprost (conjunctival hyperaemia, increased iris pigmentation, eyelash growth), Timolol (bradycardia, bronchospasm — caution in asthma/COPD).',
    'Glaucoma is a lifelong condition. The drops do not cure glaucoma — they control it. You must take them every day even if your vision feels fine. Most people with glaucoma never go blind if they take treatment. The drops work best when taken consistently. Once vision is lost, it cannot be restored — the goal is to prevent further loss.',
    'Ophthalmology clinic: 4-6 weeks for IOP check, then every 3-12 months depending on control. If progression despite medical therapy: refer for SLT or trabeculectomy. Annual visual fields. Inform family members to get screened for glaucoma.',
    'Glaucoma is the leading cause of irreversible blindness worldwide. POAG is asymptomatic until late stages — by the time patients notice vision loss, significant damage has occurred. The ONLY modifiable risk factor is IOP. A single missed dose of Latanoprost can cause IOP to rise within 24 hours. Punctal occlusion after drop instillation reduces systemic absorption by 60-70%. Prostaglandin analogues are first-line because of superior IOP-lowering efficacy, once-daily dosing, and minimal systemic side effects. Beta-blockers (Timolol) must be used with caution in patients with asthma, COPD, or bradycardia.',
    ['AAO Guidelines: Primary Open-Angle Glaucoma', 'NICE Guidelines: Glaucoma', 'Kenya Clinical Guidelines: Ophthalmology'],
  ),
  t('Ophthalmology', 'Ophthalmology', 'Bacterial Conjunctivitis', 'Acute Bacterial Conjunctivitis in a School-Aged Child', 'Beginner',
    'Red, sticky, crusted eye with purulent discharge for 3 days',
    '{name}, a {age}-year-old child from {location}, presents with acute onset (3 days) of red, irritated right eye with thick, purulent yellow-green discharge. Eyelids are crusted shut upon waking. Reports mild discomfort but no significant pain, photophobia, or blurred vision. No trauma or foreign body. Left eye now starting to show similar symptoms. Several classmates have had "pink eye" in the past 2 weeks.',
    'No significant PMH. No known drug allergies. No contact lens use.',
    'No regular medications. No recent antibiotic use.',
    'Right eye: diffuse conjunctival injection (redness), moderate purulent discharge, eyelid oedema and crusting. Left eye: mild conjunctival injection. Cornea: clear OU, no fluorescein uptake (no keratitis). No preauricular lymphadenopathy (more common in viral conjunctivitis). VA: normal (6/6 OU).',
    'No specific labs required. If recurrent or atypical: conjunctival swab for culture and Gram stain.',
    'No imaging indicated.',
    'Acute Purulent Bacterial Conjunctivitis (Mucopurulent Conjunctivitis) — likely Staph aureus or H. influenzae',
    ['Bacterial Conjunctivitis', 'Viral Conjunctivitis (more watery, less purulent, preauricular node)', 'Allergic Conjunctivitis (itching, clear discharge)', 'Chemical Conjunctivitis', 'Keratitis (corneal involvement — pain, photophobia, fluorescein+)'],
    'Eradicate infection, reduce contagion, prevent complications (corneal involvement, recurrent infections)',
    '1. Topical antibiotic (first-line): Chloramphenicol 0.5% eye drops — 1-2 drops q2h for 2 days, then q4h for 5-7 days. OR Fusidic Acid 1% gel — BID for 7 days (less frequent, cream-based — good for children). 2. Alternative (if allergy or MRSA): Ciprofloxacin 0.3% or Ofloxacin 0.3% eye drops q2-6h. 3. Cleaning: Gently cleanse eyelids with sterile saline or clean water. 4. No role for systemic antibiotics in simple conjunctivitis.',
    'Hand hygiene — wash hands before and after touching eyes. Do not share towels, pillows, or eye drops. Stay home from school until 24 hours after starting treatment. Dispose of eye makeup. Do not patch the eye (can worsen infection).',
    'Start Chloramphenicol 0.5% eye drops q2h for 2 days then q4h. Educate on hygiene and contagion. Review in 3 days if not improving. If worsening (pain, photophobia, decreased vision) — refer to ophthalmology.',
    '1. Common infectious conjunctivitis in school-aged child with close contact history. 2. Self-limiting but antibiotics reduce duration and prevent spread.',
    'Symptoms daily (pain, redness, discharge). If not improved by 72 hours: consider alternative diagnosis, culture, or refer. Contact lens wearers require urgent ophthalmology review (risk of Pseudomonas keratitis).',
    'Pink eye is highly contagious. Wash your hands often and do not touch or rub your eyes. Use a clean towel each day and do not share with family members. The drops go into the eye — do not touch the tip to the eye or eyelashes. You can return to school 24 hours after starting treatment.',
    'Follow-up only if not improving in 3 days. If recurrent: consider nasolacrimal duct obstruction (irrigate) or chronic infection (culture).',
    'Simple bacterial conjunctivitis is often self-limiting (7-10 days) but topical antibiotics reduce duration to 2-5 days and reduce contagion. Chloramphenicol is widely used in Kenya and is effective against most gram-positive pathogens. However, Fusidic Acid has better compliance (BID vs frequent drops). The main differential is viral conjunctivitis — more watery discharge, preauricular lymphadenopathy, and often follows an upper respiratory infection. Contact lens wearers are at high risk for Pseudomonas keratitis — a vision-threatening emergency. ALWAYS check for corneal involvement (fluorescein) if the patient reports pain or photophobia.',
    ['WHO: Conjunctivitis Guidelines', 'Kenya Clinical Guidelines: Ophthalmology', 'NICE Guidelines: Conjunctivitis'],
  ),
];
