// ================================================================
// Ophthalmology — Case Templates (4 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const OPHTHALMOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Ophthalmology', 'Ophthalmology', 'Open Angle Glaucoma', 'Newly Diagnosed Open-Angle Glaucoma in a Hypertensive Patient', 'Intermediate',
    'Gradual loss of peripheral vision over the past year, now bumping into door frames',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive, painless loss of peripheral vision over 12 months, first noticed when bumping into objects on the side. Also reports difficulty seeing at night. No eye pain, redness, or halos around lights. No sudden vision loss. Eye exam: IOP elevated. Previously treated for hypertension.',
    'Hypertension (well-controlled). No known DM. No prior eye surgery. Family history: father had glaucoma.',
    'Amlodipine 5mg daily, Hydrochlorothiazide 25mg daily. No current eye drops.',
    'VA: R 6/9, L 6/9 (best corrected). IOP: R 28 mmHg, L 26 mmHg (normal 10-21). Gonioscopy: open angles bilaterally. Optic disc cupping: vertical cup-to-disc ratio 0.8 R, 0.7 L (increased). Visual field: bilateral arcuate scotomas (inferior and superior). Cornea: clear. Anterior chamber: deep and quiet.',
    'No specific labs required for diagnosis. If starting Acetazolamide: check K+, bicarbonate, baseline renal function.',
    'OCT (Optical Coherence Tomography): reduced retinal nerve fibre layer (RNFL) thickness in both eyes — inferior and superior quadrants.',
    'Primary Open-Angle Glaucoma (POAG), Moderate-Stage Bilateral',
    ['Primary Open-Angle Glaucoma', 'Ocular Hypertension (elevated IOP but no disc/field damage)', 'Angle-Closure Glaucoma (excluded by gonioscopy)', 'Normal Tension Glaucoma', 'Secondary Glaucoma'],
    'Lower IOP to target (target <18 mmHg), preserve remaining vision, prevent progression to blindness, lifelong adherence',
    '1. First-line (prostaglandin analogue): Latanoprost 0.005% eye drops once daily at night (most effective, once daily, well-tolerated). 2. If IOP not at target after 4-6 weeks, add: Timolol 0.5% (beta-blocker) BID. Or Dorzolamide 2% TID (carbonic anhydrase inhibitor). Or Brimonidine 0.2% BID (alpha-2 agonist). 3. If IOP still elevated: fixed combination drops (e.g., Latanoprost/Timolol) to improve adherence. 4. If maximal medical therapy fails AND IOP remains elevated with progression: Laser Trabeculoplasty (SLT) or Trabeculectomy (surgery). 5. Avoid systemic carbonic anhydrase inhibitors (Acetazolamide) for chronic use (side effects). Reserve for acute IOP elevation.',
    'Avoid activities that raise IOP: heavy lifting, head-down positions, Valsalva manoeuvre. Eye protection. Driving: report to licensing authority (visual field loss may affect driving ability).',
    'Start Latanoprost 0.005% at night. Teach proper eye drop instillation technique (punctal occlusion to reduce systemic absorption). Review in 4-6 weeks to check IOP. If IOP target not reached, add Timolol 0.5% BID. Continue monitoring visual fields and optic disc annually.',
    '1. New diagnosis of POAG with moderate field loss — needs consistent treatment to prevent progression. 2. Requires long-term monitoring and medication adherence.',
    'IOP measurement at each visit. Visual field testing every 6-12 months. Optic disc photography/OCT annually. Check adherence and technique at each visit. Monitor for side effects: Latanoprost (conjunctival hyperaemia, increased iris pigmentation, eyelash growth), Timolol (bradycardia, bronchospasm — caution in asthma/COPD).',
    'Glaucoma is a lifelong condition. The drops do not cure glaucoma — they control it. You must take them every day even if your vision feels fine. Most people with glaucoma never go blind if they take treatment. The drops work best when taken consistently. Once vision is lost, it cannot be restored — the goal is to prevent further loss.',
    'Ophthalmology clinic: 4-6 weeks for IOP check, then every 3-12 months depending on control. If progression despite medical therapy: refer for SLT or trabeculectomy. Annual visual fields. Inform family members to get screened for glaucoma.',
    'Glaucoma is the leading cause of irreversible blindness worldwide. POAG is asymptomatic until late stages — by the time patients notice vision loss, significant damage has occurred. The ONLY modifiable risk factor is IOP. A single missed dose of Latanoprost can cause IOP to rise within 24 hours. Punctal occlusion after drop instillation reduces systemic absorption by 60-70%. Prostaglandin analogues are first-line because of superior IOP-lowering efficacy, once-daily dosing, and minimal systemic side effects. Beta-blockers (Timolol) must be used with caution in patients with asthma, COPD, or bradycardia.',
    ['AAO Guidelines: Primary Open-Angle Glaucoma', 'NICE Guidelines: Glaucoma', 'Kenya Clinical Guidelines: Ophthalmology'],
  ),
  t('Ophthalmology', 'Ophthalmology', 'Bacterial Conjunctivitis', 'Acute Bacterial Conjunctivitis in a School-Aged Child', 'Beginner',
    'Red, sticky, crusted eye with purulent discharge for 3 days',
    '{name}, a {age}-year-old child from {location}, presents with acute onset (3 days) of red, irritated right eye with thick, purulent yellow-green discharge. Eyelids are crusted shut upon waking. Reports mild discomfort but no significant pain, photophobia, or blurred vision. No trauma or foreign body. Left eye now starting to show similar symptoms. Several classmates have had "pink eye" in the past 2 weeks.',
    'No significant PMH. No known drug allergies. No contact lens use.',
    'No regular medications. No recent antibiotic use.',
    'Right eye: diffuse conjunctival injection (redness), moderate purulent discharge, eyelid oedema and crusting. Left eye: mild conjunctival injection. Cornea: clear OU, no fluorescein uptake (no keratitis). No preauricular lymphadenopathy (more common in viral conjunctivitis). VA: normal (6/6 OU).',
    'No specific labs required. If recurrent or atypical: conjunctival swab for culture and Gram stain.',
    'No imaging indicated.',
    'Acute Purulent Bacterial Conjunctivitis (Mucopurulent Conjunctivitis) — likely Staph aureus or H. influenzae',
    ['Bacterial Conjunctivitis', 'Viral Conjunctivitis (more watery, less purulent, preauricular node)', 'Allergic Conjunctivitis (itching, clear discharge)', 'Chemical Conjunctivitis', 'Keratitis (corneal involvement — pain, photophobia, fluorescein+)'],
    'Eradicate infection, reduce contagion, prevent complications (corneal involvement, recurrent infections)',
    '1. Topical antibiotic (first-line): Chloramphenicol 0.5% eye drops — 1-2 drops q2h for 2 days, then q4h for 5-7 days. OR Fusidic Acid 1% gel — BID for 7 days (less frequent, cream-based — good for children). 2. Alternative (if allergy or MRSA): Ciprofloxacin 0.3% or Ofloxacin 0.3% eye drops q2-6h. 3. Cleaning: Gently cleanse eyelids with sterile saline or clean water. 4. No role for systemic antibiotics in simple conjunctivitis.',
    'Hand hygiene — wash hands before and after touching eyes. Do not share towels, pillows, or eye drops. Stay home from school until 24 hours after starting treatment. Dispose of eye makeup. Do not patch the eye (can worsen infection).',
    'Start Chloramphenicol 0.5% eye drops q2h for 2 days then q4h. Educate on hygiene and contagion. Review in 3 days if not improving. If worsening (pain, photophobia, decreased vision) — refer to ophthalmology.',
    '1. Common infectious conjunctivitis in school-aged child with close contact history. 2. Self-limiting but antibiotics reduce duration and prevent spread.',
    'Symptoms daily (pain, redness, discharge). If not improved by 72 hours: consider alternative diagnosis, culture, or refer. Contact lens wearers require urgent ophthalmology review (risk of Pseudomonas keratitis).',
    'Pink eye is highly contagious. Wash your hands often and do not touch or rub your eyes. Use a clean towel each day and do not share with family members. The drops go into the eye — do not touch the tip to the eye or eyelashes. You can return to school 24 hours after starting treatment.',
    'Follow-up only if not improving in 3 days. If recurrent: consider nasolacrimal duct obstruction (irrigate) or chronic infection (culture).',
    'Simple bacterial conjunctivitis is often self-limiting (7-10 days) but topical antibiotics reduce duration to 2-5 days and reduce contagion. Chloramphenicol is widely used in Kenya and is effective against most gram-positive pathogens. However, Fusidic Acid has better compliance (BID vs frequent drops). The main differential is viral conjunctivitis — more watery discharge, preauricular lymphadenopathy, and often follows an upper respiratory infection. Contact lens wearers are at high risk for Pseudomonas keratitis — a vision-threatening emergency. ALWAYS check for corneal involvement (fluorescein) if the patient reports pain or photophobia.',
    ['WHO: Conjunctivitis Guidelines', 'Kenya Clinical Guidelines: Ophthalmology', 'NICE Guidelines: Conjunctivitis'],
  ),
  t('Ophthalmology', 'Ophthalmology', 'Primary Open-Angle Glaucoma', 'Glaucoma with Progressive Visual Field Loss Requiring Escalation', 'Intermediate',
    'Gradual worsening of peripheral vision over the past 2 years, now trouble navigating busy markets',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 2-year history of gradually worsening peripheral vision, now difficulty navigating crowded spaces and occasionally bumping into objects on the left side. Reports no eye pain, redness, or sudden vision changes. Denies halos or coloured rings around lights. Was diagnosed with glaucoma 18 months ago at a local eye camp and was started on eye drops but admits to poor adherence ("sometimes I forget for a week"). No history of eye surgery or trauma.',
    'Hypertension (on medication). No diabetes. No prior ocular surgery. Family history: elder brother was diagnosed with glaucoma.',
    'Amlodipine 5mg daily, Latanoprost 0.005% eye drops at bedtime (self-reported adherence: intermittent).',
    'VA: R 6/12, L 6/18 (best corrected). IOP: R 28 mmHg, L 26 mmHg (on current therapy — above target). Gonioscopy: open angles bilaterally. Optic disc: vertical cup-to-disc ratio 0.8 R, 0.85 L with bayoneting of vessels, nasal shift, and disc haemorrhage noted on left eye. Visual field (Humphrey 24-2): bilateral superior and inferior arcuate scotomas, more advanced on the left. Cornea clear. Anterior chamber deep. Pachymetry: R 540 microns, L 530 microns.',
    'No systemic labs required. If considering topical beta-blocker: heart rate, respiratory history. Renal function if oral acetazolamide considered.',
    'OCT: Marked bilateral RNFL thinning, worse superiorly and inferiorly. Macular ganglion cell analysis: diffuse thinning bilaterally consistent with advanced glaucomatous damage.',
    'Primary Open-Angle Glaucoma, Advanced Bilateral with Inadequate IOP Control on Monotherapy',
    ['Primary Open-Angle Glaucoma', 'Normal Tension Glaucoma', 'Secondary Glaucoma (pigmentary, pseudoexfoliation)', 'Ocular Hypertension', 'Angle-Closure Glaucoma (excluded by gonioscopy)'],
    'Achieve target IOP <18 mmHg (or 30% reduction from baseline), halt visual field progression, preserve remaining vision, improve adherence',
    '1. Continue Latanoprost 0.005% at bedtime (prostaglandin analogue — first-line, most effective IOP lowering). 2. ADD Timolol 0.5% eye drops BID (beta-blocker, second agent). Warn: avoid in asthma, COPD, bradycardia. Counsel on punctal occlusion to reduce systemic absorption. 3. If IOP still above target after 4-6 weeks of dual therapy: add Dorzolamide 2% TID (carbonic anhydrase inhibitor) or Brimonidine 0.2% BID (alpha-2 agonist). 4. Fixed combination drops (e.g., Timolol/Dorzolamide) to reduce pill/drop burden and improve adherence. 5. If maximal medical therapy (3 agents) fails to control IOP: refer for laser trabeculoplasty (SLT) or surgical trabeculectomy. 6. Consider short course of oral Acetazolamide 250mg BID if acute IOP control needed (monitor for paraesthesia, metabolic acidosis, hypokalaemia).',
    'Proper drop instillation technique with punctal occlusion (press inner corner of eye for 2 minutes after drop). Avoid heavy lifting and head-down positions. Eye protection in dusty environments. Adequate hydration.',
    'Add Timolol 0.5% BID to existing Latanoprost. Reinforce adherence: once-daily dosing of Latanoprost is key advantage. Educate that vision lost to glaucoma cannot be restored — treatment prevents further loss. Review IOP in 4-6 weeks. If target not met, add third agent. Refer for SLT if triple therapy insufficient.',
    '1. Advanced bilateral POAG with suboptimal IOP control due to medication non-adherence. 2. Disc haemorrhage indicates active disease progression requiring urgent IOP optimisation. 3. Need for long-term monitoring and adherence reinforcement.',
    'IOP at each visit (target <18 mmHg). Visual field testing every 6 months (compare with baseline). OCT RNFL annually. Optic disc photography every 6-12 months. Monitor for Timolol side effects: bradycardia, bronchospasm, fatigue, reduced exercise tolerance. Monitor for Latanoprost side effects: conjunctival hyperaemia, iris pigmentation changes (irreversible — counsel patient), eyelash growth.',
    'Glaucoma is called the "silent thief of sight" because you lose peripheral vision without noticing until it is advanced. Your drops must be taken every single day — even one week of missed drops can allow IOP to rise and cause further permanent damage. Latanoprost works best at night. When you put in the Timolol drops, press the inner corner of your eye for 2 minutes to prevent it entering your bloodstream. Once vision is lost from glaucoma, it cannot be restored — we are preventing further loss.',
    'Ophthalmology clinic: 4-6 weeks for IOP recheck after adding Timolol, then every 3 months for monitoring. If IOP not controlled on 3 agents: refer for SLT or trabeculectomy. Annual visual fields and OCT. Screen first-degree relatives for glaucoma (2-4x increased risk with family history).',
    'POAG is the most common type of glaucoma worldwide and the leading cause of irreversible blindness. Risk factors: elevated IOP, age >40, family history, African descent, myopia, thin corneas. The "30% rule": target IOP is 30% below untreated baseline IOP. Adherence is the greatest challenge in glaucoma management — once-daily prostaglandin analogues have better adherence than BID/TID regimens. Timolol is contraindicated in asthma and severe COPD due to beta-2 blockade causing bronchospasm. Disc haemorrhage is a sign of disease progression, not just a finding — it precedes visual field loss. In Kenya, glaucoma accounts for approximately 15-20% of blindness cases, and many patients present late with advanced disease.',
    ['AAO Guidelines: Primary Open-Angle Glaucoma', 'NICE Guidelines: Glaucoma (NG81)', 'Kenya Clinical Guidelines: Ophthalmology'],
  ),
  t('Ophthalmology', 'Ophthalmology', 'Bacterial Conjunctivitis', 'Bacterial Conjunctivitis in a Young Child with Crusted Eyelids', 'Beginner',
    'Red, sticky eyes with yellow-green discharge for 4 days, eyelids crusted shut on waking',
    '{name}, a {age}-year-old child from {location}, presents with a 4-day history of bilateral red eyes with thick, purulent yellow-green discharge. Mother reports the child wakes up with eyelids crusted shut and needs to be cleaned with warm water before opening. The child complains of a "sandy" feeling in both eyes but denies pain or difficulty seeing. No history of trauma, foreign body, or contact lens use. Several children at school have had similar red eyes in the past 2 weeks. No fever, no cough, no respiratory symptoms.',
    'No significant PMH. No known drug allergies. Fully immunised for age.',
    'No regular medications. No recent antibiotic use.',
    'Both eyes: bilateral diffuse conjunctival injection with moderate purulent mucopurulent discharge. Eyelid oedema present bilaterally, worse in the mornings. Cornea: clear bilaterally, no fluorescein staining (no epithelial defect or keratitis). No preauricular lymphadenopathy. No chemosis. VA: child cooperates for basic testing — appears normal bilaterally. Pupils: equal, round, reactive.',
    'No labs required for straightforward bacterial conjunctivitis. If recurrent or not responding to treatment: conjunctival swab for culture and sensitivity, Gram stain.',
    'No imaging indicated.',
    'Acute Bacterial Conjunctivitis (Mucopurulent Type) — likely Staphylococcus aureus or Haemophilus influenzae',
    ['Bacterial Conjunctivitis', 'Viral Conjunctivitis (watery discharge, preauricular lymphadenopathy, often unilateral initially)', 'Allergic Conjunctivitis (itching, clear/watery discharge, papillae on everting lids)', 'Chlamydial Conjunctivitis (chronic, inclusion conjunctivitis)', 'Keratoconjunctivitis (corneal involvement — pain, photophobia, reduced VA)'],
    'Eradicate infection within 5-7 days, reduce contagion, prevent complications (keratitis, secondary infection), educate parents on hygiene',
    '1. Topical antibiotic (first-line): Chloramphenicol 0.5% eye drops — 1-2 drops in affected eye(s) every 2 hours while awake for the first 2 days, then every 4 hours for 5-7 days (total 7-day course). 2. Alternative: Fusidic Acid 1% eye ointment — apply a small strip (约5mm) inside the lower eyelid BID for 7 days (better for young children — less frequent dosing, cream formulation). 3. If severe or not responding: Ciprofloxacin 0.3% drops q2-6h (covers broader spectrum including Pseudomonas). 4. For crusting: clean eyelids gently with warm damp cotton wool before applying drops. 5. No role for oral antibiotics in simple conjunctivitis. 6. Both eyes should be treated even if one appears less affected (infection spreads easily between eyes).',
    'Strict hand hygiene — wash hands with soap before and after touching the child\'s eyes. Use separate towels, flannels, and pillowcases. Do not share eye drops with other family members. Clean discharge with separate cotton wool for each eye. Keep the child home from school/daycare until 24 hours after starting antibiotic drops. Dispose of old discharge cloths safely. Avoid swimming pools until conjunctivitis resolved.',
    'Start Chloramphenicol 0.5% drops (or Fusidic Acid ointment) in both eyes. Educate mother on eyelid cleaning technique and hand hygiene. Counsel on when to return: if no improvement in 48 hours, if pain develops, if photophobia occurs, or if vision becomes blurred. Review at 7 days or sooner if worsening. Check for corneal involvement (fluorescein) if pain or photophobia develops at any point.',
    '1. Common childhood infectious conjunctivitis in school setting with close contact. 2. Self-limiting but antibiotics shorten duration and reduce transmission. 3. Parent education critical for hygiene compliance and preventing spread.',
    'Symptom improvement expected within 48-72 hours of starting antibiotics. If no improvement by 48 hours: review diagnosis, consider culture, or alternative organism (may need fluoroquinolone drops). Check daily for: pain (suggests keratitis), photophobia (suggests anterior uveitis or keratitis), decreased vision (serious — refer urgently). Contact lens wearers (if applicable) require urgent ophthalmology referral to rule out Pseudomonas aeruginosa keratitis.',
    'The eye drops are safe for your child. Clean the crusty discharge with warm water and cotton wool before putting the drops in. Wash your hands every time before and after touching the eyes. Your child can return to school 24 hours after starting the drops. Use a separate towel and do not share it with other children. If the eyes do not improve in 2 days, or if your child develops pain or sensitivity to light, come back immediately.',
    'Follow-up at 7 days if no improvement. If recurrent bacterial conjunctivitis (>3 episodes in 6 months): consider nasolacrimal duct obstruction (especially in younger children — may need probing), chronic blepharitis, or allergic component. Screen household members for asymptomatic carriage (especially Staph aureus).',
    'Simple bacterial conjunctivitis is self-limiting (7-10 days without treatment) but topical antibiotics reduce duration to 2-5 days and significantly reduce contagion. Chloramphenicol is widely available and affordable in Kenya. Fusidic Acid has better compliance (BID dosing vs QID) and is preferred for young children. The key differential is viral conjunctivitis — more watery discharge, preauricular lymphadenopathy, and often follows an upper respiratory infection. NEVER patch an infected eye — occlusion promotes bacterial growth. Contact lens wearers are at risk for Pseudomonas keratitis, a sight-threatening emergency requiring urgent ophthalmology review and fluoroquinolone therapy. In Kenya, trachoma (Chlamydia trachomatis) should be considered in chronic cases, especially in rural areas with limited sanitation.',
    ['WHO: Conjunctivitis Guidelines', 'Kenya Clinical Guidelines: Ophthalmology', 'NICE Guidelines: Conjunctivitis (CK90)'],
  ),
];
