// ================================================================
// Pain & Inflammation — Case Templates
// 5 templates covering: Acute Pain, Chronic Pain, Rheumatoid
// Arthritis, Osteoarthritis, Gout
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';
function tpl(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}

export const PAIN_INFLAMMATION_TEMPLATES: ClinicalCaseTemplate[] = [
  tpl('Pain & Inflammation', 'Orthopaedics', 'Acute Pain', 'Acute Post-Operative Pain Following Fracture Fixation', 'Beginner',
    'Severe left leg pain after surgical fixation of a tibial fracture',
    '{name}, a {age}-year-old {occupation} from {location}, is on Day 1 post open reduction and internal fixation (ORIF) of a left tibial fracture sustained in a road traffic accident. Reports severe pain (8/10) at the surgical site, constant, sharp, worse with movement. Has received IM Diclofenac 75mg 4 hours ago with minimal relief. No fever, no wound discharge.',
    'Previously healthy. No prior surgeries. Non-smoker.',
    'IM Diclofenac 75mg q12h (poor pain control), IV Paracetamol 1g q6h',
    'Left lower leg: surgical wound clean, dry, intact sutures, mild oedema. Distal neurovascular exam intact. Pain on passive movement of ankle. No calf tenderness. No fever.',
    'Hb 11.5 g/dL (post-op drop). WBC 12.0 (post-op leukocytosis). CRP 45. Creatinine 0.9. LFTs normal.',
    'Post-operative X-ray: satisfactory alignment and hardware position.',
    'Acute Post-Operative Pain (Moderate-Severe) Following Tibial ORIF',
    ['Acute Surgical Pain', 'Compartment Syndrome', 'Wound Infection', 'DVT'],
    'Achieve adequate pain control (target pain score <4/10), facilitate early mobilisation, prevent chronic pain, minimise opioid use',
    '1. WHO Analgesic Ladder Step 2 (moderate pain not controlled by Step 1): Add Tramadol 50-100mg PO/IM q6h PRN (max 400mg/day). 2. Continue Paracetamol 1g QID (scheduled, not PRN). 3. Continue Diclofenac 75mg IM/PO BID (max 5-7 days, add PPI cover). 4. If pain still uncontrolled, escalate to WHO Step 3: Morphine 5-10mg PO/SC q4h PRN. 5. Neuropathic component: add Gabapentin 300mg at bedtime (or Pregabalin 75mg BID) if nerve injury suspected. 6. Laxative (Lactulose 15mL BID or Senna) if on opioids. 7. Antiemetic (Ondansetron 4mg TID PRN) for opioid nausea.',
    'Elevation of left leg. Ice packs to surgical site 20 mins on/off. Early physiotherapy for mobilisation. Relaxation techniques. Adequate sleep hygiene.',
    'Review analgesic regimen: switch from PRN to scheduled dosing for better pain control. Add Tramadol. Start PPI. Monitor pain scores q4h. If pain controlled, transition to oral analgesics and prepare for discharge with physiotherapy.',
    '1. Inadequate post-operative pain control requiring escalation of analgesia. 2. Opioid use requires monitoring for side effects (constipation, nausea, respiratory depression).',
    'Pain score (NRS 0-10) at rest and with movement q4h. Sedation score if on opioids. Bowel function chart. Respiratory rate if on morphine. Watch for signs of compartment syndrome (pain out of proportion, paraesthesia, pallor, pulselessness, poikilothermia).',
    'Pain control is important for healing and recovery — do not try to "tough it out." Take pain medications on a schedule (not PRN) for the first few days. As pain improves, we will reduce and stop the stronger medications. Physiotherapy and movement are also important for pain relief. Report any new severe pain, numbness, or tingling.',
    'Orthopaedic clinic in 2 weeks for wound check and X-ray. Continue physiotherapy. Gradually reduce analgesia over 1-2 weeks as pain improves.',
    'The WHO Analgesic Ladder is a stepwise approach: Step 1 (non-opioid ± adjuvant) → Step 2 (weak opioid + non-opioid ± adjuvant) → Step 3 (strong opioid + non-opioid ± adjuvant). Paracetamol and NSAIDs have a ceiling effect — increasing the dose beyond maximum does not increase analgesia. Scheduled dosing is superior to PRN for acute pain. Multimodal analgesia (using drugs with different mechanisms) improves pain control and reduces opioid requirements.',
    ['WHO Guidelines: Pain Management', 'Kenya Clinical Guidelines: Acute Pain', 'BJA: Multimodal Analgesia'],
  ),
  tpl('Pain & Inflammation', 'Rheumatology', 'Rheumatoid Arthritis', 'Active Rheumatoid Arthritis with Disease-Modifying Antirheumatic Drug Initiation', 'Advanced',
    'Painful, swollen joints in both hands and feet, morning stiffness lasting >2 hours for 3 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with symmetrical pain and swelling of the wrists, knuckles (MCP, PIP joints), and feet (MTP joints) for 3 months. Morning stiffness lasts >2 hours. Reports fatigue, low-grade fever, and difficulty performing daily tasks (opening jars, walking). Has been self-medicating with Ibuprofen with minimal relief. No prior joint disease.',
    'No significant PMH. Non-smoker. No family history of autoimmune disease.',
    'Ibuprofen 400mg PRN (ineffective)',
    'Bilateral: swollen, tender MCP joints (2nd-5th), PIP joints, wrists. Positive squeeze test. Bilateral MTP joint tenderness. Mild ulnar deviation not present yet. No rheumatoid nodules. No other organ involvement.',
    'Rheumatoid Factor: positive (145 IU/mL). Anti-CCP: positive (strongly, >200 U/mL). ESR 65 mm/hr. CRP 45 mg/L. Hb 10.5 (anaemia of chronic disease). X-ray hands: juxta-articular osteopenia, no erosions yet (early disease).',
    'X-ray hands and feet: juxta-articular osteopenia, soft tissue swelling. No erosions or joint space narrowing.',
    'Seropositive Rheumatoid Arthritis (Early, Active, Moderate-High Disease Activity — DAS28-ESR 5.8)',
    ['Rheumatoid Arthritis', 'Psoriatic Arthritis', 'Osteoarthritis', 'Systemic Lupus Erythematosus', 'Gouty Arthritis'],
    'Achieve remission or low disease activity (DAS28 <2.6), prevent joint damage, maintain function, improve quality of life',
    '1. Start Methotrexate (first-line DMARD): 7.5-15mg ONCE WEEKLY (oral or SC). Start at 7.5mg, increase by 2.5-5mg every 4-8 weeks to target 20-25mg weekly. 2. Folic Acid 5mg once weekly (taken 24-48 hours after Methotrexate to reduce side effects). 3. Bridging therapy: Prednisolone 10-15mg daily for 4-8 weeks, then taper by 2.5mg weekly as DMARD takes effect. 4. If inadequate response at 3 months on max tolerated MTX: add Sulfasalazine + Hydroxychloroquine (triple therapy) or biologic DMARD (Adalimumab 40mg SC every 2 weeks). 5. NSAID for symptom relief: Naproxen 500mg BID + PPI (short-term).',
    'Joint protection techniques. Occupational therapy for adaptive equipment. Physiotherapy for range of motion and strengthening. Smoking cessation. Cardiovascular risk screening (RA increases CV risk).',
    'Start Methotrexate 10mg once weekly + Folic Acid. Start Prednisolone 10mg daily as bridge. Refer to physiotherapy/occupational therapy. Baseline: CXR (MTX screening), FBC, LFTs, Cr, HBV/HCV, Quantiferon. Review in 4 weeks for tolerability and dose titration. Aim for DAS28 remission by 6 months.',
    '1. Active, erosive RA requiring early and aggressive DMARD therapy to prevent irreversible joint damage. 2. Risk of disease progression and loss of function if treatment delayed.',
    'Monthly: FBC, LFTs, Cr (MTX monitoring). DAS28-ESR every 1-3 months. Annual: CXR, lipids, CV risk assessment. Monitor for MTX side effects: nausea, fatigue, mouth ulcers, hair thinning, hepatotoxicity, pneumonitis. Folic acid reduces side effects substantially.',
    'Methotrexate is taken ONCE A WEEK, not daily. It is a safe and effective medication for RA but requires regular blood tests. Folic acid helps reduce side effects. Prednisolone is a temporary bridge while methotrexate takes effect (usually 6-12 weeks). Do not stop prednisolone abruptly. Report fever, shortness of breath, mouth ulcers, or significant nausea.',
    'Rheumatology clinic in 4 weeks for MTX dose titration. DAS28 assessment in 3 months. If not achieving remission, escalate therapy (triple DMARD or biologic). Annual BP, lipids, glucose, and bone density monitoring.',
    'Early, aggressive treatment of RA within the "window of opportunity" (first 3-6 months) improves long-term outcomes. Methotrexate is the anchor DMARD — it can be used alone or in combination. Folic acid reduces MTX side effects without reducing efficacy. MTX is teratogenic — pregnancy must be avoided. Biologics (TNF inhibitors like Adalimumab) are highly effective but require TB screening. RA patients have 2x increased cardiovascular risk — manage CV risk factors aggressively.',
    ['EULAR Guidelines: RA Management', 'ACR Guidelines: RA Treatment', 'Kenya Clinical Guidelines: Inflammatory Arthritis'],
  ),
  tpl('Pain & Inflammation', 'Rheumatology', 'Gout', 'Acute Gout Flare with Hyperuricaemia — First Episode', 'Beginner',
    'Sudden onset of severe pain, redness, and swelling in the left big toe for 1 day',
    '{name}, a {age}-year-old {occupation} from {location}, woke up at 3 AM with excruciating pain in his left big toe. The joint is red, hot, swollen, and so tender that even the bedsheet touching it causes severe pain. Reports eating a large meal of nyama choma with beer 2 nights ago. No prior episodes. No joint trauma.',
    'Overweight (BMI 32). Hypertension (diet-controlled). No prior gout. No kidney disease.',
    'No regular medications',
    'Left 1st MTP joint: erythema, warmth, swelling, marked tenderness to palpation, limited range of motion. Temperature 37.8°C. No other joint involvement. No tophi.',
    'Serum Uric Acid: 9.2 mg/dL (normal <7.0). WBC 11.5 (mild leukocytosis). CRP 95 mg/L. ESR 55 mm/hr. Creatinine 0.9 mg/dL. Joint aspiration (if performed): negatively birefringent monosodium urate crystals on polarised light microscopy.',
    'X-ray left foot: soft tissue swelling over 1st MTP, no erosions or calcifications.',
    'Acute Gout Flare (First Episode)',
    ['Gout', 'Pseudogout (CPPD)', 'Septic Arthritis', 'Trauma', 'Cellulitis'],
    'Rapidly relieve pain and inflammation, treat acute flare, lower uric acid long-term to prevent recurrence',
    '1. Acute flare treatment (start immediately): First-line: Oral NSAID — Indomethacin 50mg TID for 3-5 days (or Naproxen 500mg BID, or Diclofenac 50mg TID). Add PPI if GI risk. Or Oral Colchicine 1.2mg (2 tabs) stat, then 0.6mg (1 tab) 1 hour later, then 0.6mg BID for 3-5 days (dose-reduce if CKD). Or Oral Prednisolone 30-40mg daily for 5-7 days (if NSAID/colchicine contraindicated). 2. Intra-articular steroid injection (if single joint, septic arthritis ruled out). 3. Ice packs to joint 20 mins on/off. 4. DO NOT start urate-lowering therapy (ULT) during acute flare — wait until flare fully resolved (2-4 weeks).',
    'Rest and elevate left foot. Ice packs. Avoid alcohol and purine-rich foods (red meat, organ meats, shellfish). Hydrate well (2-3L water/day). Use a bed cradle to keep sheets off the toe.',
    'Start Indomethacin 50mg TID for 5 days. Ice, rest, elevation. Review in 1 week. If flare resolved: discuss lifestyle modifications. Check uric acid in 4 weeks. If uric acid >9.0 or recurrent flares (>2/year), start ULT (Allopurinol 100mg daily, titrate to 300mg daily, target uric acid <6.0 mg/dL). Start ULT 2-4 weeks after flare completely resolves.',
    '1. Acute gouty inflammation requiring rapid anti-inflammatory therapy. 2. Hyperuricaemia requiring lifestyle modification and possible ULT.',
    'Pain score, joint inflammation (warmth, swelling, erythema) daily during flare. Uric acid level at 4 weeks post-flare. Renal function. Watch for NSAID side effects (GI, renal).',
    'Gout is caused by uric acid crystals forming in the joint — like tiny needles causing intense inflammation. The acute flare usually resolves in 3-7 days with treatment. Avoid triggers: red meat, offal, beer, and sugary drinks. Drink plenty of water. If you have further attacks, we may start long-term medication to lower uric acid.',
    'Review in 1 week for flare resolution. In 4 weeks: check uric acid. If ULT started: monthly uric acid checks until target reached, then 6-monthly. Lifestyle: weight loss, reduced alcohol and purine intake.',
    'Gout is the most common inflammatory arthritis in men. The classic presentation: acute monoarthritis of the 1st MTP (podagra) with excruciating pain. Colchicine is most effective if given within 12 hours of onset. ULT should NEVER be started during an acute flare (can prolong the flare). If starting ULT in a patient already on it during a flare, continue ULT. Allopurinol hypersensitivity syndrome (DRESS) is rare but serious — start at 100mg and titrate slowly, especially in CKD.',
    ['EULAR Guidelines: Gout Management', 'ACR Guidelines: Gout', 'Kenya Clinical Guidelines: Rheumatic Diseases'],
  ),
];
