// ================================================================
// Pain & Inflammation — Case Templates
// 6 templates covering: Acute Pain, Chronic Pain, Rheumatoid
// Arthritis, Osteoarthritis, Gout, Neuropathic Low Back Pain
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';
function tpl(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}

export const PAIN_INFLAMMATION_TEMPLATES: ClinicalCaseTemplate[] = [
  tpl('Pain & Inflammation', 'Orthopaedics', 'Acute Pain', 'Acute Post-Operative Pain Following Fracture Fixation', 'Beginner',
    'Severe left leg pain after surgical fixation of a tibial fracture',
    '{name}, a {age}-year-old {occupation} from {location}, is on Day 1 post open reduction and internal fixation (ORIF) of a left tibial fracture sustained in a road traffic accident. Reports severe pain (8/10) at the surgical site, constant, sharp, worse with movement. Has received IM Diclofenac 75mg 4 hours ago with minimal relief. No fever, no wound discharge.',
    'Previously healthy. No prior surgeries. Non-smoker.',
    'IM Diclofenac 75mg q12h (poor pain control), IV Paracetamol 1g q6h',
    'Left lower leg: surgical wound clean, dry, intact sutures, mild oedema. Distal neurovascular exam intact. Pain on passive movement of ankle. No calf tenderness. No fever.',
    'Hb 11.5 g/dL (post-op drop). WBC 12.0 (post-op leukocytosis). CRP 45. Creatinine 0.9. LFTs normal.',
    'Post-operative X-ray: satisfactory alignment and hardware position.',
    'Acute Post-Operative Pain (Moderate-Severe) Following Tibial ORIF',
    ['Acute Surgical Pain', 'Compartment Syndrome', 'Wound Infection', 'DVT'],
    'Achieve adequate pain control (target pain score <4/10), facilitate early mobilisation, prevent chronic pain, minimise opioid use',
    '1. WHO Analgesic Ladder Step 2 (moderate pain not controlled by Step 1): Add Tramadol 50-100mg PO/IM q6h PRN (max 400mg/day). 2. Continue Paracetamol 1g QID (scheduled, not PRN). 3. Continue Diclofenac 75mg IM/PO BID (max 5-7 days, add PPI cover). 4. If pain still uncontrolled, escalate to WHO Step 3: Morphine 5-10mg PO/SC q4h PRN. 5. Neuropathic component: add Gabapentin 300mg at bedtime (or Pregabalin 75mg BID) if nerve injury suspected. 6. Laxative (Lactulose 15mL BID or Senna) if on opioids. 7. Antiemetic (Ondansetron 4mg TID PRN) for opioid nausea.',
    'Elevation of left leg. Ice packs to surgical site 20 mins on/off. Early physiotherapy for mobilisation. Relaxation techniques. Adequate sleep hygiene.',
    'Review analgesic regimen: switch from PRN to scheduled dosing for better pain control. Add Tramadol. Start PPI. Monitor pain scores q4h. If pain controlled, transition to oral analgesics and prepare for discharge with physiotherapy.',
    '1. Inadequate post-operative pain control requiring escalation of analgesia. 2. Opioid use requires monitoring for side effects (constipation, nausea, respiratory depression).',
    'Pain score (NRS 0-10) at rest and with movement q4h. Sedation score if on opioids. Bowel function chart. Respiratory rate if on morphine. Watch for signs of compartment syndrome (pain out of proportion, paraesthesia, pallor, pulselessness, poikilothermia).',
    'Pain control is important for healing and recovery — do not try to "tough it out." Take pain medications on a schedule (not PRN) for the first few days. As pain improves, we will reduce and stop the stronger medications. Physiotherapy and movement are also important for pain relief. Report any new severe pain, numbness, or tingling.',
    'Orthopaedic clinic in 2 weeks for wound check and X-ray. Continue physiotherapy. Gradually reduce analgesia over 1-2 weeks as pain improves.',
    'The WHO Analgesic Ladder is a stepwise approach: Step 1 (non-opioid ± adjuvant) → Step 2 (weak opioid + non-opioid ± adjuvant) → Step 3 (strong opioid + non-opioid ± adjuvant). Paracetamol and NSAIDs have a ceiling effect — increasing the dose beyond maximum does not increase analgesia. Scheduled dosing is superior to PRN for acute pain. Multimodal analgesia (using drugs with different mechanisms) improves pain control and reduces opioid requirements.',
    ['WHO Guidelines: Pain Management', 'Kenya Clinical Guidelines: Acute Pain', 'BJA: Multimodal Analgesia'],
  ),
  tpl('Pain & Inflammation', 'Rheumatology', 'Rheumatoid Arthritis', 'Active Rheumatoid Arthritis with Disease-Modifying Antirheumatic Drug Initiation', 'Advanced',
    'Painful, swollen joints in both hands and feet, morning stiffness lasting >2 hours for 3 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with symmetrical pain and swelling of the wrists, knuckles (MCP, PIP joints), and feet (MTP joints) for 3 months. Morning stiffness lasts >2 hours. Reports fatigue, low-grade fever, and difficulty performing daily tasks (opening jars, walking). Has been self-medicating with Ibuprofen with minimal relief. No prior joint disease.',
    'No significant PMH. Non-smoker. No family history of autoimmune disease.',
    'Ibuprofen 400mg PRN (ineffective)',
    'Bilateral: swollen, tender MCP joints (2nd-5th), PIP joints, wrists. Positive squeeze test. Bilateral MTP joint tenderness. Mild ulnar deviation not present yet. No rheumatoid nodules. No other organ involvement.',
    'Rheumatoid Factor: positive (145 IU/mL). Anti-CCP: positive (strongly, >200 U/mL). ESR 65 mm/hr. CRP 45 mg/L. Hb 10.5 (anaemia of chronic disease). X-ray hands: juxta-articular osteopenia, no erosions yet (early disease).',
    'X-ray hands and feet: juxta-articular osteopenia, soft tissue swelling. No erosions or joint space narrowing.',
    'Seropositive Rheumatoid Arthritis (Early, Active, Moderate-High Disease Activity — DAS28-ESR 5.8)',
    ['Rheumatoid Arthritis', 'Psoriatic Arthritis', 'Osteoarthritis', 'Systemic Lupus Erythematosus', 'Gouty Arthritis'],
    'Achieve remission or low disease activity (DAS28 <2.6), prevent joint damage, maintain function, improve quality of life',
    '1. Start Methotrexate (first-line DMARD): 7.5-15mg ONCE WEEKLY (oral or SC). Start at 7.5mg, increase by 2.5-5mg every 4-8 weeks to target 20-25mg weekly. 2. Folic Acid 5mg once weekly (taken 24-48 hours after Methotrexate to reduce side effects). 3. Bridging therapy: Prednisolone 10-15mg daily for 4-8 weeks, then taper by 2.5mg weekly as DMARD takes effect. 4. If inadequate response at 3 months on max tolerated MTX: add Sulfasalazine + Hydroxychloroquine (triple therapy) or biologic DMARD (Adalimumab 40mg SC every 2 weeks). 5. NSAID for symptom relief: Naproxen 500mg BID + PPI (short-term).',
    'Joint protection techniques. Occupational therapy for adaptive equipment. Physiotherapy for range of motion and strengthening. Smoking cessation. Cardiovascular risk screening (RA increases CV risk).',
    'Start Methotrexate 10mg once weekly + Folic Acid. Start Prednisolone 10mg daily as bridge. Refer to physiotherapy/occupational therapy. Baseline: CXR (MTX screening), FBC, LFTs, Cr, HBV/HCV, Quantiferon. Review in 4 weeks for tolerability and dose titration. Aim for DAS28 remission by 6 months.',
    '1. Active, erosive RA requiring early and aggressive DMARD therapy to prevent irreversible joint damage. 2. Risk of disease progression and loss of function if treatment delayed.',
    'Monthly: FBC, LFTs, Cr (MTX monitoring). DAS28-ESR every 1-3 months. Annual: CXR, lipids, CV risk assessment. Monitor for MTX side effects: nausea, fatigue, mouth ulcers, hair thinning, hepatotoxicity, pneumonitis. Folic acid reduces side effects substantially.',
    'Methotrexate is taken ONCE A WEEK, not daily. It is a safe and effective medication for RA but requires regular blood tests. Folic acid helps reduce side effects. Prednisolone is a temporary bridge while methotrexate takes effect (usually 6-12 weeks). Do not stop prednisolone abruptly. Report fever, shortness of breath, mouth ulcers, or significant nausea.',
    'Rheumatology clinic in 4 weeks for MTX dose titration. DAS28 assessment in 3 months. If not achieving remission, escalate therapy (triple DMARD or biologic). Annual BP, lipids, glucose, and bone density monitoring.',
    'Early, aggressive treatment of RA within the "window of opportunity" (first 3-6 months) improves long-term outcomes. Methotrexate is the anchor DMARD — it can be used alone or in combination. Folic acid reduces MTX side effects without reducing efficacy. MTX is teratogenic — pregnancy must be avoided. Biologics (TNF inhibitors like Adalimumab) are highly effective but require TB screening. RA patients have 2x increased cardiovascular risk — manage CV risk factors aggressively.',
    ['EULAR Guidelines: RA Management', 'ACR Guidelines: RA Treatment', 'Kenya Clinical Guidelines: Inflammatory Arthritis'],
  ),
  tpl('Pain & Inflammation', 'Rheumatology', 'Gout', 'Acute Gout Flare with Hyperuricaemia — First Episode', 'Beginner',
    'Sudden onset of severe pain, redness, and swelling in the left big toe for 1 day',
    '{name}, a {age}-year-old {occupation} from {location}, woke up at 3 AM with excruciating pain in his left big toe. The joint is red, hot, swollen, and so tender that even the bedsheet touching it causes severe pain. Reports eating a large meal of nyama choma with beer 2 nights ago. No prior episodes. No joint trauma.',
    'Overweight (BMI 32). Hypertension (diet-controlled). No prior gout. No kidney disease.',
    'No regular medications',
    'Left 1st MTP joint: erythema, warmth, swelling, marked tenderness to palpation, limited range of motion. Temperature 37.8°C. No other joint involvement. No tophi.',
    'Serum Uric Acid: 9.2 mg/dL (normal <7.0). WBC 11.5 (mild leukocytosis). CRP 95 mg/L. ESR 55 mm/hr. Creatinine 0.9 mg/dL. Joint aspiration (if performed): negatively birefringent monosodium urate crystals on polarised light microscopy.',
    'X-ray left foot: soft tissue swelling over 1st MTP, no erosions or calcifications.',
    'Acute Gout Flare (First Episode)',
    ['Gout', 'Pseudogout (CPPD)', 'Septic Arthritis', 'Trauma', 'Cellulitis'],
    'Rapidly relieve pain and inflammation, treat acute flare, lower uric acid long-term to prevent recurrence',
    '1. Acute flare treatment (start immediately): First-line: Oral NSAID — Indomethacin 50mg TID for 3-5 days (or Naproxen 500mg BID, or Diclofenac 50mg TID). Add PPI if GI risk. Or Oral Colchicine 1.2mg (2 tabs) stat, then 0.6mg (1 tab) 1 hour later, then 0.6mg BID for 3-5 days (dose-reduce if CKD). Or Oral Prednisolone 30-40mg daily for 5-7 days (if NSAID/colchicine contraindicated). 2. Intra-articular steroid injection (if single joint, septic arthritis ruled out). 3. Ice packs to joint 20 mins on/off. 4. DO NOT start urate-lowering therapy (ULT) during acute flare — wait until flare fully resolved (2-4 weeks).',
    'Rest and elevate left foot. Ice packs. Avoid alcohol and purine-rich foods (red meat, organ meats, shellfish). Hydrate well (2-3L water/day). Use a bed cradle to keep sheets off the toe.',
    'Start Indomethacin 50mg TID for 5 days. Ice, rest, elevation. Review in 1 week. If flare resolved: discuss lifestyle modifications. Check uric acid in 4 weeks. If uric acid >9.0 or recurrent flares (>2/year), start ULT (Allopurinol 100mg daily, titrate to 300mg daily, target uric acid <6.0 mg/dL). Start ULT 2-4 weeks after flare completely resolves.',
    '1. Acute gouty inflammation requiring rapid anti-inflammatory therapy. 2. Hyperuricaemia requiring lifestyle modification and possible ULT.',
    'Pain score, joint inflammation (warmth, swelling, erythema) daily during flare. Uric acid level at 4 weeks post-flare. Renal function. Watch for NSAID side effects (GI, renal).',
    'Gout is caused by uric acid crystals forming in the joint — like tiny needles causing intense inflammation. The acute flare usually resolves in 3-7 days with treatment. Avoid triggers: red meat, offal, beer, and sugary drinks. Drink plenty of water. If you have further attacks, we may start long-term medication to lower uric acid.',
    'Review in 1 week for flare resolution. In 4 weeks: check uric acid. If ULT started: monthly uric acid checks until target reached, then 6-monthly. Lifestyle: weight loss, reduced alcohol and purine intake.',
    'Gout is the most common inflammatory arthritis in men. The classic presentation: acute monoarthritis of the 1st MTP (podagra) with excruciating pain. Colchicine is most effective if given within 12 hours of onset. ULT should NEVER be started during an acute flare (can prolong the flare). If starting ULT in a patient already on it during a flare, continue ULT. Allopurinol hypersensitivity syndrome (DRESS) is rare but serious — start at 100mg and titrate slowly, especially in CKD.',
    ['EULAR Guidelines: Gout Management', 'ACR Guidelines: Gout', 'Kenya Clinical Guidelines: Rheumatic Diseases'],
  ),
  tpl('Pain & Inflammation', 'Rheumatology', 'Fibromyalgia', 'Fibromyalgia Syndrome — Pharmacological Management of Chronic Widespread Pain', 'Advanced',
    'Widespread body pain, fatigue, and poor sleep for over 6 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with 7-month history of widespread musculoskeletal pain affecting all four quadrants (above and below waist, both sides). Pain is dull, aching, constant, rated 7/10. Reports severe fatigue (worse than pain), unrefreshing sleep (wakes up tired), "brain fog" (poor concentration and memory), and tender points. Multiple visits to different doctors. Previous ibuprofen and paracetamol ineffective. No inflammatory arthritis features. No trauma.',
    'Irritable bowel syndrome (diagnosed 3 years ago). Tension headaches. Anxiety. No thyroid disease, no inflammatory arthritis.',
    'Ibuprofen 400mg PRN (ineffective). Paracetamol 1g PRN (minimal relief). No psychotropic medications.',
    'Normal appearance. No joint swelling or deformity. Tender points: positive at 14 of 18 ACR-defined tender points (including bilateral occiput, low cervical, trapezius, supraspinatus, second rib, lateral epicondyle, gluteal, greater trochanter, knees). No synovitis. No skin rash. Muscle strength: normal. Neurological exam: normal.',
    'FBC, ESR, CRP: all normal. Rheumatoid factor: negative. Anti-CCP: negative. ANA: negative. TSH: normal. Vitamin D: 20 ng/mL (insufficient, normal >30). CPK: normal.',
    'None needed — fibromyalgia is a clinical diagnosis.',
    'Fibromyalgia Syndrome (2016 ACR Criteria met: WPI >7, SSS >5, symptoms present >3 months, no other explanatory disorder)',
    ['Fibromyalgia', 'Rheumatoid Arthritis (seronegative)', 'Systemic Lupus', 'Myofascial Pain Syndrome', 'Polymyalgia Rheumatica', 'Hypothyroidism', 'Chronic Fatigue Syndrome'],
    'Reduce pain (target <4/10), improve sleep quality, increase function and activity level, reduce fatigue, improve mood and quality of life',
    '1. Pregabalin (first-line): Start 75mg BID, titrate to 150mg BID over 4 weeks based on response/tolerance. Reduce dose if CKD. 2. Duloxetine (first-line, especially if anxiety/depression present): Start 30mg daily for 1 week, then increase to 60mg daily. SNRI improves pain, mood, and function. 3. Amitriptyline (for sleep): Low dose 10-25mg at bedtime. Titrate slowly. 4. Alternative: Milnacipran 50mg BID (SNRI, third first-line agent). 5. Avoid: opioids (ineffective long-term, risk of dependence), NSAIDs (ineffective for fibromyalgia pain), corticosteroids. 6. Adjunctive: Paracetamol PRN (limited efficacy). Vitamin D supplementation if deficient. 7. For neuropathic pain not controlled by first-line: consider Gabapentin 300mg TID (off-label, less effective than pregabalin).',
    'Exercise therapy: graded aerobic exercise (walking, swimming) start 5-10 min/day, increase gradually to 30 min/day. CBT for pain management and coping skills. Sleep hygiene (regular sleep-wake schedule, no screens before bed). Stress reduction techniques (mindfulness, relaxation). Pacing activity (avoid boom-bust cycles). Patient education: fibromyalgia is real, not "in your head."',
    'Start Pregabalin 75mg BID + Amitriptyline 10mg at bedtime. Educate about fibromyalgia as a central sensitisation syndrome. Refer to physiotherapy for graded exercise programme. Sleep hygiene counselling. Review in 4 weeks. If good response, continue. If not, add/increase Duloxetine. If no response to 2 first-line agents, consider referral to pain clinic.',
    '1. Chronic widespread pain due to central sensitisation (fibromyalgia). 2. Significant impact on sleep, function, and quality of life. 3. Failed simple analgesics — requires centrally acting medications.',
    'Pain score (NRS) and function (FIQ questionnaire) every visit. Sleep quality (self-report). Assess for side effects: Pregabalin (dizziness, sedation, weight gain, peripheral oedema), Duloxetine (nausea, insomnia, sexual dysfunction), Amitriptyline (dry mouth, constipation, sedation). Monitor for mood changes (depression, suicidal ideation with duloxetine — rare).',
    'Fibromyalgia is a real condition where the brain amplifies pain signals — it is not "in your head" or just a mental health issue. Treatment involves both medications and lifestyle changes. Exercise is one of the most effective treatments — start slowly and build up. Pacing activities helps prevent pain flare-ups. Improve sleep with good habits: go to bed at the same time, avoid screens, and keep the room dark. Medications reduce pain by about 30-50% — they do not cure fibromyalgia but help you function better.',
    'Clinic in 4 weeks to assess response and tolerability. If Pregabalin effective, continue. If inadequate, add Duloxetine 30mg increasing to 60mg. Physiotherapy: weekly for 8 weeks. Consider psychology referral for CBT. Annual review: re-assess ACR criteria, screen for comorbid depression/anxiety.',
    'Fibromyalgia is a central sensitivity syndrome — the brain processes normal sensory input as pain (allodynia, hyperalgesia). It is NOT an inflammatory condition — NSAIDs, steroids, and opioids are ineffective. The 2016 ACR diagnostic criteria require: Widespread Pain Index (WPI) >7 AND Symptom Severity Scale (SSS) >5, symptoms present >3 months, AND no other explanation. First-line pharmacotherapy: Pregabalin, Duloxetine, or Milnacipran (all FDA-approved for fibromyalgia). Amitriptyline is effective for sleep but not FDA-approved for fibromyalgia. Non-pharmacological therapy (exercise, CBT) is equally important as medication. In Kenya, fibromyalgia is underdiagnosed — prevalence estimated at 2-4% but most cases are missed. Pregabalin is available as 75mg capsules. Duloxetine is available as generic (30mg/60mg).',
    ['ACR Guidelines: Fibromyalgia Diagnosis', 'EULAR Guidelines: Fibromyalgia Management', 'Kenya Clinical Guidelines: Chronic Pain'],
  ),
  tpl('Pain & Inflammation', 'Orthopaedics', 'Osteoarthritis', 'Osteoarthritis of the Knee — Multimodal Management', 'Beginner',
    'Chronic right knee pain worse with walking and stiffness after rest',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 3-year history of progressive right knee pain. The pain is deep and aching, worse with walking (especially on uneven ground and climbing stairs), and stiff after periods of inactivity (morning stiffness lasting <30 minutes). Reports clicking and grinding sensation in the knee. Has been self-treating with paracetamol irregularly. Pain is now interfering with daily activities — difficulty squatting, walking to the market, and climbing stairs. No locking, giving way, or acute swelling. No other joint involvement. No systemic symptoms (no fever, weight loss, or rash).',
    'Overweight (BMI 33). Hypertension (on medication). No diabetes. No prior joint surgery. History of occupational heavy lifting. No family history of inflammatory arthritis.',
    'Paracetamol 500mg PRN (taken irregularly, 2-3 tablets per week). No regular analgesia.',
    'Right knee: mild crepitus on passive flexion/extension. Medial joint line tenderness. No joint effusion (or small physiological effusion). No erythema or warmth. Range of motion: flexion 110° (reduced from normal 135°), extension full. Varus alignment (mild medial compartment wear). Quadriceps wasting (mild). Gait: antalgic, favouring right leg. No ligamentous instability. Left knee: normal. Other joints: normal.',
    'No bloods required for primary OA. If considering differential diagnosis: ESR, CRP, RF, Anti-CCP (to exclude inflammatory arthritis). Vitamin D level (deficiency common in knee OA and worsens pain).',
    'X-ray right knee (AP and lateral): Medial joint space narrowing, subchondral sclerosis, osteophyte formation at medial tibial and femoral margins, small subchondral cyst. Kellgren-Lawrence Grade 3 (moderate-severe OA). No loose bodies. No chondrocalcinosis (excludes pseudogout).',
    'Moderate-Severe Osteoarthritis of the Right Knee (Medial Compartment Predominant)',
    ['Knee Osteoarthritis', 'Inflammatory Arthritis (RA, PsA — systemic features, morning stiffness >1 hour)', 'Meniscal Tear (acute onset, locking, catching)', 'Gout/Pseudogout (acute flare pattern)', 'Osteonecrosis (night pain, MRI changes)'],
    'Reduce knee pain to tolerable level (<4/10), improve function and mobility, slow disease progression, prevent disability, reduce reliance on analgesics',
    '1. Paracetamol (regular, not PRN): 1g QID scheduled (maximum 4g/day — but limit to 3g/day if elderly or hepatic risk). 2. Topical NSAIDs (first-line add-on): Diclofenac 1% gel — apply to right knee 3-4 times daily (minimal systemic absorption, effective for localised OA). 3. Oral NSAIDs (if topical insufficient): Naproxen 250mg BID OR Ibuprofen 400mg TID (add PPI — Omeprazole 20mg daily for GI protection). Limit to shortest duration possible. 4. Intra-articular corticosteroid injection (if flare or refractory pain): Triamcinolone 40mg or Methylprednisolone 80mg into right knee (provides 4-8 weeks relief). Maximum 3-4 injections per year. 5. Intra-articular hyaluronic acid (viscosupplementation): Consider if steroid injection insufficient — 3-5 weekly injections. 6. Avoid opioids — ineffective for OA, high risk of dependence. 7. Duloxetine 60mg daily if chronic pain with central sensitisation component.',
    'Weight loss (target 5-10% body weight — reduces knee loading by 25-50%). Physiotherapy: quadriceps strengthening exercises (strong quads protect the knee), low-impact aerobic exercise (swimming, cycling). Walking aids (walking stick in opposite hand to unload knee). Heat packs for stiffness. Cold packs for acute flare. Joint protection techniques — avoid deep squatting, kneeling, and prolonged standing.',
    'Start Paracetamol 1g QID scheduled + Diclofenac 1% gel TID to right knee. Refer to physiotherapy for quadriceps strengthening and exercise programme. Weight loss counselling. X-ray findings explained to patient. If inadequate pain control in 4-6 weeks: add oral NSAID (Naproxen + PPI) or consider intra-articular steroid injection. Long-term plan: discuss arthroplasty referral if conservative measures fail and symptoms severely impact quality of life.',
    '1. Symptomatic knee OA requiring multimodal management. 2. Overweight status is a major modifiable risk factor. 3. Requires long-term management strategy rather than cure.',
    'Pain score (NRS) at each visit. Knee function (WOMAC score) every 3 months. Monitor for NSAID side effects: GI bleeding (on PPI), renal function (check Cr periodically), cardiovascular risk (NSAIDs increase CV risk — avoid in high CV risk patients). Weight (target 5-10% loss). Repeat X-ray only if symptoms change significantly or surgical planning needed.',
    'Osteoarthritis is "wear and tear" of the joint cartilage — there is no cure, but it can be managed effectively. The most important things you can do are lose weight (even 5kg makes a big difference) and strengthen the muscles around the knee (quadriceps exercises). Take paracetamol on a schedule, not just when the pain is bad. The diclofenac gel goes on the knee directly — rub it in 3 times daily. Avoid kneeling and deep squatting. If these measures are not enough after 4-6 weeks, we can consider an injection into the knee.',
    'Physiotherapy referral within 1 week. Review in 6 weeks for pain assessment and medication review. If still symptomatic: consider intra-articular steroid injection. Annual review for progression. If Kellgren-Lawrence Grade 4 or symptoms refractory to all conservative measures: refer to orthopaedics for total knee arthroplasty.',
    'OA is the most common joint disease globally, affecting >50% of people over 65. In Kenya, knee OA is highly prevalent due to occupational physical demands, obesity, and limited access to joint replacement. Paracetamol has modest efficacy in OA (NNT ~4 for pain relief) but is safe and should be used regularly. NSAIDs are more effective but carry GI, renal, and CV risks — always use with PPI cover and for shortest duration. Intra-articular corticosteroids provide short-term relief (4-8 weeks) but repeated injections may accelerate cartilage loss — limit to 3-4 per year. Weight loss of 5-10% body weight reduces knee pain by 50% and is the single most effective non-pharmaceutical intervention. Total knee arthroplasty is highly effective for end-stage OA (>90% satisfaction at 15 years) but is expensive and has limited availability in Kenya.',
    ['OARSI Guidelines: Knee OA Management', 'NICE Guidelines: OA (CG177)', 'Kenya Clinical Guidelines: Musculoskeletal Conditions'],
  ),
  tpl('Pain & Inflammation', 'Neurology / Pain Medicine', 'Neuropathic Pain', 'Chronic Low Back Pain with Neuropathic Component (Lumbar Disc Herniation)', 'Intermediate',
    'Chronic low back pain radiating to the right leg for 6 months, worse with sitting',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 6-month history of chronic low back pain radiating to the right leg (sciatica distribution — buttock, posterior thigh, and lateral calf). The pain is burning and shooting in quality, rated 7/10, worse with sitting (especially on low chairs) and bending forward, partially relieved by lying down. Reports tingling and numbness along the right lateral shin and dorsum of the foot. No bowel or bladder dysfunction (no cauda equina). No bilateral symptoms. No fever, weight loss, or night pain. Previous treatment with ibuprofen and physiotherapy provided minimal relief.',
    'No significant PMH. Non-smoker. No history of cancer. No diabetes. Previous episode of low back pain 3 years ago (resolved with physiotherapy).',
    'Ibuprofen 400mg TID (ineffective for the neuropathic component). Paracetamol 1g QID (minimal relief). Physiotherapy (6 sessions — no significant improvement).',
    'Posture: antalgic, leaning to the left (away from pain). Lumbar spine: reduced flexion (can reach mid-shin). Straight leg raise (SLR) test: positive on the right at 45° (reproduces leg pain — confirms nerve root tension). Weakness: right extensor hallucis longus (EHL) 4/5 (L5 myotome). Sensory: reduced light touch over right L5 dermatome (lateral shin, dorsum of foot). Reflexes: knee and ankle reflexes 2+ bilaterally. No saddle anaesthesia. No lower limb oedema.',
    'No acute bloods needed. If considering differentials: ESR, CRP, FBC, calcium, alkaline phosphatase. If neurological deficit progressing: urgent MRI.',
    'MRI Lumbar Spine: Large right-sided L4-L5 disc herniation (posterolateral, extruded fragment) compressing the L5 nerve root. Mild canal stenosis. No other significant disc pathology. No evidence of tumour, infection, or fracture.',
    'Chronic Low Back Pain with Right L5 Radiculopathy (Neuropathic Pain Component) due to L4-L5 Disc Herniation',
    ['Lumbar Disc Herniation with Radiculopathy', 'Facet Joint Pain (axial low back pain, negative SLR)', 'Spinal Stenosis (neurogenic claudication — pain with walking, relieved by flexion)', 'Piriformis Syndrome', 'Peripheral Neuropathy (bilateral, symmetric — diabetes)', 'Spinal Tumour/Infection (red flags: night pain, weight loss, fever)'],
    'Relieve neuropathic pain (target <4/10), improve functional capacity (walking, sitting), reduce opioid reliance, prevent chronicity, address psychological impact',
    '1. Neuropathic pain agent (first-line): Gabapentin 300mg at night, titrate by 300mg every 3-5 days as tolerated — target 300mg TID (900mg/day). Maximum 3600mg/day. Slow titration reduces dizziness/sedation. OR Pregabalin 75mg BID, titrate to 150mg BID over 2-4 weeks. 2. Tricyclic antidepressant (second-line / adjunct): Amitriptyline 10-25mg at bedtime, titrate slowly (max 75mg). Effective for neuropathic pain and sleep. Avoid if cardiac history. 3. Weak opioid (short-term only): Tramadol 50mg q6h PRN (max 400mg/day) — for acute flares. Strict time-limited (2-4 weeks). 4. Neuropathic pain cream: Capsaicin 0.025-0.075% cream applied to affected area TID (depletes substance P). 5. Continue paracetamol 1g QID for the mechanical/axial component. 6. If neuropathic pain refractory to 2 first-line agents: refer for epidural steroid injection (transforaminal L4-L5 on the right — targeted delivery of corticosteroid to the inflamed nerve root). 7. Avoid opioids long-term (ineffective for neuropathic pain, risk of dependence, opioid-induced hyperalgesia).',
    'Physiotherapy: core strengthening programme (McKenzie method, Pilates-based exercises), neural mobilisation techniques. Ergonomic modifications: lumbar support in chair, sit-stand desk if available, avoid prolonged sitting. Walking programme: 20-30 minutes daily (swimming or hydrotherapy if available). Weight loss if overweight (reduces disc loading). TENS machine (transcutaneous electrical nerve stimulation) for pain relief. Sleep hygiene — adequate sleep reduces pain perception.',
    'Start Gabapentin 300mg at night, titrate to 300mg TID over 2 weeks. Add Amitriptyline 10mg at bedtime. Continue paracetamol. Refer for physiotherapy (neural mobilisation + core strengthening). Ergonomic advice. Review in 4 weeks: assess neuropathic pain (DN4 questionnaire). If adequate response: continue. If inadequate: increase gabapentin to 600mg TID or switch to pregabalin. If still refractory after 6-8 weeks: refer for epidural steroid injection. If progressive neurological deficit develops (worsening weakness, bowel/bladder symptoms): urgent surgical referral.',
    '1. Chronic neuropathic pain requiring targeted pharmacotherapy (gabapentinoids, not just simple analgesics). 2. L5 radiculopathy with motor deficit (EHL 4/5) — monitor for progression. 3. Failed first-line conservative measures — escalation needed.',
    'Pain score (NRS) and DN4 neuropathic pain score every visit. Functional assessment: walking distance, sitting tolerance, sleep quality. Monitor gabapentin side effects: drowsiness, dizziness, weight gain, peripheral oedema. Monitor amitriptyline: dry mouth, constipation, sedation, QT prolongation (ECG if cardiac risk). Watch for progressive motor weakness (surgical emergency if developing). Monitor for cauda equina syndrome: any new bowel/bladder dysfunction, saddle anaesthesia — immediate surgical referral.',
    'Neuropathic pain is different from regular pain — it is caused by damage to the nerve itself, producing burning, shooting, and tingling sensations. Standard painkillers (paracetamol, ibuprofen) work poorly for neuropathic pain. Gabapentin works by calming overactive nerve signals. Start low and increase slowly to reduce side effects. Amitriptyline at low doses helps both pain and sleep. Do not drive until you know how gabapentin affects you (drowsiness). Avoid alcohol with these medications. Physiotherapy with neural mobilisation is important — it helps the nerve glide more freely and reduces irritation.',
    'Pain clinic / neurology follow-up in 4 weeks for gabapentin titration and pain assessment. Physiotherapy: weekly for 8 weeks. If no improvement in 6-8 weeks on maximal neuropathic pain medications: refer for epidural steroid injection or neurosurgical opinion. MRI repeat only if new symptoms develop or surgical planning.',
    'Neuropathic pain affects 6-8% of the general population and is one of the most difficult pain syndromes to treat. The NNT (number needed to treat) for neuropathic pain medications is typically 3-5 (much higher than simple analgesics), meaning many patients need trials of multiple agents. Gabapentin and pregabalin are alpha-2-delta calcium channel ligands — they reduce excitatory neurotransmitter release at the dorsal horn. Amitriptyline (TCA) inhibits reuptake of noradrenaline and serotonin in descending pain pathways. In Kenya, gabapentin is available as 100mg and 300mg capsules (relatively affordable). Pregabalin is more expensive but has more predictable pharmacokinetics. The McKenzie method of physiotherapy is evidence-based for disc herniation and is widely applicable. Epidural steroid injections provide targeted anti-inflammatory effect to the nerve root and can provide 4-12 weeks of relief — useful as a bridge while waiting for natural disc resorption.',
    ['NICE Guidelines: Neuropathic Pain (CG173)', 'Kenya Clinical Guidelines: Chronic Pain', 'IASP Guidelines: Neuropathic Pain Management'],
  ),
];
