// ================================================================
// Renal Pharmacology — Case Templates (4 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const RENAL_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Renal Pharmacology', 'Nephrology', 'Chronic Kidney Disease', 'Newly Diagnosed CKD Stage 4 in a Patient with Diabetes and Hypertension', 'Intermediate',
    'Gradual fatigue, leg swelling, and frothy urine for 4 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive fatigue, bilateral ankle swelling, and noticing frothy/foamy urine for 4 months. Reports nocturia (3-4x/night). Has a long history of Type 2 Diabetes (15 years) and hypertension (12 years) with poor control. No known prior kidney disease.',
    'Type 2 Diabetes (15 years), Hypertension (12 years), Diabetic Retinopathy (background, on annual screening).',
    'Metformin 1g BID, Glibenclamide 10mg BID, Amlodipine 10mg daily, Losartan 50mg daily, Atorvastatin 20mg daily, Aspirin 75mg daily',
    'Overweight (BMI 30). BP 158/92 (poorly controlled). Fundoscopy: background diabetic retinopathy. Pedal oedema 2+ bilateral. No JVP elevation. Lungs clear. Peripheral pulses reduced. Neuropathy: reduced monofilament sensation in feet.',
    'Creatinine 3.2 mg/dL, eGFR 18 mL/min/1.73m2 (CKD Stage 4). Hb 9.5 g/dL (normocytic, normochromic — anaemia of CKD). K+ 4.8 mEq/L. Bicarbonate 18 mEq/L. Ca 8.6, Phos 5.2, PTH 180 pg/mL. Albumin 3.0 g/dL. HbA1c 8.8%. Urinalysis: protein 3+, no haematuria. UPCR (urine protein/creatinine ratio): 3500 mg/g (nephrotic range proteinuria). Hb electrophoresis: normal.',
    'Renal ultrasound: Bilateral small kidneys (R 9.2cm, L 9.0cm), increased cortical echogenicity, thin parenchyma — consistent with chronic kidney disease.',
    'Chronic Kidney Disease Stage 4 (eGFR 18) with Nephrotic-Range Proteinuria likely due to Diabetic Nephropathy and Hypertensive Nephrosclerosis',
    ['CKD Stage 4 (Diabetic Nephropathy)', 'CKD (Hypertensive Nephrosclerosis)', 'Primary Glomerulonephritis', 'Nephrotic Syndrome', 'Multiple Myeloma'],
    'Slow CKD progression, manage complications (anaemia, metabolic acidosis, mineral bone disease), prepare for renal replacement therapy, optimise CV risk',
    '1. Nephroprotective therapy: Losartan 50mg daily (max tolerated dose 100mg — reduces proteinuria and slows CKD progression). Add SGLT2i: Dapagliflozin 10mg daily (slows CKD progression, reduces albuminuria, CV benefit) — when eGFR >25. 2. Optimise BP target <130/80 mmHg. 3. Stop Metformin (contraindicated when eGFR <30 — risk of lactic acidosis). Switch insulin or sulfonylurea as needed to control glucose. 4. Anaemia management: Start Darbepoetin alfa (ESA) 0.45 mcg/kg SC weekly OR Epoetin alfa 50 units/kg SC 3x/week — target Hb 10-12 g/dL. Iron: Ferrous sulphate 200mg TID or IV iron (if ferritin <100 or TSAT <20%). 5. Mineral bone disease: Calcitriol 0.25-0.5mcg daily (for secondary hyperparathyroidism). Phosphate binders: Calcium carbonate 500-1000mg with meals OR Sevelamer if hypercalcaemia. 6. Metabolic acidosis: Sodium bicarbonate 600mg TID (target bicarbonate >22). 7. Diuretics: Furosemide 40mg daily for oedema (titrate as needed). 8. Vaccinations: HBV, influenza, pneumococcal.',
    'Dietary: Reduce salt (<2g/day), moderate protein (0.8 g/kg/day), limit K+ (avoid oranges, bananas, potatoes, tomatoes), limit phosphate (avoid soda, processed foods, organ meats). Fluid restriction if oedema or hyponatraemia. AV fistula education and vein preservation.',
    'Refer to nephrology for CKD management. Calculate eGFR monthly. Start Dapagliflozin 10mg if eGFR >25. Start ESA + iron. Start Calcitriol. Optimise BP and proteinuria. Educate on renal diet. Discuss RRT options: haemodialysis, peritoneal dialysis, or pre-emptive transplant. AV fistula creation when eGFR approaches 15-20.',
    '1. Advanced CKD with multiple complications requiring comprehensive nephrology care. 2. Multiple medication adjustments needed due to declining renal function (stop metformin, dose-adjust others). 3. Preparation for RRT needed in the near future.',
    'Monthly: eGFR, K+, bicarbonate, Hb, Ca, Phos, PTH, albumin. UPCR every 3 months. BP at every visit. HbA1c quarterly. Annual: cardiac echo, vascular access assessment. Monitor for: hyperkalaemia (ACEi/ARB + Dapagliflozin + low-K diet), fluid overload, ESA resistance (check Fe, B12, folate, inflammation).',
    'Your kidneys are working at only 18% of normal. We need to protect them, manage complications, and prepare for the possibility of dialysis or a kidney transplant in the future. Work closely with the dietitian — what you eat matters a lot now. Take your medications as prescribed. We will monitor your blood tests monthly.',
    'Nephrology clinic monthly. Prepare for RRT (education, counselling, AV fistula creation when eGFR 15-20). Vaccinations. Annual: cardiac assessment, eye exam, foot exam. Plan for transplant evaluation if eligible.',
    'CKD management is a multidisciplinary effort: nephrologist, dietitian, pharmacist, diabetes educator. The "holy trinity" of renoprotection: ACEi/ARB (for proteinuria), SGLT2i (for progression slowing), and tight BP control. Metformin must be stopped when eGFR <30 (lactic acidosis risk). ESA therapy should target Hb 10-12 g/dL (NOT higher — increased CV risk). Phosphate binders should be taken with meals. AV fistula is the preferred dialysis access (lower infection and thrombosis rates than catheters).',
    ['KDIGO Guidelines: CKD Evaluation and Management', 'Kenya Clinical Guidelines: CKD', 'WHO: CKD Management'],
  ),
  t('Renal Pharmacology', 'Nephrology', 'Hyperkalaemia', 'Life-Threatening Hyperkalaemia in a CKD Patient on ACE Inhibitor', 'Advanced',
    'Severe weakness, palpitations, and ECG changes on routine labs',
    '{name}, a {age}-year-old {occupation} from {location}, was brought to casualty after a routine clinic blood test showed potassium of 7.0 mEq/L. The lab phoned the result as a critical value. Patient reports mild muscle weakness and palpitations over the past 2 days. Has CKD Stage 4 and recently had his Losartan dose increased from 50mg to 100mg daily. Also started Spironolactone 25mg daily 1 week ago for resistant hypertension. Has been eating large amounts of fruit (oranges, bananas, tomatoes) as part of a "healthy diet."',
    'CKD Stage 4 (eGFR 22), Hypertension (resistant), Diabetes Type 2',
    'Losartan 100mg daily (recently increased), Spironolactone 25mg daily (new, started 1 week ago), Amlodipine 10mg, Metformin 500mg BID, Furosemide 40mg BID, Atorvastatin 20mg',
    'Generalised muscle weakness, areflexic. HR 50 (bradycardic), BP 140/80. ECG: Peaked T waves (tented, narrow-based), absent P waves, widened QRS (120ms). Lethargic but conscious.',
    'K+ 7.0 mEq/L (critical). Na+ 137, Cl- 105, Bicarb 16 (metabolic acidosis). Creatinine 2.8 mg/dL (eGFR 22). BUN 65 mg/dL. Glucose 150 mg/dL. Mg 1.8 mg/dL. Digoxin level: not on digoxin.',
    'ECG: Peaked T waves (tented), prolonged PR, absent P wave, widened QRS (120ms) — life-threatening hyperkalaemia.',
    'Life-Threatening Hyperkalaemia (K+ 7.0) with ECG Changes — Exacerbated by ACEi + MRA + High-K+ Diet in CKD',
    ['Hyperkalaemia (drug-induced)', 'Hyperkalaemia (CKD)', 'Hypokalaemic Periodic Paralysis', 'Digoxin Toxicity', 'Acute Kidney Injury'],
    'Immediately lower serum potassium to <6.0, protect the heart, correct acidosis, identify and remove precipitating factors',
    '1. Cardiac protection (IMMEDIATE): IV Calcium Gluconate 10% 10-20mL (or Calcium Chloride 5-10mL) over 2-5 minutes. Repeat in 5 minutes if ECG changes persist. 2. Shift K+ intracellularly (temporary): Nebulised Salbutamol 10-20mg (onset 30 min, reduces K+ by 0.5-1.5). OR IV Insulin 10 units + 50% Dextrose 50mL (onset 15 min, peak 30-60 min). 3. Remove K+ from body: IV Furosemide 40-80mg (if some renal function). KCl-binding resin: Calcium Resonium 15g TID PO/PR. Consider haemodialysis (definitive, if K+ remains >6.5 despite medical therapy). 4. Reverse precipitating factors: STOP Spironolactone. STOP/Hold Losartan (ACEi/ARB). Stop K+-sparing drugs. Review diet. 5. Correct acidosis: IV Sodium Bicarbonate 50-100 mEq (if pH <7.2).',
    'Cardiac monitoring continuously. Strict I/O. Limit K+ intake (avoid high-K+ foods). Identify and stop offending medications.',
    'EMERGENCY: IV Calcium Gluconate immediately for ECG changes. Then insulin+glucose, salbutamol, furosemide. Check K+ q1h. Consider dialysis if K+ refractory. Admit to HDU/ICU. Review all medications for K+ elevation risk.',
    '1. Acute life-threatening hyperkalaemia from combined use of ACEi + MRA + high-K+ diet in advanced CKD. 2. Polypharmacy-related adverse event requiring urgent medical management.',
    'Continuous ECG monitoring. K+ q1h until <6.0, then q4-6h. Glucose q1h (if insulin given). Creatinine and bicarbonate. Monitor for hypoglycaemia after insulin/dextrose (recheck glucose q30min x 2h).',
    'This is a serious electrolyte disturbance. The medications you take for your kidneys and blood pressure can raise potassium, especially when combined with a high-potassium diet. We need to adjust your medications and diet. Avoid: oranges, bananas, tomatoes, potatoes, avocado, and salt substitutes.',
    'Nephrology review for medication reconciliation. Spironolactone should not be restarted. Dose-reduce Losartan. Dietary counselling. Check K+ 1 week after medication changes.',
    'Hyperkalaemia is a medical emergency — ECG changes indicate imminent cardiac arrest. Calcium Gluconate does NOT lower K+ — it stabilises the cardiac membrane. The shifters (insulin+glucose, salbutamol, bicarbonate) are temporary measures that last 2-4 hours. The removers (Furosemide, Resonium, dialysis) are definitive. Insulin+glucose is the most predictable and effective shifter. The triad of ACEi/ARB + MRA + CKD is the most common cause of life-threatening hyperkalaemia.',
    ['KDIGO Guidelines: CKD-MBD and Electrolytes', 'Kenya Clinical Guidelines: Electrolyte Disorders', 'UK Renal Association: Hyperkalaemia'],
  ),
  t('Renal Pharmacology', 'Nephrology', 'Acute Kidney Injury', 'NSAID-Induced Acute Kidney Injury in an Elderly Patient with Osteoarthritis', 'Intermediate',
    'Oliguria and confusion for 3 days after increasing ibuprofen dose for knee pain',
    '{name}, a {age}-year-old {occupation} from {location}, presents with 3 days of reduced urine output (estimated <400mL/day), generalized weakness, and mild confusion. Reports increasing bilateral knee pain over the past 2 weeks and has been taking ibuprofen 400mg TID (increased from PRN use). Also takes lisinopril for hypertension. Has not been eating well due to knee pain and reports reduced fluid intake. No history of kidney disease. No recent nephrotoxic drugs or contrast exposure. No haematuria or dysuria.',
    'Osteoarthritis (bilateral knees, diagnosed 5 years ago). Hypertension (10 years). No known diabetes. No prior kidney disease.',
    'Ibuprofen 400mg TID (recently increased from PRN over 2 weeks), Lisinopril 10mg daily, Amlodipine 5mg daily, Omeprazole 20mg daily.',
    'Dehydrated: dry mucous membranes, reduced skin turgor, reduced jugular venous pressure. BP 98/62 (lower than baseline of 140/85). HR 95 bpm. Temp 37.0°C. Bilateral膝关节crepitus and mild swelling, no erythema or warmth. No peripheral oedema. Lungs clear. Abdomen soft, no renal angle tenderness.',
    'Creatinine 3.2 mg/dL (baseline ~0.9 mg/dL — acute rise). BUN 45 mg/dL. K+ 6.0 mEq/L. Na+ 135 mEq/L. Bicarbonate 18 mEq/L (metabolic acidosis). eGFR 18 mL/min/1.73m². Urine osmolality 380 mOsm/kg. Urine Na+ 18 mEq/L. Fractional excretion of sodium (FENa) 0.8%. Urinalysis: muddy brown granular casts (ATN pattern). BUN/Cr ratio >20:1 (prerenal component). Blood glucose normal.',
    'Renal ultrasound: normal-sized kidneys (R 10.5cm, L 10.3cm), preserved cortical thickness, no hydronephrosis, no stones. Increased echogenicity suggestive of acute change.',
    'Acute Kidney Injury (AKI Stage 2) — NSAID-Induced Prerenal AKI with Superimposed Acute Tubular Necrosis, in the setting of ACEi use and volume depletion',
    ['NSAID-Induced AKI', 'ACEi-Induced AKI', 'Acute Tubular Necrosis (ischaemic)', 'Pre-renal AKI (dehydration)', 'Obstructive Uropathy', 'Rapidly Progressive Glomerulonephritis'],
    'Restore renal function (normalise creatinine and urine output), correct hyperkalaemia and metabolic acidosis, identify and remove nephrotoxins, prevent permanent kidney damage',
    '1. IMMEDIATELY STOP Ibuprofen (NSAID — the primary offending agent). 2. STOP Lisinopril (ACEi — contributes to efferent arteriolar dilation and worsens GFR in AKI; restart only after creatinine normalises). 3. IV Fluid resuscitation: 0.9% Normal Saline 500mL bolus over 1 hour, then reassess. Repeat if still dehydrated (target urine output >0.5 mL/kg/hr). 4. Hyperkalaemia management: K+ 6.0 — if ECG changes (peaked T waves): IV Calcium Gluconate 10% 10mL over 5 minutes. Nebulised Salbutamol 10-20mg. IV Insulin 10 units + 50% Dextrose 50mL. If no ECG changes: Kayexalate 15g PO. 5. Correct metabolic acidosis: Sodium Bicarbonate 500mg TID PO (or IV if severe). 6. Avoid all nephrotoxins: no NSAIDs, no aminoglycosides, no contrast. 7. Monitor fluid balance carefully (risk of overload if oliguria persists). 8. Consider renal replacement therapy (dialysis) if: K+ refractory, severe acidosis (pH <7.1), fluid overload, or uremic symptoms.',
    'Strict fluid balance monitoring (hourly I&O). Daily weights. Renal diet: moderate protein (0.8 g/kg/day), low K+ (avoid oranges, bananas, tomatoes, potatoes). Avoid all NSAIDs permanently. Educate on reading medication labels (NSAIDs in OTC products like Combiflex, Brufen).',
    'Stop Ibuprofen and Lisinopril. Start IV fluids. Manage hyperkalaemia aggressively. Monitor creatinine and K+ daily. Target urine output >0.5 mL/kg/hr. Once creatinine starts falling and urine output improving: gradual mobilisation. Nephrology review if no improvement in 48-72 hours. Avoid NSAIDs for future pain management — use paracetamol, topical NSAIDs, or low-dose codeine with caution.',
    '1. AKI caused by NSAIDs in the setting of concurrent ACEi use and volume depletion — a classic "triple whammy" nephrotoxic scenario. 2. Elderly patient at high risk for drug-induced AKI. 3. Requires medication reconciliation and patient education to prevent recurrence.',
    'Creatinine and K+ daily until downtrending. Urine output hourly. Fluid balance chart. BUN and bicarbonate every 2-3 days. Once stable: creatinine weekly until back to baseline. Monitor for relapse if NSAIDs re-exposed. Renal function should recover within 1-3 weeks if AKI was purely prerenal/ATN from NSAIDs.',
    'The medications you have been taking for pain and blood pressure can combine to damage your kidneys, especially when you are not drinking enough fluids. Ibuprofen is particularly harmful to the kidneys. We need to stop it permanently. For pain, you can use paracetamol (up to 4g/day) or topical diclofenac gel (which has much less systemic absorption). Always check with a pharmacist before taking any over-the-counter pain medication — many contain ibuprofen or other NSAIDs. Drink at least 2 litres of water daily.',
    'Nephrology follow-up in 1 week. Repeat creatinine and K+ weekly until normalised. Review all medications for nephrotoxic potential. Long-term: avoid NSAIDs permanently. Ensure adequate hydration. BP management: restart ACEi only after AKI fully resolved, at a lower dose, with close monitoring.',
    'The "triple whammy" of NSAID + ACEi/ARB + diuretic (or volume depletion) is the most common drug-induced AKI combination in elderly patients. NSAIDs inhibit prostaglandin-mediated afferent arteriolar vasodilation, while ACEi inhibit angiotensin II-mediated efferent arteriolar constriction — together they drastically reduce GFR. FENa <1% indicates prerenal physiology (kidney is still trying to conserve sodium). Muddy brown granular casts indicate some component of ATN has developed. In Kenya, ibuprofen is widely available OTC and often used without medical supervision — patient education is critical. Elderly patients on ACEi/ARB should be counselled about dehydration risks (hot weather, reduced intake, diarrhoea/vomiting) and to temporarily stop ACEi if acutely unwell ("sick day rules").',
    ['KDIGO Guidelines: AKI Management', 'Kenya Clinical Guidelines: Acute Kidney Injury', 'NICE Guidelines: AKI (CG169)'],
  ),
  t('Renal Pharmacology', 'Nephrology', 'CKD-Mineral and Bone Disorder', 'CKD-MBD with Secondary Hyperparathyroidism in Advanced CKD', 'Advanced',
    'Bone pain and itching for several months, worse in the legs and ribs',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 6-month history of progressive bone pain affecting the legs, ribs, and lower back. Pain is deep, aching, worse at night, and aggravated by weight-bearing. Also reports intractable pruritus (itching) that disrupts sleep, and recent episodes of muscle cramps in the calves. Denies joint swelling, fever, or trauma. Has been diagnosed with CKD Stage 4 for 3 years (due to diabetic nephropathy) but has been poorly compliant with follow-up. Last nephrology visit was 8 months ago.',
    'CKD Stage 4 (eGFR 25), Type 2 Diabetes (20 years), Hypertension, Diabetic Retinopathy (background), Peripheral Neuropathy.',
    'Metformin 1g BID (should be stopped at this eGFR), Gliclazide 80mg BID, Amlodipine 10mg daily, Ramipril 5mg daily, Atorvastatin 20mg daily, Ferrous Sulphate 200mg TID.',
    'Thin, chronically ill-appearing. BP 150/88. Pallor (conjunctival). Bilateral pedal oedema 2+. Bone tenderness: costal margin, tibial shafts, lumbar spine. No fractures clinically. Skin: excoriations from scratching, no calciphylaxis. No Kayser-Fleischer rings. Neuropathy: reduced sensation in feet (diabetic). No renal osteodystrophy deformities (no bowing, no fractures).',
    'Creatinine 4.1 mg/dL (eGFR 22). K+ 5.2 mEq/L. Ca 2.0 mmol/L (low, normal 2.2-2.6). Phosphate 1.8 mmol/L (high, normal 0.8-1.5). Intact PTH 350 pg/mL (very elevated, normal 10-65). 25-OH Vitamin D: 15 ng/mL (deficient, normal >30). ALP 280 U/L (elevated). Hb 9.0 g/dL (anaemia of CKD). Ferritin 250 ng/mL. Transferrin saturation (TSAT) 22%. HbA1c 8.5%. Ca x Phosphate product: 3.6 mmol²/L² (>5.5 increases calcification risk — borderline).',
    'X-ray pelvis and lateral spine: subperiosteal resorption along radial aspect of middle phalanges (classic for renal osteodystrophy). Looser zones (pseudofractures) in pubic rami. Basal ganglia calcification not present. No fractures. Renal ultrasound: small kidneys bilaterally (9.0 cm), consistent with CKD.',
    'CKD-Mineral and Bone Disorder (CKD-MBD) with Secondary Hyperparathyroidism (SHPT), Vitamin D Deficiency, Hyperphosphataemia, and Hypocalcaemia in CKD Stage 4',
    ['CKD-MBD (secondary hyperparathyroidism)', 'Primary Hyperparathyroidism', 'Osteomalacia (vitamin D deficiency)', 'Osteitis Fibrosa Cystica', 'Paget\'s Disease of Bone', 'Malignant Bone Disease (myeloma)'],
    'Normalise calcium and phosphate levels, suppress PTH to <2x upper limit of normal, prevent vascular calcification, relieve bone pain and pruritus, prevent fractures',
    '1. Phosphate binders (first-line for hyperphosphataemia): Calcium Carbonate 500mg 1-2 tablets WITH EACH MEAL (chewable, binds dietary phosphate in gut). If calcium already high or Ca x PO4 >5.5: switch to Sevelamer 800mg TID with meals (non-calcium-based — preferred to avoid hypercalcaemia and vascular calcification). 2. Vitamin D analogue: Calcitriol (active vitamin D) 0.25mcg daily, titrate up to 0.5mcg BID. Monitor calcium — risk of hypercalcaemia. OR Paricalcitol 1-2mcg daily (less hypercalcaemia risk than calcitriol). 3. Calcimimetic (if PTH remains >300 despite phosphate binders and vitamin D): Cinacalcet 30mg daily, titrate by 30mg every 4 weeks to target PTH <200 (max 60mg BID). Cinacalcet lowers calcium and phosphate while suppressing PTH. 4. Dietary phosphate restriction: <800-1000mg/day. Avoid: processed foods (phosphate additives), cola, dairy in excess, organ meats, processed meats. 5. STOP Metformin (contraindicated at eGFR <30). Switch to Gliclazide or insulin for diabetes control. 6. Consider IV iron if TSAT <20% (Ferric Carboxymaltose 500-1000mg IV).',
    'Dietary counselling: reduce phosphate intake (avoid processed foods, colas, processed meats). Calcium-rich foods in moderation (milk, yoghurt — but limited if calcium is high). Adequate protein intake (0.8-1.0 g/kg/day to prevent malnutrition). Regular weight-bearing exercise as tolerated. Skin care for pruritus: emollients, antihistamines (Cetirizine 10mg at bedtime).',
    'Start Calcitriol 0.25mcg daily + Calcium Carbonate 1g TID with meals. Refer to renal dietitian for phosphate restriction education. Check Ca, PO4, PTH in 2 weeks. If PTH still >300 and PO4 not at target: add Cinacalcet 30mg daily and titrate. Consider switching Calcium Carbonate to Sevelamer if Ca x PO4 product >5.5. Refer to nephrology for CKD-MBD optimisation and planning for renal replacement therapy. Ensure appropriate diabetes management without metformin.',
    '1. CKD-MBD is a systemic complication of advanced CKD affecting bone, cardiovascular system, and calcium-phosphate metabolism. 2. Secondary hyperparathyroidism leads to renal osteodystrophy (bone pain, fractures, deformities) and vascular calcification. 3. Requires coordinated management of phosphate, calcium, PTH, and vitamin D simultaneously.',
    'Serum Ca, PO4, PTH every 2-4 weeks until stabilised, then every 1-3 months. ALP monthly (marker of bone turnover). Vitamin D level every 3 months. Ca x PO4 product at every lab draw. Monitor for: hypercalcaemia (nausea, confusion, constipation, cardiac changes), hypocalcaemia (tetany, Chvostek/Trousseau signs), cinacalcet side effects (nausea, hypocalcaemia). DEXA scan if fracture risk assessment needed (interpret with caution in CKD-MBD — may underestimate risk).',
    'Your bones are being weakened by your kidney disease. The treatment involves taking medications to balance calcium and phosphate in your blood and to suppress a hormone (PTH) that is causing your bones to thin. Take the phosphate binders WITH your meals — they work by binding phosphate in the food you eat. The calcitriol helps your body absorb calcium properly. Avoid processed foods and colas — they contain high levels of phosphate additives. We will check your blood regularly to make sure the levels are improving.',
    'Nephrology clinic in 2-4 weeks for Ca/PO4/PTH recheck. Renal dietitian referral within 1 week. Cinacalcet dose review monthly. Plan for renal replacement therapy when eGFR approaches 15. Consider nephrology referral for parathyroidectomy if PTH >800 and refractory to medical therapy. Annual cardiac assessment (vascular calcification risk).',
    'CKD-MBD affects nearly 100% of patients with CKD Stage 4-5. The pathophysiology: declining GFR → phosphate retention → hypocalcaemia → secondary hyperparathyroidism → renal osteodystrophy. The Ca x PO4 product should be kept <5.5 mmol²/L² to prevent metastatic calcification (especially vascular). Cinacalcet is a calcimimetic that acts on the calcium-sensing receptor (CaSR) of the parathyroid gland — it lowers PTH, calcium, and phosphate simultaneously. In Kenya, Cinacalcet is expensive and may not be available in all facilities — dietary phosphate restriction and phosphate binders become even more critical. Vitamin D deficiency is extremely common in CKD patients and contributes to SHPT — always check and treat. Metformin must be stopped at eGFR <30 due to lactic acidosis risk.',
    ['KDIGO Guidelines: CKD-MBD', 'Kenya Clinical Guidelines: CKD Complications', 'NICE Guidelines: CKD-MBD (CG182)'],
  ),
];
