// ================================================================
// Renal Pharmacology — Case Templates (5 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const RENAL_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Renal Pharmacology', 'Nephrology', 'Chronic Kidney Disease', 'Newly Diagnosed CKD Stage 4 in a Patient with Diabetes and Hypertension', 'Intermediate',
    'Gradual fatigue, leg swelling, and frothy urine for 4 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive fatigue, bilateral ankle swelling, and noticing frothy/foamy urine for 4 months. Reports nocturia (3-4x/night). Has a long history of Type 2 Diabetes (15 years) and hypertension (12 years) with poor control. No known prior kidney disease.',
    'Type 2 Diabetes (15 years), Hypertension (12 years), Diabetic Retinopathy (background, on annual screening).',
    'Metformin 1g BID, Glibenclamide 10mg BID, Amlodipine 10mg daily, Losartan 50mg daily, Atorvastatin 20mg daily, Aspirin 75mg daily',
    'Overweight (BMI 30). BP 158/92 (poorly controlled). Fundoscopy: background diabetic retinopathy. Pedal oedema 2+ bilateral. No JVP elevation. Lungs clear. Peripheral pulses reduced. Neuropathy: reduced monofilament sensation in feet.',
    'Creatinine 3.2 mg/dL, eGFR 18 mL/min/1.73m2 (CKD Stage 4). Hb 9.5 g/dL (normocytic, normochromic — anaemia of CKD). K+ 4.8 mEq/L. Bicarbonate 18 mEq/L. Ca 8.6, Phos 5.2, PTH 180 pg/mL. Albumin 3.0 g/dL. HbA1c 8.8%. Urinalysis: protein 3+, no haematuria. UPCR (urine protein/creatinine ratio): 3500 mg/g (nephrotic range proteinuria). Hb electrophoresis: normal.',
    'Renal ultrasound: Bilateral small kidneys (R 9.2cm, L 9.0cm), increased cortical echogenicity, thin parenchyma — consistent with chronic kidney disease.',
    'Chronic Kidney Disease Stage 4 (eGFR 18) with Nephrotic-Range Proteinuria likely due to Diabetic Nephropathy and Hypertensive Nephrosclerosis',
    ['CKD Stage 4 (Diabetic Nephropathy)', 'CKD (Hypertensive Nephrosclerosis)', 'Primary Glomerulonephritis', 'Nephrotic Syndrome', 'Multiple Myeloma'],
    'Slow CKD progression, manage complications (anaemia, metabolic acidosis, mineral bone disease), prepare for renal replacement therapy, optimise CV risk',
    '1. Nephroprotective therapy: Losartan 50mg daily (max tolerated dose 100mg — reduces proteinuria and slows CKD progression). Add SGLT2i: Dapagliflozin 10mg daily (slows CKD progression, reduces albuminuria, CV benefit) — when eGFR >25. 2. Optimise BP target <130/80 mmHg. 3. Stop Metformin (contraindicated when eGFR <30 — risk of lactic acidosis). Switch insulin or sulfonylurea as needed to control glucose. 4. Anaemia management: Start Darbepoetin alfa (ESA) 0.45 mcg/kg SC weekly OR Epoetin alfa 50 units/kg SC 3x/week — target Hb 10-12 g/dL. Iron: Ferrous sulphate 200mg TID or IV iron (if ferritin <100 or TSAT <20%). 5. Mineral bone disease: Calcitriol 0.25-0.5mcg daily (for secondary hyperparathyroidism). Phosphate binders: Calcium carbonate 500-1000mg with meals OR Sevelamer if hypercalcaemia. 6. Metabolic acidosis: Sodium bicarbonate 600mg TID (target bicarbonate >22). 7. Diuretics: Furosemide 40mg daily for oedema (titrate as needed). 8. Vaccinations: HBV, influenza, pneumococcal.',
    'Dietary: Reduce salt (<2g/day), moderate protein (0.8 g/kg/day), limit K+ (avoid oranges, bananas, potatoes, tomatoes), limit phosphate (avoid soda, processed foods, organ meats). Fluid restriction if oedema or hyponatraemia. AV fistula education and vein preservation.',
    'Refer to nephrology for CKD management. Calculate eGFR monthly. Start Dapagliflozin 10mg if eGFR >25. Start ESA + iron. Start Calcitriol. Optimise BP and proteinuria. Educate on renal diet. Discuss RRT options: haemodialysis, peritoneal dialysis, or pre-emptive transplant. AV fistula creation when eGFR approaches 15-20.',
    '1. Advanced CKD with multiple complications requiring comprehensive nephrology care. 2. Multiple medication adjustments needed due to declining renal function (stop metformin, dose-adjust others). 3. Preparation for RRT needed in the near future.',
    'Monthly: eGFR, K+, bicarbonate, Hb, Ca, Phos, PTH, albumin. UPCR every 3 months. BP at every visit. HbA1c quarterly. Annual: cardiac echo, vascular access assessment. Monitor for: hyperkalaemia (ACEi/ARB + Dapagliflozin + low-K diet), fluid overload, ESA resistance (check Fe, B12, folate, inflammation).',
    'Your kidneys are working at only 18% of normal. We need to protect them, manage complications, and prepare for the possibility of dialysis or a kidney transplant in the future. Work closely with the dietitian — what you eat matters a lot now. Take your medications as prescribed. We will monitor your blood tests monthly.',
    'Nephrology clinic monthly. Prepare for RRT (education, counselling, AV fistula creation when eGFR 15-20). Vaccinations. Annual: cardiac assessment, eye exam, foot exam. Plan for transplant evaluation if eligible.',
    'CKD management is a multidisciplinary effort: nephrologist, dietitian, pharmacist, diabetes educator. The "holy trinity" of renoprotection: ACEi/ARB (for proteinuria), SGLT2i (for progression slowing), and tight BP control. Metformin must be stopped when eGFR <30 (lactic acidosis risk). ESA therapy should target Hb 10-12 g/dL (NOT higher — increased CV risk). Phosphate binders should be taken with meals. AV fistula is the preferred dialysis access (lower infection and thrombosis rates than catheters).',
    ['KDIGO Guidelines: CKD Evaluation and Management', 'Kenya Clinical Guidelines: CKD', 'WHO: CKD Management'],
  ),
  t('Renal Pharmacology', 'Nephrology', 'Hyperkalaemia', 'Life-Threatening Hyperkalaemia in a CKD Patient on ACE Inhibitor', 'Advanced',
    'Severe weakness, palpitations, and ECG changes on routine labs',
    '{name}, a {age}-year-old {occupation} from {location}, was brought to casualty after a routine clinic blood test showed potassium of 7.0 mEq/L. The lab phoned the result as a critical value. Patient reports mild muscle weakness and palpitations over the past 2 days. Has CKD Stage 4 and recently had his Losartan dose increased from 50mg to 100mg daily. Also started Spironolactone 25mg daily 1 week ago for resistant hypertension. Has been eating large amounts of fruit (oranges, bananas, tomatoes) as part of a "healthy diet."',
    'CKD Stage 4 (eGFR 22), Hypertension (resistant), Diabetes Type 2',
    'Losartan 100mg daily (recently increased), Spironolactone 25mg daily (new, started 1 week ago), Amlodipine 10mg, Metformin 500mg BID, Furosemide 40mg BID, Atorvastatin 20mg',
    'Generalised muscle weakness, areflexic. HR 50 (bradycardic), BP 140/80. ECG: Peaked T waves (tented, narrow-based), absent P waves, widened QRS (120ms). Lethargic but conscious.',
    'K+ 7.0 mEq/L (critical). Na+ 137, Cl- 105, Bicarb 16 (metabolic acidosis). Creatinine 2.8 mg/dL (eGFR 22). BUN 65 mg/dL. Glucose 150 mg/dL. Mg 1.8 mg/dL. Digoxin level: not on digoxin.',
    'ECG: Peaked T waves (tented), prolonged PR, absent P wave, widened QRS (120ms) — life-threatening hyperkalaemia.',
    'Life-Threatening Hyperkalaemia (K+ 7.0) with ECG Changes — Exacerbated by ACEi + MRA + High-K+ Diet in CKD',
    ['Hyperkalaemia (drug-induced)', 'Hyperkalaemia (CKD)', 'Hypokalaemic Periodic Paralysis', 'Digoxin Toxicity', 'Acute Kidney Injury'],
    'Immediately lower serum potassium to <6.0, protect the heart, correct acidosis, identify and remove precipitating factors',
    '1. Cardiac protection (IMMEDIATE): IV Calcium Gluconate 10% 10-20mL (or Calcium Chloride 5-10mL) over 2-5 minutes. Repeat in 5 minutes if ECG changes persist. 2. Shift K+ intracellularly (temporary): Nebulised Salbutamol 10-20mg (onset 30 min, reduces K+ by 0.5-1.5). OR IV Insulin 10 units + 50% Dextrose 50mL (onset 15 min, peak 30-60 min). 3. Remove K+ from body: IV Furosemide 40-80mg (if some renal function). KCl-binding resin: Calcium Resonium 15g TID PO/PR. Consider haemodialysis (definitive, if K+ remains >6.5 despite medical therapy). 4. Reverse precipitating factors: STOP Spironolactone. STOP/Hold Losartan (ACEi/ARB). Stop K+-sparing drugs. Review diet. 5. Correct acidosis: IV Sodium Bicarbonate 50-100 mEq (if pH <7.2).',
    'Cardiac monitoring continuously. Strict I/O. Limit K+ intake (avoid high-K+ foods). Identify and stop offending medications.',
    'EMERGENCY: IV Calcium Gluconate immediately for ECG changes. Then insulin+glucose, salbutamol, furosemide. Check K+ q1h. Consider dialysis if K+ refractory. Admit to HDU/ICU. Review all medications for K+ elevation risk.',
    '1. Acute life-threatening hyperkalaemia from combined use of ACEi + MRA + high-K+ diet in advanced CKD. 2. Polypharmacy-related adverse event requiring urgent medical management.',
    'Continuous ECG monitoring. K+ q1h until <6.0, then q4-6h. Glucose q1h (if insulin given). Creatinine and bicarbonate. Monitor for hypoglycaemia after insulin/dextrose (recheck glucose q30min x 2h).',
    'This is a serious electrolyte disturbance. The medications you take for your kidneys and blood pressure can raise potassium, especially when combined with a high-potassium diet. We need to adjust your medications and diet. Avoid: oranges, bananas, tomatoes, potatoes, avocado, and salt substitutes.',
    'Nephrology review for medication reconciliation. Spironolactone should not be restarted. Dose-reduce Losartan. Dietary counselling. Check K+ 1 week after medication changes.',
    'Hyperkalaemia is a medical emergency — ECG changes indicate imminent cardiac arrest. Calcium Gluconate does NOT lower K+ — it stabilises the cardiac membrane. The shifters (insulin+glucose, salbutamol, bicarbonate) are temporary measures that last 2-4 hours. The removers (Furosemide, Resonium, dialysis) are definitive. Insulin+glucose is the most predictable and effective shifter. The triad of ACEi/ARB + MRA + CKD is the most common cause of life-threatening hyperkalaemia.',
    ['KDIGO Guidelines: CKD-MBD and Electrolytes', 'Kenya Clinical Guidelines: Electrolyte Disorders', 'UK Renal Association: Hyperkalaemia'],
  ),
];
