// ================================================================
// Respiratory Pharmacology — Case Templates
// 8 templates covering: Asthma, COPD, TB, CAP, HAP, Allergic
// Rhinitis, Bronchiectasis, Acute Bronchitis
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';

function tpl(
  pharmacologySubject: string, specialty: string, disease: string,
  title: string, difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string, hpi: string, pmh: string, medHx: string,
  pe: string, labs: string, imaging: string,
  diagnosis: string, ddx: string[],
  goals: string, pharm: string, nonPharm: string, carePlan: string,
  dtps: string, monitoring: string, counselling: string, followUp: string,
  pearls: string, references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject, specialty, disease, title, difficulty,
    chiefComplaintTemplate: chiefComplaint, hpiTemplate: hpi,
    pmhTemplate: pmh, medHxTemplate: medHx, peTemplate: pe,
    labsTemplate: labs, imagingTemplate: imaging, diagnosis, ddx,
    goalsTemplate: goals, pharmTemplate: pharm,
    nonPharmTemplate: nonPharm, carePlanTemplate: carePlan,
    dtpsTemplate: dtps, monitoringTemplate: monitoring,
    counsellingTemplate: counselling, followUpTemplate: followUp,
    pearlsTemplate: pearls, references,
  };
}

export const RESPIRATORY_TEMPLATES: ClinicalCaseTemplate[] = [
  tpl(
    'Respiratory Pharmacology', 'Respiratory Medicine', 'Asthma',
    'Acute Severe Asthma Exacerbation with Poor Controller Adherence',
    'Intermediate',
    'Worsening shortness of breath, chest tightness, and wheezing for 2 days',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive dyspnoea, wheezing, and non-productive cough. Has been using salbutamol inhaler 6-8 times daily for the past 48 hours with minimal relief. Reports multiple recent asthma attacks triggered by the cold season and dust. Has not been using preventer inhaler regularly due to cost.',
    'Persistent asthma diagnosed 5 years ago, Allergic rhinitis, Occasional sinusitis',
    'Salbutamol MDI 100mcg PRN (uses 2-3 times daily at baseline), Beclometasone MDI 100mcg BID (defaulted 3 months ago due to cost)',
    'Speaking in broken sentences, accessory muscle use (suprasternal retractions), diffuse expiratory wheeze bilaterally, prolonged expiration. RR 32, HR 115, SpO2 89% on room air. PEF 180 L/min (35% of predicted).',
    'WBC 11.2 x10^9/L with eosinophilia 8%. CRP 25 mg/L. Serum K+ 3.3 mEq/L (mild hypokalaemia from beta-agonist use). ABG: pH 7.43, pCO2 32 mmHg, pO2 68 mmHg on RA, HCO3 22.',
    'Chest X-ray: hyperinflated lungs, no pneumothorax or consolidation. ECG: sinus tachycardia.',
    'Acute Severe Asthma Exacerbation (BTS Step 3)',
    ['Acute Asthma', 'COPD Exacerbation', 'Anaphylaxis', 'Foreign Body Aspiration', 'Pneumothorax'],
    'Relieve bronchospasm rapidly, correct hypoxaemia, reduce airway inflammation, re-establish controller therapy',
    '1. Oxygen via non-rebreather mask at 15L/min, target SpO2 94-98%. 2. Nebulised Salbutamol 5mg + Ipratropium 0.5mg every 20 mins for 3 doses, then 4-hourly. 3. IV Hydrocortisone 200mg stat, then oral Prednisolone 50mg daily for 5-7 days. 4. If PEF <50% after initial treatment: consider IV Magnesium Sulfate 2g over 20 mins. 5. Monitor K+ and replace if <3.5.',
    'Upright positioning, reassurance, avoid sedatives. High-flow nasal oxygen if SpO2 remains <92%. Prepare for NIV if respiratory acidosis develops.',
    'Admit to medical ward. Back-to-back nebulisers and systemic steroids. Monitor PEF every 30 mins initially. When improving, transition nebulisers to MDI + spacer (4-10 puffs 4-hourly). Re-establish Beclometasone 200mcg BID via spacer before discharge. Create written Asthma Action Plan.',
    '1. Suboptimal controller adherence leading to severe exacerbation. 2. Overuse of short-acting beta-agonist indicating poor asthma control. 3. Access barrier: cost of preventer medication.',
    'PEF every 30 mins until improving, then 4-hourly. SpO2 continuously. ECG monitoring. Serum K+. Assess need for step-up therapy (add LABA or increase ICS dose).',
    'Demonstrate correct MDI + spacer technique. Explain difference between preventer (Beclometasone) and reliever (Salbutamol). Discuss the Asthma Action Plan: green = well, yellow = worsening, red = emergency. Emphasise daily preventer use even when well.',
    'Asthma clinic follow-up in 1 week. Repeat PEF and symptom diary review. Consider stepping up to ICS/LABA combination if attacks persist.',
    'A PEF <33% of predicted indicates life-threatening asthma. Silent chest (no wheeze) is a sign of severe obstruction and impending respiratory arrest. IV magnesium is second-line but effective in severe exacerbations. Always prescribe an spacer with MDI — it doubles lung deposition.',
    ['GINA Guidelines 2024: Global Strategy for Asthma Management', 'BTS/SIGN Guideline for Asthma Management', 'Kenya Essential Medicines List: Respiratory Medicines'],
  ),

  tpl(
    'Respiratory Pharmacology', 'Respiratory Medicine', 'COPD',
    'Acute Exacerbation of COPD in a Long-Term Smoker',
    'Intermediate',
    'Worsening shortness of breath, increased sputum purulence and volume for 4 days',
    '{name}, a {age}-year-old {occupation} from {location}, presents with increased dyspnoea, productive cough with yellow-green sputum, and wheezing for 4 days. Has had 2 similar exacerbations in the past year requiring hospitalisation. Long-term smoker with 40 pack-year history, continues to smoke. Has been using inhalers inconsistently.',
    'COPD (GOLD Stage 3), Hypertension, Osteoporosis (from long-term steroid use)',
    'Tiotropium 18mcg inhaler daily (uses occasionally), Salbutamol MDI PRN, no ICS/LABA. Amlodipine 5mg daily.',
    'Barrel-shaped chest, pursed-lip breathing, use of accessory muscles. Diffuse wheeze and prolonged expiration. Decreased breath sounds at bases. No peripheral oedema. JVP not elevated.',
    'ABG (room air): pH 7.35, pCO2 52 mmHg, pO2 55 mmHg, HCO3 28. WBC 14.5 x10^9/L (neutrophilia). CRP 85 mg/L. Sputum culture: pending. Chest X-ray: hyperinflation, flattened diaphragm, no consolidation. ECG: P pulmonale.',
    'Chest X-ray: Hyperinflated lungs, flattened hemidiaphragms, increased retrosternal airspace. No acute consolidation.',
    'Acute Exacerbation of COPD (Anthonisen Type I — all 3 cardinal symptoms)',
    ['COPD Exacerbation', 'Community-Acquired Pneumonia', 'Heart Failure Exacerbation', 'Pulmonary Embolism', 'Bronchiectasis Exacerbation'],
    'Treat infection, relieve bronchospasm, correct hypoxaemia, prevent respiratory failure, avoid future exacerbations',
    '1. Oxygen via Venturi mask 24-28% to target SpO2 88-92% (caution: CO2 retention). 2. Nebulised Salbutamol 5mg + Ipratropium 0.5mg 4-hourly. 3. IV Hydrocortisone 200mg stat then oral Prednisolone 30mg daily for 5-7 days. 4. Antibiotics: Amoxicillin/Clavulanate 625mg PO TID for 7 days (or Doxycycline 100mg BID if penicillin-allergic). 5. Consider NIV if pH <7.35 and pCO2 >45 despite medical therapy.',
    'Smoking cessation counselling. Chest physiotherapy and sputum clearance techniques. Pulmonary rehabilitation referral. Nutritional support.',
    'Admit to medical ward. Controlled oxygen therapy. Bronchodilators, steroids, and antibiotics as above. Monitor ABGs. Assess for NIV need. Once stable, optimise maintenance therapy: LAMA/LABA/ICS triple therapy. Vaccinate against influenza and pneumococcus before discharge.',
    '1. Acute infective exacerbation requiring immediate antibiotics and bronchodilators. 2. Risk of hypercapnic respiratory failure requiring NIV. 3. Suboptimal maintenance therapy (no ICS/LABA).',
    'ABGs daily or as clinically indicated. SpO2 continuously. Sputum colour and volume. Temperature. Monitor for CO2 retention (headache, confusion, flapping tremor).',
    'Emphasise smoking cessation as the single most important intervention. Demonstrate correct inhaler technique. Teach sputum clearing techniques (huff cough). Explain signs of worsening to watch for. Importance of pulmonary rehabilitation.',
    'COPD clinic in 2 weeks. Pulmonary rehabilitation referral. Smoking cessation clinic. Vaccinations: annual influenza, pneumococcal (PCV13 then PPSV23).',
    'In COPD exacerbations, oxygen must be titrated carefully to avoid worsening hypercapnia by blunting hypoxic drive. Target SpO2 88-92%, not higher. NIV is first-line for hypercapnic respiratory failure. Triple therapy (ICS/LAMA/LABA) reduces exacerbation frequency in GOLD Group E.',
    ['GOLD 2024 Report: Global Strategy for COPD', 'NICE Guideline: COPD in Over 16s', 'Kenya Essential Medicines List: COPD Medicines'],
  ),

  tpl(
    'Respiratory Pharmacology', 'Infectious Diseases', 'Tuberculosis',
    'New Diagnosis of Pulmonary Tuberculosis in a Young Adult',
    'Intermediate',
    'Chronic cough for 3 weeks, night sweats, weight loss, and haemoptysis',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 3-week history of persistent cough producing yellowish sputum, intermittent haemoptysis (streaks of blood), drenching night sweats, unintentional weight loss of 6 kg over 2 months, and low-grade fever. Lives in a crowded shared apartment with 4 other family members. Works in a market where there is high dust exposure.',
    'No significant PMH. No prior TB treatment. No known HIV status.',
    'No regular medications',
    'Thin-built, pale conjunctivae. Respiratory: dullness to percussion over right upper lobe, bronchial breath sounds, crackles. No lymphadenopathy. No neck stiffness. No BCG scar visible.',
    'Sputum Xpert MTB/RIF: Detected, Rifampicin resistance: Not detected. Sputum smear microscopy: AFB 2+. HIV test: Negative. Hb 10.2 g/dL. ESR 85 mm/hr.',
    'Chest X-ray: Right upper lobe consolidation with cavitation, hilar lymphadenopathy. Findings suggestive of active pulmonary TB.',
    'Pulmonary Tuberculosis (New, Smear-Positive, Rifampicin-Sensitive)',
    ['Pulmonary TB', 'Community-Acquired Pneumonia', 'Lung Cancer', 'Bronchiectasis', 'Fungal Pneumonia'],
    'Achieve bacteriological cure, prevent transmission, prevent drug resistance, minimise drug side effects',
    '1. Start standard 4-drug intensive phase: Rifampicin 600mg daily (10mg/kg), Isoniazid 300mg daily (5mg/kg), Pyrazinamide 1500mg daily (25mg/kg), Ethambutol 800mg daily (15mg/kg) for 2 months. 2. Continuation phase (after 2 months): Rifampicin 600mg + Isoniazid 300mg daily for 4 months. 3. Pyridoxine (Vitamin B6) 25mg daily with INH to prevent peripheral neuropathy. Weight-based dosing with current weight: 56 kg.',
    'Cough etiquette: wear mask, cover mouth when coughing, sputum disposal in designated container. Adequate ventilation at home. Nutritional counselling: high-protein, high-energy diet.',
    'Initiate DOT (Directly Observed Therapy) through local TB clinic. Register patient in the National TB Program. Monitor for drug-induced hepatitis (check LFTs at baseline and monthly). Provide Pyridoxine. Contact tracing: screen all household contacts for TB. Test for HIV if not already done.',
    '1. Active infectious pulmonary TB requiring immediate initiation of anti-TB therapy. 2. Risk of transmission to close contacts (crowded living conditions). 3. Potential drug-induced hepatotoxicity requiring monitoring.',
    'Weekly: sputum smear microscopy until conversion (typically 2-8 weeks). Monthly: LFTs, serum creatinine, uric acid (if on PZA). Visual acuity testing for Ethambutol toxicity (monthly). Watch for: jaundice, visual changes, rash, peripheral neuropathy.',
    'Explain the full TB treatment duration (6 months minimum). Importance of adherence — stopping early leads to drug resistance and relapse. DOT ensures compliance. Cover cough with tissue/mask. Separate sleeping area if possible. Side effects: reddish-orange urine (rifampicin — harmless), hepatitis signs (jaundice, dark urine, nausea — report immediately).',
    'TB clinic follow-up at 2, 4, and 6 months. Repeat chest X-ray at 6 months. Sputum conversion check at 2 months. If positive at 2 months, extend intensive phase to 3 months.',
    'TB is curable with standard 6-month regimens. DOT is critical for adherence. INH-induced peripheral neuropathy is prevented by Pyridoxine 25mg daily. Ethambutol can cause optic neuritis — test red-green colour discrimination monthly. Rifampicin is a potent CYP450 inducer — check drug interactions (OCPs, warfarin, ARVs).',
    ['Kenya National TB Program Guidelines', 'WHO Guidelines for Treatment of Drug-Susceptible TB', 'National TB & Leprosy Program (NTLP-Kenya)'],
  ),

  tpl(
    'Respiratory Pharmacology', 'Respiratory Medicine', 'Community Acquired Pneumonia',
    'Community-Acquired Pneumonia in an Adult with No Comorbidities',
    'Beginner',
    'Fever, productive cough with rusty sputum, and pleuritic chest pain for 3 days',
    '{name}, a {age}-year-old {occupation} from {location}, presents with acute onset of high-grade fever (39°C), rigours, productive cough with rust-coloured sputum, and sharp right-sided chest pain worsened by deep breathing. Symptoms started 3 days ago after being caught in the rain. Reports myalgia and generalised weakness. No haemoptysis.',
    'Previously healthy. No chronic medical conditions. Non-smoker. No recent hospitalisation.',
    'No regular medications. Occasional paracetamol for fevers.',
    'Acutely unwell, febrile, tachypnoeic. Right lower lobe: dull percussion, bronchial breath sounds, egophony, fine crackles. No cyanosis. No signs of sepsis.',
    'WBC 18.5 x10^9/L (neutrophilia 85%). CRP 180 mg/L. Procalcitonin 2.5 ng/mL. Blood cultures: drawn. Sputum Gram stain: Gram-positive diplococci (Streptococcus pneumoniae). Sputum culture: pending. RBS 5.8 mmol/L. HIV test: negative.',
    'Chest X-ray: Right lower lobe consolidation with air bronchograms. No pleural effusion.',
    'Community-Acquired Pneumonia (Streptococcus pneumoniae) — CURB-65 Score 1',
    ['CAP (Pneumococcal)', 'Atypical Pneumonia (Mycoplasma)', 'Pulmonary TB', 'Pulmonary Embolism with Infarction', 'Bronchiectasis'],
    'Eradicate infection, prevent complications (empyema, sepsis), return to baseline function',
    '1. First-line antibiotics per Kenya CAP guidelines: Oral Amoxicillin 1g TID for 7 days (mild-moderate). 2. If hospitalised for IV therapy: IV Ampicillin 2g QID + Doxycycline 200mg stat then 100mg BID (or Azithromycin 500mg IV daily). 3. Alternative: IV Ceftriaxone 1g daily if concern for Gram-negative coverage. 4. Paracetamol 1g QID for fever and pleuritic pain. 5. Monitor for clinical response at 48-72 hours.',
    'Increased oral fluids. Rest. Cough etiquette. Smoking cessation (if smoker).',
    'Given CURB-65 score of 1 (low mortality risk), manage as outpatient with oral antibiotics if home environment adequate and able to tolerate oral medications. If admitting for social reasons or clinical judgement: IV antibiotics for 48 hours then switch to oral once afebrile and improving. Complete 7-day course total.',
    '1. Active bacterial pneumonia requiring prompt antibiotic therapy. 2. Risk of complications (parapneumonic effusion, empyema, sepsis) if not adequately treated.',
    'Temperature 6-hourly. Oxygen saturation. Clinical response at 48 hours (fever curve, respiratory symptoms). Repeat CXR in 6-8 weeks if slow to resolve or smoker (to exclude underlying mass).',
    'Complete the full antibiotic course even if feeling better. Return if fever returns, chest pain worsens, or develops shortness of breath. Deep breathing exercises. Avoid smoke and dust. Annual influenza vaccination recommended.',
    'GP clinic review in 2 weeks. Repeat CXR at 6-8 weeks to document radiographic resolution. If smoker, discuss smoking cessation.',
    'CURB-65: Confusion (1 pt), Urea >7 (1 pt), RR >30 (1 pt), BP <90/60 (1 pt), Age >65 (1 pt). Score 0-1: outpatient; 2: admit; >3: severe CAP, ICU. Streptococcus pneumoniae is the most common cause of CAP in adults. Amoxicillin remains first-line in Kenya for mild-moderate CAP per national guidelines.',
    ['Kenya Clinical Guidelines: Management of Pneumonia', 'BTS Guidelines for CAP', 'WHO Pocket Book: Pneumonia Management'],
  ),

  tpl(
    'Respiratory Pharmacology', 'Respiratory Medicine', 'Hospital Acquired Pneumonia',
    'Late-Onset Hospital-Acquired Pneumonia in Post-Surgical Patient',
    'Advanced',
    'New fever, purulent sputum, and worsening oxygenation 8 days after abdominal surgery',
    '{name}, a {age}-year-old {occupation} from {location}, is a post-operative patient on Day 8 after emergency laparotomy for perforated duodenal ulcer. Developed new fever of 38.8°C, purulent tracheal secretions, and increasing oxygen requirements over the past 24 hours. Initially extubated on Day 2 but required re-intubation yesterday for respiratory distress. Has a central line and urinary catheter in situ.',
    'Perforated duodenal ulcer s/p laparotomy, Hypertension, Type 2 Diabetes',
    'IV Ceftriaxone 1g daily + IV Metronidazole 500mg TDS (peri-operative antibiotics, Day 8), Insulin sliding scale, Amlodipine 5mg daily via NG',
    'Intubated, sedated. Temperature 38.9°C. Copious purulent yellow-green tracheal secretions on suction. Lungs: bilateral coarse crackles, right lower lobe more prominent. Surgical wound clean, no discharge.',
    'WBC 22.5 x10^9/L (left shift). CRP 320 mg/L. Procalcitonin 4.8 ng/mL. Tracheal aspirate Gram stain: Many Gram-negative rods. ABG (on FiO2 0.5, PEEP 8): pH 7.31, pCO2 40, pO2 88, HCO3 20, PaO2/FiO2 ratio 176 (moderate ARDS). Blood cultures: drawn.',
    'Chest X-ray: New bilateral infiltrates, dense consolidation in right lower lobe. No effusion.',
    'Late-Onset Hospital-Acquired Pneumonia (HAP) with Possible Multi-Drug Resistant Organisms',
    ['HAP (Ventilator-Associated)', 'ARDS', 'Pulmonary Oedema', 'Pulmonary Embolism', 'Aspiration Pneumonitis'],
    'Identify causative organism, initiate appropriate broad-spectrum antibiotics, prevent progression to sepsis, wean from ventilation',
    '1. Send tracheal aspirate for culture and sensitivity before antibiotics. 2. Start empiric broad-spectrum antibiotics for late-onset HAP per local antibiogram: IV Piperacillin/Tazobactam 4.5g Q6H + IV Vancomycin 15-20 mg/kg Q12H (dose based on renal function). 3. Alternative: IV Meropenem 1g Q8H + IV Vancomycin (if high MRSA prevalence). 4. De-escalate when culture results return. 5. Consider antifungal (IV Fluconazole or Echinocandin) if no response after 72 hours.',
    'Elevate head of bed 30-45°. Daily sedation vacation and spontaneous breathing trials. Oral care with chlorhexidine 0.12% Q6H. VAP prevention bundle. DVT and stress ulcer prophylaxis.',
    'ICU admission. Start empiric antibiotics. Strict input/output chart. Daily microbiology review for de-escalation. Monitor CPIS (Clinical Pulmonary Infection Score) daily. Ventilator weaning protocol once improving. If no response in 72 hours: bronchoscopy with BAL, consider fungal or viral aetiology, consider CT chest.',
    '1. Late-onset HAP in a post-surgical patient with high risk of MDR organisms. 2. Ventilator dependence with moderate ARDS requiring careful fluid and ventilator management. 3. Multiple invasive devices (ETT, CVC, catheter) increasing infection risk.',
    'Daily: WBC, CRP, procalcitonin, CXR, CPIS score, temperature curve. ABGs as needed. Ventilator parameters (PaO2/FiO2, PEEP, plateau pressure). Renal function for antibiotic dosing. Blood cultures if new fever spikes.',
    'Explain the situation to family: patient has developed a hospital-acquired lung infection requiring strong antibiotics and ongoing breathing support. Recovery may be prolonged. Daily updates will be provided.',
    'Tracheostomy if prolonged ventilation expected. Step-down to ward when off vasopressors, improving oxygenation, and no fever. Follow-up CXR at 2 weeks post-discharge.',
    'Late-onset HAP (>5 days hospitalisation) is more likely to be caused by MDR organisms (Pseudomonas, Acinetobacter, MRSA, ESBL-producing Enterobacteriaceae). Empiric antibiotics must cover these. De-escalation based on cultures is critical to prevent further resistance. VAP prevention bundles reduce incidence by 50%.',
    ['IDSA/ATS Guidelines for HAP/VAP', 'Kenya Clinical Guidelines: Hospital-Acquired Infections', 'WHO: Prevention of HAP'],
  ),

  tpl(
    'Respiratory Pharmacology', 'ENT', 'Allergic Rhinitis',
    'Persistent Allergic Rhinitis Affecting Quality of Life',
    'Beginner',
    'Chronic nasal congestion, sneezing, and itchy eyes for most of the year',
    '{name}, a {age}-year-old {occupation} from {location}, presents with persistent symptoms of nasal congestion, clear rhinorrhoea, paroxysmal sneezing (especially in the morning), itchy nose and palate, and watery itchy eyes. Symptoms are worse during the rainy season but present year-round. Reports fatigue and difficulty concentrating at work due to poor sleep from nasal obstruction. Has tried various over-the-counter antihistamines with partial relief.',
    'Mild asthma (diagnosed in childhood, now well-controlled). No known drug allergies.',
    'Loratadine 10mg daily (intermittent use), Salbutamol MDI PRN (rarely used)',
    'Nasal mucosa: pale, boggy, oedematous turbinates with clear discharge. Allergic shiner (dark circles under eyes). Nasal crease (from frequent nose rubbing). Conjunctival injection. Post-nasal drip visible on oropharynx. Lungs clear.',
    'Allergy skin prick test: Positive to dust mites (Dermatophagoides pteronyssinus), grass pollen, cockroach. Total IgE: 250 IU/mL (elevated). Eosinophil count: 6%. Nasal endoscopy: bilateral oedematous turbinates, no polyps.',
    'No imaging indicated.',
    'Persistent Moderate-to-Severe Allergic Rhinitis (ARIA Classification)',
    ['Allergic Rhinitis', 'Non-Allergic Rhinitis', 'Chronic Sinusitis', 'Nasal Polyps', 'Deviated Nasal Septum'],
    'Control symptoms, improve quality of life and sleep, prevent complications (sinusitis, asthma exacerbation)',
    '1. Step-up therapy per ARIA guidelines: Step 1: Intranasal Corticosteroid (Fluticasone Furoate 27.5mcg, 2 sprays each nostril daily). Step 2: Add oral antihistamine (Cetirizine 10mg or Levocetirizine 5mg daily). Step 3: If eye symptoms prominent, add Olopatadine eye drops 0.1% BID. 2. Consider Montelukast 10mg daily if concomitant asthma. 3. Saline nasal irrigation daily. 4. Allergen avoidance measures.',
    'Allergen mitigation: dust mite covers for mattress and pillows, wash bedding in hot water weekly, remove carpets and stuffed toys, keep windows closed during pollen season, use HEPA air purifier.',
    'Start intranasal corticosteroid daily — takes 1-2 weeks for full effect. Add oral antihistamine for immediate relief. Saline nasal rinses BID. Review in 4 weeks. If inadequate response, consider allergy immunotherapy referral.',
    '1. Chronic allergic inflammation requiring consistent anti-inflammatory therapy. 2. Impaired quality of life due to poorly controlled symptoms.',
    'Symptom diary (nasal congestion, sneezing, rhinorrhoea, itching — 0-3 scale). Peak nasal inspiratory flow if available. Assess asthma control (ACT score).',
    'Intranasal steroids are safe and effective but must be used daily — not PRN. Correct technique: aim spray slightly away from septum. Clean nozzle weekly. Avoid decongestant sprays (risk of rhinitis medicamentosa).',
    'Allergy clinic in 4 weeks for treatment response assessment. Consider referral for immunotherapy if moderate-severe and not controlled on pharmacotherapy.',
    'Intranasal corticosteroids are the most effective treatment for allergic rhinitis — they work better than oral antihistamines alone. The ARIA guidelines recommend a step-up approach. Decongestant nasal sprays should not be used for >5 days due to rebound congestion. Allergen immunotherapy is disease-modifying and should be considered early.',
    ['ARIA Guidelines 2024: Allergic Rhinitis', 'Kenya ENT Society Guidelines', 'WHO: Allergic Rhinitis Management'],
  ),

  tpl(
    'Respiratory Pharmacology', 'Respiratory Medicine', 'Bronchiectasis',
    'Bronchiectasis Exacerbation in a Patient with Previous TB',
    'Advanced',
    'Increased cough with purulent sputum, haemoptysis, and worsening shortness of breath',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a 5-day history of increased cough producing large volumes (approx 150mL/day) of yellow-green purulent sputum, streaky haemoptysis, worsening dyspnoea, and low-grade fever. Has a known history of post-TB bronchiectasis diagnosed 8 years after completing TB treatment. Uses an inhaled corticosteroid/LABA combination and performs daily chest physiotherapy.',
    'Pulmonary TB treated 12 years ago (completed 6-month regimen), Post-TB bronchiectasis, Chronic Pseudomonas colonisation',
    'Budesonide/Formoterol 160/4.5mcg 2 puffs BID, Salbutamol MDI PRN, Chest physiotherapy daily, occasional courses of oral antibiotics',
    'Digital clubbing. Respiratory: coarse crackles throughout both lung fields, more prominent at bases. Scattered wheeze. Use of accessory muscles. No cyanosis. Sputum pot shows purulent green sputum.',
    'WBC 13.5 x10^9/L (neutrophilia). CRP 95 mg/L. Sputum culture: Heavy growth of Pseudomonas aeruginosa (mucoid phenotype). Hb 11.0 g/dL. ABG: pH 7.38, pCO2 45, pO2 72 on RA. HIV: negative.',
    'Chest X-ray: Bilateral lower lobe tram-track opacities, cystic changes, volume loss at right upper lobe (prior TB). HRCT chest (recent): Bilateral bronchiectasis, most severe in lower lobes.',
    'Acute Infective Exacerbation of Bronchiectasis (Pseudomonas aeruginosa)',
    ['Bronchiectasis Exacerbation', 'COPD Exacerbation', 'Pneumonia', 'Pulmonary TB Reactivation', 'Allergic Bronchopulmonary Aspergillosis'],
    'Eradicate or suppress Pseudomonas, improve sputum clearance, reduce exacerbation frequency, preserve lung function',
    '1. Antibiotics based on previous sputum cultures: Oral Ciprofloxacin 750mg BID for 14 days (if Pseudomonas sensitive). 2. If resistant or severe exacerbation: consider IV antibiotics — Ceftazidime 2g Q8H or Meropenem 1g Q8H + Tobramycin (if needed). 3. Airway clearance: Nebulised hypertonic saline (7%) BID + chest physiotherapy TID. 4. Bronchodilator: Salbutamol neb 5mg before physiotherapy. 5. If haemoptysis significant: consider bronchial artery embolisation (BAE).',
    'Chest physiotherapy (postural drainage + percussion) TID. Increased fluid intake to thin secretions. Nutritional support: high-protein diet. Pulmonary rehabilitation.',
    'Admit for IV antibiotics and intensive chest physiotherapy. Send sputum for culture and sensitivity. Start IV Ceftazidime 2g Q8H + Ciprofloxacin 750mg PO BID. Monitor sputum volume and purulence daily. Consider N-acetylcysteine 600mg BID as mucolytic. If frequent exacerbations (>3/year), consider long-term macrolide therapy (Azithromycin 250mg 3x/week).',
    '1. Acute infective exacerbation of bronchiectasis with Pseudomonas requiring targeted antibiotic therapy. 2. Chronic sputum production and impaired airway clearance requiring physiotherapy. 3. Risk of disease progression and lung function decline with each exacerbation.',
    'Daily: sputum volume and purulence chart, temperature, oxygen saturation. CRP and WBC trend. Pulmonary function tests when stable. Sputum culture at end of antibiotics. Monitor for aminoglycoside toxicity if on Tobramycin.',
    'Perform chest physiotherapy diligently every day — it is as important as medication. Drink plenty of water to keep sputum thin. Watch for signs of exacerbation: change in sputum colour/volume, increased SOB, fever. Complete antibiotics fully.',
    'Respiratory clinic in 4 weeks. Repeat sputum culture. Consider long-term azithromycin if >3 exacerbations/year. Annual influenza and pneumococcal vaccines. Pulmonary function tests every 6-12 months.',
    'Pseudomonas aeruginosa is the most common pathogen in advanced bronchiectasis. Mucoid phenotype indicates chronic infection. Ciprofloxacin is the only oral anti-pseudomonal — resistance emerges rapidly with repeated use. Nebulised hypertonic saline improves mucociliary clearance. Long-term macrolides reduce exacerbation frequency via immunomodulation, not just anti-inflammatory effects.',
    ['BTS Guideline for Bronchiectasis', 'ERS Guidelines for Bronchiectasis', 'Kenya Clinical Guidelines: Respiratory Infections'],
  ),

  tpl(
    'Respiratory Pharmacology', 'Respiratory Medicine', 'Acute Bronchitis',
    'Acute Bronchitis with Troublesome Cough in Otherwise Healthy Adult',
    'Beginner',
    'Persistent cough and fever for 5 days after a common cold',
    '{name}, a {age}-year-old {occupation} from {location}, presents with a persistent hacking cough, initially dry now productive of clear sputum, associated with low-grade fever, sore throat, and general malaise. Symptoms started 5 days ago with coryzal symptoms (runny nose, sneezing). Cough is worse at night interfering with sleep. No shortness of breath, no wheezing, no haemoptysis.',
    'No significant PMH. Non-smoker. No asthma or allergies. Fully vaccinated.',
    'No regular medications. Has been taking over-the-counter Paracetamol and Vitamin C.',
    'Afebrile (37.2°C). Mild pharyngeal erythema. Lungs clear to auscultation, no wheeze or crackles. Chest clear on percussion. No lymphadenopathy.',
    'WBC 8.2 x10^9/L (normal differential). CRP 15 mg/L. Viral PCR (nasopharyngeal swab): pending. Rapid strep test: negative.',
    'Chest X-ray (if indicated): No consolidation, no infiltrates, normal lung fields.',
    'Acute Bronchitis (Likely Viral Aetiology)',
    ['Acute Bronchitis', 'Community-Acquired Pneumonia', 'Post-Viral Cough', 'Pertussis', 'Asthma Exacerbation'],
    'Symptom relief, exclude pneumonia, avoid unnecessary antibiotic use, return to normal activity',
    '1. No antibiotics indicated — this is almost certainly viral. 2. Symptomatic management: Honey 10mL at bedtime (cough suppressant, evidence-supported). Steam inhalation. 3. If cough severely disrupting sleep: Short-term Dextromethorphan 15-30mg at bedtime (weak evidence, use sparingly). 4. Paracetamol 1g QID PRN for fever/malaise. 5. Salbutamol inhaler only if wheeze present.',
    'Adequate fluid intake (warm honey-lemon drinks). Rest. Humidify room air. Avoid smoke and irritants. Sleeping with head elevated may reduce nighttime cough.',
    'Outpatient management. Reassure patient that viral bronchitis typically lasts 7-21 days and antibiotics will not help. Return if develops high fever, shortness of breath, haemoptysis, or no improvement after 3 weeks.',
    '1. No drug therapy problem — antibiotic stewardship: viral infection not requiring antimicrobials. 2. Patient education: managing expectations about duration of viral cough.',
    'Symptom diary. Temperature. Return if worsening symptoms or persistent fever beyond 7 days.',
    'Explain that antibiotics do not work for viral infections and taking them unnecessarily contributes to antibiotic resistance. The cough can last 2-3 weeks even as you improve. Honey at bedtime is as effective as over-the-counter cough medicines for nighttime symptoms.',
    'No specific follow-up needed. Return if symptoms persist beyond 3 weeks or worsen. Yearly influenza vaccination recommended.',
    'Acute bronchitis is one of the most common conditions leading to inappropriate antibiotic prescribing. The DECLINE trial showed that a C-reactive Protein point-of-care test reduces antibiotic prescribing safely. Honey is more effective than diphenhydramine and dextromethorphan for nocturnal cough in adults. Pertussis should be considered in adults with paroxysmal cough and post-tussive vomiting.',
    ['NICE Guideline: Cough (Acute)', 'CDC: Management of Acute Bronchitis', 'WHO: Antibiotic Stewardship in Respiratory Infections'],
  ),
];
