// ================================================================
// Toxicology — Case Templates (5 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const TOXICOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Toxicology', 'Emergency Medicine / Toxicology', 'Paracetamol Overdose', 'Acute Paracetamol Overdose in a Young Adult', 'Advanced',
    'Ingested 20 tablets of paracetamol (1g each) 8 hours ago in a suicide attempt',
    '{name}, a {age}-year-old {occupation} from {location}, was brought to casualty 8 hours after ingesting 20 tablets of paracetamol (500mg each = 10g total) in an impulsive suicide attempt following a relationship breakup. Patient initially asymptomatic but now reports nausea and vague right upper quadrant abdominal discomfort. No vomiting. No altered consciousness. Brought by a friend who found the empty blister packs.',
    'No significant PMH. No known liver disease. No regular medications. No prior suicide attempts.',
    'No regular medications.',
    'Awake, alert, oriented. Pulse 88, BP 120/75, RR 16, O2 sat 98%. Mild tenderness in the right upper quadrant. No jaundice, asterixis, or encephalopathy. No signs of other drug ingestion.',
    'Paracetamol level at 8 hours post-ingestion: 180 mcg/mL (treatment line: >150 mcg/mL at 8 hours — requires NAC). LFTs: AST 120 U/L (mildly elevated), ALT 95 U/L, INR 1.1, Total Bilirubin 1.0 mg/dL. Cr 0.9 mg/dL. Glucose 90 mg/dL. Blood gas: pH 7.38. HCG: negative (if applicable).',
    'No imaging indicated.',
    'Acute Paracetamol (Acetaminophen) Overdose — Single Acute Ingestion of 10g, at 8 Hours Post-Ingestion, Potentially Hepatotoxic Level',
    ['Paracetamol Overdose', 'Acute Hepatitis (viral, alcoholic)', 'Other Drug Overdose (e.g., NSAIDs)', 'Acute Cholecystitis', 'Pancreatitis'],
    'Prevent hepatotoxicity, start NAC within the window of maximal efficacy, assess need for liver transplant, provide psychosocial support',
    '1. AC activated charcoal: Only if <4 hours post-ingestion and intact airway. NOT indicated here (8 hours post). 2. ANTIDOTE: IV Acetylcysteine (NAC) — start IMMEDIATELY. Three-bag protocol: Loading: 150 mg/kg in 5% dextrose 200mL over 1 hour. Second: 50 mg/kg in 500mL over 4 hours. Third: 100 mg/kg in 1000mL over 16 hours. Total: 300 mg/kg over 21 hours. 3. Continue NAC beyond 21 hours if: INR >2, ALT >1000, encephalopathy, or paracetamol level still detectable. NAC is most effective if started within 8 hours but still beneficial up to 24+ hours. 4. IV fluids: Maintain hydration. 5. Monitor for NAC adverse effects: anaphylactoid reaction (flushing, rash, bronchospasm, hypotension) — usually during loading dose. If occurs: temporarily stop NAC, give antihistamines (Chlorpheniramine), restart at slower rate. 6. Do NOT give activated charcoal after NAC started (may adsorb NAC). 7. N-acetylcysteine can be given PO (140 mg/kg loading, then 70 mg/kg q4h x 17 doses) if IV NAC unavailable — but IV is preferred.',
    'Psychiatric assessment — suicide risk evaluation. Provide safe environment. 1:1 nursing observation. Remove access to medications.',
    'EMERGENCY: IV NAC started immediately at 8h post-ingestion. Admit to medical ward. Monitor LFTs, INR, glucose, mental status q6-8h. Continue NAC for full 21-hour course. Arrange psychiatric evaluation. Check paracetamol level, LFTs, INR at baseline and q8-12h.',
    '1. Paracetamol overdose is a medical emergency — NAC must be started immediately (do NOT wait for levels to come back if history is clear). 2. Overdose is potentially fatal but 100% preventable with timely NAC. 3. Psychiatric and social factors need addressing.',
    'Paracetamol level, ALT, AST, INR, glucose, bicarbonate, lactate q8-12h until stable. Signs of hepatotoxicity: ALT rising (peak day 3-4), INR prolonged, hypoglycaemia, encephalopathy, metabolic acidosis. If INR >2.0 or ALT >1000: continue NAC beyond 21 hours. If severe hepatotoxicity: discuss with transplant centre (King\'s College Criteria: pH <7.3 OR all three of INR >6.5, Cr >3.4 mg/dL, Grade III-IV encephalopathy).',
    'Paracetamol overdose can cause liver failure that may not be noticeable for 24-72 hours. You have received the antidote which will protect your liver. You will need to stay on the infusion for 21 hours. We will monitor your blood tests regularly. We also need to address the reasons behind this — a psychiatrist will speak with you.',
    'Medical: Complete NAC course. Discharge when: LFTs improving/improved, INR normalising, no encephalopathy. Psychiatric: Before discharge, must be assessed by psychiatrist — do NOT discharge without psychiatric clearance. Follow-up LFTs in 1 week.',
    'NAC is the antidote of choice — it works by replenishing hepatic glutathione stores. It is most effective within 8 hours of ingestion (almost 100% protective). Paracetamol is metabolised primarily by glucuronidation and sulphation; a small fraction goes through CYP2E1 to form NAPQI (toxic metabolite). In overdose, glucuronidation/sulphation pathways become saturated, and NAPQI accumulates. Glutathione can detoxify up to ~5g paracetamol — beyond that, liver injury occurs. The Rumack-Matthew nomogram is used for timing of ingestion and need for NAC. In resource-limited settings, if paracetamol levels cannot be obtained: give NAC if ingestion >150 mg/kg or >7.5g total. Single acute ingestions >150 mg/kg are considered potentially toxic.',
    ['Kenya Clinical Guidelines: Paracetamol Overdose', 'TOXBASE: Paracetamol Poisoning', 'WHO: Poisoning Management'],
  ),
  t('Toxicology', 'Emergency Medicine / Toxicology', 'Organophosphate Poisoning', 'Acute Organophosphate Poisoning in an Agricultural Worker', 'Advanced',
    'Sudden onset of excessive salivation, sweating, and difficulty breathing after spraying crops',
    '{name}, a {age}-year-old {occupation} from {location}, presents to casualty 2 hours after accidental dermal and inhalational exposure to an organophosphate pesticide (confirmed as "Dudu Nuru" — contains Chlorpyrifos) while spraying maize crops without protective equipment. Developed: excessive salivation, lacrimation, sweating, nausea/vomiting, abdominal cramps, and loose stools within 30 minutes of exposure. Now reports: difficulty breathing, blurred vision, muscle twitching, and weakness.',
    'No significant PMH. No known allergies. No regular medications. Young, previously healthy.',
    'No regular medications.',
    'Excess secretions (salivation, lacrimation, rhinorrhoea). Profuse diaphoresis. Constricted pupils (pinpoint, 1mm bilaterally). Muscle fasciculations (face, shoulders, limbs). Generalised weakness. HR 54 bpm (bradycardia), BP 100/60, RR 28 (tachypnoea), SpO2 89% on room air. Auscultation: bilateral crackles and wheeze (pulmonary oedema due to bronchorrhoea). Altered mental status: Glasgow Coma Scale 12 (confused, drowsy). Foul (garlic-like) odour on breath.',
    'No immediate labs needed to start treatment. Send later: plasma and RBC cholinesterase levels (but treatment should NOT be delayed waiting for results). Baseline: creatinine, K+, glucose, arterial blood gas (to assess respiratory status).',
    'Chest X-ray: may show pulmonary oedema (aspiration or bronchorrhoea).',
    'Acute Organophosphate Poisoning (Severe) — Cholinergic Crisis due to Chlorpyrifos (dermal + inhalational exposure)',
    ['Organophosphate Poisoning', 'Carbamate Poisoning (no fasciculations, shorter duration)', 'Nerve Agent Exposure', 'Severe Pneumonia', 'Acute Pulmonary Oedema (cardiogenic)'],
    'Atropinisation (counter muscarinic effects), pralidoxime (reactivate cholinesterase), respiratory support, decontamination',
    '1. DECONTAMINATION: Remove all clothing. Wash skin thoroughly with soap and water (wear gloves — providers must protect themselves). Irrigate eyes if exposed. 2. AIRWAY + BREATHING: Ensure airway patency. Suction secretions. Give O2. Prepare for intubation if GCS <8, unable to protect airway, respiratory failure, or refractory hypoxia. 3. ANTIDOTE 1 — ATROPINE (blocks muscarinic receptors): Give IV Atropine 2mg bolus. Repeat 2mg IV every 5 minutes until atropinisation achieved (drying of secretions, HR >60, pupils dilating). Atropine: no upper limit — may need 20-50mg initially in severe cases. Once atropinised: start infusion (10-20% of loading dose per hour). 4. ANTIDOTE 2 — PRALIDOXIME (reactivates cholinesterase): Give IV Pralidoxime (2-PAM) 1-2g over 15-30 minutes, then 0.5 g/hour IV infusion. OR 1g IM q4-6h. Most effective if given within 12 hours. 5. Seizure control: IV Diazepam 10mg or Midazolam 5-10mg. 6. Atropine test: Give atropine 1mg IV — if no mydriasis or tachycardia, confirms OP poisoning.',
    'Healthcare workers must wear PPE (gloves, gown, mask, eye protection) during decontamination to avoid secondary contamination. Admit to ICU/HDU.',
    'EMERGENCY: Decontaminate immediately. Secure airway (intubate if needed). Start atropine (2mg IV q5min until atropinised). Give pralidoxime 2g IV loading. Admit to ICU. IV fluids. Continuous monitoring. Psychiatric evaluation (intentional poisoning — suicide attempt may be involved).',
    '1. Life-threatening cholinergic crisis requiring aggressive atropinisation and possibly intubation. 2. Accidental occupational exposure — highlight need for PPE and safety measures.',
    'Continuous: HR, BP, RR, O2 sat, GCS, secretions (atropinisation status). Atropine infusion rate adjusted to keep secretions dry. Labs: serial cholinesterase levels (if available), ABG, electrolytes. Monitor for intermediate syndrome (days 1-4): proximal muscle weakness, respiratory insufficiency. Monitor for delayed neuropathy (2-3 weeks): peripheral neuropathy (organophosphate-induced delayed neuropathy, OIDN).',
    'You have been poisoned by a pesticide. The treatment involves medications that block the effects of the poison and help clean it from your system. You will be closely monitored in the intensive care unit. This is a serious condition but treatable if we act quickly. We need to discuss how this happened — was it accidental or intentional?',
    'Monitor atropine requirements (taper as secretions decrease). Continue pralidoxime for 24-48h. Extubate when respiratory function adequate. Psychiatric evaluation if intentional ingestion. Follow-up: neurological exam in 2-3 weeks for delayed neuropathy. Return to work: not before full recovery and with appropriate PPE training.',
    'Organophosphates inhibit acetylcholinesterase (AChE), causing accumulation of acetylcholine at muscarinic, nicotinic, and CNS synapses. The three classic presentations: muscarinic (SLUDGE syndrome: Salivation, Lacrimation, Urination, Defecation, GI upset, Emesis), nicotinic (muscle fasciculations, weakness, tachycardia), and CNS (seizures, coma). Atropine reverses ONLY muscarinic effects — it does NOT reverse nicotinic weakness (which requires pralidoxime for AChE reactivation). Pralidoxime is most effective early (<12h) before the bond between OP and AChE becomes irreversible ("ageing"). The ageing half-life of chlorpyrifos is about 30 hours, so pralidoxime has a wider window for this compound. Atropine may be required in very high doses — do not hesitate to give repeated boluses. The end-point of atropinisation is drying of bronchial secretions, not a specific heart rate.',
    ['Kenya Clinical Guidelines: Pesticide Poisoning', 'TOXBASE: Organophosphate Poisoning', 'WHO: Management of Pesticide Poisoning'],
  ),
];
