// ================================================================
// Toxicology — Case Templates (4 templates)
// ================================================================
import type { ClinicalCaseTemplate } from '../generateCases';
function t(
  pharmacologySubject: string,
  specialty: string,
  disease: string,
  title: string,
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string,
  hpi: string,
  pmh: string,
  medHx: string,
  pe: string,
  labs: string,
  imaging: string,
  diagnosis: string,
  ddx: string[],
  goals: string,
  pharm: string,
  nonPharm: string,
  carePlan: string,
  dtps: string,
  monitoring: string,
  counselling: string,
  followUp: string,
  pearls: string,
  references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject,
    specialty,
    disease,
    title,
    difficulty,
    chiefComplaintTemplate: chiefComplaint,
    hpiTemplate: hpi,
    pmhTemplate: pmh,
    medHxTemplate: medHx,
    peTemplate: pe,
    labsTemplate: labs,
    imagingTemplate: imaging,
    diagnosis,
    ddx,
    goalsTemplate: goals,
    pharmTemplate: pharm,
    nonPharmTemplate: nonPharm,
    carePlanTemplate: carePlan,
    dtpsTemplate: dtps,
    monitoringTemplate: monitoring,
    counsellingTemplate: counselling,
    followUpTemplate: followUp,
    pearlsTemplate: pearls,
    references,
  };
}
export const TOXICOLOGY_TEMPLATES: ClinicalCaseTemplate[] = [
  t('Toxicology', 'Emergency Medicine / Toxicology', 'Paracetamol Overdose', 'Acute Paracetamol Overdose in a Young Adult', 'Advanced',
    'Ingested 20 tablets of paracetamol (1g each) 8 hours ago in a suicide attempt',
    '{name}, a {age}-year-old {occupation} from {location}, was brought to casualty 8 hours after ingesting 20 tablets of paracetamol (500mg each = 10g total) in an impulsive suicide attempt following a relationship breakup. Patient initially asymptomatic but now reports nausea and vague right upper quadrant abdominal discomfort. No vomiting. No altered consciousness. Brought by a friend who found the empty blister packs.',
    'No significant PMH. No known liver disease. No regular medications. No prior suicide attempts.',
    'No regular medications.',
    'Awake, alert, oriented. Pulse 88, BP 120/75, RR 16, O2 sat 98%. Mild tenderness in the right upper quadrant. No jaundice, asterixis, or encephalopathy. No signs of other drug ingestion.',
    'Paracetamol level at 8 hours post-ingestion: 180 mcg/mL (treatment line: >150 mcg/mL at 8 hours — requires NAC). LFTs: AST 120 U/L (mildly elevated), ALT 95 U/L, INR 1.1, Total Bilirubin 1.0 mg/dL. Cr 0.9 mg/dL. Glucose 90 mg/dL. Blood gas: pH 7.38. HCG: negative (if applicable).',
    'No imaging indicated.',
    'Acute Paracetamol (Acetaminophen) Overdose — Single Acute Ingestion of 10g, at 8 Hours Post-Ingestion, Potentially Hepatotoxic Level',
    ['Paracetamol Overdose', 'Acute Hepatitis (viral, alcoholic)', 'Other Drug Overdose (e.g., NSAIDs)', 'Acute Cholecystitis', 'Pancreatitis'],
    'Prevent hepatotoxicity, start NAC within the window of maximal efficacy, assess need for liver transplant, provide psychosocial support',
    '1. AC activated charcoal: Only if <4 hours post-ingestion and intact airway. NOT indicated here (8 hours post). 2. ANTIDOTE: IV Acetylcysteine (NAC) — start IMMEDIATELY. Three-bag protocol: Loading: 150 mg/kg in 5% dextrose 200mL over 1 hour. Second: 50 mg/kg in 500mL over 4 hours. Third: 100 mg/kg in 1000mL over 16 hours. Total: 300 mg/kg over 21 hours. 3. Continue NAC beyond 21 hours if: INR >2, ALT >1000, encephalopathy, or paracetamol level still detectable. NAC is most effective if started within 8 hours but still beneficial up to 24+ hours. 4. IV fluids: Maintain hydration. 5. Monitor for NAC adverse effects: anaphylactoid reaction (flushing, rash, bronchospasm, hypotension) — usually during loading dose. If occurs: temporarily stop NAC, give antihistamines (Chlorpheniramine), restart at slower rate. 6. Do NOT give activated charcoal after NAC started (may adsorb NAC). 7. N-acetylcysteine can be given PO (140 mg/kg loading, then 70 mg/kg q4h x 17 doses) if IV NAC unavailable — but IV is preferred.',
    'Psychiatric assessment — suicide risk evaluation. Provide safe environment. 1:1 nursing observation. Remove access to medications.',
    'EMERGENCY: IV NAC started immediately at 8h post-ingestion. Admit to medical ward. Monitor LFTs, INR, glucose, mental status q6-8h. Continue NAC for full 21-hour course. Arrange psychiatric evaluation. Check paracetamol level, LFTs, INR at baseline and q8-12h.',
    '1. Paracetamol overdose is a medical emergency — NAC must be started immediately (do NOT wait for levels to come back if history is clear). 2. Overdose is potentially fatal but 100% preventable with timely NAC. 3. Psychiatric and social factors need addressing.',
    'Paracetamol level, ALT, AST, INR, glucose, bicarbonate, lactate q8-12h until stable. Signs of hepatotoxicity: ALT rising (peak day 3-4), INR prolonged, hypoglycaemia, encephalopathy, metabolic acidosis. If INR >2.0 or ALT >1000: continue NAC beyond 21 hours. If severe hepatotoxicity: discuss with transplant centre (King\'s College Criteria: pH <7.3 OR all three of INR >6.5, Cr >3.4 mg/dL, Grade III-IV encephalopathy).',
    'Paracetamol overdose can cause liver failure that may not be noticeable for 24-72 hours. You have received the antidote which will protect your liver. You will need to stay on the infusion for 21 hours. We will monitor your blood tests regularly. We also need to address the reasons behind this — a psychiatrist will speak with you.',
    'Medical: Complete NAC course. Discharge when: LFTs improving/improved, INR normalising, no encephalopathy. Psychiatric: Before discharge, must be assessed by psychiatrist — do NOT discharge without psychiatric clearance. Follow-up LFTs in 1 week.',
    'NAC is the antidote of choice — it works by replenishing hepatic glutathione stores. It is most effective within 8 hours of ingestion (almost 100% protective). Paracetamol is metabolised primarily by glucuronidation and sulphation; a small fraction goes through CYP2E1 to form NAPQI (toxic metabolite). In overdose, glucuronidation/sulphation pathways become saturated, and NAPQI accumulates. Glutathione can detoxify up to ~5g paracetamol — beyond that, liver injury occurs. The Rumack-Matthew nomogram is used for timing of ingestion and need for NAC. In resource-limited settings, if paracetamol levels cannot be obtained: give NAC if ingestion >150 mg/kg or >7.5g total. Single acute ingestions >150 mg/kg are considered potentially toxic.',
    ['Kenya Clinical Guidelines: Paracetamol Overdose', 'TOXBASE: Paracetamol Poisoning', 'WHO: Poisoning Management'],
  ),
  t('Toxicology', 'Emergency Medicine / Toxicology', 'Organophosphate Poisoning', 'Acute Organophosphate Poisoning in an Agricultural Worker', 'Advanced',
    'Sudden onset of excessive salivation, sweating, and difficulty breathing after spraying crops',
    '{name}, a {age}-year-old {occupation} from {location}, presents to casualty 2 hours after accidental dermal and inhalational exposure to an organophosphate pesticide (confirmed as "Dudu Nuru" — contains Chlorpyrifos) while spraying maize crops without protective equipment. Developed: excessive salivation, lacrimation, sweating, nausea/vomiting, abdominal cramps, and loose stools within 30 minutes of exposure. Now reports: difficulty breathing, blurred vision, muscle twitching, and weakness.',
    'No significant PMH. No known allergies. No regular medications. Young, previously healthy.',
    'No regular medications.',
    'Excess secretions (salivation, lacrimation, rhinorrhoea). Profuse diaphoresis. Constricted pupils (pinpoint, 1mm bilaterally). Muscle fasciculations (face, shoulders, limbs). Generalised weakness. HR 54 bpm (bradycardia), BP 100/60, RR 28 (tachypnoea), SpO2 89% on room air. Auscultation: bilateral crackles and wheeze (pulmonary oedema due to bronchorrhoea). Altered mental status: Glasgow Coma Scale 12 (confused, drowsy). Foul (garlic-like) odour on breath.',
    'No immediate labs needed to start treatment. Send later: plasma and RBC cholinesterase levels (but treatment should NOT be delayed waiting for results). Baseline: creatinine, K+, glucose, arterial blood gas (to assess respiratory status).',
    'Chest X-ray: may show pulmonary oedema (aspiration or bronchorrhoea).',
    'Acute Organophosphate Poisoning (Severe) — Cholinergic Crisis due to Chlorpyrifos (dermal + inhalational exposure)',
    ['Organophosphate Poisoning', 'Carbamate Poisoning (no fasciculations, shorter duration)', 'Nerve Agent Exposure', 'Severe Pneumonia', 'Acute Pulmonary Oedema (cardiogenic)'],
    'Atropinisation (counter muscarinic effects), pralidoxime (reactivate cholinesterase), respiratory support, decontamination',
    '1. DECONTAMINATION: Remove all clothing. Wash skin thoroughly with soap and water (wear gloves — providers must protect themselves). Irrigate eyes if exposed. 2. AIRWAY + BREATHING: Ensure airway patency. Suction secretions. Give O2. Prepare for intubation if GCS <8, unable to protect airway, respiratory failure, or refractory hypoxia. 3. ANTIDOTE 1 — ATROPINE (blocks muscarinic receptors): Give IV Atropine 2mg bolus. Repeat 2mg IV every 5 minutes until atropinisation achieved (drying of secretions, HR >60, pupils dilating). Atropine: no upper limit — may need 20-50mg initially in severe cases. Once atropinised: start infusion (10-20% of loading dose per hour). 4. ANTIDOTE 2 — PRALIDOXIME (reactivates cholinesterase): Give IV Pralidoxime (2-PAM) 1-2g over 15-30 minutes, then 0.5 g/hour IV infusion. OR 1g IM q4-6h. Most effective if given within 12 hours. 5. Seizure control: IV Diazepam 10mg or Midazolam 5-10mg. 6. Atropine test: Give atropine 1mg IV — if no mydriasis or tachycardia, confirms OP poisoning.',
    'Healthcare workers must wear PPE (gloves, gown, mask, eye protection) during decontamination to avoid secondary contamination. Admit to ICU/HDU.',
    'EMERGENCY: Decontaminate immediately. Secure airway (intubate if needed). Start atropine (2mg IV q5min until atropinised). Give pralidoxime 2g IV loading. Admit to ICU. IV fluids. Continuous monitoring. Psychiatric evaluation (intentional poisoning — suicide attempt may be involved).',
    '1. Life-threatening cholinergic crisis requiring aggressive atropinisation and possibly intubation. 2. Accidental occupational exposure — highlight need for PPE and safety measures.',
    'Continuous: HR, BP, RR, O2 sat, GCS, secretions (atropinisation status). Atropine infusion rate adjusted to keep secretions dry. Labs: serial cholinesterase levels (if available), ABG, electrolytes. Monitor for intermediate syndrome (days 1-4): proximal muscle weakness, respiratory insufficiency. Monitor for delayed neuropathy (2-3 weeks): peripheral neuropathy (organophosphate-induced delayed neuropathy, OIDN).',
    'You have been poisoned by a pesticide. The treatment involves medications that block the effects of the poison and help clean it from your system. You will be closely monitored in the intensive care unit. This is a serious condition but treatable if we act quickly. We need to discuss how this happened — was it accidental or intentional?',
    'Monitor atropine requirements (taper as secretions decrease). Continue pralidoxime for 24-48h. Extubate when respiratory function adequate. Psychiatric evaluation if intentional ingestion. Follow-up: neurological exam in 2-3 weeks for delayed neuropathy. Return to work: not before full recovery and with appropriate PPE training.',
    'Organophosphates inhibit acetylcholinesterase (AChE), causing accumulation of acetylcholine at muscarinic, nicotinic, and CNS synapses. The three classic presentations: muscarinic (SLUDGE syndrome: Salivation, Lacrimation, Urination, Defecation, GI upset, Emesis), nicotinic (muscle fasciculations, weakness, tachycardia), and CNS (seizures, coma). Atropine reverses ONLY muscarinic effects — it does NOT reverse nicotinic weakness (which requires pralidoxime for AChE reactivation). Pralidoxime is most effective early (<12h) before the bond between OP and AChE becomes irreversible ("ageing"). The ageing half-life of chlorpyrifos is about 30 hours, so pralidoxime has a wider window for this compound. Atropine may be required in very high doses — do not hesitate to give repeated boluses. The end-point of atropinisation is drying of bronchial secretions, not a specific heart rate.',
    ['Kenya Clinical Guidelines: Pesticide Poisoning', 'TOXBASE: Organophosphate Poisoning', 'WHO: Management of Pesticide Poisoning'],
  ),
  t('Toxicology', 'Emergency Medicine / Toxicology', 'Snake Envenomation', 'Saw-Scaled Viper (Carpet Viper) Envenomation with Consumptive Coagulopathy', 'Advanced',
    'Painful swollen foot with bleeding from a bite site sustained while farming',
    '{name}, a {age}-year-old {occupation} from {location}, presents to casualty 4 hours after being bitten on the right foot by a snake while working in the shamba (farm). The patient describes the snake as small-to-medium sized, brown with a zigzag pattern, which sawed its body coils together before striking — consistent with a saw-scaled viper (Echis carinatus, carpet viper). The bite was initially painful with immediate local swelling. Over 4 hours, the swelling has extended from the foot to the lower leg. The patient reports oozing of blood from the bite site and from the gums. No vomiting, no abdominal pain, no difficulty breathing. The patient did not attempt to suck out the venom or apply a tourniquet. Was brought by family members to the nearest health facility.',
    'No significant PMH. No known drug allergies. No anticoagulant use. Non-smoker. No prior snakebite.',
    'No regular medications.',
    'Right foot and lower leg: significant oedema extending from toes to below the knee. Two puncture wounds on the dorsum of the foot with active oozing of blood. Ecchymosis spreading over the foot. Gums: mild oozing on brushing teeth. BP 110/70, HR 105 (mildly tachycardic), Temp 37.2°C, SpO2 98% on room air. Neurological: alert, GCS 15. No ptosis, no respiratory weakness, no cranial nerve palsies (rules out neurotoxic envenomation from elapids). Right inguinal lymphadenopathy. No skin necrosis at bite site yet.',
    'Coagulation profile: PT 45 seconds (INR >12, severely prolonged). APTT >100 seconds. Fibrinogen 0.4 g/L (very low — consumptive coagulopathy). Platelets 45,000/µL (thrombocytopenia). 20-minute whole blood clotting test (20WTCT): positive (clot does not form or lyses within 20 minutes — confirms venom-induced consumptive coagulopathy, VICC). Haemoglobin 10.0 g/dL (drop from estimated baseline of 14). Creatinine 1.1 mg/dL. ALT 80 U/L. Blood group and crossmatch: 2 units packed red cells available.',
    'X-ray right foot: no fracture, soft tissue swelling. Doppler ultrasound: intact vascular flow (no compartment syndrome yet). No evidence of foreign body.',
    'Saw-Scaled Viper (Echis carinatus) Envenomation with Venom-Induced Consumptive Coagulopathy (VICC) — Neurotoxicity excluded clinically',
    ['Saw-Scaled Viper Envenomation (Viperidae)', 'Puff Adder Envenomation (more local tissue necrosis, less coagulopathy)', 'Black Mamba Envenomation (neurotoxic — ptosis, respiratory failure)', 'Cobra Envenomation (neurotoxic + cytotoxic)', 'Non-venomous snake bite (no coagulopathy, minimal swelling)', 'Disseminated Intravascular Coagulation (DIC from sepsis, not snakebite)'],
    'Neutralise venom with antivenom, restore coagulation, prevent bleeding complications, manage local effects, monitor for compartment syndrome and secondary infection',
    '1. ANTIVENOM (IMMEDIATE — do not delay): Polyvalent anti-snake venom (SAIMR or EchITAbG polyvalent) — dose based on severity. For moderate envenomation with coagulopathy: give 2-4 vials IV in 100mL 0.9% NS over 30 minutes. For severe envenomation (VICC + active bleeding): 4-6 vials initially, may repeat in 1-2 hours if coagulopathy persists. Antivenom is the ONLY specific treatment. 2. BLOOD PRODUCTS (if active severe bleeding): Packed Red Blood Cells (transfuse if Hb <7 or active haemorrhage). Cryoprecipitate (fibrinogen <0.5 g/L) — give 10 units. Fresh Frozen Plasma (if coagulopathy persists despite antivenom) — 15mL/kg. Platelet transfusion (if <50,000 and bleeding). 3. WOUND CARE: Clean the bite site with soap and water. Do NOT incise, excise, or apply a tourniquet. Elevation of the limb. Immobilise with a splint. 4. Tetanus prophylaxis: Tetanus toxoid booster if not fully immunised. 5. Antibiotics (only if secondary infection develops): Amoxicillin-clavulanate or Cephalexin. 6. Pain management: Paracetamol 1g QID. Avoid NSAIDs (worsen coagulopathy). Low-dose morphine 0.1mg/kg SC if severe pain refractory to paracetamol. 7. Pressure immobilisation bandage (PIB): Apply a firm crepe bandage from the bite site proximally (similar to a sprained ankle bandage) to slow lymphatic absorption of venom. Do NOT apply a tourniquet.',
    'Pressure immobilisation bandage in situ. Limb elevated. Splint to prevent movement. Avoid any alcohol or aspirin. Ensure the patient does not manipulate the wound.',
    'ADMINISTER POLYVALENT ANTIVENOM immediately (2-4 vials IV). Monitor for anaphylaxis to antivenom (give adrenaline 0.5mg IM if severe reaction). Check coagulation profile (20WTCT, PT, fibrinogen) 1-2 hours post-antivenom and repeat q6h. If coagulopathy persists: repeat antivenom dose. Transfuse cryoprecipitate if fibrinogen <0.5. Monitor for compartment syndrome (rising compartment pressures, pain on passive stretch, tense limb). Admit for minimum 24-48 hours observation.',
    '1. Life-threatening envenomation from a saw-scaled viper (Echis carinatus) — the most common cause of snakebite morbidity and mortality in East Africa. 2. Consumptive coagulopathy requires urgent antivenom and blood products. 3. Compartment syndrome risk requires close monitoring.',
    'Coagulation (20WTCT, PT, fibrinogen, platelets) every 2-6 hours until normalised and stable for 24 hours. Limb circumference measured every 2 hours (rising = compartment syndrome). Neurological observation every hour (to rule out delayed neurotoxicity — though uncommon with vipers). Renal function (creatinine, urine output) — venom nephrotoxicity possible. Watch for secondary bleeding (can occur 2-5 days post-bite even after initial treatment).',
    'You were bitten by a saw-scaled viper, which is one of the most dangerous snakes in Kenya. The venom affects your blood clotting system, which is why you are bleeding from the bite site and gums. We have given you antivenom which will neutralise the venom, and blood products to help your blood clot again. You need to stay in hospital for at least 2 days. The wound may become swollen and painful — this is expected. If you see any new swelling, bleeding, or difficulty breathing, tell a nurse immediately. Do not attempt traditional remedies — they do not work and can cause harm.',
    'Nephrology/toxicology follow-up in 1 week. Wound review in 3-5 days (watch for secondary infection, tissue necrosis). Coagulation profile at 1 week (may take weeks to normalise fully). Counselling: avoid walking in shambas at night without torch and protective footwear. Wear boots when farming. Most snakes flee from humans — the bite is usually defensive.',
    'Saw-scaled vipers (Echis carinatus) are the most medically important snakes in East Africa, causing more envenomations and deaths than any other species in Kenya. They are small, nocturnal, and found in rocky areas and agricultural land. The characteristic "saw-scaling" behaviour (rubbing body coils together to produce a sizzling sound) is distinctive. The venom is primarily haemotoxic — causing venom-induced consumptive coagulopathy (VICC): destruction of clotting factors, fibrinogen depletion, and thrombocytopenia. The 20WTCT is a simple bedside test: place 2mL of whole blood in a clean glass tube at room temperature — if it does not clot within 20 minutes, VICC is confirmed. Antivenom (polyvalent) is the specific antidote and must be given IV (not IM). Polyvalent antivenom covers viper, cobra, and mamba venoms. In Kenya, the most common venomous snakes are: carpet viper (saw-scaled viper), puff adder, black mamba, and Egyptian cobra. Traditional healers often delay definitive treatment — patient education is critical.',
    ['Kenya Medical Research Institute (KEMRI): Snakebite Guidelines', 'WHO Guidelines: Snakebite Envenomation', 'Kenya Clinical Guidelines: Toxicology'],
  ),
  t('Toxicology', 'Emergency Medicine / Toxicology', 'Alcohol Withdrawal', 'Acute Alcohol Withdrawal Syndrome with Delirium Tremens Risk', 'Intermediate',
    'Tremors, sweating, and confusion 24 hours after stopping heavy alcohol use',
    '{name}, a {age}-year-old {occupation} from {location}, presents to casualty 24 hours after his last alcoholic drink. Reports drinking approximately 1 bottle of Safari Cane (local spirit, ~40% ABV, ~750mL) daily for the past 8 years. Yesterday, he was admitted to hospital for an unrelated surgical procedure and was unable to drink. Since this morning, he has developed tremors in both hands, profuse sweating, nausea, vomiting, and anxiety. Reports seeing small animals crawling on the walls (visual hallucinations). Denies auditory or tactile hallucinations. No seizures so far. No headache, fever, or neck stiffness. Alert but disoriented to time (knows his name and place but not the date).',
    'Chronic alcohol use disorder (8 years, heavy daily use). No prior documented alcohol withdrawal or seizures. No liver disease diagnosed. No prior psychiatric admissions.',
    'No regular medications. Denies use of other recreational drugs. Does not smoke.',
    'Tremor: bilateral upper limb resting tremor (coarse). Diaphoresis (profuse sweating). Tachycardia: HR 110 bpm. BP 155/95 (elevated — withdrawal-related sympathetic overactivity). Temp 37.5°C (low-grade, likely from withdrawal). Pupils: dilated bilaterally. Tremor present in hands and tongue. Orientation: person and place intact, time confused (knows month but not exact date). GCS 14 (confused). No nystagmus. No hepatomegaly clinically. No jaundice. No ascites.',
    'CIWA-Ar Score: 22 (Moderate withdrawal — score >20 indicates risk for seizures and delirium tremens). Glucose 70 mg/dL (low — common in alcohol withdrawal). WBC 12.5 (mild leukocytosis). Mg 1.2 mg/dL (low, normal 1.7-2.2). AST 85 U/L, ALT 45 U/L (AST:ALT >2 suggests alcoholic liver disease). Bilirubin 1.5 mg/dL (mildly elevated). Albumin 3.2 g/dL. INR 1.3. K+ 3.5 mEq/L. FBC: Hb 13.0 g/dL. Platelets 180,000. Blood alcohol level: 0 mg/dL (currently sober). Urine: negative for other substances.',
    'No imaging required. If seizures occur: CT head (to exclude structural cause). If concern for Wernicke\'s: MRI brain (shows mammillary body changes) — but treat empirically without waiting for imaging.',
    'Alcohol Withdrawal Syndrome (Moderate-Severe) with Visual Hallucinations — CIWA-Ar 22, at high risk for seizures and delirium tremens',
    ['Alcohol Withdrawal Syndrome', 'Alcoholic Hallucinosis (isolated hallucinations without other withdrawal features)', 'Delirium Tremens (full syndrome — confusion, autonomic instability, hallucinations, seizures)', 'Wernicke\'s Encephalopathy (confusion, ataxia, ophthalmoplegia)', 'Hepatic Encephalopathy', 'Intracranial Haemorrhage (if seizures occur)'],
    'Prevent seizures and delirium tremens, control autonomic hyperactivity, correct electrolyte abnormalities, prevent Wernicke\'s encephalopathy, provide nutritional support',
    '1. BENZODIAZEPINES (first-line for withdrawal): Chlordiazepoxide 20-50mg PO q6h (or Diazepam 10-20mg PO q6h) per CIWA protocol. For CIWA-Ar >20: give Diazepam 20mg PO/IV stat, then 10mg q5min until calm (max 40mg in first hour). Once calm: start regular dosing. 2. Thiamine (Vitamin B1) — CRITICAL to prevent Wernicke\'s Encephalopathy: IV Thiamine 500mg in 100mL NS over 30 minutes (MUST be given BEFORE glucose/IV fluids). Then 250mg IV TID for 3 days. Then 100mg PO daily long-term. 3. Folic Acid 5mg daily (alcoholics are folate deficient — prevents megaloblastic anaemia). 4. Multivitamin daily (B-complex, especially B6, B12). 5. IV Fluids: 0.9% NS with 40mEq KCl (correct dehydration, hypokalaemia). Add 5% Dextrose when glucose normal and thiamine given. 6. Correct Mg2+: IV Magnesium Sulphate 2g over 15 minutes (Mg deficiency worsens withdrawal and causes seizures). 7. If seizures occur: Diazepam 10mg IV (or Lorazepam 4mg IV). If refractory: Phenobarbital 10-20mg/kg IV. 8. Monitor for delirium tremens: peak 48-72 hours after last drink — if occurs, escalate benzodiazepines and consider ICU admission.',
    'Continuous observation (1:1 nursing if CIWA >20). Seizure precautions (padded side rails, suction, oxygen at bedside). Strict I&O. No physical restraint (can worsen agitation). Calm, well-lit environment. Nutritional support: high-calorie diet once tolerating oral.',
    'CIWA-Ar protocol: reassess every 2 hours (or 1 hour if score rising). Give Diazepam 5-10mg q1-2h as needed to keep CIWA <15. Give IV Thiamine 500mg NOW (before any dextrose-containing fluids). Correct Mg2+ and K+. Start regular oral nutrition. If CIWA-Ar >35 or seizures: ICU admission. If visual hallucinations persist despite adequate sedation: consider alcoholic hallucinosis (requires different management — antipsychotics).',
    '1. Moderate-severe alcohol withdrawal at risk for seizures and delirium tremens. 2. Visual hallucinations present — requires aggressive benzodiazepine management. 3. Nutritional deficiencies (thiamine, folate, magnesium) requiring immediate correction.',
    'CIWA-Ar score every 1-2 hours (titrate benzodiazepines to score). Vital signs hourly. Blood glucose every 4-6 hours. Electrolytes (K+, Mg2+, phosphate) every 12-24 hours. Watch for: seizures (peak 12-48 hours), delirium tremens (peak 48-72 hours — 5% mortality if untreated), Wernicke\'s encephalopathy (confusion, ataxia, ophthalmoplegia — requires immediate thiamine). Monitor hepatic function.',
    'You are experiencing alcohol withdrawal, which can be dangerous. The medications we give will help prevent seizures and reduce the tremors and anxiety. You MUST receive thiamine (vitamin B1) before any sugar-containing fluids — this prevents a serious brain condition called Wernicke\'s encephalopathy. You will feel better in a few days, but the first 3-5 days are the most critical. After recovery, we need to discuss long-term management of your alcohol use and consider addiction services.',
    'Nephrology/toxicology review in 24-48 hours. If CIWA stabilises <15 on oral medication for 24h: step down observation. Discharge planning: addiction medicine referral, psychiatric assessment, AA (Alcoholics Anonymous) support groups, hepatology follow-up if liver function abnormal. Benzodiazepine taper over 5-7 days once withdrawal resolved. Long-term thiamine supplementation (100mg daily).',
    'Alcohol withdrawal syndrome occurs due to rebound CNS excitability after chronic alcohol exposure (alcohol potentiates GABA, so chronic use downregulates GABA receptors and upregulates glutamate receptors — withdrawal removes the alcohol "brake" causing hyperexcitability). CIWA-Ar (Clinical Institute Withdrawal Assessment for Alcohol — Revised) guides benzodiazepine dosing: mild (5-15) = oral chlordiazepoxide, moderate (15-30) = oral diazepam, severe (>30) = IV diazepam + ICU. Delirium tremens (DT) is the most severe form: occurs in 3-5% of alcohol withdrawals, peaks 48-72 hours after last drink, and carries 5% mortality if untreated. Benzodiazepines are the treatment of choice — they replace the missing GABAergic tone. Thiamine deficiency (Wernicke-Korsakoff syndrome) is common in chronic alcoholics and can be precipitated by giving glucose before thiamine — always give thiamine first. In Kenya, "Safari Cane" (local spirits) is a common cause of alcohol-related presentations. Chronic heavy drinking is also a major risk factor for liver disease, pancreatitis, and oesophageal cancer.',
    ['Kenya Clinical Guidelines: Alcohol Withdrawal', 'WHO: Management of Alcohol Withdrawal', 'NICE Guidelines: Alcohol-Use Disorders (CG115)'],
  ),
];
