// ================================================================
// Vitamins & Nutrition — Case Templates
// 6 templates covering: Iron Deficiency Anaemia, Vitamin A, D, B12,
// Folate Deficiencies, Malnutrition
// ================================================================

import type { ClinicalCaseTemplate } from '../generateCases';

function tpl(
  pharmacologySubject: string, specialty: string, disease: string,
  title: string, difficulty: 'Beginner' | 'Intermediate' | 'Advanced',
  chiefComplaint: string, hpi: string, pmh: string, medHx: string,
  pe: string, labs: string, imaging: string,
  diagnosis: string, ddx: string[],
  goals: string, pharm: string, nonPharm: string, carePlan: string,
  dtps: string, monitoring: string, counselling: string, followUp: string,
  pearls: string, references: string[],
): ClinicalCaseTemplate {
  return {
    pharmacologySubject, specialty, disease, title, difficulty,
    chiefComplaintTemplate: chiefComplaint, hpiTemplate: hpi,
    pmhTemplate: pmh, medHxTemplate: medHx, peTemplate: pe,
    labsTemplate: labs, imagingTemplate: imaging, diagnosis, ddx,
    goalsTemplate: goals, pharmTemplate: pharm,
    nonPharmTemplate: nonPharm, carePlanTemplate: carePlan,
    dtpsTemplate: dtps, monitoringTemplate: monitoring,
    counsellingTemplate: counselling, followUpTemplate: followUp,
    pearlsTemplate: pearls, references,
  };
}

export const VITAMINS_TEMPLATES: ClinicalCaseTemplate[] = [
  tpl(
    'Vitamins & Nutrition', 'Internal Medicine', 'Iron Deficiency Anaemia',
    'Iron Deficiency Anaemia Secondary to Menorrhagia',
    'Beginner',
    'Extreme fatigue, dizziness on standing, and paleness for 2 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with progressive fatigue, weakness, exertional dyspnoea, dizziness, and headache over the past 2-3 months. Reports heavy menstrual bleeding (soaking through pads every 1-2 hours, passing clots, 7-9 day periods) since her teens. Also has cravings for eating ice (pagophagia — pica symptom). No melena, haematochezia, or haematuria.',
    'Heavy menstrual bleeding (menorrhagia) since menarche. No known GI disease. Diet: moderate red meat intake.',
    'No regular medications. Takes occasional over-the-counter iron supplements (intermittent).',
    'Pale conjunctivae, pale palmar creases, generalised pallor. Tachycardic (HR 100). BP 100/65 with mild postural drop. Angular cheilitis. Koilonychia (spoon nails). No hepatosplenomegaly. Rectal exam: brown stool, occult blood negative.',
    'Hb 7.2 g/dL (12-15). MCV 72 fL (80-100) — microcytic. MCH 24 pg (27-32). RDW 17% (elevated — anisocytosis). Ferritin 8 ng/mL (15-150). Serum Iron 30 mcg/dL (50-150). TIBC 480 mcg/dL (250-400) — elevated. Transferrin saturation 6% (15-50). Platelets 450 (reactive thrombocytosis). Hb electrophoresis: normal (rules out thalassaemia trait).',
    'No imaging indicated. Pelvic ultrasound if menorrhagia workup needed: normal uterine anatomy, no fibroids.',
    'Moderate-to-Severe Iron Deficiency Anaemia (Microcytic, Hypochromic) Secondary to Menorrhagia',
    ['Iron Deficiency Anaemia', 'Thalassaemia Trait', 'Anaemia of Chronic Disease', 'Lead Poisoning', 'Vitamin B6 Deficiency'],
    'Correct anaemia, replenish iron stores, identify and treat underlying cause (menorrhagia), improve quality of life',
    '1. Oral iron replacement: Ferrous Sulphate 200mg (65mg elemental iron) TID taken between meals (or with Vitamin C to enhance absorption). 2. If intolerant: Ferrous Gluconate or Ferrous Fumarate. 3. Duration: 3-6 months (until Hb normalised AND ferritin >50 ng/mL). 4. Consider IV iron (Iron Sucrose or Ferric Carboxymaltose) if: severe anaemia with symptoms, intolerance to oral iron, non-adherence, or ongoing blood loss. 5. For menorrhagia management: Tranexamic acid 1g TID during menses. Hormonal therapy (combined OCP or Mirena IUS) if appropriate.',
    'Dietary counselling: increase heme iron sources (red meat, liver, fish) and enhance non-heme iron absorption with Vitamin C (citrus, tomatoes). Avoid tea/coffee with meals (tannins inhibit absorption).',
    'Start oral ferrous sulphate 200mg TID. Advise about side effects (dark stools, constipation, nausea). Check Hb and ferritin in 4-6 weeks. If Hb rise >2 g/dL, continue until ferritin normalised. If poor response: check adherence, consider ongoing blood loss, check for malabsorption (coeliac).',
    '1. Iron deficiency from chronic blood loss exceeding dietary iron intake. 2. Pica (pagophagia) indicating moderate-to-severe deficiency.',
    'Hb and reticulocyte count in 2 weeks (reticulocytosis indicates bone marrow response). Hb, MCV, ferritin at 4-6 weeks. Target: Hb rise >1 g/dL every 2-3 weeks. Continue until ferritin >50 ng/mL (usually 3-6 months total).',
    'Iron tablets cause dark stools (harmless), constipation, and sometimes nausea. Take them on an empty stomach with Vitamin C (orange juice). If stomach upset, take with a small amount of food. Do not take with tea, coffee, or milk. Iron poisoning is dangerous — keep tablets away from children.',
    'GP follow-up in 4-6 weeks for repeat Hb. Gynaecology referral for menorrhagia management if not already addressed. Once Hb normalised, continue iron for 3 more months to replenish stores.',
    'Iron deficiency is the most common deficiency worldwide. In premenopausal women, menorrhagia is the most common cause until proven otherwise. Ferritin is the best marker of iron stores — it is an acute phase reactant, so check CRP concurrently (ferritin can be falsely normal in inflammation). Pica (pagophagia = ice craving) is highly specific for iron deficiency.',
    ['WHO Guidelines: Iron Deficiency Anaemia Prevention', 'BSH Guidelines: Iron Deficiency Anaemia', 'Kenya Clinical Guidelines: Anaemia Management'],
  ),

  tpl(
    'Vitamins & Nutrition', 'Ophthalmology', 'Vitamin A Deficiency',
    'Night Blindness and Xerophthalmia in a Malnourished Child',
    'Intermediate',
    'Difficulty seeing at night and dry, cloudy eyes for 2 months',
    '{name}, a {age}-year-old boy from a rural area near {location}, is brought by his mother with complaints of difficulty seeing at dusk and in dim light (night blindness) for 2 months. His eyes look dry and have whitish patches. He also has a history of recurrent diarrhoea and frequent coughs. The family\'s diet consists mainly of maize porridge (uji) and lacks fruits, vegetables, and animal-source foods. He has not received vitamin A supplementation.',
    'Frequent respiratory infections, Recurrent diarrhoea. Malnutrition (underweight for age). Measles 4 months ago.',
    'None. No vitamin supplements.',
    'Weight 12 kg (underweight, below 3rd percentile for age). Generalised thinness. Bitot spots (white, foamy patches) on temporal conjunctiva bilaterally. Conjunctival xerosis (dry, dull conjunctiva). Corneal xerosis with mild clouding. No corneal ulceration or keratomalacia. Skin: dry, rough texture (follicular hyperkeratosis).',
    'Haemoglobin 9.5 g/dL (mild anaemia). Serum retinol (Vitamin A): 0.5 µmol/L (deficient, normal >0.7). Stool microscopy: negative for ova and parasites. HIV test: negative.',
    'No acute imaging.',
    'Vitamin A Deficiency with Xerophthalmia (Night Blindness, Bitot Spots, Corneal Xerosis) — WHO Classification X1B + X2',
    ['Vitamin A Deficiency', 'Conjunctivitis', 'Trachoma', 'Corneal Ulcer', 'Measles Keratitis'],
    'Reverse Vitamin A deficiency, prevent corneal destruction and blindness, treat underlying malnutrition, prevent mortality from infections',
    '1. High-dose Vitamin A supplementation per WHO protocol: Age-adjusted: Children 6-11 months: Vitamin A 100,000 IU orally immediately, then 100,000 IU the next day. Children 12-59 months: 200,000 IU orally immediately, then 200,000 IU the next day. 2. If corneal involvement present (as here): Give same dose immediately, repeat next day, AND give a third dose at least 2 weeks later. 3. Treat underlying malnutrition: therapeutic feeding (F75/F100 therapeutic milk, PlumpyNut). 4. Empiric antibiotics for infection: Co-trimoxazole prophylaxis. 5. Deworming: Albendazole 400mg stat.',
    'Nutritional rehabilitation: high-energy, high-protein diet with Vitamin A-rich foods (liver, eggs, orange-fleshed sweet potatoes, mangoes, dark leafy greens, carrots, fortified oil). Promote exclusive breastfeeding for infants (or continued breastfeeding). Prevent measles with vaccination (MMR).',
    'Give immediate high-dose Vitamin A. Refer to nutrition rehabilitation programme. Deworm. Ensure MMR vaccination if not received. Educate mother on Vitamin A-rich foods. Follow-up in 2 weeks to reassess eyes and nutritional status.',
    '1. Severe Vitamin A deficiency with xerophthalmia requiring urgent high-dose supplementation to prevent blindness. 2. Underlying chronic malnutrition and recurrent infections perpetuating deficiency. 3. High mortality risk — Vitamin A deficiency increases severity of infections (measles, diarrhoea).',
    'Ocular examination at each visit (corneal clarity, Bitot spots). Weight gain and nutritional status. Monitor for respiratory and diarrhoeal infections.',
    'Vitamin A is essential for vision, immune function, and growth. Feed your child foods rich in Vitamin A: liver, eggs, orange sweet potatoes, mangoes, sukuma wiki, carrots, and fortified cooking oil. Continue breastfeeding. The eye condition can reverse with treatment, but severe corneal damage is permanent.',
    'Growth monitoring at a well-child clinic monthly. Repeat Vitamin A supplementation every 6 months until age 5 (per WHO EPI schedule). Complete immunisation schedule.',
    'Vitamin A deficiency is the leading cause of preventable childhood blindness in developing countries. Even mild deficiency (subclinical) increases childhood mortality from measles, diarrhoea, and pneumonia by 20-30%. Bitot spots are highly specific for Vitamin A deficiency but take weeks to months to resolve. Measles infection acutely depletes Vitamin A stores — give Vitamin A to all children with measles per WHO protocol, regardless of whether they have eye signs.',
    ['WHO Guideline: Vitamin A Supplementation', 'IVACG Guidelines: Vitamin A Deficiency', 'Kenya Clinical Guidelines: Micronutrient Deficiency'],
  ),

  tpl(
    'Vitamins & Nutrition', 'Endocrinology', 'Vitamin D Deficiency',
    'Vitamin D Deficiency Presenting with Bone Pain and Proximal Muscle Weakness',
    'Intermediate',
    'Widespread bone pain, difficulty climbing stairs, and fatigue for 4 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with gradual onset of dull, aching pain in the hips, thighs, and lower back, and difficulty rising from a chair or climbing stairs. Reports muscle weakness, "heaviness" in the legs, and a waddling gait. Works in an office and rarely goes outdoors. Wears full-body clothing for modesty. Does not take any vitamin supplements. No prior fractures.',
    'No significant PMH. Mild iron deficiency anaemia (history). No GI malabsorption symptoms. No liver or kidney disease.',
    'No regular medications',
    'Proximal muscle weakness (hip flexors 3/5, difficulty rising from squat). Waddling gait. Tenderness to palpation over ribs, pelvis, and femurs. No spinal tenderness. No deformities. Chvostek and Trousseau signs: negative.',
    '25(OH) Vitamin D: 8 ng/mL (severely deficient, normal >30). Calcium: 8.2 mg/dL (low-normal). Phosphate: 2.2 mg/dL (low, normal 2.5-4.5). ALP: 165 U/L (elevated). PTH: 95 pg/mL (elevated — secondary hyperparathyroidism). Magnesium: normal. Creatinine: normal. Hb: 11.5 g/dL (mild anaemia).',
    'X-ray pelvis and hips: osteopenia, Looser zones (pseudofractures) in the left superior pubic ramus — pathognomonic for osteomalacia. No fractures.',
    'Symptomatic Vitamin D Deficiency with Secondary Hyperparathyroidism and Osteomalacia (Pseudofractures Present)',
    ['Vitamin D Deficiency / Osteomalacia', 'Osteoporosis', 'Rheumatoid Arthritis', 'Polymyositis', 'Fibromyalgia'],
    'Correct Vitamin D deficiency, heal pseudofractures, normalise calcium metabolism, improve muscle strength, prevent falls and fractures',
    '1. Vitamin D loading: High-dose Vitamin D3 (cholecalciferol) 50,000 IU ONCE WEEKLY for 8 weeks, or 4000 IU daily for 8-12 weeks. 2. Maintenance after loading: Vitamin D3 800-2000 IU daily long-term. 3. Calcium supplementation to treat hypocalcaemia and hungry bone: Calcium carbonate 1000 mg daily (in divided doses with meals). 4. If severe hypocalcaemia (Ca <8.0): hospitalise for IV calcium gluconate. 5. Monitor PTH — should normalise after Vit D correction.',
    'Sun exposure: 15-30 mins of sunlight on exposed forearms and face between 10 AM and 3 PM, 2-3 times per week (when feasible). Dietary sources: fatty fish (salmon, mackerel, sardines), egg yolks, fortified foods. Physiotherapy for muscle strengthening. Fall prevention.',
    'Start weekly high-dose Vitamin D3 50,000 IU for 8 weeks with daily calcium 1000mg. Recheck 25(OH)D, Ca, Phos, ALP, PTH after 8-12 weeks. When 25(OH)D >30 ng/mL, switch to maintenance dosing. Physiotherapy referral. Home safety assessment.',
    '1. Severe Vitamin D deficiency causing osteomalacia and myopathy requiring high-dose replacement. 2. Secondary hyperparathyroidism driving bone demineralisation and fracture risk.',
    '25(OH)D, Calcium, Phosphate, ALP, PTH at 8 and 12 weeks. Ensure 25(OH)D >30 ng/mL before switching to maintenance. Monitor calcium weekly for first month if on calcium supplements. ALP should decrease as bone healing occurs.',
    'Vitamin D comes from sunlight (80%) and diet (20%). Spend 15-30 minutes outdoors daily with forearms exposed if possible. Foods rich in Vitamin D: fatty fish, eggs, fortified milk, and fortified cooking oil. The loading dose is to quickly replenish your stores — then a daily maintenance dose is needed long-term.',
    'Endocrine/metabolic bone clinic in 3 months for repeat labs. Physiotherapy for ongoing muscle strengthening. If no improvement or concerning features, check for malabsorption (coeliac, pancreatic insufficiency).',
    'Vitamin D deficiency is highly prevalent in Kenya, especially in urban populations with limited sun exposure (office workers, full-body clothing). The clinical syndrome of Vitamin D deficiency spans: rickets (children), osteomalacia (adults — bone pain, muscle weakness, pseudofractures), and osteoporosis (elderly). Looser zones (pseudofractures) on X-ray are pathognomonic for osteomalacia. Vitamin D is fat-soluble — absorption requires dietary fat.',
    ['Endocrine Society Guidelines: Vitamin D Deficiency', 'Kenya Clinical Guidelines: Metabolic Bone Disease', 'WHO: Vitamin D Supplementation'],
  ),

  tpl(
    'Vitamins & Nutrition', 'Internal Medicine', 'Vitamin B12 Deficiency',
    'Vitamin B12 Deficiency Presenting with Megaloblastic Anaemia and Neuropathy',
    'Intermediate',
    'Progressive fatigue, numbness and tingling in hands and feet, and difficulty walking for 3 months',
    '{name}, a {age}-year-old {occupation} from {location}, presents with gradually worsening fatigue, shortness of breath on exertion, palpitations, and pallor over 3-4 months. Also reports numbness, tingling ("pins and needles") in both hands and feet, unsteady gait (worse in the dark), and memory lapses. Diet is strictly vegetarian (no meat, fish, eggs, or dairy). No GI symptoms. No family history of pernicious anaemia.',
    'Longstanding vegetarian diet (lifelong, no animal products). No known GI disease. No gastric surgery. No alcohol use.',
    'No regular medications',
    'Pale with mild jaundice (lemon-yellow tint). Tachycardic (HR 108). Glossitis (smooth, red, depapillated tongue). Neurological: decreased vibration sense in both ankles (128 Hz tuning fork: 8 seconds, normal >15), impaired proprioception (positive Romberg test), and a wide-based ataxic gait. Bilateral extensor plantars (Babinski present). Peripheral sensory loss in a stocking-glove distribution.',
    'Hb 7.8 g/dL (12-15). MCV 115 fL (80-100) — macrocytic. MCH 35 pg (27-32). Reticulocyte count: 0.5% (low). WBC 3.5 (mild leukopenia). Platelets 120 (mild thrombocytopenia). Peripheral smear: macro-ovalocytes, hypersegmented neutrophils (5+ lobes). Vitamin B12: 110 pg/mL (normal 200-900). Folate: 12 ng/mL (normal >4). Intrinsic Factor Antibodies: negative (suggests nutritional cause rather than pernicious anaemia). Bilirubin: 1.4 mg/dL (mildly elevated, indirect). LDH: 850 U/L (elevated, haemolysis).',
    'No imaging indicated.',
    'Vitamin B12 Deficiency — Megaloblastic Anaemia with Subacute Combined Degeneration of the Spinal Cord',
    ['B12 Deficiency', 'Folate Deficiency', 'Myelodysplastic Syndrome', 'Thyroid Disease', 'Multiple Sclerosis'],
    'Correct B12 deficiency, reverse haematological and neurological abnormalities, prevent irreversible neurological damage, address dietary cause',
    '1. B12 replacement: IM Hydroxocobalamin 1000 mcg ON ALTERNATE DAYS for 1-2 weeks (6-7 injections total), then weekly for 4 weeks, then monthly for life if pernicious anaemia OR until dietary correction. 2. For severe neurological symptoms (as here): may continue weekly for 3-6 months then monthly. 3. Oral B12 maintenance (if no malabsorption): Methylcobalamin 1000-2000 mcg daily. 4. Folic acid 5mg once daily (IMPORTANT: give WITH B12, never alone in B12 deficiency — folate alone corrects anaemia but allows neurological damage to progress). 5. Blood transfusion only if severe anaemia with cardiac compromise (not needed here).',
    'Dietary counselling: include B12-rich foods (meat, liver, fish, eggs, dairy) or fortified foods. If continuing vegetarian diet, advise lifelong B12 supplementation. Balance and gait training with physiotherapy.',
    'Start IM Hydroxocobalamin loading. Add Folic acid 5mg daily. Monitor reticulocyte count (should rise in 3-5 days, peak at 7-10 days). Hb should increase by 1 g/dL per week. Neurological improvement is slower (weeks to months) and may be incomplete if damage is severe or prolonged.',
    '1. Severe B12 deficiency causing both megaloblastic anaemia and neurological damage. 2. Dietary deficiency due to strict vegetarian diet — risk of irreversible neurological damage if untreated.',
    'Reticulocyte count on Day 3-5 (should show brisk response). Hb, MCV, WBC, platelets weekly until normalised. B12 levels monthly during loading phase. Neurological exam: vibration sense, gait, Romberg, reflexes. Improvement in neurological symptoms typically begins at 4-6 weeks.',
    'B12 is found only in animal-source foods. If you continue a vegetarian diet, you must take B12 supplements for life — the deficiency can cause permanent nerve damage and paralysis. Injections will quickly improve your energy, but nerve recovery may take months. Tingling should improve first; balance may take longer.',
    'Haematology/endocrine clinic in 4 weeks. Continue IM B12 monthly. Neurological assessment at 3 and 6 months. Repeat B12 and FBC at 3 months to confirm adequacy of maintenance regimen.',
    'Megaloblastic anaemia from B12 deficiency is characterised by macrocytic RBCs (MCV >100) and hypersegmented neutrophils (more specific than MCV alone). The classic triad: anaemia, glossitis, and neuropathy. Subacute combined degeneration of the spinal cord affects: posterior columns (vibration/proprioception loss → sensory ataxia) + corticospinal tracts (spasticity, Babinski) + peripheral nerves. NEVER give folate without B12 if B12 deficiency is suspected — this corrects the anaemia but allows neurological damage to progress.',
    ['BSH Guidelines: B12 and Folate Deficiency', 'Kenya Clinical Guidelines: Macrocytic Anaemia', 'WHO: Micronutrient Supplementation'],
  ),

  tpl(
    'Vitamins & Nutrition', 'Internal Medicine', 'Folate Deficiency',
    'Folate Deficiency Anaemia in Pregnancy',
    'Beginner',
    'Extreme fatigue, shortness of breath on minimal exertion, and pallor in the third trimester',
    '{name}, a {age}-year-old pregnant woman (G2P1, 32 weeks gestation) from {location}, presents with progressive fatigue, weakness, dyspnoea on climbing stairs, palpitations, and pallor. Has not been taking her prenatal vitamins consistently due to nausea and forgetfulness. Reports adequate diet but poor vegetable intake (financial constraints). No GI symptoms. No prior anaemia in first pregnancy.',
    'G2P1 at 32 weeks gestation. First pregnancy: uncomplicated, term vaginal delivery, no anaemia. No chronic illnesses.',
    'Intermittent Folic Acid 5mg daily and Ferrous Sulphate 200mg daily (not adherent). No other medications.',
    'Pale conjunctivae, pale palmar creases. Tachycardic (HR 105). BP 110/65. Mild pitting oedema in lower extremities (non-pathological in pregnancy). Uterine fundal height 32 cm (appropriate for dates). Fetal heart rate 140 bpm, reactive. No signs of preeclampsia.',
    'Hb 8.0 g/dL (11-14 in pregnancy). MCV 106 fL (80-100) — macrocytic. MCH 34 pg. Reticulocyte count: 0.8% (low). Serum Folate: 2.5 ng/mL (normal >4). Vitamin B12: 400 pg/mL (normal). Ferritin: 45 ng/mL (normal — differentiates from iron deficiency). Peripheral smear: macro-ovalocytes, hypersegmented neutrophils. Hb electrophoresis: normal. LDH: 550 U/L.',
    'No imaging indicated.',
    'Folate Deficiency Anaemia (Megaloblastic) in Pregnancy',
    ['Folate Deficiency Anaemia', 'Iron Deficiency Anaemia', 'B12 Deficiency Anaemia', 'Anaemia of Chronic Disease', 'Haemoglobinopathy'],
    'Correct folate deficiency, manage anaemia in pregnancy, prevent neural tube defects, optimise maternal and foetal outcomes',
    '1. Folic Acid 5mg PO daily for at least 4-6 weeks (until Hb normalised). 2. Continue for the remainder of pregnancy and postpartum (at least 3 months). 3. Continue Iron supplementation concurrently (Ferrous Sulphate 200mg daily). 4. If Hb <7 g/dL with symptoms or near term: consider blood transfusion. 5. Ensure adequate dietary folate intake.',
    'Dietary counselling: increase intake of folate-rich foods (dark leafy greens — sukuma wiki, managu, spinach; beans, lentils, oranges, liver, fortified maize meal). Food preparation: avoid overcooking vegetables (folate is heat-labile). Nutrition support if financial constraints.',
    'Start Folic Acid 5mg daily. Continue iron. Recheck Hb, MCV, folate in 4 weeks. Reticulocyte count should rise in 3-5 days. Optimal Hb response: 1 g/dL per week. Ensure adherence to supplements. Assess nutritional status and provide dietary counselling.',
    '1. Folate deficiency in pregnancy due to inadequate intake and poor supplement adherence. 2. Risk of neural tube defects in this (and future) pregnancies if deficiency persists in first trimester.',
    'Hb, MCV, reticulocyte count at 4 weeks. Ensure folate level is normalised. Monitor for other pregnancy complications (preeclampsia, preterm labour). Fetal growth ultrasound if available.',
    'Folic acid is essential for the baby\'s brain and spinal cord development, especially in early pregnancy. The tablets are small and easy to take. Set a daily reminder, or take them with your evening meal. Eat plenty of green vegetables like sukuma wiki, managu, and spinach — they are natural sources of folate. This anaemia will resolve in 1-2 months with daily supplements.',
    'Obstetric clinic in 2 weeks for foetal assessment and supplement adherence check. Continue folic acid until at least 3 months postpartum. In future pregnancies: start folic acid 5mg daily at least 1 month before conception and continue through first trimester for neural tube defect prevention.',
    'Folate deficiency is one of the most common nutritional deficiencies in pregnancy due to increased requirements and inadequate intake. Macrocytosis (MCV >100) in pregnancy may be masked by concurrent iron deficiency (microcytic changes can normalise MCV). In Kenya, all pregnant women should receive daily iron + folic acid supplementation as part of routine antenatal care. Periconceptional folic acid (4 weeks before to 12 weeks after conception) reduces neural tube defect risk by up to 70%.',
    ['WHO Recommendations: Iron and Folate Supplementation in Pregnancy', 'Kenya Clinical Guidelines: Anaemia in Pregnancy', 'BSH Guidelines: Anaemia in Pregnancy'],
  ),

  tpl(
    'Vitamins & Nutrition', 'Nutrition', 'Malnutrition',
    'Severe Acute Malnutrition with Medical Complications in a Child',
    'Advanced',
    'Profound wasting, loss of appetite, and bilateral leg swelling in a 2-year-old',
    '{name}, a {age}-year-old boy from a rural area near {location}, is brought by his grandmother with a 2-month history of progressive weight loss, loss of appetite, diarrhoea, and worsening swelling of the feet and legs. He was exclusively breastfed for 3 months then switched to dilute cow milk and thin maize porridge (uji) with no added oil or protein. He had measles 3 months ago. The family is experiencing food insecurity.',
    'Frequent infections: diarrhoeal disease, measles 3 months ago. Immunisation status: incomplete (no MMR, no Vitamin A).',
    'No medications. No supplements.',
    'Weight: 7.5 kg (expected weight for age 2 years: ~11 kg). Height 78 cm. Severe wasting (weight-for-height Z-score: -3.8, below -3SD). Bilateral pitting oedema of feet and lower legs. Visible severe muscle wasting (wasted buttocks, visible ribs, "baggy pants" appearance). Skin: patchy depigmentation, flaky paint dermatosis. Hair: thin, brittle, reddish discolouration (sign of chronic malnutrition). Mild hepatomegaly. Apathetic and irritable. Temperature 36.5°C.',
    'Hb 8.5 g/dL (moderate anaemia). Albumin 1.8 g/dL (severely low). Glucose 55 mg/dL (hypoglycaemia — fasting). Na+ 132, K+ 3.1 (hyponatraemia, hypokalaemia). HIV test: negative. Stool microscopy: no ova/cysts. Tuberculin skin test: negative. CXR: normal.',
    'No acute imaging needed.',
    'Severe Acute Malnutrition (SAM) with Oedema (Kwashiorkor) and Medical Complications (Hypoglycaemia, Hypothermia Risk, Electrolyte Imbalance)',
    ['Kwashiorkor', 'Marasmus', 'Marasmic-Kwashiorkor', 'Nephrotic Syndrome', 'Chronic Liver Disease'],
    'Stabilise acute complications (hypoglycaemia, hypothermia, electrolyte imbalance), initiate therapeutic feeding, treat infections, prevent mortality',
    '1. STABILISATION PHASE (Days 1-7): a) Correct hypoglycaemia: 10% dextrose 5 mL/kg IV or 50mL of 10% dextrose orally/NG if conscious. b) Broad-spectrum antibiotics: IV Ampicillin 50mg/kg Q6H + Gentamicin 7.5mg/kg daily for 7 days (even without overt infection — SAM patients have impaired immunity). c) Therapeutic milk F75: 130 mL/kg/day divided into 8-12 feeds (start at 100 mL/kg/day if severe oedema). d) Micronutrients: Vitamin A 200,000 IU stat (age-appropriate dose), Folic Acid 5mg day 1, 1mg daily thereafter, Zinc 10mg daily, Multivitamin drops. e) NO iron in stabilisation phase (can worsen infection). f) Correct hypothermia: KMC (kangaroo mother care), warm environment. 2. TRANSITION PHASE: When appetite returns (usually Day 3-7), transition to F100 therapeutic milk. 3. REHABILITATION PHASE: Transition to nutritionally complete foods (PlumpyNut, PlumpySup). Introduce iron once infection resolved and weight gain established.',
    'Kangaroo mother care (skin-to-skin contact) for thermoregulation. Sensory stimulation (play, talking to child). Safe water and hygiene. Food security assessment and referral.',
    'Admit to nutrition rehabilitation unit. Strict monitoring: vitals q2h, blood glucose q2-4h initially, weight daily, oedema score daily. F75 feeds via NG initially (8-12 feeds/day). When appetite returns and oedema improving, transition to F100. Monitor for refeeding syndrome (hypophosphataemia, hypokalaemia, hypomagnesaemia). Immunisations: complete all catch-up vaccines when stable.',
    '1. Severe acute malnutrition with medical complications (hypoglycaemia, electrolyte imbalance, severe wasting) requiring urgent therapeutic feeding. 2. Underlying food insecurity and poor feeding practices requiring nutrition education and social support. 3. Increased infection risk due to compromised immune function.',
    'Phase 1 (Stabilisation): Blood glucose q2-4h, vitals q2h, intake/output strictly recorded. Daily: weight, oedema score, temperature. Monitor for: refeeding syndrome (phosphate, K+, Mg after 48 hours), fluid overload, infection. Once stable: weekly weight gain target >10 g/kg/day.',
    'The small frequent feeds are essential — your child\'s body needs to be carefully reintroduced to nutrition to avoid dangerous complications. With proper treatment, your child will steadily gain weight and strength. Continue breastfeeding (if still) on demand. We will teach you how to prepare nutrient-rich complementary foods at home.',
    'Weekly until discharge criteria met (child not oedematous, weight-for-height >-2 Z-score, gaining at least 10 g/kg/day for 3 consecutive days). Then monthly follow-up at outpatient therapeutic programme until fully recovered. Food security and social service referral.',
    'SAM is the most dangerous form of malnutrition with high mortality (up to 30% without treatment). The "10 Steps" of SAM management: 1) Hypoglycaemia, 2) Hypothermia, 3) Dehydration, 4) Electrolyte Imbalance, 5) Infection, 6) Micronutrients (NO iron initially), 7) Initiate F75, 8) Catch-up with F100 or RUTF, 9) Developmental stimulation, 10) Prepare for discharge. Refeeding syndrome is a real danger — start feeds slow (100 mL/kg/day F75, advance over 5-7 days).',
    ['WHO Guidelines: Severe Acute Malnutrition', 'Kenya Clinical Guidelines: SAM Management', 'UNICEF: SAM Treatment Protocol'],
  ),
];
