#!/usr/bin/env node
/**
 * finalEnrichment.mjs — Last-mile enrichment: replace remaining generic placeholders
 * by drug_class mapping, covering all 100+ classes from the generate script.
 */
import { readFileSync, writeFileSync } from 'fs'
import { CLASS_TEMPLATES } from './drugClassTemplates.mjs'

const FILE = 'src/data/drugIndexData.ts'
let src = readFileSync(FILE, 'utf-8')

// ═══════════════════════════════════════════════════════════════════════
// COMPREHENSIVE CLASS→CONTENT MAP (covers all generateDrugIndex.mjs classes)
// ═══════════════════════════════════════════════════════════════════════

const CLASS_CONTENT = {
  // Anti-infectives
  'Penicillin': { moa: 'Bactericidal: inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins (PBPs), blocking transpeptidation and peptidoglycan cross-linking.', pk: 'PO: well absorbed, food delays but not reduces absorption. Vd: wide. t1/2: 1-1.3h. Metabolism: minimal hepatic. Excretion: renal (active tubular secretion). BBW: Anaphylaxis risk — assess penicillin allergy before use.', bbw: ['Anaphylaxis and serious allergic reactions reported — assess allergy history before each course'], pearls: ['Take with food to reduce GI upset', 'Complete full course to prevent resistance', 'Cross-reactivity with cephalosporins ~5-10% if IgE-mediated'], warnings: ['Serious and occasionally fatal hypersensitivity (anaphylaxis) reported', 'C. difficile-associated diarrhea may occur', 'Superinfection with prolonged use'], overdose: 'Symptoms: seizures, GI disturbance. Management: supportive care. Penicillin is dialyzable.' },
  'Cephalosporin': { moa: 'Bactericidal: inhibits bacterial cell wall synthesis via PBP binding, disrupting peptidoglycan cross-linking. Broad-spectrum activity varying by generation.', pk: 'PO: variable absorption by generation. IV: 100% bioavailability. Vd: wide, 3rd gen penetrate CSF. t1/2: 0.5-8h depending on generation. Metabolism: minimal. Excretion: renal.', bbw: ['Ceftriaxone: do not mix with calcium-containing IV solutions in neonates — fatal precipitates'], pearls: ['1st gen: Gram-positive; 3rd gen: broad including Gram-negative; 4th gen: Pseudomonas', 'Ceftriaxone once-daily simplifies outpatient IV therapy', 'Cross-allergy with penicillins ~5-10%'], warnings: ['Hypersensitivity cross-reactivity with penicillins', 'C. difficile-associated diarrhea', 'Biliary pseudolithiasis with ceftriaxone'], overdose: 'Symptoms: seizures (especially cefepime in renal impairment). Management: supportive care, hemodialysis.' },
  'Carbapenem': { moa: 'Bactericidal: inhibits cell wall synthesis via PBP binding with exceptional stability against most beta-lactamases including ESBL and AmpC. Broadest spectrum beta-lactam.', pk: 'IV only (except tebipenem PO). Vd: wide, penetrates CSF with meningeal inflammation. t1/2: 1-1.5h (doripenem 2h). Metabolism: renal (dehydropeptidase-1 for imipenem — co-administer cilastatin). Excretion: renal.', pearls: ['Imipenem always paired with cilastatin (DHP-1 inhibitor)', 'Meropenem has lower seizure risk than imipenem', 'Doripenem: extended infusion optimizes PK/PD'], warnings: ['Seizures especially with imipenem and renal impairment', 'Cross-reactivity with penicillins ~1%', 'C. difficile-associated diarrhea'], overdose: 'Symptoms: seizures. Management: supportive care, hemodialysis.' },
  'Macrolide': { moa: 'Bacteriostatic: binds to 50S ribosomal subunit, inhibiting bacterial protein synthesis by blocking peptide chain elongation. Also has immunomodulatory effects.', pk: 'PO: absorption affected by food (except azithromycin). Hepatic metabolism via CYP3A4. t1/2: azithromycin 68h, clarithromycin 5-7h, erythromycin 1.5h. Excretion: biliary/fecal primarily.', pearls: ['Azithromycin: 3-day course for community-acquired pneumonia', 'Clarithromycin: strong CYP3A4 inhibitor — check drug interactions', 'Erythromycin: prokinetic at low doses'], warnings: ['QT prolongation risk — avoid with other QT-prolonging drugs', 'Hepatotoxicity (cholestatic jaundice)', 'CYP3A4 inhibition — significant drug interactions'], overdose: 'Symptoms: hearing loss, nausea, vomiting. Management: supportive care, activated charcoal if recent ingestion.' },
  'Fluoroquinolone': { moa: 'Bactericidal: inhibits DNA gyrase (topoisomerase II) and topoisomerase IV, preventing bacterial DNA replication and transcription.', pk: 'PO: excellent bioavailability (90-100%). Vd: wide. t1/2: 3-7h. Metabolism: hepatic (CYP1A2 for some). Excretion: renal (some biliary). Chelation with divalent cations.', pearls: ['Levofloxacin: respiratory fluoroquinolone (enhanced Gram-positive)', 'Ciprofloxacin: urinary/GI infections', 'Avoid with dairy/antacids (chelation)'], warnings: ['Tendon rupture/disopathy — stop if tendon pain occurs', 'QT prolongation, peripheral neuropathy, CNS effects', 'Avoid in myasthenia gravis (exacerbation)'], overdose: 'Symptoms: CNS stimulation, seizures. Management: supportive care, antacids to chelate.' },
  'Tetracycline': { moa: 'Bacteriostatic: binds to 30S ribosomal subunit, inhibiting bacterial protein synthesis by blocking aminoacyl-tRNA binding. Also has anti-inflammatory effects.', pk: 'PO: absorption impaired by food, dairy, antacids, iron. Vd: wide. t1/2: 6-12h. Metabolism: minimal hepatic. Excretion: fecal and renal.', pearls: ['Doxycycline: better tolerated, can take with food', 'Minocycline: CNS penetration, vestibular side effects', 'Tigecycline: glycylcycline, broad spectrum including MRSA'], warnings: ['Photosensitivity — advise sunscreen', 'Esophageal ulceration — take upright with water', 'Contraindicated in pregnancy and children <8y'], overdose: 'Symptoms: GI upset, vomiting. Management: gastric lavage, activated charcoal.' },
  'Aminoglycoside': { moa: 'Bactericidal: irreversibly binds 30S ribosomal subunit, causing mRNA misreading and inhibiting protein synthesis. Concentration-dependent killing with post-antibiotic effect.', pk: 'IV/IM only. Vd: extracellular (0.25 L/kg). t1/2: 2-3h (延长 in renal impairment). Excretion: renal (glomerular filtration). No significant metabolism.', pearls: ['Once-daily dosing: gentamicin 5mg/kg, tobramycin 5mg/kg', 'TDM mandatory: trough <1 mcg/mL, peak 5-10 mcg/mL (traditional)', 'Synergy with beta-lactams for enterococcal endocarditis'], warnings: ['Nephrotoxicity — monitor SCr, BUN', 'Ototoxicity — monitor hearing and vestibular function', 'Neuromuscular blockade risk — caution with NM blockers'], overdose: 'Symptoms: neuromuscular blockade, renal failure. Management: hemodialysis, calcium gluconate for neuromuscular effects.' },
  'Nitroimidazole': { moa: 'Bactericidal: reduced intracellularly to reactive intermediates that damage bacterial DNA and proteins. Active against anaerobes and protozoa.', pk: 'PO/IV: 100% bioavailability. Vd: wide, penetrates CSF, abscesses, amniotic fluid. t1/2: 8h (metronidazole). Metabolism: hepatic (CYP2C9). Excretion: renal and fecal.', pearls: ['Metronidazole: only oral agent for C. difficile (oral vancomycin preferred)', 'Avoid alcohol (disulfiram-like reaction)', 'Tinidazole: longer half-life, single-dose for trichomoniasis'], warnings: ['Disulfiram-like reaction with alcohol — avoid for 72h after last dose', 'Peripheral neuropathy with prolonged use', 'Carcinogenicity concern in animal studies'], overdose: 'Symptoms: seizures, peripheral neuropathy. Management: supportive care, hemodialysis.' },
  'Lincosamide': { moa: 'Bacteriostatic: binds 50S ribosomal subunit, inhibiting protein synthesis by blocking peptide bond formation. Active against anaerobes and Gram-positive cocci.', pk: 'PO: well absorbed. IV: also available. Vd: wide, penetrates bone and abscesses. t1/2: 4-5h. Metabolism: hepatic. Excretion: fecal and renal.', pearls: ['Clindamycin: excellent bone and abscess penetration', 'Clindamycin resistance testing required for S. aureus (D-test)', 'Use for anaerobic infections and penicillin allergy'], warnings: ['C. difficile-associated diarrhea — potentially fatal', 'Hepatotoxicity with IV formulation', 'Neuromuscular blockade potentiation'], overdose: 'Symptoms: GI upset. Management: supportive care.' },
  'Sulfonamide': { moa: 'Bacteriostatic: inhibits bacterial dihydrofolate synthesis by competitive antagonism of PABA, blocking nucleic acid synthesis.', pk: 'PO: well absorbed. Vd: wide. t1/2: 6-12h depending on agent. Metabolism: hepatic (acetylation). Excretion: renal (crystalluria risk).', pearls: ['TMP-SMX: first-line for PCP prophylaxis and treatment', 'IV formulation for severe infections', 'Sulfadiazine: used for toxoplasmosis and Nocardia'], warnings: ['Hypersensitivity reactions — Stevens-Johnson syndrome risk', 'Crystalluria — maintain high fluid intake', 'Blood dyscrasias — monitor CBC'], overdose: 'Symptoms: nausea, vomiting, crystalluria. Management: alkalinize urine, hemodialysis.' },
  'Urinary antiseptic': { moa: 'Concentrated in urine to achieve bactericidal levels without significant systemic absorption. Active against common uropathogens.', pk: 'PO: minimal systemic absorption. Concentrated in urine. t1/2: variable. Excretion: renal (active in urine).', pearls: ['Nitrofurantoin: avoid in CrCl <30 mL/min — ineffective and toxic', 'Fosfomycin: single-dose treatment for uncomplicated UTI', 'Methenamine: urinary antiseptic for recurrent UTI prophylaxis'], warnings: ['Nitrofurantoin: pulmonary toxicity with chronic use', 'Peripheral neuropathy with prolonged use', 'Hepatotoxicity'], overdose: 'Symptoms: GI upset. Management: supportive care.' },

  // Antifungals
  'Antifungal (Azole)': { moa: 'Antifungal: inhibits fungal CYP450 14A-demethylase, disrupting ergosterol synthesis and fungal cell membrane integrity.', pk: 'PO: variable absorption (fluconazole 90%, itraconazole 55%). Vd: wide, fluconazole penetrates CSF. t1/2: fluconazole 30h, voriconazole 6h, posaconazole 15h. Metabolism: CYP3A4/2C19 (major drug interactions). Excretion: hepatic/renal.', pearls: ['Fluconazole: first-line for Candida', 'Voriconazole: first-line for invasive aspergillosis', 'Posaconazole: broadest spectrum azole, prophylaxis in AML'], warnings: ['Hepatotoxicity — monitor LFTs', 'QT prolongation (fluconazole)', 'Drug interactions via CYP3A4 inhibition'], overdose: 'Symptoms: GI upset, hepatotoxicity. Management: supportive care, activated charcoal.' },
  'Antifungal (Polyene)': { moa: 'Antifungal: binds to ergosterol in fungal cell membranes, forming pores that cause leakage of cytoplasmic content and cell death.', pk: 'IV only (amphotericin B). Lipid formulations reduce nephrotoxicity. t1/2: 24-48h. Metabolism: minimal. Excretion: renal and biliary.', pearls: ['Liposomal amphotericin B: less nephrotoxic, preferred for most indications', 'Amphotericin B deoxycholate: nephrotoxic, use for severe mucormycosis', 'Nystatin: topical/oral only (not absorbed)'], warnings: ['Nephrotoxicity — monitor SCr, K+, Mg2+', 'Infusion-related reactions — premedicate with acetaminophen', 'Anemia — monitor Hgb'], overdose: 'Symptoms: nephrotoxicity, electrolyte disturbances. Management: supportive care, hydration.' },
  'Antifungal (Echinocandin)': { moa: 'Antifungal: inhibits beta-(1,3)-D-glucan synthase, disrupting fungal cell wall synthesis. Active against Candida and Aspergillus.', pk: 'IV only. Vd: moderate. t1/2: 9-11h (caspofungin). Metabolism: hepatic (not CYP-mediated). Excretion: biliary and renal.', pearls: ['Caspofungin: first-line for invasive candidiasis', 'Micafungin: less drug interactions', 'Anidulafungin: no hepatic metabolism'], warnings: ['Hypersensitivity reactions possible', 'Hepatotoxicity — monitor LFTs', 'Histamine-mediated reactions (flushing, rash)'], overdose: 'Symptoms: not well characterized. Management: supportive care.' },
  'Antifungal (Allylamine)': { moa: 'Antifungal: inhibits squalene epoxidase, blocking ergosterol synthesis and causing accumulation of squalene, which is toxic to the fungal cell.', pk: 'PO: well absorbed. Vd: lipophilic, concentrates in skin, nails, fat. t1/2: 17h (terbinafine). Metabolism: hepatic (CYP2D6). Excretion: fecal and renal.', pearls: ['Terbinafine: first-line for dermatophyte onychomycosis', 'Griseofulvin: older agent, for tinea capitis in children', 'Terbinafine has fungicidal activity vs. azoles (fungistatic)'], warnings: ['Hepatotoxicity — monitor LFTs', 'Taste disturbance (usually reversible)', 'Rare: Stevens-Johnson syndrome'], overdose: 'Symptoms: GI upset, headache. Management: activated charcoal if recent.' },

  // Antivirals
  'Antiviral (HSV)': { moa: 'Antiviral: phosphorylated to active triphosphate which competitively inhibits viral DNA polymerase, blocking viral DNA synthesis.', pk: 'PO: bioavailability 15-30% (acyclovir), 54% (valacyclovir). Vd: low. t1/2: 2-4h (acyclovir), extended in renal impairment. Metabolism: minimal. Excretion: renal (active tubular secretion).', pearls: ['Valacyclovir: better bioavailability than acyclovir (3-5x)', 'IV acyclovir: requires aggressive hydration — crystalline nephropathy', 'Famciclovir: good for herpes zoster'], warnings: ['Nephrotoxicity — maintain hydration', 'Neurotoxicity with IV in renal impairment', 'Thrombotic thrombocytopenic purpura (rare, immunocompromised)'], overdose: 'Symptoms: seizures, nephrotoxicity. Management: hydration, hemodialysis.' },
  'Antiviral (Influenza)': { moa: 'Antiviral: inhibits viral neuraminidase (oseltamivir, zanamivir) or cap-dependent endonuclease (baloxavir), blocking viral release or replication.', pk: 'Oseltamivir PO: bioavailability ~80%. t1/2: 6-10h. Baloxavir PO: t1/2: ~80h. Metabolism: oseltamivir hepatic to active metabolite. Excretion: renal.', pearls: ['Oseltamivir: treatment within 48h, prophylaxis for 10 days', 'Baloxavir: single-dose treatment', 'Zanamivir: inhaled — avoid in asthma/COPD'], warnings: ['Neuropsychiatric effects in adolescents (oseltamivir)', 'Bronchospasm with zanamivir inhalation', 'Drug resistance with monotherapy'], overdose: 'Symptoms: GI upset. Management: supportive care.' },
  'Antiviral (HCV)': { moa: 'Direct-acting antivirals: inhibit HCV NS3/4A protease (glecaprevir), NS5A (pibrentasvir, velpatasvir), or NS5B polymerase (sofosbuvir), blocking viral replication.', pk: 'PO: well absorbed. t1/2: 5-29h depending on agent. Metabolism: varies by agent (CYP3A4 for some). Excretion: fecal and renal.', pearls: ['Sofosbuvir/velpatasvir: pan-genotypic, 12 weeks', 'Glecaprevir/pibrentasvir: pan-genotypic, 8 weeks (treatment-naive)', 'Monitor hepatic decompensation — avoid in Child-Pugh C'], warnings: ['HBV reactivation if co-infected — screen before starting', 'Hepatic decompensation in cirrhosis', 'Significant drug interactions (CYP3A4/P-gp inducers)'], overdose: 'Symptoms: not well characterized. Management: supportive care.' },
  'Antiviral (HIV)': { moa: 'Antiretroviral: inhibits HIV replication through various mechanisms (NRTI, NNRTI, INSTI, PI, entry inhibitor).', pk: 'Varies by class. Generally well absorbed orally. Most require adherence optimization. Metabolism: CYP3A4/P-gp interactions common.', pearls: ['ART should be started as soon as possible after HIV diagnosis', 'TAF preferred over TDF for renal/bone safety', 'Bictegravir/DTG: preferred first-line INSTI backbone'], warnings: ['IRIS in advanced HIV — consider starting ART after OIs treated', 'Hepatotoxicity — monitor LFTs', 'Drug interactions critical — always check compatibility'], overdose: 'Symptoms: GI upset. Management: supportive care.' },

  // Cardiovascular
  'ACE inhibitor': { moa: 'ACE inhibitor: competitively inhibits angiotensin-converting enzyme, reducing angiotensin II formation, decreasing vasoconstriction and aldosterone secretion.', pk: 'PO: bioavailability 25-75% (varies). Vd: low-moderate. t1/2: 2-12h (enalaprilat 11h). Metabolism: hepatic (prodrug activation for enalapril). Excretion: renal.', pearls: ['Start low, titrate slowly', 'First-dose hypotension in volume-depleted patients', 'ACEi-avoid in pregnancy (teratogenic)'], warnings: ['Angioedema — discontinue permanently', 'Hyperkalemia — monitor K+ and renal function', 'Renal artery stenosis — contraindicated'], overdose: 'Symptoms: severe hypotension, bradycardia. Management: IV normal saline, atropine if needed.' },
  'ARB': { moa: 'ARB: selectively blocks AT1 angiotensin II receptors, reducing angiotensin II-mediated vasoconstriction and aldosterone secretion.', pk: 'PO: bioavailability 25-40% (losartan). Vd: moderate. t1/2: 2-9h (losartan), 11h (valsartan). Metabolism: hepatic (CYP2C9 for losartan). Excretion: biliary and renal.', pearls: ['Losartan: uricosuric effect — useful in gout', 'Valsartan/Entresto: ARNI for heart failure', 'ARBs preferred if ACEi cough occurs'], warnings: ['Fetal toxicity — contraindicated in pregnancy', 'Hyperkalemia — monitor with K+ and renal function', 'Angioedema (rare compared to ACEi)'], overdose: 'Symptoms: hypotension, bradycardia. Management: IV fluids, vasopressors if needed.' },
  'Calcium channel blocker (DHP)': { moa: 'Dihydropyridine CCB: blocks L-type calcium channels in vascular smooth muscle, causing arterial vasodilation and reduced peripheral vascular resistance.', pk: 'PO: variable absorption. Vd: high. t1/2: amlodipine 35-50h, nifedipine 2-5h (extended-release). Metabolism: hepatic (CYP3A4). Excretion: fecal primarily.', pearls: ['Amlodipine: longest half-life, once-daily dosing', 'Peripheral edema is dose-related — add ACEi to manage', 'Extended-release formulations preferred'], warnings: ['Peripheral edema (not fluid overload)', 'Gingival hyperplasia', 'Reflex tachycardia with short-acting formulations'], overdose: 'Symptoms: hypotension, bradycardia. Management: IV calcium, vasopressors, atropine.' },
  'Calcium channel blocker (Non-DHP)': { moa: 'Non-dihydropyridine CCB: blocks L-type calcium channels in cardiac myocytes and vascular smooth muscle, reducing heart rate, AV conduction, and contractility.', pk: 'PO: well absorbed. Vd: moderate. t1/2: verapamil 3-7h, diltiazem 3-5h. Metabolism: hepatic (CYP3A4 — significant interactions). Excretion: renal and fecal.', pearls: ['Verapamil: rate control in AF, migraine prophylaxis', 'Diltiazem: intermediate — less negative inotrope than verapamil', 'Both: avoid with beta-blockers (heart block risk)'], warnings: ['Heart failure exacerbation — avoid in systolic HF', 'AV block — monitor ECG', 'Constipation (verapamil — common in elderly)'], overdose: 'Symptoms: hypotension, bradycardia, heart block. Management: IV calcium, atropine, glucagon.' },
  'Beta-blocker': { moa: 'Beta-blocker: blocks beta-adrenergic receptors, reducing heart rate, contractility, and myocardial oxygen demand.', pk: 'PO: variable bioavailability (propranolol 25%, metoprolol 50%, bisoprolol 90%). Vd: lipophilic (propranolol) vs hydrophilic (atenolol). t1/2: 6-12h. Metabolism: hepatic (CYP2D6). Excretion: renal.', pearls: ['Metoprolol succinate: once-daily, prefer for HF', 'Bisoprolol: most cardioselective, once-daily', 'Carvedilol: alpha+beta blockade, good for HF'], warnings: ['Bradycardia — avoid in HR <50', 'Bronchospasm — avoid non-selective in asthma', 'Withdrawal tachycardia — taper over 1-2 weeks'], overdose: 'Symptoms: severe bradycardia, hypotension, bronchospasm. Management: glucagon, atropine, isoproterenol.' },
  'Thiazide diuretic': { moa: 'Thiazide diuretic: inhibits Na+/Cl- cotransporter in distal convoluted tubule, increasing sodium and water excretion while reducing peripheral vascular resistance.', pk: 'PO: well absorbed. t1/2: 6-15h (hydrochlorothiazide). Metabolism: minimal. Excretion: renal.', pearls: ['Chlorthalidone: preferred for HTN trials — longer acting', 'HCTZ: most commonly prescribed', 'Indapamide: metabolically neutral'], warnings: ['Hypokalemia — monitor K+', 'Hyperuricemia — caution in gout', 'Hyperglycemia — monitor in diabetes'], overdose: 'Symptoms: dehydration, hypotension, electrolyte disturbances. Management: fluid resuscitation, electrolyte correction.' },
  'Loop diuretic': { moa: 'Loop diuretic: inhibits Na+/K+/2Cl- cotransporter in thick ascending loop of Henle, producing potent diuresis and venodilation.', pk: 'PO/IV: variable absorption. IV onset 5min (furosemide). t1/2: 1.5h (furosemide). Metabolism: minimal. Excretion: renal.', pearls: ['Furosemide: IV preferred for acute pulmonary edema', 'Bumetanide: 40x more potent than furosemide', 'Torsemide: longer acting, better bioavailability'], warnings: ['Ototoxicity — avoid with aminoglycosides', 'Hypokalemia, hyponatremia', 'Dehydration — monitor volume status'], overdose: 'Symptoms: dehydration, hypotension, electrolyte disturbances. Management: fluid resuscitation.' },
  'Potassium-sparing diuretic': { moa: 'Potassium-sparing diuretic: competitive aldosterone antagonist in collecting duct, inhibiting Na+/K+ exchange.', pk: 'PO: variable absorption. t1/2: 1.3h (spironolactone), 3.5h (amiloride). Metabolism: hepatic (spironolactone). Excretion: renal.', pearls: ['Spironolactone: first-line for HF (RALES trial)', 'Eplerenone: selective — less gynecomastia', 'Amiloride: K+-sparing without aldosterone antagonism'], warnings: ['Hyperkalemia — monitor K+', 'Gynecomastia with spironolactone', 'Avoid with ACEi/ARB in renal impairment'], overdose: 'Symptoms: hyperkalemia, dehydration. Management: calcium gluconate, insulin/glucose.' },
  'Statin': { moa: 'HMG-CoA reductase inhibitor: inhibits HMG-CoA reductase, reducing hepatic cholesterol biosynthesis. Also has pleiotropic anti-inflammatory and plaque-stabilizing effects.', pk: 'PO: variable absorption (simvastatin 5%, atorvastatin 14%). Vd: high hepatic extraction. t1/2: 1.5-2h (simvastatin), 14h (atorvastatin). Metabolism: CYP3A4 (atorvastatin, simvastatin, lovastatin), CYP2C9 (fluvastatin), minimal (rosuvastatin, pravastatin). Excretion: fecal.', pearls: ['Atorvastatin: most potent, once-daily', 'Rosuvastatin: lowest drug interaction potential', 'Pravastatin: no CYP metabolism — safest'], warnings: ['Myopathy/rhabdomyolysis — report unexplained muscle pain', 'Hepatotoxicity — monitor LFTs', 'Contraindicated in pregnancy'], overdose: 'Symptoms: GI upset. Management: supportive care.' },
  'Anticoagulant': { moa: 'Anticoagulant: inhibits coagulation factors. Heparin potentiates antithrombin III. Warfarin inhibits VKORC1. DOACs directly inhibit specific factors.', pk: 'Heparin: IV/SC, no oral. Warfarin: PO, 100% bioavailability, rapid onset. DOACs: PO, variable absorption. Most hepatic metabolism.', pearls: ['LMWH: weight-based, no routine monitoring', 'DOACs: no INR monitoring needed', 'Warfarin: multiple food/drug interactions'], warnings: ['Bleeding risk — monitor for signs', 'Heparin-induced thrombocytopenia (HIT)', 'Warfarin: many drug interactions'], overdose: 'Heparin: protamine sulfate. Warfarin: vitamin K, FFP/PCC. DOACs: specific reversal agents (andexanet alfa for Xa inhibitors).' },
  'Antiplatelet': { moa: 'Antiplatelet: inhibits platelet aggregation. Aspirin irreversibly acetylates COX-1. P2Y12 inhibitors reversibly block ADP receptor.', pk: 'Aspirin: PO, rapid absorption. Clopidogrel: PO, prodrug (CYP2C19). Ticagrelor: PO, reversible binding. Prasugrel: PO, prodrug (faster activation).', pearls: ['Aspirin 75-100mg for secondary prevention', 'Clopidogrel: CYP2C19 poor responders — consider ticagrelor', 'DAPT: aspirin + P2Y12 inhibitor for ACS/stenting'], warnings: ['Bleeding risk — GI protection with PPI if high risk', 'Aspirin resistance', 'Thrombotic thrombocytopenic purpura (clopidogrel)'], overdose: 'Symptoms: bleeding. Management: platelet transfusion, desmopressin for aspirin.' },
  'Cardiac glycoside': { moa: 'Cardiac glycoside: inhibits Na+/K+-ATPase, increasing intracellular Ca2+, enhancing myocardial contractility. Vagomimetic effects on AV node.', pk: 'PO/IV. Vd: large (5-7 L/kg). t1/2: 36-40h (digoxin). Metabolism: hepatic (minimal, 15%). Excretion: renal (60-80%). Narrow therapeutic index.', pearls: ['Therapeutic level: 0.5-0.9 ng/mL', 'Hypokalemia increases toxicity risk — monitor K+', 'Antidote: Digibind (digoxin immune Fab)'], warnings: ['Toxicity: visual changes, arrhythmias, GI symptoms', 'Renal impairment reduces clearance', 'Drug interactions: amiodarone, verapamil increase levels'], overdose: 'Symptoms: life-threatening arrhythmias. Management: Digibind, atropine, electrical cardioversion.' },
  'Nitrate vasodilator': { moa: 'Nitrate vasodilator: converted to nitric oxide, activating guanylate cyclase, increasing cGMP, causing smooth muscle relaxation and vasodilation.', pk: 'Sublingual: rapid onset (1-3min). PO: extensive first-pass (nitroglycerin). Transdermal: avoids first-pass. t1/2: 1-4min (nitroglycerin). Metabolism: hepatic (aldehyde dehydrogenase).', pearls: ['Nitrate-free interval: 10-12h to prevent tolerance', 'Isosorbide mononitrate: once-daily, no tolerance', 'Sublingual nitroglycerin: acute angina'], warnings: ['Severe hypotension — avoid with PDE5 inhibitors (24h for sildenafil, 48h for tadalafil)', 'Headache (common, dose-limiting)', 'Tolerance with continuous use'], overdose: 'Symptoms: severe hypotension, headache. Management: elevation of legs, IV fluids.' },
  'ARNI': { moa: 'ARNI (sacubitril/valsartan): sacubitril inhibits neprilysin, increasing natriuretic peptides; valsartan blocks AT1 receptors. Combined neurohormonal blockade.', pk: 'PO: sacubitril bioavailability ~60%. Active metabolite LBQ657: t1/2 11h. Valsartan: t1/2 9.5h. Metabolism: hepatic. Excretion: fecal.', pearls: ['Replace ACEi/ARB, not additive — 36h washout from ACEi', 'PARADIGM-HF: reduced mortality vs enalapril in HFrEF', 'Target dose: 97/103mg BID'], warnings: ['Angioedema risk — higher than ACEi alone', 'Hypotension — start low in volume-depleted', 'Hyperkalemia — monitor K+'], overdose: 'Symptoms: hypotension, dizziness. Management: IV fluids, vasopressors.' },

  // CNS
  'Benzodiazepine': { moa: 'Benzodiazepine: positive allosteric modulator of GABA-A receptors, enhancing chloride conductance and neuronal inhibition.', pk: 'PO: rapid absorption. Vd: varies (lorazepam low, diazepam high). t1/2: lorazepam 12-18h, diazepam 20-100h, midazolam 1.5-2.5h. Metabolism: hepatic (glucuronidation for lorazepam, CYP for others).', pearls: ['Lorazepam: no active metabolites, safest in elderly/liver disease', 'Diazepam: longest acting — accumulation risk', 'Midazolam: preferred for procedural sedation'], warnings: ['Respiratory depression — especially with opioids', 'Dependence and withdrawal seizures', 'Falls risk in elderly'], overdose: 'Symptoms: sedation, respiratory depression. Management: flumazenil (antidote), supportive care.' },
  'Opioid analgesic': { moa: 'Opioid: agonist at mu-opioid receptors, inhibiting pain transmission, causing analgesia, euphoria, respiratory depression, and constipation.', pk: 'Morphine: PO bioavailability 30%, IV 100%. t1/2: 2-4h. Fentanyl: 100x morphine potency. Oxycodone: CYP2D6 metabolism.', pearls: ['Morphine: active metabolite (M6G) accumulates in renal failure', 'Fentanyl: transdermal patch for chronic pain, sublingual for breakthrough', 'Methadone: NMDA receptor activity — useful for neuropathic pain'], warnings: ['Respiratory depression — titrate slowly', 'Constipation — co-prescribe laxative', 'Physical dependence — taper to avoid withdrawal'], overdose: 'Symptoms: pinpoint pupils, respiratory depression, coma. Management: naloxone (titrate to respiration, not consciousness).' },
  'Non-opioid analgesic': { moa: 'Non-opioid analgesic: inhibits COX-1/2 (NSAIDs) or central pain processing (paracetamol), reducing prostaglandin synthesis and pain perception.', pk: 'NSAIDs: variable absorption, high protein binding. t1/2: ibuprofen 2h, naproxen 14h, diclofenac 1h. Paracetamol: rapid absorption, t1/2 2h.', pearls: ['Paracetamol: first-line for most pain, <4g/day', 'NSAIDs: add PPI if GI risk factors', 'Naproxen: lowest CV risk among NSAIDs'], warnings: ['GI ulceration/bleeding with NSAIDs', 'Renal impairment — avoid in CKD', 'Paracetamol: hepatotoxic in overdose (>10g)'], overdose: 'Paracetamol: NAC (N-acetylcysteine) within 8h. NSAIDs: supportive care, hemodialysis if severe.' },
  'Anticonvulsant': { moa: 'Anticonvulsant: stabilizes voltage-gated sodium channels (carbamazepine, phenytoin, valproate), enhances GABAergic inhibition (gabapentin, pregabalin), or blocks glutamate (lamotrigine).', pk: 'Variable absorption and metabolism. Many have zero-order kinetics (phenytoin). Extensive CYP metabolism. Many interactions.', pearls: ['Levetiracetam: fewest drug interactions', 'Valproate: broadest spectrum but teratogenic', 'Phenytoin: saturation kinetics — monitor levels closely'], warnings: ['Stevens-Johnson syndrome (carbamazepine, lamotrigine)', 'Teratogenicity — avoid valproate in women of childbearing age', 'Suicidality warning (all antiepileptics)'], overdose: 'Varies by drug. Generally: supportive care, activated charcoal. Specific: charcoal for carbamazepine, hemodialysis for topiramate.' },
  'SSRI': { moa: 'SSRI: selectively inhibits serotonin reuptake transporter (SERT), increasing synaptic serotonin availability in the CNS.', pk: 'PO: well absorbed. Vd: high. t1/2: fluoxetine 2-6 days, sertraline 26h, escitalopram 27-32h. Metabolism: CYP2D6/2C19. Excretion: renal.', pearls: ['Sertraline: fewest drug interactions among SSRIs', 'Escitalopram: most selective SSRI', 'Fluoxetine: longest half-life — less withdrawal risk'], warnings: ['Suicidality in young adults (<25) — monitor closely', 'Serotonin syndrome with MAOIs/other serotonergic drugs', 'Sexual dysfunction — common, discuss upfront'], overdose: 'Symptoms: serotonin syndrome (mild in SSRI monotherapy). Management: cyproheptadine if severe.' },
  'TCA': { moa: 'TCA: inhibits serotonin and norepinephrine reuptake, with anticholinergic, antihistaminic, and alpha-blocking effects.', pk: 'PO: variable absorption. Vd: high. t1/2: 10-50h. Metabolism: hepatic (CYP2D6). Excretion: renal.', pearls: ['Amitriptyline: chronic pain, migraine prophylaxis', 'Nortriptyline: less anticholinergic than amitriptyline', 'Low-dose amitriptyline for insomnia'], warnings: ['Cardiac conduction prolongation — avoid in heart disease', 'Anticholinergic effects — urinary retention, dry mouth', 'Overdose is potentially fatal — cardiac toxicity'], overdose: 'Symptoms: seizures, cardiac arrhythmias, respiratory depression. Management: sodium bicarbonate for arrhythmias, activated charcoal.' },
  'SNRI': { moa: 'SNRI: inhibits both serotonin and norepinephrine reuptake, providing dual neurotransmitter enhancement.', pk: 'PO: well absorbed. t1/2: venlafaxine 5h, duloxetine 12h. Metabolism: CYP2D6/3A4. Excretion: renal.', pearls: ['Venlafaxine: dose-dependent SNRI effect (>150mg)', 'Duloxetine: diabetic neuropathy, fibromyalgia', 'Desvenlafaxine: active metabolite of venlafaxine'], warnings: ['Hypertension at high doses (venlafaxine)', 'Serotonin syndrome with MAOIs', 'Discontinuation syndrome — taper gradually'], overdose: 'Symptoms: serotonin syndrome, seizures. Management: supportive care, cyproheptadine.' },
  'Antipsychotic (atypical)': { moa: 'Atypical antipsychotic: blocks dopamine D2 and serotonin 5-HT2A receptors, with variable additional receptor affinities.', pk: 'PO: variable absorption. Vd: high. t1/2: olanzapine 21-54h, quetiapine 7h, aripiprazole 75h. Metabolism: CYP3A4/2D6. Excretion: fecal and renal.', pearls: ['Aripiprazole: partial D2 agonist — less metabolic effects', 'Olanzapine: effective but high metabolic risk', 'Quetiapine: sedating, used for insomnia/anxiety'], warnings: ['Metabolic syndrome — monitor weight, glucose, lipids', 'Tardive dyskinesia (less than typical)', 'Neuroleptic malignant syndrome'], overdose: 'Symptoms: sedation, hypotension, QT prolongation. Management: supportive care, activated charcoal.' },
  'Antipsychotic (typical)': { moa: 'Typical antipsychotic: primarily blocks dopamine D2 receptors in the mesolimbic pathway, reducing positive psychotic symptoms.', pk: 'PO/IM. Variable absorption. t1/2: haloperidol 14-36h, chlorpromazine 16-30h. Metabolism: hepatic. Excretion: fecal and renal.', pearls: ['Haloperidol: most potent, IM for acute agitation', 'Chlorpromazine: most sedating, lowest potency', 'Flupentixol depot: monthly injection'], warnings: ['Tardive dyskinesia — higher risk than atypicals', 'Extrapyramidal symptoms — EPS, akathisia', 'QT prolongation — ECG monitoring'], overdose: 'Symptoms: severe EPS, hypotension, QT prolongation. Management: benztropine for EPS, IV fluids.' },
  'Antiparkinsonian (dopaminergic)': { moa: 'Dopaminergic: provides dopamine precursor (levodopa) or mimics dopamine action (agonists), compensating for dopaminergic neuron loss in substantia nigra.', pk: 'Levodopa: PO, absorbed in small intestine. t1/2: 1-2h. Carbidopa inhibits peripheral DOPA decarboxylase. Bromocriptine: t1/2 15h.', pearls: ['Levodopa/carbidopa: most effective, first-line', 'Delayed-release: reduces motor fluctuations', 'Bromocriptine: preferred in pregnancy'], warnings: ['Impulse control disorders — gambling, hypersexuality', 'Hallucinations — reduce dose', 'Orthostatic hypotension'], overdose: 'Symptoms: hallucinations, dyskinesia, hypotension. Management: supportive care.' },

  // Endocrine
  'Insulin': { moa: 'Insulin: binds to insulin receptor, activating tyrosine kinase, promoting glucose uptake into cells, and suppressing hepatic glucose output.', pk: 'SC injection: onset 15-30min (rapid), 1-2h (regular), 1-2h (intermediate), 1-2h (long). Duration varies from 4-36h.', pearls: ['Rapid-acting (lispro/aspart): inject just before meals', 'Long-acting (glargine/detemir): basal, once-daily', 'Rotate injection sites — lipodystrophy risk'], warnings: ['Hypoglycemia — most common, educate on recognition/treatment', 'Lipodystrophy at injection sites', 'Hypokalemia — monitor K+ in DKA treatment'], overdose: 'Symptoms: severe hypoglycemia. Management: glucose IV/oral, glucagon if unconscious.' },
  'Biguanide': { moa: 'Biguanide (metformin): activates AMPK, reducing hepatic glucose production and improving insulin sensitivity. Does not stimulate insulin secretion.', pk: 'PO: bioavailability 50-60%. Not protein-bound. t1/2: 4-8h (plasma), 20h (tissue). Metabolism: not metabolized. Excretion: renal (tubular secretion).', pearls: ['First-line for T2DM — benefits beyond glucose (weight neutral)', 'Take with food to reduce GI effects', 'Hold before contrast procedures — renal function risk'], warnings: ['Lactic acidosis (rare, 3-10/100,000) — risk with renal impairment', 'GI side effects — titrate slowly', 'Hold 48h before and after iodinated contrast'], overdose: 'Symptoms: lactic acidosis. Management: hemodialysis, sodium bicarbonate.' },
  'Sulfonylurea': { moa: 'Sulfonylurea: binds to SUR1 on pancreatic beta cells, closing K-ATP channels, depolarizing the cell, and stimulating insulin secretion.', pk: 'PO: well absorbed. t1/2: glibenclamide 4-10h, glimepiride 5-9h, gliclazide 8-12h. Metabolism: hepatic (CYP2C9). Excretion: renal and biliary.', pearls: ['Gliclazide MR: once-daily, lowest hypoglycemia risk', 'Glimepiride: once-daily, less hypoglycemia than glibenclamide', 'Avoid in elderly — use lower doses'], warnings: ['Hypoglycemia — especially in elderly and CKD', 'Weight gain', 'Hemolytic anemia (G6PD deficiency)'], overdose: 'Symptoms: severe hypoglycemia. Management: glucose IV, octreotide if refractory.' },
  'DPP-4 inhibitor': { moa: 'DPP-4 inhibitor: blocks dipeptidyl peptidase-4, preventing degradation of GLP-1 and GIP, enhancing glucose-dependent insulin secretion.', pk: 'PO: bioavailability 70-87%. t1/2: sitagliptin 12h, vildagliptin 3h, saxagliptin 2.5h. Metabolism: varies (sitagliptin renal, saxagliptin hepatic). Excretion: renal.', pearls: ['Sitagliptin: once-daily, weight neutral', 'Saxagliptin: do not use in HF (SAVOR-TIMI 53)', 'Linagliptin: no renal adjustment needed'], warnings: ['Pancreatitis (rare) — discontinue if suspected', 'Joint pain (arthralgia)', 'Hypoglycemia when combined with insulin/sulfonylurea'], overdose: 'Symptoms: hypoglycemia. Management: oral glucose, dextrose IV.' },
  'GLP-1 receptor agonist': { moa: 'GLP-1 RA: mimics glucagon-like peptide-1, enhancing glucose-dependent insulin secretion, suppressing glucagon, delaying gastric emptying, and promoting satiety.', pk: 'Exenatide: SC, t1/2 2.4h (bid), 6h (weekly). Liraglutide: SC, t1/2 13h. Semaglutide: SC weekly (t1/2 165h) or PO (t1/2 1 week). Dulaglutide: SC weekly (t1/2 5 days).', pearls: ['Semaglutide: most potent for weight loss and CV benefit', 'Liraglutide: LEADER trial — CV benefit', 'Exenatide: first GLP-1 RA approved'], warnings: ['Pancreatitis (rare) — discontinue if suspected', 'Thyroid C-cell tumors (rodent studies) — contraindicated in MEN2/MTC', 'GI side effects — nausea, vomiting, diarrhea'], overdose: 'Symptoms: severe nausea, vomiting, hypoglycemia. Management: supportive care.' },
  'SGLT2 inhibitor': { moa: 'SGLT2 inhibitor: blocks sodium-glucose co-transporter 2 in proximal tubule, increasing urinary glucose excretion and reducing blood glucose.', pk: 'PO: bioavailability 65-90%. t1/2: dapagliflozin 13h, empagliflozin 12h, canagliflozin 10-13h. Metabolism: hepatic glucuronidation. Excretion: renal.', pearls: ['Empagliflozin: EMPA-REG — CV benefit in T2DM', 'Dapagliflozin: DAPA-CKD — benefit even without diabetes', 'Canagliflozin: CANVAS — amputation risk (class effect debated)'], warnings: ['Genital mycotic infections — counsel on hygiene', 'Diabetic ketoacidosis (euglycemic) — hold before surgery', 'Volume depletion — may cause hypotension'], overdose: 'Symptoms: dehydration, hypotension. Management: supportive care.' },
  'Thyroid hormone': { moa: 'Thyroid hormone: provides exogenous thyroid hormone (T4/T3) to replace or supplement endogenous production, regulating metabolic processes.', pk: 'Levothyroxine: PO, 40-80% absorbed, take on empty stomach. t1/2: 6-7 days (T4). Metabolism: hepatic deiodination to T3. Excretion: fecal and renal.', pearls: ['Levothyroxine: first-line for hypothyroidism', 'Start low in elderly/cardiac disease (12.5-25mcg/day)', 'Take on empty stomach, 30-60min before breakfast'], warnings: ['Overtreatment: atrial fibrillation, osteoporosis', 'Cardiac monitoring in elderly', 'Drug interactions: calcium, iron, PPI — separate by 4h'], overdose: 'Symptoms: thyrotoxicosis. Management: beta-blocker, supportive care.' },
  'Corticosteroid': { moa: 'Corticosteroid: binds to glucocorticoid receptors, modulating gene transcription to produce anti-inflammatory and immunosuppressive effects.', pk: 'PO: well absorbed. t1/2: prednisone 3-4h, prednisolone 2-3h, dexamethasone 4h, methylprednisolone 3h. Metabolism: hepatic. Excretion: renal.', pearls: ['Prednisone: most commonly used, requires hepatic conversion', 'Dexamethasone: longest acting, for cerebral edema', 'Hydrocortisone: for adrenal insufficiency (physiologic dose)'], warnings: ['Immunosuppression — infection risk', 'Hyperglycemia — monitor blood glucose', 'Osteoporosis with chronic use — bone protection needed'], overdose: 'Symptoms: hyperglycemia, immunosuppression. Management: supportive care.' },
  'Antithyroid': { moa: 'Antithyroid: inhibits thyroid peroxidase, blocking iodine organification and coupling, reducing thyroid hormone synthesis.', pk: 'PO: well absorbed. t1/2: methimazole 6h, propylthiouracil 1-2h. Metabolism: hepatic. Excretion: renal.', pearls: ['Methimazole: first-line for Graves disease (once-daily dosing)', 'Propylthiouracil: preferred in first trimester pregnancy', 'MMI: teratogenic in first trimester (aplasia cutis)'], warnings: ['Agranulocytosis — monitor WBC if fever/sore throat', 'Hepatotoxicity — PTU more than MMI', 'Hypothyroidism — monitor TFTs'], overdose: 'Symptoms: hypothyroidism. Management: supportive care.' },
  'Potassium supplement': { moa: 'Potassium: provides exogenous potassium to correct or prevent hypokalemia, essential for normal cellular, cardiac, and neuromuscular function.', pk: 'PO: well absorbed. IV: requires cardiac monitoring. t1/2: 1.5 days (total body). Excretion: renal.', pearls: ['KCl: most common, take with food to reduce GI upset', 'K-Cl SR: sustained release, less GI irritation', 'IV KCl: max 10-20 mEq/hr via central line'], warnings: ['Hyperkalemia — monitor K+ and ECG', 'GI ulceration with oral KCl', 'Extravasation necrosis with IV'], overdose: 'Symptoms: cardiac arrhythmias, cardiac arrest. Management: calcium gluconate, insulin/glucose, albuterol.' },
  'Phosphate binder': { moa: 'Phosphate binder: binds dietary phosphate in the GI tract, forming insoluble complexes that are excreted in feces, reducing phosphate absorption.', pk: 'PO: minimal systemic absorption (sevelamer, lanthanum). Calcium-based: some calcium absorbed.', pearls: ['Sevelamer: first-line, also lowers LDL', 'Lanthanum: chewable tablets, good adherence', 'Calcium-based: risk of vascular calcification'], warnings: ['Hypercalcemia with calcium-based binders', 'GI obstruction (rare)', 'Sevelamer: vitamin D and folate deficiency'], overdose: 'Symptoms: constipation. Management: supportive care.' },
  'Vitamin D': { moa: 'Vitamin D: converted to active form (1,25-dihydroxyvitamin D) in kidneys, promoting calcium absorption from gut and bone mineralization.', pk: 'PO: well absorbed with fat. t1/2: cholecalciferol 15-30 days, calcitriol 6h. Metabolism: hepatic (25-hydroxylation), renal (1-alpha-hydroxylation).', pearls: ['Cholecalciferol (D3): preferred over ergocalciferol (D2)', 'Calcitriol: active form, for CKD/renal osteodystrophy', 'Vitamin D levels: 25-OH-D, target >30 ng/mL'], warnings: ['Hypercalcemia with excessive dosing', 'Renal stones with calcium-based formulations', 'Monitor calcium and phosphate in CKD'], overdose: 'Symptoms: hypercalcemia, nephrocalcinosis. Management: hydration, corticosteroids.' },

  // Anti-infective specialty
  'Antimycobacterial': { moa: 'Antimycobacterial: inhibits mycobacterial cell wall synthesis (INH, ethambutol), protein synthesis (streptomycin), or nucleic acid synthesis (rifampicin, pyrazinamide).', pk: 'RIPE: INH (t1/2 1-3h), rifampicin (t1/2 3-4h), ethambutol (t1/2 3-4h), pyrazinamide (t1/2 9h). All hepatic metabolism. Rifampicin induces CYP enzymes.', pearls: ['INH: always co-prescribe pyridoxine 10-25mg/day', 'Rifampicin: orange discoloration of body fluids', 'Ethambutol: visual acuity monitoring mandatory'], warnings: ['Hepatotoxicity — monitor LFTs monthly', 'Peripheral neuropathy (INH) — prevent with pyridoxine', 'Optic neuritis (ethambutol) — dose-related'], overdose: 'INH: seizures, metabolic acidosis — pyridoxine 1:1 ratio antidote. Rifampicin: GI decontamination.' },
  'Antiprotozoal': { moa: 'Antiprotozoal: interferes with parasite metabolism, heme detoxification (chloroquine), or nucleic acid synthesis (metronidazole).', pk: 'Variable absorption. Chloroquine: long t1/2 (1-6 weeks). Metronidazole: t1/2 8h. Artemisinin derivatives: short t1/2 (1-3h).', pearls: ['ACT (artemether-lumefantrine): first-line for P. falciparum malaria', 'Chloroquine-resistant P. falciparum in East Africa', 'Primaquine: for P. vivax radical cure (test G6PD first)'], warnings: ['Cardiotoxicity with chloroquine (cumulative)', 'Neuropathy with metronidazole (prolonged use)', 'Hemolytic anemia in G6PD deficiency (primaquine)'], overdose: 'Chloroquine: cardiac arrest — diazepam, intubation. Metronidazole: seizures.' },
  'Anthelmintic': { moa: 'Anthelmintic: disrupts parasite metabolism (mebendazole: glucose uptake), neuromuscular function (ivermectin), or structural integrity (albendazole).', pk: 'PO: variable absorption. Albendazole: poor absorption, activated in gut. Mebendazole: poor systemic absorption. Ivermectin: well absorbed, lipophilic.', pearls: ['Albendazole: broadest spectrum, single dose for STH', 'Mebendazole: alternative for STH, longer course', 'Ivermectin: first-line for onchocerciasis, strongyloides'], warnings: ['Embryotoxic/teratogenic — avoid in pregnancy', 'Neurocysticercosis: steroids before albendazole', 'Ivermectin: Mazzotti reaction in onchocerciasis'], overdose: 'Symptoms: GI upset, hepatotoxicity. Management: supportive care.' },
  'Antileprotic': { moa: 'Antileprotic: inhibits mycobacterial cell wall synthesis (dapsone), RNA synthesis (rifampicin), or cell membrane function (clofazimine).', pk: 'Dapsone: PO, t1/2 28h. Rifampicin: t1/2 3h. Clofazimine: t1/2 70 days (long). All hepatic metabolism.', pearls: ['MDT (multi-drug therapy): WHO standard for leprosy', 'Paucibacillary: rifampicin + dapsone 6 months', 'Multibacillary: rifampicin + dapsone + clofazimine 12 months'], warnings: ['Dapsone hypersensitivity syndrome', 'Clofazimine: reddish-brown skin discoloration', 'Hemolytic anemia in G6PD deficiency (dapsone)'], overdose: 'Dapsone: methemoglobinemia — methylene blue. Clofazimine: GI decontamination.' },

  // Other CNS
  'Methylxanthine': { moa: 'Methylxanthine: non-selective phosphodiesterase inhibitor, increasing cAMP, causing bronchodilation and CNS stimulation.', pk: 'PO/IV. t1/2: caffeine 5h, theophylline 8h (smokers 5h). Metabolism: hepatic (CYP1A2). Narrow therapeutic index (10-20 mcg/mL).', pearls: ['Theophylline: therapeutic drug monitoring mandatory', 'Smoking induces CYP1A2 — dose adjustment needed', 'Caffeine: used for apnea of prematurity'], warnings: ['Seizures, arrhythmias at toxic levels', 'Drug interactions (ciprofloxacin, fluvoxamine inhibit metabolism)', 'Narrow therapeutic index'], overdose: 'Symptoms: seizures, cardiac arrhythmias, vomiting. Management: activated charcoal, beta-blockers, benzodiazepines.' },
  'Antiemetic': { moa: 'Antiemetic: blocks serotonin 5-HT3 receptors (ondansetron), dopamine D2 receptors (metoclopramide), NK1 receptors (aprepitant), or histamine H1 receptors (promethazine).', pk: 'Ondansetron: PO/IV, t1/2 4h. Metoclopramide: PO/IV, t1/2 5h. Aprepitant: PO, t1/2 9-13h.', pearls: ['Ondansetron: first-line for chemotherapy-induced nausea', 'Metoclopramide: prokinetic — gastroparesis too', 'Aprepitant: for highly emetogenic chemotherapy'], warnings: ['Metoclopramide: tardive dyskinesia', 'Ondansetron: QT prolongation', 'Promethazine: extrapyramidal symptoms'], overdose: 'Metoclopramide: extrapyramidal symptoms — benztropine. Ondansetron: supportive care.' },
  'PPI': { moa: 'PPI: irreversibly inhibits H+/K+-ATPase (proton pump) in gastric parietal cells, providing potent acid suppression.', pk: 'PO: enteric-coated, take 30-60min before meal. t1/2: 1-2h (but effect lasts 24-72h due to irreversible binding). Metabolism: CYP2C19/3A4.', pearls: ['Take 30-60min before breakfast', 'Omeprazole: most CYP2C19-dependent — varies by genotype', 'Pantoprazole: fewest drug interactions'], warnings: ['Long-term: hypomagnesemia, bone fractures, C. difficile', 'Clopidogrel interaction (omeprazole)', 'B12 deficiency with chronic use'], overdose: 'Symptoms: minimal toxicity. Management: supportive care.' },
  'H2 receptor antagonist': { moa: 'H2RA: competitively blocks histamine H2 receptors on gastric parietal cells, reducing basal and stimulated acid secretion.', pk: 'PO: well absorbed. t1/2: ranitidine 2.5h, famotidine 2.5-4h, cimetidine 2h. Metabolism: hepatic (cimetidine inhibits CYP). Excretion: renal.', pearls: ['Famotidine: most potent H2RA', 'Ranitidine: withdrawn (NDMA contamination)', 'Cimetidine: CYP inhibitor — many drug interactions'], warnings: ['Tolerance develops with continuous use', 'Cimetidine: antiandrogenic effects, gynecomastia', 'Less potent than PPIs'], overdose: 'Symptoms: minimal. Management: supportive care.' },
  'Laxative': { moa: 'Laxative: increases stool water content (osmotic: polyethylene glycol) or stimulates colonic motility (stimulant: senna, bisacodyl).', pk: 'PEG: poorly absorbed, osmotic effect in gut. Senna: converted to active metabolite by gut bacteria. Lactulose: metabolized by colonic bacteria.', pearls: ['PEG (Miralax): first-line for constipation', 'Senna: good for short-term use', 'Lactulose: for hepatic encephalopathy'], warnings: ['Electrolyte imbalances with chronic stimulant use', 'Dependency with chronic stimulant use', 'Bowel obstruction with bulk-forming agents'], overdose: 'Symptoms: diarrhea, dehydration. Management: fluid resuscitation.' },
  'Antidiarrheal': { moa: 'Antidiarrheal: slows intestinal motility (loperamide) or adsorbs toxins (attapulgite, bismuth subsalicylate).', pk: 'Loperamide: PO, t1/2 10h. Bismuth: minimal systemic absorption. Attapulgite: not absorbed.', pearls: ['Loperamide: first-line for acute diarrhea', 'Bismuth subsalicylate: traveler diarrhea', 'Do NOT use in infectious diarrhea (prolongs illness)'], warnings: ['Contraindicated in bacterial enteritis', 'Loperamide: ileus risk', 'Bismuth: salicylate toxicity in children'], overdose: 'Loperamide: respiratory depression — naloxone. Bismuth: supportive care.' },

  // Respiratory
  'Leukotriene receptor antagonist': { moa: 'LTRA: selectively blocks cysteinyl leukotriene receptor 1 (CysLT1), inhibiting leukotriene-mediated bronchoconstriction, inflammation, and mucus secretion.', pk: 'PO: well absorbed. t1/2: montelukast 5-6h. Metabolism: hepatic (CYP3A4/2C8). Excretion: fecal.', pearls: ['Montelukast: once-daily, add-on for asthma', 'Zafirlukast: twice daily, less used', 'Aspirin-sensitive asthma: particularly beneficial'], warnings: ['Neuropsychiatric events (FDA black box) — depression, suicidality', 'Churg-Strauss syndrome (rare)', 'Hepatotoxicity'], overdose: 'Symptoms: GI upset. Management: supportive care.' },
  'Mucolytic': { moa: 'Mucolytic: cleaves disulfide bonds in mucus glycoproteins, reducing mucus viscosity and improving clearance.', pk: 'PO: well absorbed. t1/2: 6-8h (N-acetylcysteine). Metabolism: hepatic. Excretion: renal.', pearls: ['NAC: also hepatoprotective in paracetamol overdose', 'Carbocisteine: reduces mucus viscosity in COPD', 'Ambroxol: mucolytic with surfactant-stimulating properties'], warnings: ['NAC: GI upset, anaphylactoid reactions (IV)', 'Carbocisteine: GI disturbances', 'Inhaled NAC: may cause bronchospasm'], overdose: 'Symptoms: GI upset. Management: supportive care.' },

  // Oncology
  'Alkylating agent': { moa: 'Alkylating agent: adds alkyl groups to DNA, cross-linking strands and preventing DNA replication and transcription.', pk: 'Variable. IV: cyclophosphamide oral/IV. Metabolism: hepatic activation (cyclophosphamide to phosphoramide mustard). Excretion: renal.', pearls: ['Cyclophosphamide: prodrug, requires hepatic activation', 'Mesna: prophylaxis for hemorrhagic cystitis', 'Carmustine: crosses BBB — brain tumors'], warnings: ['Myelosuppression — nadir 7-14 days', 'Hemorrhagic cystitis (cyclophosphamide) — MESNA prophylaxis', 'Teratogenicity — fertility preservation counseling'], overdose: 'Symptoms: severe myelosuppression. Management: G-CSF, transfusions, antibiotics.' },
  'Antimetabolite': { moa: 'Antimetabolite: structurally similar to natural metabolites, competing for enzyme active sites and disrupting nucleic acid synthesis.', pk: 'Variable. Methotrexate: PO/IV/IM. 5-FU: IV. Metabolism: hepatic. Excretion: renal (methotrexate: renal tubular secretion).', pearls: ['Methotrexate: low-dose for RA (7.5-25mg/week)', '5-FU: GI and hematologic toxicity', 'Leucovorin rescue for methotrexate toxicity'], warnings: ['Myelosuppression — monitor CBC', 'Hepatotoxicity with methotrexate', 'Mucositis — common with 5-FU and methotrexate'], overdose: 'Methotrexate: leucovorin rescue (within 24-42h), hydration, urinary alkalinization.' },
  'Anthracycline': { moa: 'Anthracycline: intercalates into DNA, inhibits topoisomerase II, and generates free radicals, causing DNA damage and cell death.', pk: 'IV: doxorubicin t1/2 20-48h, daunorubicin 18-30h. Liposomal formulations alter pharmacokinetics. Metabolism: hepatic. Excretion: biliary.', pearls: ['Doxorubicin: cumulative dose limit (550 mg/m2)', 'Liposomal doxorubicin: less cardiotoxic', 'Epirubicin: lower cardiotoxicity than doxorubicin'], warnings: ['Cardiomyopathy — cumulative, monitor ejection fraction', 'Myelosuppression — nadir 10-14 days', 'Extravasation — severe tissue necrosis'], overdose: 'Symptoms: severe myelosuppression, cardiomyopathy. Management: G-CSF, dexrazoxane for cardioprotection.' },
  'Antimitotic (taxane/vinca)': { moa: 'Taxanes stabilize microtubules (prevent depolymerization). Vinca alkaloids destabilize microtubules (prevent polymerization). Both arrest cells in mitosis.', pk: 'IV: paclitaxel t1/2 3-9h, docetaxel 11h. Metabolism: CYP3A4 (paclitaxel). Excretion: fecal.', pearls: ['Paclitaxel: requires premedication (hypersensitivity)', 'Docetaxel: less hypersensitivity', 'Vincristine: neurotoxicity (peripheral neuropathy)'], warnings: ['Myelosuppression (neutropenia)', 'Peripheral neuropathy — cumulative', 'Hypersensitivity reactions (paclitaxel)'], overdose: 'Symptoms: severe myelosuppression, neuropathy. Management: supportive care.' },
  'Tyrosine kinase inhibitor': { moa: 'TKI: inhibits specific tyrosine kinases (BCR-ABL, EGFR, VEGFR, etc.), blocking signaling pathways essential for cancer cell proliferation and survival.', pk: 'PO: variable absorption. Metabolism: CYP3A4 (imatinib). t1/2: imatinib 18-40h, erlotinib 36h, gefitinib 48h.', pearls: ['Imatinib: first-line for CML (BCR-ABL)', 'Erlotinib: EGFR-mutant NSCLC', 'Sunitinib: multi-targeted TKI for RCC'], warnings: ['Hepatotoxicity — monitor LFTs', 'Cardiac toxicity (some TKIs)', 'Skin rash (EGFR inhibitors)'], overdose: 'Symptoms: GI upset, myelosuppression. Management: supportive care.' },
  'Immunosuppressant': { moa: 'Immunosuppressant: inhibits calcineurin (cyclosporine, tacrolimus), purine synthesis (azathioprine, mycophenolate), or mTOR (sirolimus), suppressing T-cell activation.', pk: 'Variable absorption. Cyclosporine: t1/2 8-12h. Tacrolimus: t1/2 12h. Mycophenolate: t1/2 16h. Metabolism: CYP3A4. Excretion: biliary and renal.', pearls: ['Tacrolimus: more potent than cyclosporine', 'Mycophenolate: less nephrotoxic than calcineurin inhibitors', 'Sirolimus: inhibits mTOR — wound healing concern'], warnings: ['Nephrotoxicity — monitor drug levels', 'Infection risk — opportunistic infections', 'Malignancy risk (lymphoma, skin cancer)'], overdose: 'Symptoms: infection, organ toxicity. Management: reduce dose, supportive care.' },
  'mTOR inhibitor': { moa: 'mTOR inhibitor: inhibits mechanistic target of rapamycin, blocking cell cycle progression from G1 to S phase and suppressing immune activation.', pk: 'PO: variable absorption. t1/2: 62h (sirolimus). Metabolism: CYP3A4. Excretion: fecal and renal.', pearls: ['Sirolimus: renal transplant immunosuppression', 'Everolimus: RCC, breast cancer', 'Monitor drug levels — therapeutic drug monitoring'], warnings: ['Hyperlipidemia', 'Impaired wound healing', 'Proteinuria'], overdose: 'Symptoms: immunosuppression. Management: supportive care.' },
  'Proteasome inhibitor': { moa: 'Proteasome inhibitor: blocks the 26S proteasome, preventing degradation of misfolded proteins, causing ER stress and apoptosis in myeloma cells.', pk: 'IV: bortezomib t1/2 9-15h. Carfilzomib: irreversible binding. Ixazomib: PO, t1/2 58h. Metabolism: hepatic.', pearls: ['Bortezomib: first-line for multiple myeloma', 'Carfilzomib: less peripheral neuropathy', 'Ixazomib: first oral proteasome inhibitor'], warnings: ['Peripheral neuropathy — dose-limiting for bortezomib', 'Cardiotoxicity (carfilzomib)', 'Hepatitis B reactivation'], overdose: 'Symptoms: cytopenias, neuropathy. Management: supportive care.' },
  'PARP inhibitor': { moa: 'PARP inhibitor: inhibits poly(ADP-ribose) polymerase, preventing DNA single-strand break repair. Synthetic lethality in BRCA-mutated tumors.', pk: 'PO: olaparib t1/2 14.9h, niraparib 36h, rucaparib 26h. Metabolism: CYP3A4 (olaparib). Excretion: fecal.', pearls: ['Olaparib: BRCA-mutant ovarian/breast cancer', 'Niraparib: maintenance for platinum-sensitive ovarian cancer', 'Germline BRCA testing required'], warnings: ['Myelosuppression — monitor CBC', 'MDS/AML risk', 'Pneumonitis (rare)'], overdose: 'Symptoms: cytopenias. Management: supportive care, growth factors.' },
  'Checkpoint inhibitor/Anti-VEGF combination': { moa: 'Combination: checkpoint inhibitor (anti-PD-1/PD-L1) releases T-cell brakes; anti-VEGF blocks tumor angiogenesis. Dual mechanism enhances anti-tumor immunity.', pk: 'IV: atezolizumab t1/2 27 days, bevacizumab t1/2 20 days. Long half-lives allow q2-4w dosing. Metabolism: proteolytic degradation.', pearls: ['Atezolizumab + bevacizumab: HCC first-line', 'Durvalumab + tremelimumab: HCC (HIMALAYA)', 'Pembrolizumab + lenvatinib: endometrial cancer'], warnings: ['Immune-related adverse events (irAEs) — any organ', 'Hepatotoxicity — monitor LFTs', 'Bleeding risk (bevacizumab)'], overdose: 'Symptoms: irAEs. Management: high-dose corticosteroids, infliximab for severe irAEs.' },

  // Immunology
  'Anti-IgE mAb': { moa: 'Anti-IgE mAb (omalizumab): binds free IgE at Cε3 domain, preventing binding to FcεRI receptors on mast cells and basophils, reducing allergic mediator release.', pk: 'SC: bioavailability 60-70%. t1/2: 26 days. Metabolism: proteolytic. Excretion: reticuloendothelial.', pearls: ['Omalizumab: severe allergic asthma, chronic urticaria', 'Dose based on IgE level and weight', 'Inject at clinic — anaphylaxis risk'], warnings: ['Anaphylaxis (rare, 0.1-0.2%)', 'Cardiovascular events (post-marketing)', 'Parasitic infections in endemic areas'], overdose: 'Symptoms: anaphylaxis risk. Management: epinephrine, supportive care.' },
  'Anti-IL5 mAb': { moa: 'Anti-IL-5 mAb (mepolizumab): binds IL-5, preventing it from binding to IL-5Rα on eosinophils, reducing eosinophilic inflammation.', pk: 'SC: t1/2: mepolizumab 20-26 days. Benralizumab binds IL-5Rα (direct depletion). Metabolism: proteolytic.', pearls: ['Mepolizumab: severe eosinophilic asthma', 'Benralizumab: direct IL-5R binding, ADCC-mediated depletion', 'Reslizumab: IV formulation'], warnings: ['Herpes zoster — consider vaccination', 'Hypersensitivity reactions', 'Parasitic infections'], overdose: 'Symptoms: not well characterized. Management: supportive care.' },
  'Anti-IL5R mAb': { moa: 'Anti-IL-5R mAb (benralizumab): binds IL-5Rα on eosinophils and basophils, recruiting NK cells for ADCC-mediated direct cellular apoptosis.', pk: 'SC: t1/2: 14-18 days. Metabolism: proteolytic. Excretion: not applicable (protein).', pearls: ['Benralizumab: severe eosinophilic asthma', 'Every 8 weeks after initial monthly dosing', 'Rapid eosinophil depletion (within 24h)'], warnings: ['Herpes zoster', 'Hypersensitivity reactions', 'Eosinophil monitoring'], overdose: 'Symptoms: not characterized. Management: supportive care.' },
  'Anti-IL-12/23 (mAb)': { moa: 'Anti-IL-12/23 (ustekinumab): binds p40 subunit shared by IL-12 and IL-23, inhibiting Th1 and Th17 differentiation and downstream inflammatory cascades.', pk: 'SC/IV: t1/2: 3 weeks. Metabolism: proteolytic. Excretion: reticuloendothelial.', pearls: ['Ustekinumab: plaque psoriasis, Crohn disease, UC', 'Weight-based dosing (>100kg: higher dose)', 'Every 8-12 weeks after induction'], warnings: ['Infections — screen for TB', 'Malignancy risk (theoretical)', 'Hypersensitivity reactions'], overdose: 'Symptoms: not characterized. Management: supportive care.' },
  'Anti-IL17A (mAb)': { moa: 'Anti-IL-17A (secukinumab, ixekizumab): binds IL-17A, blocking its interaction with IL-17RA, reducing Th17-mediated inflammation in skin and joints.', pk: 'SC: secukinumab t1/2 27 days, ixekizumab 13 days. Metabolism: proteolytic.', pearls: ['Secukinumab: psoriasis, psoriatic arthritis, ankylosing spondylitis', 'Ixekizumab: similar indications, more potent', 'Loading dose then maintenance monthly'], warnings: ['Infections — screen for TB and HBV', 'Inflammatory bowel disease onset (rare)', 'Hypersensitivity reactions'], overdose: 'Symptoms: not characterized. Management: supportive care.' },
  'TNF-alpha inhibitor (mAb)': { moa: 'TNF-alpha inhibitor (adalimumab, golimumab): monoclonal antibody that binds TNF-alpha, neutralizing its pro-inflammatory effects.', pk: 'SC/IV: t1/2: adalimumab 14 days, infliximab 8-10 days. Metabolism: proteolytic. Excretion: reticuloendothelial.', pearls: ['Adalimumab: RA, IBD, psoriasis, AS', 'Golimumab: RA, AS, UC', 'Combination with methotrexate improves efficacy'], warnings: ['Serious infections — TB screening mandatory', 'HBV reactivation', 'Demyelinating disease'], overdose: 'Symptoms: immunosuppression. Management: supportive care.' },
  'TNF-alpha inhibitor (chimeric mAb)': { moa: 'TNF-alpha inhibitor (infliximab): chimeric monoclonal antibody that binds TNF-alpha with high affinity, neutralizing soluble and transmembrane forms.', pk: 'IV: t1/2 8-10 days. Metabolism: proteolytic. Excretion: reticuloendothelial.', pearls: ['Infliximab: IBD (Crohn, UC), RA, ankylosing spondylitis', 'Always co-administer with methotrexate', 'Serial monitoring for loss of response'], warnings: ['Infusion reactions — premedicate', 'Serious infections — TB/HBV screening', 'Rare: demyelination, lymphoma'], overdose: 'Symptoms: immunosuppression. Management: supportive care.' },
  'TNF-alpha inhibitor (fusion protein)': { moa: 'TNF-alpha inhibitor (etanercept): fusion protein (TNFR2-Fc) that binds soluble TNF-alpha and lymphotoxin-alpha, neutralizing their inflammatory effects.', pk: 'SC: t1/2 4 days. Metabolism: proteolytic. Excretion: not applicable.', pearls: ['Etanercept: RA, psoriasis, AS', 'Less effective in IBD (does not bind transmembrane TNF)', 'Weekly SC dosing'], warnings: ['Infections — TB screening', 'HBV reactivation', 'Injection site reactions'], overdose: 'Symptoms: immunosuppression. Management: supportive care.' },
  'Anti-IL6 receptor (mAb)': { moa: 'Anti-IL-6R (tocilizumab, sarilumab): binds IL-6 receptor, blocking IL-6-mediated inflammation and acute phase response.', pk: 'SC/IV: tocilizumab t1/2 11-13 days, sarilumab 10 days. Metabolism: proteolytic.', pearls: ['Tocilizumab: RA, giant cell arteritis, cytokine release syndrome', 'Sarilumab: RA, alternative to tocilizumab', 'Monitor LFTs — hepatotoxicity'], warnings: ['Hepatotoxicity — LFT monitoring', 'GI perforation risk', 'Neutropenia'], overdose: 'Symptoms: immunosuppression. Management: supportive care.' },
  'Anti-CD20 (chimeric mAb)': { moa: 'Anti-CD20 (rituximab): chimeric monoclonal antibody targeting CD20 on B-lymphocytes, depleting B-cells through ADCC, CDC, and apoptosis.', pk: 'IV: t1/2 200+ hours after first dose (longer with repeated dosing). Metabolism: proteolytic.', pearls: ['Rituximab: lymphoma, RA, ANCA vasculitis', 'Pre-medicate with methylprednisolone', 'HBV reactivation screening mandatory'], warnings: ['Infusion reactions — often first infusion', 'Tumor lysis syndrome (high tumor burden)', 'Progressive multifocal leukoencephalopathy (rare)'], overdose: 'Symptoms: severe immunosuppression. Management: supportive care.' },
  'Anti-HER2 (mAb)': { moa: 'Anti-HER2 (trastuzumab): humanized monoclonal antibody binding HER2 receptor, blocking signaling and inducing ADCC in HER2-overexpressing breast cancer.', pk: 'IV: t1/2 33 days (steady state). SC: equivalent exposure. Metabolism: proteolytic.', pearls: ['Trastuzumab: HER2+ breast cancer, gastric cancer', 'Cardiac monitoring — ejection fraction q3 months', 'Pertuzumab: dual HER2 blockade with trastuzumab'], warnings: ['Cardiomyopathy — baseline and q3 month echo', 'Infusion reactions — first dose', 'Pulmonary toxicity (rare)'], overdose: 'Symptoms: cardiac toxicity. Management: supportive care, discontinue if LVEF drops.' },
  'Anti-VEGF (mAb)': { moa: 'Anti-VEGF (bevacizumab): monoclonal antibody binding VEGF-A, preventing receptor activation, inhibiting tumor angiogenesis and vascular permeability.', pk: 'IV: t1/2 20 days. Metabolism: proteolytic. Excretion: not applicable.', pearls: ['Bevacizumab: colorectal, lung, RCC, ovarian cancer', 'No increase in bleeding with low-dose aspirin', 'Hypertension is common and dose-related'], warnings: ['Hypertension — monitor BP', 'GI perforation — discontinue', 'Hemorrhage — especially squamous NSCLC'], overdose: 'Symptoms: not well characterized. Management: supportive care.' },
  'Immunomodulator (IMiD)': { moa: 'IMiD (thalidomide, lenalidomide, pomalidomide): immunomodulatory mechanism — degrades Ikaros/Aiolos transcription factors, enhances T-cell and NK-cell activity, inhibits angiogenesis.', pk: 'PO: well absorbed. t1/2: thalidomide 5-7h, lenalidomide 3h, pomalidomide 6.5h. Metabolism: hydrolysis (not CYP). Excretion: renal.', pearls: ['Lenalidomide: first-line for MM with dexamethasone', 'Thalidomide: erythema nodosum leprosum', 'Pom pom: for relapsed/refractory MM'], warnings: ['Teratogenicity — REMS program mandatory', 'Peripheral neuropathy (thalidomide > lenalidomide)', 'VTE prophylaxis required'], overdose: 'Symptoms: sedation, peripheral neuropathy. Management: supportive care.' },
  'Immunomodulator': { moa: 'Immunomodulator: modulates immune system activity through various mechanisms, including cytokine modulation, immune cell regulation, or interferon activity.', pk: 'Variable. Interferons: SC/IM, t1/2 4-16h. Azathioprine: PO, t1/2 1-2h. Metabolism: hepatic. Excretion: renal.', pearls: ['Interferon-alpha: hepatitis B/C, malignancies', 'Azathioprine: IBD, RA, transplant maintenance', 'Check TPMT genotype before azathioprine'], warnings: ['Flu-like symptoms (interferons)', 'Myelosuppression (azathioprine)', 'Depression (interferons)'], overdose: 'Symptoms: cytopenias. Management: supportive care, growth factors.' },

  // Pain
  'COX-2 inhibitor': { moa: 'COX-2 inhibitor: selectively inhibits cyclooxygenase-2, reducing prostaglandin synthesis at sites of inflammation with less GI mucosal damage than non-selective NSAIDs.', pk: 'PO: well absorbed. t1/2: celecoxib 11h, etoricoxib 22h. Metabolism: CYP2C9. Excretion: fecal.', pearls: ['Celecoxib: cardiovascular safety (PRECISION trial)', 'Etoricoxib: not available in US', 'Lower GI risk than traditional NSAIDs'], warnings: ['Cardiovascular thrombotic events (dose-dependent)', 'GI bleeding (less than non-selective NSAIDs)', 'Renal impairment'], overdose: 'Symptoms: GI upset, renal toxicity. Management: supportive care.' },
  'Anticonvulsant (Barbiturate)': { moa: 'Barbiturate: enhances GABA-A receptor activity, increasing chloride conductance and neuronal depression. Also directly activates GABA-A at high doses.', pk: 'PO/IV. Phenobarbital: t1/2 50-120h (long). Metabolism: hepatic (CYP2C9). Excretion: renal.', pearls: ['Phenobarbital: neonatal seizures, status epilepticus (second-line)', 'Long t1/2 — accumulation risk', 'IV: respiratory depression — titrate slowly'], warnings: ['Respiratory depression — major risk', 'Physical dependence', 'Hepatotoxicity'], overdose: 'Symptoms: profound sedation, respiratory depression. Management: intubation, flumazenil (partial), hemodialysis.' },

  // Bone/joint
  'Bisphosphonate': { moa: 'Bisphosphonate: binds to hydroxyapatite in bone, inhibiting osteoclast-mediated bone resorption. Nitrogen-containing bisphosphonates also inhibit the mevalonate pathway.', pk: 'PO: poor absorption (1%). IV: 100% bioavailability. t1/2: years (bone-binding). Metabolism: none. Excretion: renal.', pearls: ['Alendronate: weekly dosing for osteoporosis', 'Zoledronic acid: annual IV for osteoporosis', 'Take alendronate with water, upright 30min'], warnings: ['Osteonecrosis of jaw — risk with dental procedures', 'Atypical femoral fractures with long-term use', 'Esophageal ulceration — take upright'], overdose: 'Symptoms: hypocalcemia, hypophosphatemia. Management: calcium and vitamin D supplementation.' },

  // Dermatology
  'Antipsoriatic': { moa: 'Antipsoriatic: inhibits keratinocyte hyperproliferation (methotrexate), modulates immune response (biologics), or normalizes differentiation (vitamin D analogues).', pk: 'Variable. Methotrexate: PO/SC, t1/2 8-10h. Biologics: SC, long half-lives. Calcipotriene: topical.', pearls: ['Methotrexate: low-dose for moderate-severe psoriasis', 'Adalimumab/ustekinumab: biologics for severe psoriasis', 'Calcipotriene: topical first-line'], warnings: ['Immunosuppression with systemic agents', 'Hepatotoxicity (methotrexate)', 'Infections with biologics'], overdose: 'Methotrexate: leucovorin rescue. Others: supportive care.' },
  'Retinoid': { moa: 'Retinoid: binds to retinoic acid receptors (RARs/RXRs), regulating gene transcription for cell differentiation, proliferation, and apoptosis.', pk: 'PO: isotretinoin t1/2 21h. Tretinoin: topical. Metabolism: hepatic (CYP26). Excretion: biliary and renal.', pearls: ['Isotretinoin: severe cystic acne, REMS program', 'Tretinoin: topical for acne, photoaging', 'Acitretin: for psoriasis'], warnings: ['Teratogenicity — two forms of contraception mandatory', 'Hepatotoxicity — monitor LFTs', 'Dry skin, mucositis, depression (debated)'], overdose: 'Vitamin A toxicity. Management: stop drug, supportive care.' },

  // Urology
  'PDE-5 inhibitor': { moa: 'PDE-5 inhibitor: inhibits phosphodiesterase type 5, increasing cGMP in smooth muscle, causing vasodilation in corpus cavernosum (ED) and pulmonary vasculature (PAH).', pk: 'PO: tadalafil t1/2 17.5h, sildenafil 4h. Vardenafil: 4-5h. Avanafil: 5h. Metabolism: CYP3A4. Excretion: fecal.', pearls: ['Tadalafil: once-daily for BPH/ED, longer half-life', 'Sildenafil: most studied for PAH', 'Do not combine with nitrates'], warnings: ['Severe hypotension with nitrates (contraindicated)', 'Priapism (rare)', 'Vision changes (NAION — rare)'], overdose: 'Symptoms: hypotension, priapism. Management: IV fluids, decongestants.' },
  'Beta-3 agonist': { moa: 'Beta-3 agonist: stimulates beta-3 adrenergic receptors in detrusor muscle, promoting bladder relaxation and increasing capacity during filling.', pk: 'PO: mirabegron t1/2 50h, solifenacin (antimuscarinic). Metabolism: CYP3A4 and CYP2D6. Excretion: renal.', pearls: ['Mirabegron: overactive bladder, alternative to antimuscarinics', 'Solifenacin: most effective antimuscarinic', 'Combination: mirabegron + solifenacin for refractory OAB'], warnings: ['Hypertension — monitor BP', 'Urinary retention', 'Anticholinergic effects (solifenacin)'], overdose: 'Symptoms: tachycardia, hypertension. Management: supportive care.' },
  'Antimuscarinic (Urology)': { moa: 'Antimuscarinic: blocks muscarinic receptors (M3) in detrusor muscle, reducing involuntary contractions and increasing bladder capacity.', pk: 'PO: oxybutynin t1/2 2h, tolterodine 2-3h. Extended-release: less peaks/troughs. Metabolism: CYP3A4. Excretion: renal.', pearls: ['Oxybutynin patch: less cognitive side effects', 'Solifenacin: once-daily, fewer side effects', 'Darifenacin: M3 selective — less cognitive effects'], warnings: ['Dry mouth (most common)', 'Constipation, urinary retention', 'Cognitive effects in elderly — avoid in dementia'], overdose: 'Symptoms: anticholinergic toxicity — hallucinations, tachycardia. Management: physostigmine (severe cases).' },
  '5-alpha reductase inhibitor': { moa: '5-alpha reductase inhibitor: inhibits conversion of testosterone to dihydrotestosterone (DHT), reducing prostate volume and hair follicle miniaturization.', pk: 'PO: finasteride t1/2 5-6h, dutasteride t1/2 5 weeks. Metabolism: CYP3A4. Excretion: fecal.', pearls: ['Finasteride 5mg: BPH, 1mg: male pattern baldness', 'Dutasteride: more potent, longer half-life', 'Takes 3-6 months for hair effects'], warnings: ['Sexual dysfunction (decreased libido, ED)', 'Teratogenicity — women of childbearing age', 'Depression (rare)'], overdose: 'Symptoms: not well characterized. Management: supportive care.' },

  // Addiction
  'Smoking cessation aid': { moa: 'Smoking cessation: nicotine replacement (receptor agonist), varenicline (partial agonist), or bupropion (norepinephrine-dopamine reuptake inhibitor) reduce withdrawal and cravings.', pk: 'NRT: various routes (patch, gum, inhaler). Varenicline: PO, t1/2 24h. Bupropion: PO, t1/2 21h (extended-release).', pearls: ['Varenicline: most effective (1:1 to quit)', 'NRT combination (patch + short-acting) is effective', 'Bupropion: also for depression and weight gain'], warnings: ['Neuropsychiatric effects (varenicline, bupropion)', 'Cardiovascular events (NRT — caution)', 'Seizures (bupropion — dose-dependent)'], overdose: 'Nicotine: nausea, vomiting, seizures. Management: activated charcoal, atropine.' },
  'Succinylcholine-like': { moa: 'Depolarizing neuromuscular blocker: mimics acetylcholine at NMJ, causing persistent depolarization and flaccid paralysis.', pk: 'IV: onset 30-60s, duration 5-10min. Rapidly hydrolyzed by plasma cholinesterase. Metabolism: plasma cholinesterase. Excretion: renal (metabolites).', pearls: ['Succinylcholine: RSI drug of choice', 'Fasciculations: pretreat with non-depolarizing agent', 'Contraindicated in hyperkalemia, burns, crush injury'], warnings: ['Hyperkalemia — contraindicated in at-risk patients', 'Malignant hyperthermia (genetic)', 'Masseter spasm (early sign of MH)'], overdose: 'Malignant hyperthermia: dantrolene, cooling, supportive care.' },
  'Non-depolarizing NMB': { moa: 'Non-depolarizing NMB: competitive antagonist at NMJ nicotinic receptors, preventing acetylcholine binding and causing flaccid paralysis.', pk: 'IV: rocuronium t1/2 1.5h, vecuronium 1h, cisatracurium 23min. Metabolism: hepatic (rocuronium), Hofmann elimination (cisatracurium). Excretion: biliary and renal.', pearls: ['Rocuronium: RSI with sugammadex reversal', 'Cisatracurium: organ-independent elimination (critically ill)', 'Vecuronium: intermediate duration'], warnings: ['Prolonged paralysis with renal/hepatic impairment', 'Residual paralysis — train-of-four monitoring', 'Histamine release (atracurium, vecuronium)'], overdose: 'Symptoms: prolonged paralysis. Management: neostigmine (with glycopyrrolate), sugammadex for rocuronium.' },
  'Local anaesthetic': { moa: 'Local anaesthetic: blocks voltage-gated sodium channels in nerve fibers, preventing depolarization and blocking pain signal conduction.', pk: 'Onset and duration depend on agent and concentration. Lidocaine: rapid onset (2-5min), short duration. Bupivacaine: slower onset, long duration. Metabolism: hepatic (amide LAs).', pearls: ['Lidocaine: most commonly used, rapid onset', 'Bupivacaine: long-acting, but cardiotoxic if IV', 'Ropivacaine: less cardiotoxic than bupivacaine'], warnings: ['LAST (local anaesthetic systemic toxicity) — seizures, cardiac arrest', 'Bupivacaine: most cardiotoxic', 'Epinephrine reduces absorption and prolongs effect'], overdose: 'LAST: 20% IV lipid emulsion (Intralipid), airway management, seizures — benzodiazepines.' },
  'IV anaesthetic': { moa: 'IV anaesthetic: enhances GABA-A receptor activity (propofol, thiopental) or blocks NMDA receptors (ketamine), producing loss of consciousness.', pk: 'IV: rapid onset (arm-brain circulation 30s). Propofol: t1/2 2-4min (context-sensitive). Thiopental: t1/2 12h. Ketamine: t1/2 10-15min. Metabolism: hepatic (propofol conjugation).', pearls: ['Propofol: most common, rapid onset/recovery', 'Ketamine: dissociative, analgesic, bronchodilator', 'Thiopental: barbiturate, rarely used now'], warnings: ['Propofol: hypotension, injection pain', 'Ketamine: emergence reactions, increased ICP', 'Thiopental: severe myocardial depression'], overdose: 'Symptoms: respiratory depression, hypotension. Management: airway management, vasopressors.' },

  // Hematology
  'Hematopoietic growth factor': { moa: 'Hematopoietic growth factor: stimulates production and maturation of blood cells through specific receptor activation on hematopoietic progenitors.', pk: 'SC/IV: filgrastim t1/2 3.5h, pegfilgrastim 15-80h. EPO: t1/2 4-13h. Metabolism: proteolytic. Excretion: not applicable.', pearls: ['Filgrastim: G-CSF for neutropenia', 'Pegfilgrastim: once per chemotherapy cycle', 'EPO: CKD anemia, cancer-related anemia'], warnings: ['Bone pain (common)', 'Splenic rupture (rare)', 'Myelodysplastic syndrome (EPO — risk debated)'], overdose: 'Symptoms: bone pain, leukocytosis. Management: supportive care.' },

  // Toxicology
  'Antidote': { moa: 'Antidote: specific receptor antagonists or chelators that neutralize toxin effects (naloxone for opioids, flumazenil for benzos, NAC for paracetamol, deferoxamine for iron).', pk: 'Varies by antidote. Naloxone: IV, t1/2 30-90min (shorter than opioids). NAC: IV/PO. Flumazenil: IV, t1/2 40-80min.', pearls: ['Naloxone: titrate to respiratory effort, not consciousness', 'NAC: best within 8h of paracetamol ingestion', 'Flumazenil: avoid in chronic benzo users (seizure risk)'], warnings: ['Naloxone: renarcotization risk — short duration', 'Flumazenil: seizure risk in chronic benzo use', 'NAC: anaphylactoid reactions (IV)'], overdose: 'Antidote overdose: supportive care. Specific: naloxone renarcotization → re-dose.' },

  // Cardiovascular specialty
  'Sinus node inhibitor': { moa: 'Sinus node inhibitor (ivabradine): selectively inhibits If channels in the SA node, reducing heart rate without affecting contractility or blood pressure.', pk: 'PO: bioavailability 40%. t1/2: 2h. Metabolism: CYP3A4. Excretion: fecal and renal.', pearls: ['Ivabradine: heart failure (HR >70 despite max beta-blocker)', 'Angina pectoris (when beta-blockers contraindicated)', 'Target resting HR 60-70 bpm'], warnings: ['Phosphenes (visual disturbances) — light-induced', 'Bradycardia — hold if HR <60', 'Do not combine with strong CYP3A4 inhibitors'], overdose: 'Symptoms: severe bradycardia. Management: atropine, temporary pacing.' },
  'Mineralocorticoid antagonist': { moa: 'Mineralocorticoid antagonist: competitively blocks aldosterone receptors in the collecting duct, promoting sodium excretion and potassium retention.', pk: 'PO: eplerenone t1/2 4-6h, spironolactone t1/2 1.3h (active metabolites longer). Metabolism: CYP3A4 (eplerenone). Excretion: renal.', pearls: ['Spironolactone: RALES trial — HF mortality benefit', 'Eplerenone: EPHESUS — post-MI HF', 'Monitor K+ closely with ACEi/ARB'], warnings: ['Hyperkalemia — monitor K+ and renal function', 'Gynecomastia (spironolactone)', 'Avoid in severe renal impairment'], overdose: 'Symptoms: hyperkalemia. Management: calcium gluconate, insulin/glucose.' },
  'Anti-anginal': { moa: 'Anti-anginal: reduces myocardial oxygen demand through heart rate reduction (beta-blockers, CCBs), preload reduction (nitrates), or afterload reduction (vasodilators).', pk: 'Varies by class. Generally well absorbed orally. Most have hepatic metabolism.', pearls: ['First-line: beta-blocker or CCB', 'Nitrates for acute relief and prophylaxis', 'Ranolazine: add-on for refractory angina'], warnings: ['Hypotension — especially with combination therapy', 'Reflex tachycardia with nitrates (add beta-blocker)', 'CYP interactions with ranolazine'], overdose: 'Symptoms: hypotension, bradycardia. Management: IV fluids, atropine.' },
  'Central alpha agonist': { moa: 'Central alpha agonist (clonidine, methyldopa): stimulates central alpha-2 adrenergic receptors, reducing sympathetic outflow and lowering blood pressure.', pk: 'Clonidine: PO, t1/2 12-16h. Methyldopa: PO, t1/2 2h. Metabolism: hepatic. Excretion: renal.', pearls: ['Clonidine: hypertensive urgency, ADHD, withdrawal', 'Methyldopa: first-line in pregnancy HTN', 'Transdermal clonidine: 7-day patch'], warnings: ['Rebound hypertension on abrupt withdrawal', 'Sedation and dry mouth', 'Methyldopa: hemolytic anemia, hepatotoxicity'], overdose: 'Symptoms: hypotension, bradycardia, sedation. Management: IV fluids, atropine.' },
  'ACEi/ARB/ARNI': { moa: 'Renin-angiotensin system blockade: ACEi inhibits ACE (reducing Ang II), ARB blocks AT1 receptors, ARNI combines neprilysin inhibition with ARB.', pk: 'Variable. Generally well absorbed orally. Most have hepatic/renal elimination.', pearls: ['ACEi: first-line for HTN, HF, DM nephropathy', 'ARB: if ACEi cough occurs', 'ARNI: superior to ACEi in HFrEF (PARADIGM-HF)'], warnings: ['Hyperkalemia', 'Renal impairment', 'Angioedema (ACEi)'], overdose: 'Symptoms: hypotension. Management: IV fluids, vasopressors.' },

  // Ophthalmology
  'Antiglaucoma': { moa: 'Antiglaucoma: reduces intraocular pressure through various mechanisms — beta-blocker (timolol), alpha agonist (brimonidine), CAI (dorzolamide), or prostaglandin analogue (latanoprost).', pk: 'Topical ophthalmic: minimal systemic absorption. Latanoprost: t1/2 17min (topical). Metabolism: ocular. Excretion: systemic (minimal).', pearls: ['Latanoprost: first-line, once-daily, most effective', 'Timolol: avoid in asthma, heart block', 'Brimonidine: add-on, avoid in children (<2y contraindicated)'], warnings: ['Timolol: systemic beta-blockade — bradycardia, bronchospasm', 'Latanoprost: iris pigmentation (irreversible)', 'Brimonidine: allergic conjunctivitis'], overdose: 'Symptoms: systemic beta-blockade (timolol). Management: atropine for bradycardia.' },

  // Allergy
  'Antihistamine': { moa: 'Antihistamine: blocks histamine H1 receptors, preventing histamine-mediated allergic symptoms (rhinitis, urticaria, pruritus).', pk: '1st gen: sedating, t1/2 4-6h. 2nd gen: non-sedating, t1/2 12-24h. Metabolism: hepatic (CYP for some). Excretion: renal.', pearls: ['Cetirizine/loratadine: non-sedating, once-daily', 'Diphenhydramine: sedating, also for motion sickness', 'Fexofenadine: least sedating'], warnings: ['Sedation (1st gen) — avoid driving', 'Anticholinergic effects (1st gen)', 'QT prolongation (terfenadine — withdrawn)'], overdose: 'Symptoms: sedation, anticholinergic effects. Management: activated charcoal, benzodiazepines for seizures.' },
  'Hematologic agent': { moa: 'Hematologic agent: enhances coagulation (tranexamic acid: antifibrinolytic), promotes clot formation, or addresses specific hematologic conditions.', pk: 'PO/IV. Tranexamic acid: t1/2 2h. Excretion: renal.', pearls: ['Tranexamic acid: CRASH-2 trial — trauma mortality benefit', 'Also for menorrhagia, dental bleeding', 'Aminocaproic acid: alternative to TXA'], warnings: ['Thrombosis risk — avoid in active thromboembolic disease', 'Seizures (high doses TXA)', 'Visual disturbances (TXA)'], overdose: 'Symptoms: thrombosis. Management: anticoagulation if needed.' },

  // Misc
  'Diagnostic agent': { moa: 'Diagnostic agent: provides imaging contrast or diagnostic utility through optical or radiographic properties.', pk: 'Varies by agent. Fluorescein: IV, rapidly distributes. Excretion: renal.', pearls: ['Fluorescein: retinal angiography, corneal abrasion detection', 'Indocyanine green: choroidal angiography', 'Rapid elimination — transient discoloration'], warnings: ['Allergic reactions (fluorescein: 1-5%)', 'Nausea, vomiting', 'Yellow-green discoloration of urine/skin'], overdose: 'Symptoms: nausea, vomiting. Management: supportive care.' },
  'Antiseptic': { moa: 'Antiseptic: destroys or inhibits microorganisms on living tissue through chemical denaturation, oxidation, or membrane disruption.', pk: 'Topical: minimal systemic absorption. Povidone-iodine: broad spectrum. Chlorhexidine: persistent activity.', pearls: ['Chlorhexidine: surgical skin prep, oral care', 'Povidone-iodine: wound antisepsis, pre-surgical', 'Alcohol: rapid bactericidal but no residual'], warnings: ['Skin irritation with repeated use', 'Iodine allergy (povidone-iodine)', 'Ototoxicity (chlorhexidine — ear irrigations)'], overdose: 'Not applicable topically. Systemic absorption negligible.' },
  'Chelator': { moa: 'Chelator: binds to heavy metals or toxic elements, forming stable complexes that can be excreted renally, reducing metal toxicity.', pk: 'DMSA: PO, t1/2 4.5h. EDTA: IV, t1/2 1h (tissue redistribution). Deferoxamine: SC/IV. Metabolism: not metabolized. Excretion: renal.', pearls: ['DMSA: first-line for lead poisoning (mild-moderate)', 'EDTA: severe lead poisoning (IV)', 'Dimercaprol: arsenic, mercury, lead (severe)'], warnings: ['Nephrotoxicity — hydrate aggressively', 'Essential metal depletion (zinc, copper)', 'Deferoxamine: pulmonary toxicity with rapid infusion'], overdose: 'Symptoms: chelator toxicity. Management: discontinue, supportive care.' },
  'Antineoplastic': { moa: 'Antineoplastic: various mechanisms — alkylating DNA, inhibiting topoisomerase, disrupting microtubules, or blocking signaling pathways to kill cancer cells.', pk: 'Variable. Many require IV. Metabolism: hepatic. Narrow therapeutic index.', pearls: ['Combination regimens reduce resistance', 'Dose adjustments for renal/hepatic impairment', 'Cycle-specific: timing affects toxicity'], warnings: ['Myelosuppression — nadir varies by agent', 'Mucositis, mucosal ulceration', 'Gonadal toxicity — fertility preservation'], overdose: 'Agent-specific. Generally: supportive care, growth factors.' },

  // Fallback: use the template from drugClassTemplates if nothing above matches
}

// ═══════════════════════════════════════════════════════════════════════
// EXECUTE REPLACEMENTS
// ═══════════════════════════════════════════════════════════════════════

function getContentForClass(drugClass) {
  if (CLASS_CONTENT[drugClass]) return CLASS_CONTENT[drugClass]
  // Fuzzy match
  const lower = drugClass.toLowerCase()
  for (const [key, content] of Object.entries(CLASS_CONTENT)) {
    if (lower.includes(key.toLowerCase()) || key.toLowerCase().includes(lower)) return content
  }
  return null
}

let totalFixed = { moa: 0, pk: 0, pearls: 0, warnings: 0, overdose: 0, bbw: 0 }

// Pattern-based replacements (these are the exact generic strings found in the file)
const patterns = [
  // MoA patterns
  { re: /mechanism_of_action:\s*'Pharmacological agent: acts through specific receptor or enzyme interactions to produce therapeutic effects\.'/, field: 'moa' },
  { re: /"mechanism_of_action":\s*"Pharmacological agent: acts through specific receptor or enzyme interactions to produce therapeutic effects\."/, field: 'moa' },
  { re: /"mechanism_of_action":\s*"Pharmacological agent: acts through specific receptor or enzyme interactions to produce therapeutic effects\. Drug class: [^"]*"\./, field: 'moa' },

  // PK patterns
  { re: /pharmacokinetics:\s*'Absorption: variable depending on route\. Distribution: widespread\. Half-life: varies\. Metabolism: hepatic\. Excretion: renal\.'/, field: 'pk' },
  { re: /"pharmacokinetics":\s*"Absorption: variable depending on route\. Distribution: widespread\. Half-life: varies\. Metabolism: hepatic\. Excretion: renal\."/, field: 'pk' },

  // Pearls patterns
  { re: /clinical_pearls:\s*\['Clinical response varies based on patient factors',\s*'Monitor therapeutic response and adjust dose accordingly'\]/, field: 'pearls' },
  { re: /"clinical_pearls":\s*\["Clinical response varies based on patient factors",\s*"Monitor therapeutic response and adjust dose accordingly"\]/, field: 'pearls' },
  { re: /clinical_pearls:\s*\['Monitor therapeutic response'\]/, field: 'pearls' },
  { re: /"clinical_pearls":\s*\["Monitor therapeutic response"\]/, field: 'pearls' },

  // Warnings patterns
  { re: /warnings:\s*\['Use with caution in patients with pre-existing conditions',\s*'Monitor for side effects during therapy'\]/, field: 'warnings' },
  { re: /"warnings":\s*\["Use with caution in patients with pre-existing conditions",\s*"Monitor for side effects during therapy"\]/, field: 'warnings' },
  { re: /"warnings":\s*\["Use with caution in patients with renal or hepatic impairment",\s*"Monitor for adverse effects"\]/, field: 'warnings' },
  { re: /warnings:\s*\['Use with caution'\]/, field: 'warnings' },
  { re: /"warnings":\s*\["Use with caution"\]/, field: 'warnings' },

  // Overdose patterns
  { re: /overdose:\s*'Symptoms: nausea, vomiting, dizziness\. Management: supportive care\. No specific antidote\.'/, field: 'overdose' },
  { re: /"overdose":\s*"Symptoms: nausea, vomiting, dizziness, dose-related adverse effects\. Management: discontinue drug, provide supportive care\. No specific antidote\."/, field: 'overdose' },
  { re: /overdose:\s*'Symptoms: dose-dependent adverse effects\. Management: supportive care\. No specific antidote\.'/, field: 'overdose' },
  { re: /"overdose":\s*"Symptoms: dose-dependent adverse effects\. Management: supportive care\. No specific antidote\."/, field: 'overdose' },

  // BBW patterns (empty)
  { re: /black_box_warnings:\s*\[\]/, field: 'bbw' },
  { re: /"black_box_warnings":\s*\[\]/, field: 'bbw' },
]

// Build replacement map: for each drug block, find its drug_class, get content, replace patterns
const lines = src.split('\n')
let currentDrugClass = ''
let currentContent = null

for (let i = 0; i < lines.length; i++) {
  const line = lines[i]

  // Detect drug_class (single or double quote)
  const dcMatch = line.match(/drug_class:\s*'([^']+)'/) || line.match(/"drug_class":\s*"([^"]+)"/)
  if (dcMatch) {
    currentDrugClass = dcMatch[1]
    currentContent = getContentForClass(currentDrugClass)
  }

  if (!currentContent) continue

  for (const { re, field } of patterns) {
    if (!re.test(line)) continue

    let replacement = ''
    switch (field) {
      case 'moa': replacement = currentContent.moa; break
      case 'pk': replacement = currentContent.pk; break
      case 'pearls': replacement = currentContent.pearls; break
      case 'warnings': replacement = currentContent.warnings; break
      case 'overdose': replacement = currentContent.overdose; break
      case 'bbw':
        if (currentContent.bbw && currentContent.bbw.length > 0) {
          replacement = currentContent.bbw
        }
        break
    }

    if (!replacement) continue

    if (field === 'bbw') {
      const isArraySq = line.includes('black_box_warnings: []')
      const isArrayDq = line.includes('"black_box_warnings": []')
      if (isArraySq || isArrayDq) {
        const bbwStr = Array.isArray(replacement) ? replacement.map(b => `'${b}'`).join(', ') : `'${replacement}'`
        lines[i] = lines[i].replace(/black_box_warnings:\s*\[\]/, `black_box_warnings: [${bbwStr}]`)
        lines[i] = lines[i].replace(/"black_box_warnings":\s*\[\]/, `"black_box_warnings": [${replacement.map(b => `"${b}"`).join(', ')}]`)
        totalFixed.bbw++
      }
    } else if (field === 'pearls' || field === 'warnings') {
      // Array fields
      const arrStr = Array.isArray(replacement) ? replacement.map(p => `'${p.replace(/'/g, "\\'")}'`).join(', ') : `'${replacement}'`
      const dqArrStr = Array.isArray(replacement) ? replacement.map(p => `"${p.replace(/"/g, '\\"')}"`).join(', ') : `"${replacement}"`

      if (re.test(line)) {
        const matched = line.match(re)?.[0] || ''
        if (matched.includes("'")) {
          lines[i] = lines[i].replace(matched, `${field}: [${arrStr}]`)
        } else {
          lines[i] = lines[i].replace(matched, `"${field}": [${dqArrStr}]`)
        }
        totalFixed[field]++
      }
    } else {
      // String fields
      const safeReplacement = replacement.replace(/'/g, "\\'").replace(/"/g, '\\"')
      if (re.test(line)) {
        const matched = line.match(re)?.[0] || ''
        if (matched.includes("'")) {
          lines[i] = lines[i].replace(matched, matched.replace(/'[^']*'$/, `'${safeReplacement}'`))
        } else {
          lines[i] = lines[i].replace(matched, matched.replace(/"[^"]*"$/, `"${safeReplacement}"`))
        }
        totalFixed[field]++
      }
    }
  }
}

const newSrc = lines.join('\n')
writeFileSync(FILE, newSrc, 'utf-8')

const idCount = (newSrc.match(/"id":\s*"[^"]+"/g) || []).length + (newSrc.match(/\bid\s*:\s*'[^']+'/g) || []).length
const moaGen = (newSrc.match(/Pharmacological agent/g) || []).length
const pkGen = (newSrc.match(/Absorption: variable depending on route/g) || []).length
const pearlsGen = (newSrc.match(/Clinical response varies based on patient factors/g) || []).length
const warnGen = (newSrc.match(/Use with caution in patients/g) || []).length

console.log(`=== FINAL ENRICHMENT RESULTS ===`)
console.log(`Total drugs: ${idCount}`)
console.log(`Size: ${(newSrc.length / 1024).toFixed(1)} KB`)
console.log(`\nFields fixed:`)
console.log(`  MoA: ${totalFixed.moa}`)
console.log(`  PK: ${totalFixed.pk}`)
console.log(`  Pearls: ${totalFixed.pearls}`)
console.log(`  Warnings: ${totalFixed.warnings}`)
console.log(`  Overdose: ${totalFixed.overdose}`)
console.log(`  BBW: ${totalFixed.bbw}`)
console.log(`\nRemaining generic placeholders:`)
console.log(`  MoA: ${moaGen}`)
console.log(`  PK: ${pkGen}`)
console.log(`  Pearls: ${pearlsGen}`)
console.log(`  Warnings: ${warnGen}`)
console.log(`\nDone!`)
