/**
 * generate-bundled-fallback.ts
 * Generates src/data/drugIndexData.ts with all 1000 drugs from the canonical registry.
 * Uses class-specific clinical content as the fallback data source.
 *
 * Usage: npx tsx scripts/generate-bundled-fallback.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface CanonicalDrug {
  name: string;
  therapeuticClass: string;
  source?: string;
  priority?: string;
}

const CLASS_CONTENT: Record<string, { drugClass: string; indications: string[]; contraindications: string[]; sideEffects: string[]; interactions: string[]; monitoring: string; counselling: string; moa: string }> = {
  'Anti-infectives': { drugClass: 'Antimicrobial agent', indications: ['Treatment of susceptible bacterial/fungal/parasitic infections', 'Empiric therapy based on local susceptibility patterns', 'Prophylaxis in immunocompromised patients where indicated'], contraindications: ['Hypersensitivity to active substance', 'Severe renal impairment (dose adjustment may be required)', 'Severe hepatic impairment'], sideEffects: ['GI disturbances: nausea, vomiting, diarrhoea', 'Allergic reactions: skin rash, urticaria; rarely anaphylaxis', 'Antimicrobial-associated diarrhoea / C. difficile infection', 'QT prolongation (certain classes)'], interactions: ['Warfarin / DOACs — many antimicrobials alter INR', 'Oral contraceptives — reduced efficacy during therapy', 'Antacids / iron / calcium — reduced absorption of tetracyclines and fluoroquinolones'], monitoring: 'Monitor renal and hepatic function, CBC for prolonged courses. TDM for aminoglycosides and vancomycin.', counselling: 'Complete the full course. Do not share antibiotics. Report rash, severe diarrhoea, or superinfection.', moa: 'Mechanism varies by subclass: inhibits cell wall synthesis (beta-lactams), protein synthesis (macrolides, tetracyclines, aminoglycosides), DNA gyrase (fluoroquinolates), or folate pathway (sulfonamides, trimethoprim).' },
  'Cardiovascular': { drugClass: 'Cardiovascular agent', indications: ['Hypertension management', 'Heart failure with reduced or preserved ejection fraction', 'Coronary artery disease / stable angina', 'Arrhythmia control'], contraindications: ['Hypersensitivity to active substance', 'Severe bradycardia / sick sinus syndrome', 'Cardiogenic shock / decompensated heart failure', 'Severe hypotension (systolic BP <90 mmHg)'], sideEffects: ['Dizziness, headache, fatigue', 'Postural hypotension', 'Bradycardia / heart block (rate-slowing agents)', 'Peripheral oedema (CCBs)', 'Dry cough (ACE inhibitors)'], interactions: ['NSAIDs — reduce antihypertensive efficacy', 'Beta-blockers / CCBs (verapamil, diltiazem) — additive bradycardia', 'Diuretics — additive hypotension', 'Digoxin — increased levels with certain agents'], monitoring: 'Monitor BP, HR, ECG at baseline and during titration. Check renal function and electrolytes with ACEi/ARB/diuretics.', counselling: 'Take at the same time each day. Do not stop suddenly. Rise slowly from sitting. Avoid excessive salt.', moa: 'Mechanism depends on drug class: ACE inhibitors block angiotensin-converting enzyme; ARBs block AT1 receptors; beta-blockers inhibit beta-adrenergic receptors; CCBs inhibit calcium influx; diuretics promote renal sodium/water excretion.' },
  'Central Nervous System': { drugClass: 'CNS agent', indications: ['Management of neuropsychiatric disorders', 'Symptom control in chronic CNS conditions', 'Acute treatment of CNS emergencies', 'Adjunctive therapy in treatment-resistant cases'], contraindications: ['Hypersensitivity to active substance', 'Acute narrow-angle glaucoma (certain agents)', 'Severe hepatic impairment', 'MAOI co-administration (certain antidepressants)'], sideEffects: ['Drowsiness, sedation, cognitive dulling', 'Psychomotor impairment', 'Weight gain / metabolic changes', 'Extrapyramidal symptoms (antipsychotics)', 'Headache, dizziness'], interactions: ['Alcohol / CNS depressants — additive sedation', 'MAOIs — hypertensive crisis risk', 'Serotonergic drugs — serotonin syndrome risk', 'Warfarin — altered metabolism'], monitoring: 'Monitor mental state, suicidal ideation, weight, metabolic parameters, ECG, LFTs, drug levels (lithium, valproate, carbamazepine).', counselling: 'May cause drowsiness — avoid driving. Take as prescribed. Report worsening mood or suicidal thoughts. Avoid alcohol.', moa: 'Varies by class: SSRIs block serotonin reuptake; antipsychotics block D2 receptors; benzodiazepines enhance GABA-A activity; anticonvulsants modulate ion channels or neurotransmitter release.' },
  'Analgesics': { drugClass: 'Analgesic agent', indications: ['Acute and chronic pain management', 'Post-operative pain control', 'Fever reduction (antipyretic effect)', 'Neuropathic pain management'], contraindications: ['Hypersensitivity to active substance or NSAIDs', 'Active peptic ulceration / GI bleeding (NSAIDs)', 'Severe hepatic or renal impairment', 'Concurrent anticoagulation (NSAIDs)'], sideEffects: ['GI: nausea, vomiting, dyspepsia, constipation (opioids)', 'Sedation, dizziness', 'GI ulceration / bleeding (NSAIDs)', 'Hepatotoxicity (paracetamol overdose)', 'Respiratory depression (opioids)'], interactions: ['Anticoagulants — increased bleeding risk (NSAIDs)', 'Methotrexate — reduced clearance (NSAIDs)', 'CNS depressants — additive sedation (opioids)', 'ACE inhibitors — reduced efficacy (NSAIDs)'], monitoring: 'Monitor pain scores, renal function, LFTs, respiratory rate, sedation score (opioids), bowel function.', counselling: 'Use lowest effective dose for shortest duration. Do not exceed max paracetamol dose. NSAIDs with food. Opioids: risk of dependence.', moa: 'NSAIDs inhibit COX-1/COX-2 reducing prostaglandin synthesis. Paracetamol acts centrally on COX pathways. Opioids bind mu-opioid receptors in the CNS inhibiting pain signalling.' },
  'Gastrointestinal': { drugClass: 'GI agent', indications: ['Acid-related disorders (GERD, peptic ulcer)', 'Nausea and vomiting', 'Diarrhoea or constipation', 'IBD management'], contraindications: ['Hypersensitivity to active substance', 'GI obstruction/perforation (prokinetics)', 'QT prolongation risk (certain antiemetics)'], sideEffects: ['Headache, GI disturbances', 'Constipation or diarrhoea', 'PPI: hypomagnesaemia, B12 deficiency', 'Extrapyramidal reactions (metoclopramide)'], interactions: ['PPIs — reduced absorption of ketoconazole, iron, digoxin', 'H2RAs — altered pH-dependent drug absorption', 'Metoclopramide — additive prokinetic effect', 'Methotrexate — reduced clearance with PPIs'], monitoring: 'Monitor symptoms, renal function, Mg2+ with prolonged PPI use, B12 status, stool occult blood. IBD: CRP, faecal calprotectin.', counselling: 'PPIs 30-60 min before meals. Antacids: separate from other meds by 2 hours. Stay hydrated. Report persistent vomiting or blood in stools.', moa: 'PPIs irreversibly inhibit H+/K+ ATPase on parietal cells. H2RAs competitively block histamine H2 receptors. Prokinetics enhance gastric motility via D2 antagonism or 5-HT4 agonism.' },
  'Endocrine/Metabolic': { drugClass: 'Endocrine / metabolic agent', indications: ['Diabetes mellitus (Type 1 and 2)', 'Thyroid disorders', 'Adrenal insufficiency', 'Dyslipidaemia management'], contraindications: ['Hypersensitivity to active substance', 'Severe renal impairment (metformin)', 'Active DKA (metformin)', 'Uncontrolled heart failure (certain agents)'], sideEffects: ['Hypoglycaemia (insulin, sulfonylureas)', 'Weight gain', 'GI disturbances (metformin, GLP-1 agonists)', 'Osteoporosis (prolonged corticosteroids)', 'Adrenal suppression'], interactions: ['Alcohol — hypoglycaemia risk', 'Corticosteroids — reduce antidiabetic efficacy', 'Thyroid hormones — alter warfarin INR', 'Beta-blockers — mask hypoglycaemic symptoms'], monitoring: 'HbA1c every 3 months, renal function, lipid profile, bone density (corticosteroids), TSH/T4, electrolytes, weight.', counselling: 'Diabetes: rotate injection sites, never skip meals on sulfonylureas. Thyroid: levothyroxine on empty stomach. Corticosteroids: do not stop abruptly.', moa: 'Metformin reduces hepatic glucose output and improves insulin sensitivity. Insulin binds insulin receptors promoting glucose uptake. Sulfonylureas stimulate pancreatic insulin secretion.' },
  'Respiratory': { drugClass: 'Respiratory agent', indications: ['Asthma maintenance and rescue', 'COPD management', 'Allergic rhinitis', 'Cough management'], contraindications: ['Hypersensitivity to active substance', 'Acute severe asthma (relievers only insufficient)', 'Severe cardiac arrhythmias (systemic sympathomimetics)'], sideEffects: ['Oral thrush (inhaled corticosteroids)', 'Tremor, tachycardia (beta-agonists)', 'Hoarseness (inhaled corticosteroids)', 'Systemic effects (high-dose ICS)', 'Paradoxical bronchospasm'], interactions: ['Beta-blockers — may antagonize bronchodilation', 'MAOIs — hypertensive crisis risk with sympathomimetics', 'CYP3A4 inhibitors — increase systemic corticosteroid levels', 'Diuretics — hypokalaemia risk'], monitoring: 'PEFR, FEV1, ACT/CAT scores, inhaler technique, growth in children, adrenal function (high-dose ICS), bone density.', counselling: 'Rinse mouth after ICS. Reliever overuse = poor control. Use spacer with MDIs. Report worsening symptoms.', moa: 'Beta-agonists relax bronchial smooth muscle via beta2-adrenergic receptor stimulation. ICS reduce airway inflammation. Anticholinergics block muscarinic receptors reducing bronchospasm.' },
  'Haematology/Oncology': { drugClass: 'Haematological / oncological agent', indications: ['Solid tumour chemotherapy', 'Haematological malignancy', 'Thromboembolic disease', 'Supportive care during chemotherapy'], contraindications: ['Severe myelosuppression', 'Severe hepatic or renal impairment', 'Pregnancy (most cytotoxic agents)', 'Active uncontrolled infection'], sideEffects: ['Myelosuppression (neutropenia, thrombocytopenia)', 'Nausea, vomiting, mucositis', 'Alopecia', 'Peripheral neuropathy', 'Cardiotoxicity (anthracyclines)'], interactions: ['Live vaccines — contraindicated', 'CYP450 substrates — altered metabolism', 'Anticoagulants — bleeding risk with thrombocytopenia', 'Nephrotoxic drugs — additive nephrotoxicity'], monitoring: 'FBC with differential before each cycle, renal and liver function, cardiac function (anthracyclines), neurological assessment, nutritional status.', counselling: 'Report fever >38°C immediately. Maintain hydration. Avoid live vaccines. Use effective contraception. Report mouth sores or unusual bleeding.', moa: 'Cytotoxic agents damage DNA (alkylating agents), inhibit topoisomerase, disrupt microtubules (taxanes, vinca alkaloids), or inhibit nucleotide synthesis (antimetabolites).' },
  'Musculoskeletal': { drugClass: 'Musculoskeletal agent', indications: ['Rheumatoid arthritis and inflammatory joint diseases', 'Osteoarthritis pain', 'Gout (acute and urate-lowering)', 'Osteoporosis prevention and treatment'], contraindications: ['Active severe infection', 'Severe hepatic or renal impairment', 'Pregnancy and lactation (many DMARDs)', 'Live vaccines during immunosuppression'], sideEffects: ['GI disturbance (NSAIDs, DMARDs)', 'Hepatotoxicity (methotrexate)', 'Bone marrow suppression (DMARDs)', 'Injection site reactions (biologics)', 'Increased infection risk'], interactions: ['NSAIDs — GI bleeding risk with corticosteroids', 'Methotrexate — toxicity with TMP-SMX, penicillins', 'Live vaccines — contraindicated', 'Warfarin — altered INR with NSAIDs'], monitoring: 'Disease activity scores, FBC, LFT, U&E regularly. TB screening before biologics. Bone density with corticosteroids.', counselling: 'DMARDs prevent disease progression — take regularly. Report infection signs. Methotrexate: weekly dose with folic acid. Avoid pregnancy during therapy.', moa: 'NSAIDs inhibit COX reducing prostaglandins. Methotrexate inhibits dihydrofolate reductase. Biologics target TNF, IL-6, or other inflammatory cytokines.' },
  'Immunology/Allergy': { drugClass: 'Immunological / anti-allergic agent', indications: ['Allergic rhinitis and urticaria', 'Autoimmune disease management', 'Transplant rejection prophylaxis', 'Hypersensitivity reactions'], contraindications: ['Active severe infection', 'Untreated latent TB', 'Severe heart failure (certain biologics)', 'Hypersensitivity to active substance'], sideEffects: ['Drowsiness (first-gen antihistamines)', 'Dry mouth, urinary retention', 'Increased infection risk (immunosuppressants)', 'Injection site reactions'], interactions: ['Live vaccines — contraindicated with immunosuppression', 'Immunosuppressants — additive effect', 'CNS depressants — additive sedation', 'CYP450 substrates — altered metabolism'], monitoring: 'TB/hepatitis B screening before immunosuppression. FBC, LFT, U&E at baseline and regularly. Disease activity scores.', counselling: 'Report fever or infection signs. Avoid live vaccines on immunosuppression. Carry treatment alert card. Do not miss doses.', moa: 'Antihistamines block H1 receptors. Immunosuppressants inhibit T-cell activation, B-cell proliferation, or cytokine production.' },
  'Renal/Electrolytes': { drugClass: 'Renal / electrolyte agent', indications: ['Electrolyte abnormalities', 'Fluid and electrolyte replacement', 'Acid-base correction', 'Hyperkalaemia management'], contraindications: ['Hypercalcaemia/hypermagnesaemia (for replacement)', 'Severe renal impairment with oliguria', 'Digitalis toxicity (calcium IV)', 'Extravasation risk'], sideEffects: ['Injection site reactions', 'Electrolyte imbalances with excessive replacement', 'Cardiac arrhythmias (rapid correction)', 'Volume overload'], interactions: ['Digoxin — hypokalaemia increases toxicity', 'Diuretics — electrolyte loss', 'ACE inhibitors — hyperkalaemia risk', 'Corticosteroids — sodium retention'], monitoring: 'Serum electrolytes (Na, K, Ca, Mg), renal function, fluid balance, ECG, acid-base status.', counselling: 'Report muscle cramps, weakness, palpitations. Take supplements as prescribed. Regular blood tests essential.', moa: 'Electrolyte supplements directly replace depleted ions. Sodium bicarbonate buffers excess acid. Potassium chloride/K-sparing diuretics manage potassium balance.' },
  'Toxicology/Antidotes': { drugClass: 'Antidote / toxicology agent', indications: ['Acute poisoning / overdose', 'Reversal of drug toxicity', 'Enhanced elimination of toxins', 'Chemical exposure management'], contraindications: ['Hypersensitivity (specific antidotes)', 'Ileus / GI obstruction (activated charcoal)', 'Caustic ingestion (charcoal contraindicated)'], sideEffects: ['GI effects (activated charcoal)', 'Tachycardia, hypertension (reversal agents)', 'Anaphylaxis (antivenoms)', 'Rebound toxicity (naloxone)'], interactions: ['Charcoal — reduces ALL oral drug absorption', 'Naloxone — concurrent opioid antagonists', 'Antivenoms — may affect vaccines'], monitoring: 'Continuous vitals, ECG, serial toxin levels (paracetamol, salicylate, lithium), electrolytes, renal/hepatic function, coagulation.', counselling: 'Poisoning is a medical emergency. Provide substance details, quantity, and timing. Do not induce vomiting unless directed.', moa: 'Naloxone competitively blocks mu-opioid receptors. N-acetylcysteine replenishes glutathione in paracetamol overdose. Activated charcoal adsorbs ingested toxins.' },
  'Nutrition/Vitamins': { drugClass: 'Nutritional supplement / vitamin', indications: ['Nutritional deficiency prevention and treatment', 'Vitamin/mineral replacement', 'Increased demand states (pregnancy, growth)', 'Malabsorption syndromes'], contraindications: ['Hypercalcaemia / hypervitaminosis D', 'Iron overload (haemochromatosis)', 'Severe renal impairment (certain formulations)', 'Galactosaemia'], sideEffects: ['GI: nausea, constipation (iron), diarrhoea (magnesium)', 'Flushing (niacin)', 'Soft tissue calcification (excess vitamin D)', 'Iron overload'], interactions: ['Tetracyclines / FQ — absorption reduced by minerals', 'Thyroxine — absorption reduced by calcium/iron', 'Warfarin — vitamin K reverses anticoagulation', 'PPIs — reduced absorption of Ca, B12, Mg'], monitoring: 'Serum levels of supplemented nutrient, iron studies, vitamin D levels, calcium, phosphate, ALP, FBC.', counselling: 'Supplements do not replace a balanced diet. Iron: take with vitamin C, avoid tea/coffee. Calcium may cause constipation. Report toxicity symptoms.', moa: 'Vitamins serve as coenzymes or cofactors in metabolic pathways. Minerals are structural components or enzyme activators. Deficiency impairs specific metabolic processes.' },
  'Anaesthesia': { drugClass: 'Anaesthetic agent', indications: ['General anaesthesia induction and maintenance', 'Local and regional anaesthesia', 'Procedural sedation', 'Muscle relaxation for intubation'], contraindications: ['Hypersensitivity', 'Malignant hyperthermia susceptibility', 'Severe cardiovascular instability', 'Raised ICP (certain agents)', 'Porphyria'], sideEffects: ['Respiratory depression', 'Hypotension', 'PONV', 'Malignant hyperthermia', 'Anaphylaxis (NMBAs)'], interactions: ['Opioids/BZDs — synergistic respiratory depression', 'Volatile anaesthetics — myocardial sensitization', 'Antihypertensives — exaggerated hypotension', 'NMBAs — potentiated by aminoglycosides, Mg'], monitoring: 'Continuous ECG, BP, SpO2, ETCO2, temperature, neuromuscular blockade, urine output. Aldrete score in recovery.', counselling: 'Follow pre-operative fasting instructions. Arrange transport home. No driving for 24-48h after anaesthesia.', moa: 'Volatile agents alter membrane fluidity and modulate ion channels. IV agents (propofol, thiopental) enhance GABA-A inhibition. Local anaesthetics block voltage-gated sodium channels.' },
  'Ophthalmology': { drugClass: 'Ophthalmic agent', indications: ['Glaucoma treatment', 'Ocular infections', 'Ocular inflammation', 'Diagnostic mydriasis'], contraindications: ['Hypersensitivity', 'Narrow-angle glaucoma (mydriatics)', 'Severe asthma / COPD (topical beta-blockers)', 'Bradycardia / heart block (topical beta-blockers)'], sideEffects: ['Local irritation, blurred vision', 'Systemic absorption (beta-blockers: bradycardia)', 'Allergic conjunctivitis', 'Periorbital changes (prostaglandins)'], interactions: ['Oral beta-blockers — additive systemic blockade', 'CCBs / digoxin — additive cardiac effects', 'Multiple eye drops — separate by 5 minutes'], monitoring: 'IOP (tonometry), visual acuity, visual fields, optic disc, anterior chamber activity, pulse/BP with beta-blockers.', counselling: 'Remove contacts before drops. Nasolacrimal occlusion for 1 min after instillation. Separate different drops by 5 min.', moa: 'Beta-blockers reduce aqueous humour production. Prostaglandin analogues increase uveoscleral outflow. Antibiotics inhibit bacterial protein synthesis or cell wall formation.' },
  'Other': { drugClass: 'Therapeutic agent', indications: ['Management of specific conditions as per approved indications', 'Symptom control', 'Disease progression prevention', 'Refractory cases'], contraindications: ['Hypersensitivity to active substance', 'Severe hepatic impairment', 'Severe renal impairment', 'Pregnancy and lactation (where applicable)'], sideEffects: ['GI disturbances', 'Headache, dizziness, fatigue', 'Hypersensitivity reactions', 'Hepatic enzyme elevations', 'Renal function effects'], interactions: ['CYP450 interactions', 'Anticoagulants', 'Antihypertensives', 'Alcohol'], monitoring: 'Clinical response, renal function, liver function, CBC as appropriate. TDM where applicable.', counselling: 'Take as prescribed. Do not stop without consulting doctor. Report unusual symptoms. Keep follow-up appointments.', moa: 'Refer to prescribing information for specific mechanism of action.' },
};

function getDrugClass(name: string): string {
  const lc = name.toLowerCase();
  if (lc.includes('cillin') || lc.includes('ceph') || lc.includes('floxacin') || lc.includes('mycin') || lc.includes('azole') || lc.includes('viral') || lc.includes('bactrim') || lc.includes('metronidazole') || lc.includes('vancomycin') || lc.includes('linezolid')) return 'Anti-infectives';
  if (lc.includes('olol') || lc.includes('pril') || lc.includes('sartan') || lc.includes('pine') && !lc.includes('penicillin') || lc.includes('dipine') || lc.includes('statin') || lc.includes('oxin') || lc.includes('digoxin') || lc.includes('amiodarone') || lc.includes('heparin') || lc.includes('warfarin') || lc.includes('rivaroxaban') || lc.includes('apixaban') || lc.includes('clopidogrel') || lc.includes('aspirin') && lc.length < 12) return 'Cardiovascular';
  if (lc.includes('prazole') || lc.includes('tidine') || lc.includes('ranitidine') || lc.includes('famotidine') || lc.includes('metoclopramide') || lc.includes('domperidone') || lc.includes('loperamide') || lc.includes('lactulose') || lc.includes('lansoprazole') || lc.includes('omeprazole') || lc.includes('pantoprazole') || lc.includes('esomeprazole')) return 'Gastrointestinal';
  if (lc.includes('statin') || lc.includes('metformin') || lc.includes('gli') || lc.includes('insulin') || lc.includes('thyroxine') || lc.includes('levothyroxine') || lc.includes('prednisolone') || lc.includes('prednisone') || lc.includes('dexamethasone') || lc.includes('hydrocortisone') || lc.includes('cortisone')) return 'Endocrine/Metabolic';
  if (lc.includes('azepam') || lc.includes('azolam') || lc.includes('pril') && lc.includes('c') || lc.includes('oxetine') || lc.includes('pramine') || lc.includes('done') || lc.includes('olone') || lc.includes('pam') || lc.includes('lam') || lc.includes('barb') || lc.includes('tiapride') || lc.includes('risperidone') || lc.includes('olanzapine') || lc.includes('quetiapine') || lc.includes('aripiprazole') || lc.includes('haloperidol') || lc.includes('lithium') || lc.includes('valproate') || lc.includes('carbamazepine') || lc.includes('gabapentin') || lc.includes('pregabalin')) return 'Central Nervous System';
  if (lc.includes('olol') && (lc.includes('sal') || lc.includes('but') || lc.includes('form') || lc.includes('terol') || lc.includes('ropium') || lc.includes('sonide') || lc.includes('icasone') || lc.includes('mometasone'))) return 'Respiratory';
  if (lc.includes('mab') || lc.includes('nib') || lc.includes('tinib') || lc.includes('cyclophosphamide') || lc.includes('methotrexate') || lc.includes('fluorouracil') || lc.includes('doxorubicin') || lc.includes('cisplatin') || lc.includes('carboplatin') || lc.includes('paclitaxel') || lc.includes('tamoxifen') || lc.includes('letrozole') || lc.includes('anastrozole') || lc.includes('imatinib')) return 'Haematology/Oncology';
  if (lc.includes('mab') && (lc.includes('umab') || lc.includes('ximab') || lc.includes('zumab')) || lc.includes('ciclosporin') || lc.includes('azathioprine') || lc.includes('mycophenolate') || lc.includes('tacrolimus')) return 'Immunology/Allergy';
  if (lc.includes('oxicam') || lc.includes('profen') || lc.includes('nabumetone') || lc.includes('meloxicam') || lc.includes('allopurinol') || lc.includes('colchicine') || lc.includes('alendronate') || lc.includes('risedronate')) return 'Musculoskeletal';
  if (lc.includes('vitamin') || lc.includes('iron') || lc.includes('calcium') || lc.includes('folate') || lc.includes('folic') || lc.includes('magnesium') || lc.includes('potassium') || lc.includes('zinc')) return 'Nutrition/Vitamins';
  if (lc.includes('fentanyl') || lc.includes('morphine') || lc.includes('pethidine') || lc.includes('ketamine') || lc.includes('propofol') || lc.includes('thiopental') || lc.includes('lidocaine') || lc.includes('bupivacaine') || lc.includes('ropivacaine')) return 'Analgesics';
  if (lc.includes('eye') || lc.includes('optic') || lc.includes('timolol') && lc.length < 10 || lc.includes('pilocarpine') || lc.includes('latanoprost') || lc.includes('brimonidine')) return 'Ophthalmology';
  if (lc.includes('naloxone') || lc.includes('naltrexone') || lc.includes('flumazenil') || lc.includes('atropine') || lc.includes('pralidoxime') || lc.includes('n-acetylcysteine') || lc.includes('activated charcoal')) return 'Toxicology/Antidotes';
  if (lc.includes('saline') || lc.includes('dextrose') || lc.includes('ringer') || lc.includes('chloride') || lc.includes('sodium') || lc.includes('bicarbonate')) return 'Renal/Electrolytes';
  return 'Other';
}

function main() {
  const registry: CanonicalDrug[] = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'drug-registry-canonical.json'), 'utf-8')
  );

  console.log(`Generating bundled fallback for ${registry.length} drugs...`);

  const lines: string[] = [
    `import type { DrugMonograph } from '../services/drugMonograph.service';`,
    ``,
    `export const BUNDLED_DRUGS: DrugMonograph[] = [`,
  ];

  for (let i = 0; i < registry.length; i++) {
    const drug = registry[i];
    const therapeuticClass = drug.therapeuticClass || getDrugClass(drug.name);
    const content = CLASS_CONTENT[therapeuticClass] || CLASS_CONTENT['Other'];

    const id = `bundled-${String(i + 1).padStart(3, '0')}`;

    const entry = [
      `{ id: '${id}', name: ${JSON.stringify(drug.name)}, generic_name: ${JSON.stringify(drug.name)}, drug_class: ${JSON.stringify(content.drugClass)}, drug_class_id: null, drug_class_name: ${JSON.stringify(drug.therapeuticClass || therapeuticClass)},`,
      `  indications: ${JSON.stringify(content.indications)},`,
      `  contraindications: ${JSON.stringify(content.contraindications)},`,
      `  side_effects: ${JSON.stringify(content.sideEffects)},`,
      `  dosage: { adult: 'Refer to prescribing guidelines. Consider renal/hepatic function, age, weight, comorbidities.', paediatric: 'Weight-based dosing per paediatric guidelines.', geriatric: 'Start low, titrate slowly. Monitor CrCl.' },`,
      `  interactions: ${JSON.stringify(content.interactions)},`,
      `  monitoring: ${JSON.stringify(content.monitoring)},`,
      `  patient_counselling: ${JSON.stringify(content.counselling)},`,
      `  mechanism_of_action: ${JSON.stringify(content.moa)},`,
      `  brand_names: [],`,
      `  pregnancy_category: 'Consult prescribing information',`,
      `  warnings: [],`,
      `  overdose: 'Seek immediate medical attention in case of overdose. No specific antidote for most agents.',`,
      `  pharmacokinetics: 'Refer to prescribing information for ADME and half-life data.',`,
      `  black_box_warnings: [],`,
      `  clinical_pearls: [],`,
      `  created_at: '' },`,
    ];

    lines.push(...entry);

    if ((i + 1) % 100 === 0) console.log(`  ${i + 1}/${registry.length} drugs processed`);
  }

  lines.push(`];`);
  lines.push(``);

  const outputPath = path.join(__dirname, '..', 'src', 'data', 'drugIndexData.ts');
  fs.writeFileSync(outputPath, lines.join('\n'));
  console.log(`\nWrote ${outputPath} with ${registry.length} drugs`);
}

main();
