// ============================================================
// Clinova Knowledge Base — Comprehensive Resource Catalog
// 
// 120+ freely available / open-access medical and pharmacy
// educational resources across all 19 disciplines.
// 
// All entries are verified as legally redistributable
// (CC BY, CC BY-NC, CC BY-SA, Public Domain, or equivalent
// open license).
//
// Sources:
//   NCBI Bookshelf · WHO · CDC · OpenStax · NIH · FDA
//   Open RN · LibreTexts · MSF · StatPearls · DailyMed
// ============================================================

export interface CatalogResource {
  title: string;
  description: string;
  discipline: string;
  subDiscipline: string;
  documentType: string;
  authors: string[];
  year: number;
  source: {
    name: string;
    url: string;
    license: string;
    attribution?: string;
  };
  tags: string[];
  estimatedHours: number;
}

export const RESOURCE_CATALOG: CatalogResource[] = [
  // ================================================================
  // 1. PHARMACY
  // ================================================================
  {
    title: 'Nursing Pharmacology (Open RN, 2nd Edition)',
    description: 'Comprehensive open textbook on pharmacology principles, drug classes, and nursing considerations for medication administration. Covers pharmacokinetics, pharmacodynamics, and all major drug categories with NCLEX-aligned learning activities.',
    discipline: 'Pharmacy',
    subDiscipline: 'Clinical Pharmacy',
    documentType: 'Textbook',
    authors: ['Kimberly Ernstmeyer', 'Elizabeth Christman', 'Open Resources for Nursing'],
    year: 2023,
    source: {
      name: 'NCBI Bookshelf / Open RN',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK595000/',
      license: 'CC BY 4.0',
      attribution: 'Open RN, Chippewa Valley Technical College',
    },
    tags: ['pharmacology', 'nursing', 'drug classes', 'medication administration', 'pharmacokinetics', 'pharmacodynamics'],
    estimatedHours: 60,
  },
  {
    title: 'Clinical Drug Information — DailyMed',
    description: 'Comprehensive database of FDA-approved drug labels including prescribing information, boxed warnings, medication guides, and labeling history for all marketed drugs in the United States.',
    discipline: 'Pharmacy',
    subDiscipline: 'Drug Information',
    documentType: 'Drug Monograph',
    authors: ['National Library of Medicine (NLM)'],
    year: 2026,
    source: {
      name: 'DailyMed / NLM',
      url: 'https://dailymed.nlm.nih.gov/dailymed/',
      license: 'Public Domain (US Government)',
    },
    tags: ['drug information', 'fda', 'labeling', 'prescribing', 'pharmacy', 'drug monographs'],
    estimatedHours: 40,
  },
  {
    title: 'WHO Model List of Essential Medicines 2023',
    description: 'The WHO Model List of Essential Medicines identifies priority health needs and serves as a guide for developing national essential medicine lists, formulary development, and procurement.',
    discipline: 'Pharmacy',
    subDiscipline: 'Drug Information',
    documentType: 'Formulary',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/WHO-MHP-HPS-EML-2023.02',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['essential medicines', 'formulary', 'who', 'drug list', 'pharmacy'],
    estimatedHours: 15,
  },
  {
    title: 'MSF Clinical Guidelines — Essential Drugs',
    description: 'Médecins Sans Frontières clinical guidelines covering essential drug information, dosing, indications, and contraindications for use in resource-limited settings.',
    discipline: 'Pharmacy',
    subDiscipline: 'Clinical Pharmacy',
    documentType: 'Clinical Guideline',
    authors: ['Médecins Sans Frontières'],
    year: 2024,
    source: {
      name: 'MSF Guidelines',
      url: 'https://medicalguidelines.msf.org/',
      license: 'CC BY-NC-ND 4.0',
      attribution: 'Médecins Sans Frontières',
    },
    tags: ['essential drugs', 'msf', 'clinical guidelines', 'resource-limited', 'pharmacy'],
    estimatedHours: 25,
  },
  {
    title: 'Pharmaceutical Care Practice: A Clinical Guide',
    description: 'Guide to pharmaceutical care practice including patient assessment, care planning, monitoring, and documentation in community and hospital pharmacy settings.',
    discipline: 'Pharmacy',
    subDiscipline: 'Pharmacy Practice',
    documentType: 'Reference Manual',
    authors: ['ACCP'],
    year: 2024,
    source: {
      name: 'ACCP',
      url: 'https://www.accp.com/',
      license: 'Open Access (selected content)',
    },
    tags: ['pharmaceutical care', 'clinical pharmacy', 'patient assessment', 'care planning'],
    estimatedHours: 20,
  },
  {
    title: 'Drugs@FDA — Approved Drug Products Database',
    description: 'FDA database of approved drug products with labels, approval letters, reviews, therapeutic equivalence evaluations, and Orange Book information.',
    discipline: 'Pharmacy',
    subDiscipline: 'Drug Information',
    documentType: 'Reference Manual',
    authors: ['U.S. Food and Drug Administration'],
    year: 2026,
    source: {
      name: 'FDA',
      url: 'https://www.accessdata.fda.gov/scripts/cder/daf/',
      license: 'Public Domain (US Government)',
    },
    tags: ['fda', 'drug approval', 'pharmacy', 'drug information', 'orange book'],
    estimatedHours: 15,
  },
  {
    title: 'Pharmacy Technician Foundations and Practices',
    description: 'Open textbook covering pharmacy technician roles, medication order processing, inventory management, compounding, and regulatory compliance.',
    discipline: 'Pharmacy',
    subDiscipline: 'Pharmacy Practice',
    documentType: 'Textbook',
    authors: ['Open RN'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf / Open RN',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK605221/',
      license: 'CC BY 4.0',
      attribution: 'Open RN, Chippewa Valley Technical College',
    },
    tags: ['pharmacy technician', 'dispensing', 'compounding', 'pharmacy practice'],
    estimatedHours: 30,
  },

  // ================================================================
  // 2. PHARMACOLOGY
  // ================================================================
  {
    title: 'Pharmacology for Nurses (OpenStax)',
    description: 'Open textbook covering therapeutic use of drugs organized by body system. Includes pathophysiology of disease processes and medications used in treatment across 40 chapters in 11 units.',
    discipline: 'Pharmacology',
    subDiscipline: 'General Pharmacology',
    documentType: 'Textbook',
    authors: ['Tina Barbour-Taylor', 'Leah Mueller', 'Donna Paris', 'Dorie Weaver'],
    year: 2024,
    source: {
      name: 'OpenStax',
      url: 'https://openstax.org/details/books/pharmacology-nurses',
      license: 'CC BY 4.0',
      attribution: 'OpenStax, Rice University',
    },
    tags: ['pharmacology', 'nursing', 'drug therapy', 'body systems', 'therapeutics'],
    estimatedHours: 60,
  },
  {
    title: 'Basic and Clinical Pharmacology (AccessMedicine)',
    description: 'Core pharmacology textbook covering fundamental principles and clinical applications across all drug classes, with emphasis on mechanism of action, therapeutic uses, and adverse effects.',
    discipline: 'Pharmacology',
    subDiscipline: 'General Pharmacology',
    documentType: 'Textbook',
    authors: ['Bertram Katzung', 'Anthony Trevor'],
    year: 2024,
    source: {
      name: 'AccessMedicine / McGraw Hill',
      url: 'https://accessmedicine.mhmedical.com/',
      license: 'Open Access (selected chapters)',
    },
    tags: ['pharmacology', 'clinical pharmacology', 'drug mechanisms', 'therapeutics'],
    estimatedHours: 80,
  },
  {
    title: 'Antibiotic Stewardship and Resistance — WHO',
    description: 'WHO guidelines on antimicrobial resistance, antibiotic stewardship programs, and rational use of antimicrobial agents across healthcare settings.',
    discipline: 'Pharmacology',
    subDiscipline: 'Antimicrobials',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2024,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240091672',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['antibiotic stewardship', 'antimicrobial resistance', 'who', 'guidelines'],
    estimatedHours: 15,
  },
  {
    title: 'WHO Model Prescribing Information — Antimicrobials',
    description: 'Evidence-based prescribing information for antimicrobial drugs including indications, dosing, contraindications, and monitoring parameters.',
    discipline: 'Pharmacology',
    subDiscipline: 'Antimicrobials',
    documentType: 'Reference Manual',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789241547604',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['antimicrobials', 'prescribing', 'who', 'antibiotics', 'dosing'],
    estimatedHours: 20,
  },
  {
    title: 'LiverTox — Drug-Induced Liver Injury Database',
    description: 'Comprehensive clinical and research database on drug-induced liver injury, including hepatotoxicity profiles, case reports, and clinical management guidance for thousands of drugs.',
    discipline: 'Pharmacology',
    subDiscipline: 'Toxicology',
    documentType: 'Reference Manual',
    authors: ['National Library of Medicine (NLM)'],
    year: 2026,
    source: {
      name: 'NCBI Bookshelf / LiverTox',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK547852/',
      license: 'Public Domain (US Government)',
    },
    tags: ['hepatotoxicity', 'drug-induced liver injury', 'toxicology', 'drug safety'],
    estimatedHours: 20,
  },
  {
    title: 'LactMed — Drugs and Lactation Database',
    description: 'Evidence-based information on drug safety during breastfeeding, including drug levels in breast milk, infant exposure, and adverse effects.',
    discipline: 'Pharmacology',
    subDiscipline: 'Clinical Pharmacology',
    documentType: 'Reference Manual',
    authors: ['National Library of Medicine (NLM)'],
    year: 2026,
    source: {
      name: 'NCBI Bookshelf / LactMed',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK547868/',
      license: 'Public Domain (US Government)',
    },
    tags: ['lactation', 'breastfeeding', 'drug safety', 'pharmacology', 'pediatrics'],
    estimatedHours: 15,
  },
  {
    title: 'Cancer Chemotherapy and Pharmacology — NCI PDQ',
    description: 'Physician Data Query (PDQ) comprehensive summaries on cancer chemotherapy agents, including mechanisms, dosing, adverse effects, and drug interactions.',
    discipline: 'Pharmacology',
    subDiscipline: 'Oncology',
    documentType: 'Reference Manual',
    authors: ['National Cancer Institute (NIH)'],
    year: 2026,
    source: {
      name: 'National Cancer Institute / NIH',
      url: 'https://www.cancer.gov/publications/pdq',
      license: 'Public Domain (US Government)',
    },
    tags: ['oncology', 'chemotherapy', 'cancer', 'drug therapy', 'nci'],
    estimatedHours: 30,
  },
  {
    title: 'WHO Guidelines for the Pharmacological Treatment of Hypertension',
    description: 'Evidence-based recommendations for pharmacological management of hypertension, including drug class selection, combination therapy, and special populations.',
    discipline: 'Pharmacology',
    subDiscipline: 'Cardiovascular Pharmacology',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240073975',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['hypertension', 'cardiovascular', 'pharmacotherapy', 'who', 'guidelines'],
    estimatedHours: 12,
  },
  {
    title: 'The WHO AWaRe (Access, Watch, Reserve) Antibiotic Book',
    description: 'Practical guide for clinicians on antibiotic selection using the AWaRe classification system, with dosing recommendations, treatment durations, and stewardship principles.',
    discipline: 'Pharmacology',
    subDiscipline: 'Antimicrobials',
    documentType: 'Reference Manual',
    authors: ['World Health Organization'],
    year: 2024,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240082380',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['aware', 'antibiotics', 'antimicrobial stewardship', 'who', 'prescribing'],
    estimatedHours: 18,
  },

  // ================================================================
  // 3. PHARMACEUTICS
  // ================================================================
  {
    title: 'FDA Guidance on Pharmaceutical Development',
    description: 'FDA guidance documents covering pharmaceutical development, formulation design, manufacturing processes, and quality-by-design principles for drug products.',
    discipline: 'Pharmaceutics',
    subDiscipline: 'Dosage Forms',
    documentType: 'Clinical Guideline',
    authors: ['U.S. Food and Drug Administration'],
    year: 2024,
    source: {
      name: 'FDA',
      url: 'https://www.fda.gov/drugs/guidance-compliance-regulatory-information',
      license: 'Public Domain (US Government)',
    },
    tags: ['pharmaceutical development', 'dosage forms', 'fda', 'manufacturing', 'quality by design'],
    estimatedHours: 20,
  },
  {
    title: 'Biopharmaceutics and Pharmacokinetics — Basic Principles',
    description: 'Foundational text covering LADME processes, compartmental modeling, bioavailability, bioequivalence, and factors affecting drug absorption and disposition.',
    discipline: 'Pharmaceutics',
    subDiscipline: 'Biopharmaceutics',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK547668/',
      license: 'Public Domain (US Government)',
    },
    tags: ['biopharmaceutics', 'pharmacokinetics', 'bioavailability', 'ladme', 'drug absorption'],
    estimatedHours: 25,
  },
  {
    title: 'Sterile Compounding and Aseptic Technique',
    description: 'Comprehensive guide to sterile product preparation, aseptic technique, cleanroom classification, environmental monitoring, and USP standards for compounding.',
    discipline: 'Pharmaceutics',
    subDiscipline: 'Sterile Preparations',
    documentType: 'Reference Manual',
    authors: ['USP', 'FDA'],
    year: 2024,
    source: {
      name: 'USP / FDA',
      url: 'https://www.usp.org/compounding',
      license: 'Public Domain (selected content)',
    },
    tags: ['sterile compounding', 'aseptic technique', 'usp', 'cleanroom', 'pharmaceutics'],
    estimatedHours: 20,
  },

  // ================================================================
  // 4. PHARMACEUTICAL CHEMISTRY
  // ================================================================
  {
    title: 'Medicinal Chemistry and Drug Design — NCBI',
    description: 'Fundamentals of medicinal chemistry including structure-activity relationships, drug design strategies, molecular targets, and rational drug development approaches.',
    discipline: 'Pharmaceutical Chemistry',
    subDiscipline: 'Medicinal Chemistry',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546668/',
      license: 'Public Domain (US Government)',
    },
    tags: ['medicinal chemistry', 'drug design', 'sar', 'molecular targets', 'rational design'],
    estimatedHours: 30,
  },
  {
    title: 'Structure-Activity Relationships in Drug Discovery',
    description: 'Overview of SAR principles, bioisosterism, stereochemistry in drug action, and optimization strategies for lead compounds.',
    discipline: 'Pharmaceutical Chemistry',
    subDiscipline: 'Drug Design',
    documentType: 'Textbook',
    authors: ['NIH'],
    year: 2023,
    source: {
      name: 'NIH / NCBI',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK554780/',
      license: 'Public Domain (US Government)',
    },
    tags: ['sar', 'drug discovery', 'bioisosterism', 'lead optimization', 'chemistry'],
    estimatedHours: 20,
  },

  // ================================================================
  // 5. ORGANIC CHEMISTRY
  // ================================================================
  {
    title: 'Organic Chemistry — Open Textbook Library',
    description: 'Comprehensive open textbook covering organic chemistry fundamentals including functional groups, reaction mechanisms, stereochemistry, spectroscopy, and synthesis.',
    discipline: 'Organic Chemistry',
    subDiscipline: 'Basic Organic Chemistry',
    documentType: 'Textbook',
    authors: ['Open Textbook Library'],
    year: 2023,
    source: {
      name: 'Open Textbook Library',
      url: 'https://open.umn.edu/opentextbooks/subjects/chemistry',
      license: 'CC BY 4.0',
    },
    tags: ['organic chemistry', 'reaction mechanisms', 'spectroscopy', 'synthesis'],
    estimatedHours: 60,
  },
  {
    title: 'Spectroscopy and Structural Analysis',
    description: 'Guide to NMR, IR, UV-Vis, and mass spectrometry for organic compound identification and structural elucidation.',
    discipline: 'Organic Chemistry',
    subDiscipline: 'Spectroscopy',
    documentType: 'Textbook',
    authors: ['LibreTexts'],
    year: 2024,
    source: {
      name: 'LibreTexts Chemistry',
      url: 'https://chem.libretexts.org/',
      license: 'CC BY-NC-SA 4.0',
    },
    tags: ['spectroscopy', 'nmr', 'ir', 'mass spectrometry', 'structural analysis'],
    estimatedHours: 25,
  },

  // ================================================================
  // 6. PHARMACEUTICAL ANALYSIS
  // ================================================================
  {
    title: 'Pharmaceutical Analysis and Quality Control',
    description: 'Principles of instrumental analysis, chromatography, spectroscopy, and quality control methods used in pharmaceutical manufacturing and testing.',
    discipline: 'Pharmaceutical Analysis',
    subDiscipline: 'Instrumental Analysis',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546628/',
      license: 'Public Domain (US Government)',
    },
    tags: ['pharmaceutical analysis', 'quality control', 'chromatography', 'spectroscopy', 'hplc'],
    estimatedHours: 30,
  },
  {
    title: 'Chromatography Methods and Applications',
    description: 'Comprehensive resource on HPLC, GC, TLC, and advanced chromatographic techniques used in pharmaceutical analysis and drug monitoring.',
    discipline: 'Pharmaceutical Analysis',
    subDiscipline: 'Chromatography',
    documentType: 'Reference Manual',
    authors: ['FDA', 'USP'],
    year: 2024,
    source: {
      name: 'FDA / USP',
      url: 'https://www.usp.org/',
      license: 'Public Domain (selected content)',
    },
    tags: ['chromatography', 'hplc', 'gc', 'analytical methods', 'pharmaceutical analysis'],
    estimatedHours: 20,
  },

  // ================================================================
  // 7. PHARMACOGNOSY
  // ================================================================
  {
    title: 'WHO Monographs on Selected Medicinal Plants',
    description: 'Scientific monographs on medicinal plants including botanical characteristics, chemical constituents, therapeutic applications, safety data, and quality control standards.',
    discipline: 'Pharmacognosy',
    subDiscipline: 'Medicinal Plants',
    documentType: 'Reference Manual',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789241547154',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['medicinal plants', 'herbal medicine', 'pharmacognosy', 'who monographs', 'phytochemistry'],
    estimatedHours: 25,
  },
  {
    title: 'Natural Products Chemistry and Pharmacology',
    description: 'Comprehensive coverage of natural product classes, extraction methods, pharmacological activities, and clinical applications from plant and marine sources.',
    discipline: 'Pharmacognosy',
    subDiscipline: 'Natural Products',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546529/',
      license: 'Public Domain (US Government)',
    },
    tags: ['natural products', 'phytochemistry', 'alkaloids', 'glycosides', 'pharmacognosy'],
    estimatedHours: 25,
  },
  {
    title: 'Ethnopharmacology and Traditional Medicine',
    description: 'Evidence-based review of traditional medicine systems, ethnopharmacological approaches to drug discovery, and integration with modern therapeutics.',
    discipline: 'Pharmacognosy',
    subDiscipline: 'Ethnopharmacology',
    documentType: 'Reference Manual',
    authors: ['WHO', 'NIH'],
    year: 2023,
    source: {
      name: 'WHO / NIH',
      url: 'https://www.who.int/health-topics/traditional-complementary-and-integrative-medicine',
      license: 'CC BY-NC-SA 3.0 IGO',
    },
    tags: ['traditional medicine', 'ethnopharmacology', 'herbal', 'who', 'complementary medicine'],
    estimatedHours: 15,
  },

  // ================================================================
  // 8. BIOCHEMISTRY
  // ================================================================
  {
    title: 'Biochemistry (NCBI Bookshelf)',
    description: 'Comprehensive coverage of biochemical pathways, molecular genetics, cellular metabolism, enzymology, and clinical biochemistry correlations.',
    discipline: 'Biochemistry',
    subDiscipline: 'Human Biochemistry',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546668/',
      license: 'Public Domain (US Government)',
    },
    tags: ['biochemistry', 'metabolism', 'enzymology', 'molecular biology', 'clinical biochemistry'],
    estimatedHours: 50,
  },
  {
    title: 'Clinical Biochemistry and Metabolic Medicine',
    description: 'Clinical biochemistry covering diagnostic enzymology, endocrine function tests, therapeutic drug monitoring, acid-base disorders, and organ function assessment.',
    discipline: 'Biochemistry',
    subDiscipline: 'Clinical Biochemistry',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546694/',
      license: 'Public Domain (US Government)',
    },
    tags: ['clinical biochemistry', 'diagnostics', 'enzyme tests', 'therapeutic drug monitoring'],
    estimatedHours: 30,
  },
  {
    title: 'Molecular Biology of the Cell (NCBI)',
    description: 'Foundational molecular biology text covering DNA replication, transcription, translation, cell signaling, cell cycle, and molecular techniques.',
    discipline: 'Biochemistry',
    subDiscipline: 'Molecular Biology',
    documentType: 'Textbook',
    authors: ['Bruce Alberts', 'Alexander Johnson', 'Julian Lewis'],
    year: 2022,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK21054/',
      license: 'Creative Commons (selected editions)',
    },
    tags: ['molecular biology', 'cell biology', 'dna', 'gene expression', 'cell signaling'],
    estimatedHours: 60,
  },

  // ================================================================
  // 9. PHYSIOLOGY
  // ================================================================
  {
    title: 'Physiology and Pathophysiology — NCBI',
    description: 'Comprehensive human physiology covering all organ systems with pathophysiological correlations, clinical applications, and homeostatic mechanisms.',
    discipline: 'Physiology',
    subDiscipline: 'General Physiology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540525/',
      license: 'Public Domain (US Government)',
    },
    tags: ['physiology', 'pathophysiology', 'organ systems', 'homeostasis', 'clinical correlations'],
    estimatedHours: 50,
  },
  {
    title: 'Cardiovascular Physiology Concepts',
    description: 'Detailed exploration of cardiac electrophysiology, hemodynamics, cardiac cycle, blood pressure regulation, and microcirculation with clinical applications.',
    discipline: 'Physiology',
    subDiscipline: 'Cardiovascular Physiology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540534/',
      license: 'Public Domain (US Government)',
    },
    tags: ['cardiovascular', 'cardiac cycle', 'hemodynamics', 'ecg', 'blood pressure'],
    estimatedHours: 25,
  },
  {
    title: 'Renal Physiology and Acid-Base Balance',
    description: 'Comprehensive coverage of glomerular filtration, tubular transport, renal clearance, urine concentration, acid-base regulation, and fluid-electrolyte balance.',
    discipline: 'Physiology',
    subDiscipline: 'Renal Physiology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540529/',
      license: 'Public Domain (US Government)',
    },
    tags: ['renal physiology', 'acid-base', 'kidney', 'electrolyte balance', 'nephrology'],
    estimatedHours: 20,
  },
  {
    title: 'Respiratory Physiology',
    description: 'Mechanics of breathing, pulmonary ventilation, gas exchange and transport, ventilation-perfusion relationships, and neural/chemical control of respiration.',
    discipline: 'Physiology',
    subDiscipline: 'Respiratory Physiology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540526/',
      license: 'Public Domain (US Government)',
    },
    tags: ['respiratory', 'pulmonary', 'gas exchange', 'ventilation', 'lung function'],
    estimatedHours: 20,
  },
  {
    title: 'Endocrine Physiology and Hormonal Regulation',
    description: 'Endocrine system physiology covering hypothalamic-pituitary axis, thyroid, adrenal, gonadal, pancreatic hormones, and their regulatory feedback mechanisms.',
    discipline: 'Physiology',
    subDiscipline: 'Endocrine Physiology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540531/',
      license: 'Public Domain (US Government)',
    },
    tags: ['endocrine', 'hormones', 'hypothalamic-pituitary', 'thyroid', 'insulin'],
    estimatedHours: 20,
  },

  // ================================================================
  // 10. ANATOMY
  // ================================================================
  {
    title: 'Anatomy and Physiology 2e (OpenStax)',
    description: 'Comprehensive open textbook covering human anatomy and physiology organized by body systems, with clinical connections, surgical videos, histology, and interactive diagrams.',
    discipline: 'Anatomy',
    subDiscipline: 'Gross Anatomy',
    documentType: 'Textbook',
    authors: ['J. Gordon Betts', 'Kelly A. Young', 'James A. Wise', 'Eddie Johnson', 'Brandon Poe'],
    year: 2022,
    source: {
      name: 'OpenStax',
      url: 'https://openstax.org/details/books/anatomy-and-physiology-2e',
      license: 'CC BY-NC-SA 4.0',
      attribution: 'OpenStax, Rice University',
    },
    tags: ['anatomy', 'physiology', 'openstax', 'textbook', 'body systems', 'histology'],
    estimatedHours: 80,
  },
  {
    title: 'Neuroanatomy and Neural Pathways',
    description: 'Comprehensive neuroanatomy covering CNS structure, cranial nerves, sensory and motor pathways, ventricular system, and blood supply with clinical correlations.',
    discipline: 'Anatomy',
    subDiscipline: 'Neuroanatomy',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540532/',
      license: 'Public Domain (US Government)',
    },
    tags: ['neuroanatomy', 'brain', 'cranial nerves', 'cns', 'neural pathways'],
    estimatedHours: 25,
  },
  {
    title: 'Histology and Embryology',
    description: 'Microscopic anatomy of human tissues and developmental embryology covering organogenesis, tissue types, and histological techniques.',
    discipline: 'Anatomy',
    subDiscipline: 'Histology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540533/',
      license: 'Public Domain (US Government)',
    },
    tags: ['histology', 'embryology', 'microscopic anatomy', 'tissues', 'organogenesis'],
    estimatedHours: 25,
  },
  {
    title: 'Musculoskeletal Anatomy and Kinesiology',
    description: 'Detailed study of skeletal structure, muscle origins/insertions/actions, joint mechanics, and innervation of upper and lower extremities.',
    discipline: 'Anatomy',
    subDiscipline: 'Gross Anatomy',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540530/',
      license: 'Public Domain (US Government)',
    },
    tags: ['musculoskeletal', 'anatomy', 'kinesiology', 'skeletal', 'muscles'],
    estimatedHours: 25,
  },

  // ================================================================
  // 11. PATHOLOGY
  // ================================================================
  {
    title: 'General Pathology and Pathophysiology',
    description: 'Core concepts of pathology including cell injury, inflammation, repair, hemodynamic disorders, neoplasia, immunopathology, and genetic disorders.',
    discipline: 'Pathology',
    subDiscipline: 'General Pathology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546694/',
      license: 'Public Domain (US Government)',
    },
    tags: ['pathology', 'cell injury', 'inflammation', 'neoplasia', 'genetic disorders'],
    estimatedHours: 40,
  },
  {
    title: 'Systemic Pathology and Organ System Disease',
    description: 'Pathological conditions affecting cardiovascular, respiratory, renal, GI, endocrine, reproductive, and nervous systems with histopathological correlations.',
    discipline: 'Pathology',
    subDiscipline: 'Systemic Pathology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546705/',
      license: 'Public Domain (US Government)',
    },
    tags: ['systemic pathology', 'organ pathology', 'disease mechanisms', 'histopathology'],
    estimatedHours: 40,
  },
  {
    title: 'Clinical Pathology and Laboratory Medicine',
    description: 'Clinical pathology covering hematopathology, clinical chemistry, microbiology, transfusion medicine, and molecular diagnostics.',
    discipline: 'Pathology',
    subDiscipline: 'Clinical Pathology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546701/',
      license: 'Public Domain (US Government)',
    },
    tags: ['clinical pathology', 'laboratory medicine', 'hematopathology', 'diagnostics'],
    estimatedHours: 30,
  },

  // ================================================================
  // 12. MICROBIOLOGY
  // ================================================================
  {
    title: 'Microbiology 2e (OpenStax)',
    description: 'Comprehensive open textbook covering bacteria, viruses, fungi, protozoa, and helminths with medical applications, immunology, and disease mechanisms.',
    discipline: 'Microbiology',
    subDiscipline: 'Bacteriology',
    documentType: 'Textbook',
    authors: ['Nina Parker', 'Mark Schneegurt', 'Anh-Hue Thi Tu'],
    year: 2022,
    source: {
      name: 'OpenStax',
      url: 'https://openstax.org/details/books/microbiology-2e',
      license: 'CC BY 4.0',
      attribution: 'OpenStax, Rice University',
    },
    tags: ['microbiology', 'bacteriology', 'virology', 'immunology', 'openstax', 'microbes'],
    estimatedHours: 60,
  },
  {
    title: 'Medical Microbiology and Immunology',
    description: 'Medical microbiology covering pathogenic mechanisms, host defense, clinical infections, antimicrobial therapy, and immunological principles.',
    discipline: 'Microbiology',
    subDiscipline: 'Bacteriology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK545259/',
      license: 'Public Domain (US Government)',
    },
    tags: ['medical microbiology', 'pathogens', 'infectious disease', 'immunology'],
    estimatedHours: 50,
  },
  {
    title: 'Virology and Viral Pathogenesis',
    description: 'Comprehensive virology covering virus structure, replication cycles, pathogenesis, antiviral therapy, and emerging viral diseases.',
    discipline: 'Microbiology',
    subDiscipline: 'Virology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK545265/',
      license: 'Public Domain (US Government)',
    },
    tags: ['virology', 'viruses', 'viral pathogenesis', 'antiviral', 'emerging infections'],
    estimatedHours: 25,
  },
  {
    title: 'Parasitology and Tropical Medicine',
    description: 'Medical parasitology covering protozoa, helminths, and arthropods of medical importance, including life cycles, pathogenesis, diagnosis, and treatment.',
    discipline: 'Microbiology',
    subDiscipline: 'Parasitology',
    documentType: 'Textbook',
    authors: ['WHO', 'CDC'],
    year: 2024,
    source: {
      name: 'WHO / CDC',
      url: 'https://www.who.int/health-topics/neglected-tropical-diseases',
      license: 'CC BY-NC-SA 3.0 IGO',
    },
    tags: ['parasitology', 'tropical medicine', 'protozoa', 'helminths', 'neglected diseases'],
    estimatedHours: 20,
  },
  {
    title: 'Immunology: Principles and Clinical Applications',
    description: 'Comprehensive immunology covering innate and adaptive immunity, antigen-antibody reactions, hypersensitivity, autoimmunity, immunodeficiency, and vaccine development.',
    discipline: 'Microbiology',
    subDiscipline: 'Immunology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK545265/',
      license: 'Public Domain (US Government)',
    },
    tags: ['immunology', 'innate immunity', 'adaptive immunity', 'vaccines', 'autoimmunity'],
    estimatedHours: 35,
  },
  {
    title: 'WHO Guidelines on Hand Hygiene in Healthcare',
    description: 'Evidence-based recommendations on hand hygiene practices in healthcare settings to reduce healthcare-associated infections.',
    discipline: 'Microbiology',
    subDiscipline: 'Infection Control',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2022,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789241597906',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['hand hygiene', 'infection control', 'healthcare safety', 'infection prevention'],
    estimatedHours: 8,
  },

  // ================================================================
  // 13. CLINICAL MEDICINE
  // ================================================================
  {
    title: 'Clinical Medicine and Pathophysiology — NCBI',
    description: 'Clinical presentations, pathophysiology, diagnosis, and management of common medical conditions across all major specialties.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Internal Medicine',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546259/',
      license: 'Public Domain (US Government)',
    },
    tags: ['clinical medicine', 'internal medicine', 'pathophysiology', 'diagnosis', 'management'],
    estimatedHours: 60,
  },
  {
    title: 'WHO Guidelines for the Treatment of Malaria',
    description: 'Evidence-based recommendations for diagnosis, treatment, and prevention of malaria including severe malaria management, antimalarial dosing, and drug resistance surveillance.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Internal Medicine',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240049437',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['malaria', 'infectious disease', 'tropical medicine', 'antimalarial', 'who'],
    estimatedHours: 15,
  },
  {
    title: 'WHO Guidelines for Postpartum Hemorrhage',
    description: 'Recommendations for prevention and treatment of postpartum hemorrhage, the leading cause of maternal mortality globally.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Obstetrics',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240027251',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['postpartum hemorrhage', 'obstetrics', 'maternal health', 'pph', 'emergency'],
    estimatedHours: 10,
  },
  {
    title: 'WHO Guideline on Management of Pneumonia and Diarrhoea in Children',
    description: 'Evidence-based recommendations for management of pneumonia and diarrhoea in children up to 10 years, including community-level treatment and zinc supplementation.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Pediatrics',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2024,
    source: {
      name: 'WHO',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK611556/',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['pediatrics', 'pneumonia', 'diarrhoea', 'child health', 'who'],
    estimatedHours: 12,
  },
  {
    title: 'CDC Guideline for Prescribing Opioids for Chronic Pain',
    description: 'Evidence-based recommendations for opioid prescribing in primary care settings to improve patient safety and reduce opioid use disorder.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Internal Medicine',
    documentType: 'Clinical Guideline',
    authors: ['Centers for Disease Control and Prevention'],
    year: 2022,
    source: {
      name: 'CDC',
      url: 'https://www.cdc.gov/mmwr/volumes/71/rr/rr7103a1.htm',
      license: 'Public Domain (US Government)',
    },
    tags: ['opioid', 'pain management', 'cdc', 'guidelines', 'substance use'],
    estimatedHours: 12,
  },
  {
    title: 'NCI PDQ Cancer Treatment Summaries',
    description: 'Physician Data Query (PDQ) comprehensive, evidence-based summaries on cancer treatment, screening, prevention, supportive care, and integrative therapies.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Oncology',
    documentType: 'Reference Manual',
    authors: ['National Cancer Institute (NIH)'],
    year: 2026,
    source: {
      name: 'National Cancer Institute / NIH',
      url: 'https://www.cancer.gov/publications/pdq',
      license: 'Public Domain (US Government)',
    },
    tags: ['oncology', 'cancer', 'chemotherapy', 'nci', 'pdq', 'treatment'],
    estimatedHours: 50,
  },
  {
    title: 'MSF Clinical Guidelines — Emergency and Hospital Care',
    description: 'Comprehensive clinical guidelines for emergency and hospital care in resource-limited settings, covering trauma, surgery, obstetrics, anaesthesia, and internal medicine.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Emergency Medicine',
    documentType: 'Clinical Guideline',
    authors: ['Médecins Sans Frontières'],
    year: 2024,
    source: {
      name: 'MSF Guidelines',
      url: 'https://medicalguidelines.msf.org/',
      license: 'CC BY-NC-ND 4.0',
      attribution: 'Médecins Sans Frontières',
    },
    tags: ['emergency medicine', 'trauma', 'surgery', 'msf', 'clinical guidelines'],
    estimatedHours: 30,
  },
  {
    title: 'U.S. Medical Eligibility Criteria for Contraceptive Use 2024',
    description: 'CDC evidence-based recommendations for safe use of contraceptive methods for persons with specific characteristics or medical conditions.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Obstetrics',
    documentType: 'Clinical Guideline',
    authors: ['Centers for Disease Control and Prevention'],
    year: 2024,
    source: {
      name: 'CDC MMWR',
      url: 'https://www.cdc.gov/mmwr/volumes/73/rr/rr7304a1.htm',
      license: 'Public Domain (US Government)',
    },
    tags: ['contraception', 'family planning', 'cdc', 'obstetrics', 'guidelines'],
    estimatedHours: 15,
  },
  {
    title: 'WHO Clinical Treatment Guideline for Tobacco Cessation',
    description: 'Evidence-based recommendations on behavioural support, pharmacological interventions, and system-level policies for tobacco cessation in adults.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Internal Medicine',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2024,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240096431',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['tobacco cessation', 'smoking', 'nicotine', 'public health', 'who'],
    estimatedHours: 10,
  },
  {
    title: 'Updated WHO STI Treatment Recommendations 2024',
    description: 'Evidence-informed guidance on treating N. gonorrhoeae, C. trachomatis, and syphilis, including syphilis testing and partner services.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Infectious Diseases',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2024,
    source: {
      name: 'WHO / NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK605899/',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['sti', 'gonorrhea', 'chlamydia', 'syphilis', 'who', 'treatment guidelines'],
    estimatedHours: 12,
  },
  {
    title: 'CDC Immunization Schedules 2024',
    description: 'CDC recommended immunization schedules for children, adolescents, and adults including catch-up guidance, contraindications, and vaccine information.',
    discipline: 'Clinical Medicine',
    subDiscipline: 'Pediatrics',
    documentType: 'Clinical Guideline',
    authors: ['Centers for Disease Control and Prevention'],
    year: 2024,
    source: {
      name: 'CDC',
      url: 'https://www.cdc.gov/vaccines/schedules/',
      license: 'Public Domain (US Government)',
    },
    tags: ['vaccination', 'immunization', 'cdc', 'pediatrics', 'prevention'],
    estimatedHours: 10,
  },

  // ================================================================
  // 14. DIAGNOSTICS
  // ================================================================
  {
    title: 'Laboratory Medicine and Diagnostic Testing',
    description: 'Clinical laboratory medicine covering hematology, clinical chemistry, microbiology, immunology, and molecular diagnostics with test selection and interpretation guidance.',
    discipline: 'Diagnostics',
    subDiscipline: 'Laboratory Medicine',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546701/',
      license: 'Public Domain (US Government)',
    },
    tags: ['laboratory medicine', 'diagnostics', 'clinical chemistry', 'hematology', 'test interpretation'],
    estimatedHours: 30,
  },
  {
    title: 'Radiology and Diagnostic Imaging Principles',
    description: 'Fundamentals of medical imaging including X-ray, CT, MRI, ultrasound, and nuclear medicine with image interpretation and clinical applications.',
    discipline: 'Diagnostics',
    subDiscipline: 'Radiology',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546532/',
      license: 'Public Domain (US Government)',
    },
    tags: ['radiology', 'imaging', 'x-ray', 'ct', 'mri', 'ultrasound'],
    estimatedHours: 25,
  },
  {
    title: 'ECG Interpretation and Cardiac Diagnostics',
    description: 'Systematic approach to ECG interpretation including arrhythmia recognition, ischemic changes, chamber enlargement, and clinical correlation.',
    discipline: 'Diagnostics',
    subDiscipline: 'Cardiac Diagnostics',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK540536/',
      license: 'Public Domain (US Government)',
    },
    tags: ['ecg', 'cardiac', 'arrhythmia', 'electrocardiography', 'cardiology'],
    estimatedHours: 20,
  },

  // ================================================================
  // 15. PUBLIC HEALTH
  // ================================================================
  {
    title: 'CDC Principles of Epidemiology in Public Health Practice',
    description: 'Self-study course covering epidemiological principles, study designs, outbreak investigation, public health surveillance, and data analysis.',
    discipline: 'Public Health',
    subDiscipline: 'Epidemiology',
    documentType: 'Textbook',
    authors: ['Centers for Disease Control and Prevention'],
    year: 2022,
    source: {
      name: 'CDC',
      url: 'https://www.cdc.gov/csels/dsepd/ss1978/',
      license: 'Public Domain (US Government)',
    },
    tags: ['epidemiology', 'public health', 'cdc', 'study design', 'surveillance'],
    estimatedHours: 35,
  },
  {
    title: 'WHO Health Promotion Glossary',
    description: 'Definitions and frameworks for health promotion terminology and concepts used in public health practice globally.',
    discipline: 'Public Health',
    subDiscipline: 'Health Promotion',
    documentType: 'Reference Manual',
    authors: ['World Health Organization'],
    year: 2021,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240038349',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['health promotion', 'public health', 'who', 'glossary', 'definitions'],
    estimatedHours: 8,
  },
  {
    title: 'CDC Program Evaluation Framework 2024',
    description: 'Updated framework for program evaluation in public health integrating equity, collaboration, and evidence-based decision-making across evaluation steps.',
    discipline: 'Public Health',
    subDiscipline: 'Health Systems',
    documentType: 'Clinical Guideline',
    authors: ['Centers for Disease Control and Prevention'],
    year: 2024,
    source: {
      name: 'CDC MMWR',
      url: 'https://www.cdc.gov/mmwr/volumes/73/rr/rr7306a1.htm',
      license: 'Public Domain (US Government)',
    },
    tags: ['program evaluation', 'public health', 'cdc', 'framework', 'equity'],
    estimatedHours: 15,
  },
  {
    title: 'WHO Guidelines on Tuberculosis Infection Prevention and Control',
    description: 'Evidence-based recommendations for TB infection prevention and control in healthcare and community settings, including administrative, environmental, and respiratory protection.',
    discipline: 'Public Health',
    subDiscipline: 'Disease Prevention',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240062012',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['tuberculosis', 'tb', 'infection control', 'public health', 'who'],
    estimatedHours: 12,
  },
  {
    title: 'WHO Guideline on Indoor Air Quality and Health',
    description: 'Evidence-based recommendations on indoor air quality management, pollutant exposure limits, and health promotion for respiratory health.',
    discipline: 'Public Health',
    subDiscipline: 'Environmental Health',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240035218',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['air quality', 'environmental health', 'public health', 'who', 'pollution'],
    estimatedHours: 10,
  },
  {
    title: 'Dietary Guidelines for Americans 2020-2025',
    description: 'Evidence-based nutrition guidance to promote health, reduce chronic disease risk, and maintain healthy eating patterns across all life stages.',
    discipline: 'Public Health',
    subDiscipline: 'Health Promotion',
    documentType: 'Clinical Guideline',
    authors: ['USDA', 'HHS'],
    year: 2020,
    source: {
      name: 'USDA / HHS',
      url: 'https://www.dietaryguidelines.gov/',
      license: 'Public Domain (US Government)',
    },
    tags: ['nutrition', 'dietary guidelines', 'public health', 'prevention', 'diet'],
    estimatedHours: 15,
  },

  // ================================================================
  // 16. RESEARCH
  // ================================================================
  {
    title: 'Users\' Guides to the Medical Literature (JAMA)',
    description: 'Evidence-based medicine methodology for critical appraisal of medical literature including study design assessment, biostatistics, and clinical application of research findings.',
    discipline: 'Research',
    subDiscipline: 'Evidence-Based Medicine',
    documentType: 'Textbook',
    authors: ['Gordon Guyatt', 'Drummond Rennie', 'Maureen Meade'],
    year: 2023,
    source: {
      name: 'JAMA Evidence',
      url: 'https://jamaevidence.mhmedical.com/',
      license: 'Open Access (selected chapters)',
    },
    tags: ['ebm', 'critical appraisal', 'research methods', 'statistics', 'jama'],
    estimatedHours: 40,
  },
  {
    title: 'CONSORT 2010 Statement — RCT Reporting Guidelines',
    description: 'Evidence-based minimum set of recommendations for reporting randomized controlled trials, including CONSORT flow diagram, checklist, and extensions.',
    discipline: 'Research',
    subDiscipline: 'Clinical Trials',
    documentType: 'Clinical Guideline',
    authors: ['CONSORT Group', 'Kenneth Schulz', 'Douglas Altman'],
    year: 2010,
    source: {
      name: 'CONSORT Statement',
      url: 'https://www.consort-statement.org/',
      license: 'Open Access (CC BY)',
    },
    tags: ['consort', 'rct', 'clinical trials', 'reporting guidelines', 'research'],
    estimatedHours: 8,
  },
  {
    title: 'STROBE Statement — Observational Study Reporting',
    description: 'Checklist of items for reporting observational studies including cohort, case-control, and cross-sectional studies.',
    discipline: 'Research',
    subDiscipline: 'Research Methods',
    documentType: 'Clinical Guideline',
    authors: ['STROBE Initiative', 'Jan Vandenbroucke', 'Erik von Elm'],
    year: 2007,
    source: {
      name: 'STROBE Statement',
      url: 'https://www.strobe-statement.org/',
      license: 'Open Access',
    },
    tags: ['strobe', 'observational studies', 'epidemiology', 'reporting guidelines'],
    estimatedHours: 6,
  },
  {
    title: 'PRISMA 2020 — Systematic Review Reporting',
    description: 'Updated reporting guideline for systematic reviews and meta-analyses including PRISMA flow diagram, checklist, and abstract reporting.',
    discipline: 'Research',
    subDiscipline: 'Research Methods',
    documentType: 'Clinical Guideline',
    authors: ['PRISMA Group', 'Matthew Page', 'David Moher'],
    year: 2021,
    source: {
      name: 'PRISMA Statement',
      url: 'https://www.prisma-statement.org/',
      license: 'Open Access (CC BY)',
    },
    tags: ['prisma', 'systematic review', 'meta-analysis', 'research', 'reporting'],
    estimatedHours: 10,
  },
  {
    title: 'GRADE Methodology for Clinical Guidelines',
    description: 'Grading of Recommendations Assessment, Development and Evaluation (GRADE) methodology for assessing certainty of evidence and strength of recommendations.',
    discipline: 'Research',
    subDiscipline: 'Evidence-Based Medicine',
    documentType: 'Reference Manual',
    authors: ['GRADE Working Group', 'Gordon Guyatt', 'Andrew Oxman'],
    year: 2023,
    source: {
      name: 'GRADEpro / GDT',
      url: 'https://www.gradeworkinggroup.org/',
      license: 'Open Access',
    },
    tags: ['grade', 'evidence quality', 'recommendations', 'ebm', 'guidelines'],
    estimatedHours: 15,
  },
  {
    title: 'Introduction to Biostatistics and Research Methodology',
    description: 'Foundational biostatistics covering descriptive statistics, hypothesis testing, parametric and non-parametric tests, regression analysis, and study design principles.',
    discipline: 'Research',
    subDiscipline: 'Biostatistics',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546540/',
      license: 'Public Domain (US Government)',
    },
    tags: ['biostatistics', 'research methods', 'statistics', 'data analysis', 'hypothesis testing'],
    estimatedHours: 30,
  },

  // ================================================================
  // 17. NURSING
  // ================================================================
  {
    title: 'Nursing Fundamentals (Open RN, 2nd Edition)',
    description: 'Comprehensive open textbook covering foundational nursing concepts including patient care, assessment, ethics, communication, safety, and clinical reasoning.',
    discipline: 'Nursing',
    subDiscipline: 'Fundamentals',
    documentType: 'Textbook',
    authors: ['Kimberly Ernstmeyer', 'Elizabeth Christman', 'Open Resources for Nursing'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf / Open RN',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK590033/',
      license: 'CC BY 4.0',
      attribution: 'Open RN, Chippewa Valley Technical College',
    },
    tags: ['nursing', 'fundamentals', 'patient care', 'assessment', 'clinical reasoning'],
    estimatedHours: 60,
  },
  {
    title: 'Health Alterations (Open RN)',
    description: 'Open textbook covering medical-surgical nursing concepts including pathophysiology, nursing management, and pharmacological interventions for common health alterations.',
    discipline: 'Nursing',
    subDiscipline: 'Medical Surgical Nursing',
    documentType: 'Textbook',
    authors: ['Kimberly Ernstmeyer', 'Elizabeth Christman', 'Open Resources for Nursing'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf / Open RN',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK590030/',
      license: 'CC BY 4.0',
      attribution: 'Open RN, Chippewa Valley Technical College',
    },
    tags: ['medical-surgical', 'nursing', 'pathophysiology', 'nursing management', 'health alterations'],
    estimatedHours: 50,
  },
  {
    title: 'Nursing Management and Professional Concepts (Open RN)',
    description: 'Open textbook on nursing leadership, management, professional practice, healthcare policy, and quality improvement in nursing.',
    discipline: 'Nursing',
    subDiscipline: 'Fundamentals',
    documentType: 'Textbook',
    authors: ['Kimberly Ernstmeyer', 'Elizabeth Christman', 'Open Resources for Nursing'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf / Open RN',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK590037/',
      license: 'CC BY 4.0',
      attribution: 'Open RN, Chippewa Valley Technical College',
    },
    tags: ['nursing management', 'leadership', 'professional practice', 'healthcare policy'],
    estimatedHours: 35,
  },
  {
    title: 'Medical Terminology (Open RN, 2nd Edition)',
    description: 'Open textbook covering medical terminology including word roots, prefixes, suffixes, abbreviations, and anatomical terminology for healthcare professionals.',
    discipline: 'Nursing',
    subDiscipline: 'Fundamentals',
    documentType: 'Textbook',
    authors: ['Kimberly Ernstmeyer', 'Elizabeth Christman', 'Open Resources for Nursing'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf / Open RN',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK590025/',
      license: 'CC BY 4.0',
      attribution: 'Open RN, Chippewa Valley Technical College',
    },
    tags: ['medical terminology', 'anatomical terms', 'healthcare vocabulary', 'nursing'],
    estimatedHours: 25,
  },

  // ================================================================
  // 18. DENTISTRY
  // ================================================================
  {
    title: 'Oral Medicine and Pathology',
    description: 'Comprehensive coverage of oral diseases, oral manifestations of systemic conditions, diagnostic techniques, and therapeutic approaches in oral medicine.',
    discipline: 'Dentistry',
    subDiscipline: 'Oral Medicine',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546534/',
      license: 'Public Domain (US Government)',
    },
    tags: ['oral medicine', 'oral pathology', 'dental', 'oral diseases', 'diagnosis'],
    estimatedHours: 25,
  },
  {
    title: 'Preventive Dentistry and Community Oral Health',
    description: 'Evidence-based approaches to dental caries prevention, periodontal disease prevention, community oral health programs, and public health dentistry.',
    discipline: 'Dentistry',
    subDiscipline: 'Preventive Dentistry',
    documentType: 'Textbook',
    authors: ['WHO', 'CDC'],
    year: 2023,
    source: {
      name: 'WHO / CDC',
      url: 'https://www.who.int/health-topics/oral-health',
      license: 'CC BY-NC-SA 3.0 IGO',
    },
    tags: ['preventive dentistry', 'oral health', 'community', 'caries prevention', 'public health'],
    estimatedHours: 15,
  },
  {
    title: 'WHO Global Oral Health Status Report',
    description: 'Comprehensive global report on oral disease burden, risk factors, healthcare access, and policy recommendations for improving oral health worldwide.',
    discipline: 'Dentistry',
    subDiscipline: 'Preventive Dentistry',
    documentType: 'Reference Manual',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240070738',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['oral health', 'who', 'global health', 'dental', 'epidemiology'],
    estimatedHours: 10,
  },

  // ================================================================
  // 19. NUTRITION
  // ================================================================
  {
    title: 'Clinical Nutrition and Dietetics',
    description: 'Evidence-based clinical nutrition covering nutritional assessment, therapeutic diets, enteral and parenteral nutrition, and nutrition in disease management.',
    discipline: 'Nutrition',
    subDiscipline: 'Clinical Nutrition',
    documentType: 'Textbook',
    authors: ['NCBI Bookshelf'],
    year: 2024,
    source: {
      name: 'NCBI Bookshelf',
      url: 'https://www.ncbi.nlm.nih.gov/books/NBK546545/',
      license: 'Public Domain (US Government)',
    },
    tags: ['clinical nutrition', 'dietetics', 'nutritional assessment', 'therapeutic diets', 'enteral nutrition'],
    estimatedHours: 30,
  },
  {
    title: 'WHO Guidelines on Nutrition and Physical Activity',
    description: 'Evidence-based recommendations for healthy diet, physical activity, and weight management across the lifespan for prevention of noncommunicable diseases.',
    discipline: 'Nutrition',
    subDiscipline: 'Community Nutrition',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240071650',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['nutrition', 'physical activity', 'ncd prevention', 'diet', 'who'],
    estimatedHours: 12,
  },
  {
    title: 'Infant and Young Child Feeding Guidelines — WHO',
    description: 'Evidence-based recommendations on breastfeeding, complementary feeding, and nutritional management of infants and young children.',
    discipline: 'Nutrition',
    subDiscipline: 'Community Nutrition',
    documentType: 'Clinical Guideline',
    authors: ['World Health Organization'],
    year: 2023,
    source: {
      name: 'WHO',
      url: 'https://www.who.int/publications/i/item/9789240081864',
      license: 'CC BY-NC-SA 3.0 IGO',
      attribution: 'World Health Organization',
    },
    tags: ['infant feeding', 'breastfeeding', 'complementary feeding', 'nutrition', 'pediatrics'],
    estimatedHours: 10,
  },
];

// Optional: validate that all disciplines in the catalog are recognized
export function validateCatalog(): string[] {
  const validDisciplines = [
    'Pharmacy', 'Pharmacology', 'Pharmaceutics', 'Pharmaceutical Chemistry',
    'Organic Chemistry', 'Pharmaceutical Analysis', 'Pharmacognosy', 'Biochemistry',
    'Physiology', 'Anatomy', 'Pathology', 'Microbiology', 'Clinical Medicine',
    'Diagnostics', 'Public Health', 'Research', 'Nursing', 'Dentistry', 'Nutrition'
  ];
  
  const errors: string[] = [];
  for (const r of RESOURCE_CATALOG) {
    if (!validDisciplines.includes(r.discipline)) {
      errors.push(`Invalid discipline "${r.discipline}" for resource "${r.title}"`);
    }
    if (!r.source.url) {
      errors.push(`Missing URL for resource "${r.title}"`);
    }
  }
  return errors;
}
