// Kenyan-market brand names keyed by lowercase generic name.
// Used to generate brand-based image search queries — branded packaging
// photos are acceptable, and Kenyan-market brands are prioritized.
export const KENYAN_BRANDS: Record<string, string[]> = {
  'acebutolol hydrochloride': ['Sectral'],
  'acyclovir': ['Zovirax', 'Acivir'],
  'alfuzosin hydrochloride': ['Xatral', 'UroXatral'],
  'amikacin sulfate': ['Amikin'],
  'amiloride hydrochloride': ['Midamor', 'Moduretic'],
  'amoxicillin/clavulanate': ['Augmentin', 'Co-amoxiclav', 'Moxikind'],
  'amphotericin b': ['Fungizone', 'AmBisome'],
  'artemether and lumefantrine': ['Coartem', 'Lonart', 'Artefan'],
  'atovaquone and proguanil hydrochloride': ['Malarone'],
  'azilsartan kamedoxomil': ['Edarbi'],
  'aztreonam': ['Azactam'],
  'baloxavir marboxil': ['Xofluza'],
  'bedaquiline fumarate': ['Sirturo'],
  'bictegravir sodium, emtricitabine, and tenofovir alafenamide fumarate': ['Biktarvy'],
  'captopril and hydrochlorothiazide': ['Capozide', 'Acezide'],
  'carbapenem': ['Meropenem'],
  'caspofungin acetate': ['Cancidas'],
  'cefoxitin sodium': ['Mefoxin'],
  'cefpodoxime proxetil': ['Vantin', 'Orelox'],
  'ceftaroline fosamil': ['Teflaro', 'Zinforo'],
  'ceftazidime': ['Fortum', 'Fortaz'],
  'ceftobiprole medocaril sodium': ['Zevtera', 'Mabelio'],
  'chloramphenicol sodium succinate': ['Chloromycetin', 'Kemicetine'],
  'chlorthalidone': ['Hygroton', 'Thalitone'],
  'clofazimine': ['Lamprene'],
  'clonidine hydrochloride': ['Catapres', 'Dixarit'],
  'colistin sulfate, neomycin sulfate, thonzonium bromide and hydrocortisone acetate': ['Coly-Mycin S'],
  'cycloserine': ['Seromycin'],
  'dalbavancin': ['Dalvance'],
  'delafloxacin meglumine': ['Baxdela'],
  'dorzolamide hydrochloride timolol maleate': ['Cosopt'],
  'eplerenone': ['Inspra'],
  'ertapenem sodium': ['Invanz'],
  'etravirine': ['Intelence'],
  'fidaxomicin': ['Dificid'],
  'foscarnet sodium': ['Foscavir'],
  'fosinopirl sodium': ['Monopril'],
  'fostemsavir tromethamine': ['Rukobia'],
  'ibalizumab': ['Trogarzo'],
  'irbesartan': ['Avapro', 'Aprovel'],
  'isosorbide dinitrate': ['Isordil', 'Sorbitrate'],
  'isosorbide mononitrate': ['Imdur', 'Monoket'],
  'ivabradine': ['Corlanor', 'Procoralan'],
  'labetalol hydrochloride': ['Trandate', 'Normodyne'],
  'lefamulin acetate': ['Xenleta'],
  'lenacapavir sodium': ['Sunlenca'],
  'mefloquine hydrochloride': ['Lariam'],
  'meropenem-vaborbactam': ['Vabomere'],
  'metolazone': ['Zaroxolyn'],
  'micafungin': ['Mycamine'],
  'minocycline hydrochloride': ['Minocin', 'Minomycin'],
  'moexipril hydrochloride': ['Univasc'],
  'nebivolol': ['Bystolic', 'Nebilet'],
  'nimodipine': ['Nimotop'],
  'nitazoxanide': ['Alinia'],
  'nitrofurantoin': ['Furadantin', 'Macrodantin'],
  'nitroglycerin': ['Nitrostat', 'Nitro-Dur', 'Nitrolingual'],
  'olmesartan medoxomil-hydrochlorothiazide': ['Benicar HCT', 'Olmetec HCT'],
  'oritavancin diphosphate': ['Orbactiv'],
  'paromomycin sulfate': ['Humatin'],
  'peginterferon alfa-2a': ['Pegasys'],
  'pentamidine isethionate': ['Pentam 300', 'Pentacarinat'],
  'perindopril erbumine': ['Coversyl', 'Aceon'],
  'pindolol': ['Visken'],
  'piperacillin sodium, tazobactam sodium': ['Tazocin', 'Zosyn'],
  'plazomicin': ['Zemdri'],
  'posaconazole': ['Noxafil'],
  'quinapril': ['Accupril'],
  'ranolazine': ['Ranexa'],
  'remdesivir': ['Veklury'],
  'rifaximin': ['Xifaxan', 'Normix'],
  'sacubitril/valsartan': ['Entresto'],
  'sodium nitroprusside': ['Nipride', 'Nitropress'],
  'sotalol hydrochloride': ['Betapace', 'Sotacor'],
  'sulfamethoxazole and trimethoprim': ['Bactrim', 'Septrin', 'Cotrimoxazole'],
  'tedizolid phosphate': ['Sivextro'],
  'telmisartan': ['Micardis', 'Pritor'],
  'tenofovir disoproxil fumarate': ['Viread'],
  'terazosin hydrochloride': ['Hytrin'],
  'tigecycline': ['Tygacil'],
  'tinidazole': ['Fasigyn', 'Trinidal'],
  'torsemide': ['Demadex', 'Torem'],
  'trandolapril': ['Mavik', 'Gopten'],
  'triamterene and hydrochlorothiazide': ['Dyazide', 'Maxzide'],
  'valacyclovir': ['Valtrex', 'Valcivir'],
  'zanamivir': ['Relenza'],
}

const NORMALIZE_RE = /\s+/g

export function normalizeGeneric(name: string): string {
  return (name || '').toLowerCase().replace(NORMALIZE_RE, ' ').trim()
}

/** Kenyan-market brand names for a generic drug (lowercase match). */
export function brandNamesFor(genericName: string): string[] {
  return KENYAN_BRANDS[normalizeGeneric(genericName)] ?? []
}
